### ISSUE TITLE
Resonating Wand Quest is dependent on having completed the glowstone quest first, though it should be the other way around.

### ISSUE THREAD

**Issue by Autowinto** [FTBTeam/FTB-Interactions#100]
## Modpack Version: 

1.0.1

## Bug Report:

The quest for obtaining glowstone dust shows as a prerequisite for obtaining the resonating wand, despite it being the other way around.

## Expected Behavior/Suggestions:

I'd expect the wand to show as a prerequisite for obtaining glowstone.

## Is It Repeatable? Steps to Reproduce: 
![image](https://user-images.githubusercontent.com/24361128/55263403-23634080-5271-11e9-8935-7400e09d6a61.png)

Attempt to create tiny pieces of glowstone dust and realize that you first need the wand that is farther down into the quest book.

## Known Fix: 
Move the resonating wand to be a prerequisite for the glowstone dust.

**Comment by Vyraal1** [comment]
Actually decided this is not a bug since there is a small glowstone pile quest you can do. Added small glowstone piles to the quest as a hint on how to make them.
