### ISSUE TITLE
OpenComputers Creative can is unopenable/indestructable in survival mode

### ISSUE THREAD

**Issue by proslackergamer** [FTBTeam/FTB-Interactions#1000]
## Modpack Version: 

2.0.3

## Bug Report:

After placing down the Computer Case (Creative) in the world, you are not able to access the inventory or destroy it in survival mode.

## Expected Behavior/Suggestions:

Make them interactable and destructible by players in survival mode.

**Comment by Saereth** [comment]
this is not something I can change the behavior is hard coded, just gotta be careful where you place it down. I'll probably just remove the creative case as loot unfortunately
