### ISSUE TITLE
Need Wool to Summon Sheep with Zen Summoning

### ISSUE THREAD

**Issue by rockdemon696** [FTBTeam/FTB-Interactions#1002]
## Modpack Version: 
2.0.3

## Bug Report:
The Zen Summoning recipe requires wool which can only be acquired by shearing or killing a poor defenseless sheep.

## Expected Behavior/Suggestions:
Bugs: Can't summon Sheep to get wool due to lack of wool.
Suggestions: The recipe should probably use another material in place of wool, my instinct tells me cotton is a good choice.

## Is It Repeatable? Steps to Reproduce: 
1. Look up ways to get wool in JEI
2. Only find a way to summon Sheep
3. The Zen Summoning ritual requires wool as a catalyst
4. You can't get wool without a sheep.
5. Stuck in loop cannot continue.

## Mod/s Affected: 
Zen Summoning

## Known Fix: 
Replace wool with another item in the Zen Summoning ritual recipe.

**Comment by Saereth** [comment]
u wot damnit. K it should be string not wool, will fix this up for 2.0.4
