### ISSUE TITLE
Tomatillo drops disabled from soggy gardens in harvestcraft.cfg

### ISSUE THREAD

**Issue by llearch** [FTBTeam/FTB-Interactions#1004]
## Modpack Version: 
2.0.3

## Bug Report:
Tomatillo drops appears disabled in config/harvestcraft.cfg, relevant section copy/pasted from my install:

```
    #  [default: [harvestcraft:brusselsproutitem], [harvestcraft:spiceleafitem], [harvestcraft:blueberryitem], [harvestcraft:asparagusitem], [harvestcraft:cranberryitem], [harvestcraft:riceitem], [harvestcraft:seaweeditem], [harvestcraft:waterchestnutitem], [harvestcraft:okraitem], [harvestcraft:cottonitem], [harvestcraft:kaleitem], [harvestcraft:milletitem], [harvestcraft:jicamaitem], [harvestcraft:greengrapeitem], [harvestcraft:mulberryitem], [harvestcraft:tomatilloitem]]
    S:soggyGarden <
        harvestcraft:brusselsproutitem
        harvestcraft:spiceleafitem
        harvestcraft:blueberryitem
        harvestcraft:asparagusitem
        harvestcraft:cranberryitem
        harvestcraft:riceitem
        harvestcraft:seaweeditem
        harvestcraft:waterchestnutitem
        harvestcraft:okraitem
        harvestcraft:cottonitem
        harvestcraft:kaleitem
        harvestcraft:milletitem
        harvestcraft:jicamaitem
        harvestcraft:greengrapeitem
        harvestcraft:mulberryitem
     >
```

Note the last and second-to-last item on the comment line vs the config below it.

This looks like a copy/paste error, since it's the last thing on the list, but may be deliberate; if so, I figured someone might be looking for it, and it would be good to have a "yes this is deliberate" note dropped here.

## Mod/s Affected: 
Pam's Harvestcraft

## Known Fix: 
Add another line, as per the comment in the file itself.

**Comment by Saereth** [comment]
nah I think because these configs were just generated long ago and pams isnt properly updating them,should be an easy fix tho

**Comment by llearch** [comment]
I do try for the easy fixes. ;-]
