### ISSUE TITLE
Golems and gt ores

### ISSUE THREAD

**Issue by faqza** [FTBTeam/FTB-Interactions#1007]
## Modpack Version: 

2.0.3
## Bug Report:

World crashes on the loading screen
## Expected Behavior/Suggestions:

I've wanted to automate placing of GTCE iron ore by golems.

## Is It Repeatable? Steps to Reproduce: 
When golem took this ore, texture of ore became broken(pink&black). Then I break the golem and this corrupted ore crashed my game. After relogging I picked up this corrupted ore and crashed again and now it is crashing on the loading screen.

## Link to Log or Crash File Paste**: 

https://paste.feed-the-beast.com/view/016c85a3
## Mod/s Affected: 

Thaumcraft 6 and GTCE

**Comment by Saereth** [comment]
oof thats nasty, edit forge.cfg and tell it to delete erroring entities/tile entities, should let you resume your game just fine. Unfortunately this is a bug on tcs side with it not properly handling an error some gt ore is causing, unfortunately the stack trace is not very useful and it doesnt seem like TC is really getting any development fix so we'll just have to avoid using golems with GT ores. Sad times

**Comment by faqza** [comment]
Editing forge.cfg ( B:removeErroringEntities=true; B:removeErroringTileEntities=true) seems helpless, I still can't enter my world.
