### ISSUE TITLE
The astrobody data processor could not be completed correctly

### ISSUE THREAD

**Issue by JackMeds** [FTBTeam/FTB-Interactions#1010]
## Modpack Version: 
2.0.3

## Bug Report:
The astrobody data processor could not be completed correctly

![image](https://user-images.githubusercontent.com/38741783/87874760-0ec73080-c9ff-11ea-8557-d027afd6b581.png)
![image](https://user-images.githubusercontent.com/38741783/87874762-1686d500-c9ff-11ea-903d-2d4847b479f2.png)

## Mod/s Affected: 
Advanced Rocketry

**Comment by Saereth** [comment]
https://github.com/zmaster587/AdvancedRocketry/issues/1879
