### ISSUE TITLE
Flint Axe

### ISSUE THREAD

**Issue by Hobdini** [FTBTeam/FTB-Interactions#1013]
## Modpack Version: 
1.9.1

## Bug Report:
When I am using the Flint Axe. I have to hold shift in order for the axe to mine a single log block. The axe also does not chop the entire tree down.
## Expected Behavior/Suggestions:
I am surprised I need to hold shift for the axe to actually work some what properly

## Is It Repeatable? Steps to Reproduce: 

1. held left click to chop the tree down normally but it wouldn't
2.

**Comment by xCykrix** [comment]
You are not using the latest version of the Mod pack. Please try updating it and make sure you are using the FTB launcher explicitly as other launchers may be outdated.
