### ISSUE TITLE
Crash while launching using FTB Launcher

### ISSUE THREAD

**Issue by Samwhell** [FTBTeam/FTB-Interactions#1015]
## Modpack Version: 
2.0.3

## Bug Report:
Receiving launching crash error explaining that it expects Pam's Harvestcraft caused a launch issue.

## Expected Behavior/Suggestions:
Be real nice if it launched. Been watching Direwolf20's latest run-through and am throroughly impressed.

## Is It Repeatable? Steps to Reproduce: 
1. After downloading the pack using the FTB Launcher (because there was a warning on twitch that it would no longer have the most up to date packs (P.S. Twitch integration was convenient, but I think ya'll can do better than them))
2. Push the play button on the FTB Interactions button.
3. Minecraft launcher opens with FTB Interactions in the pull-down
4. Launch and forge starts doing its thing
5. Get about 40 to 50 percent through load and get error screen  and crash.
6. Screen says it will give me a link, but when I use the button, it also fails.

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/b2744095

## Mod/s Affected: 
Pam's Harvestcraft

## Known Fix: 
This is why I come to you fine experts.

**Comment by Samwhell** [comment]
Sure would Love to play this fine pack you've made.

**Comment by Saereth** [comment]
Looks like you've got an incomplete/corrupt install from the launcher, please open an issue report here: https://github.com/FTBTeam/FTB-App/issues
and provide them your launcher logs so they can hopefully fix the launcher issues. 
Reinstalling the pack generally solves the issue you're having, several people have experienced this.
