### ISSUE TITLE
Can't intercat with inventory blocks on multiplayer server

### ISSUE THREAD

**Issue by Bradley4170** [FTBTeam/FTB-Interactions#1019]
**ModPack Version:** 2.0.3
**Bug Report:** So, any interactions with a placed down block that has a GUI, (excluding the transmutation table and normal crafting table) doesn't work. The items bug out and/or the crafting recipe doesn't work and glitches, as seen in the video. This is on a multiplayer server in which I have created via the tutorial on GitHub, I may have done something wrong or it might be a bug? The issue doesn't occur within the singleplayer version of the modpack.
**Expected Behaviour:** For the inventories to actually work and to be able to craft.
**Is It Repeatable?:** Yes, simply place down a workbench on a multiplayer server, and it won't work. I have tried resetting all player data and worlds, however, this does not work.
**Video:** https://youtu.be/yy4QK_7pXuQ

I appreciate the time it takes to look into bugs that people post, so I understand a fix won't be instant, however the current issue is making it unplayable for myself and my friend. If the bug is occuring due to an error on my end then I do apologise.

**Comment by Saereth** [comment]
what you're experiencing here is a server/client recipe desync, almost assuredly the server install is corrupt/missing stuff. Shut down the server and copy all your config/mods/scripts to the server from your working client and it should be fixed. We've gotten a ton of similar reports from the FTB App server install doing this, a reinstall -generally- fixes it but it is highly annoying for sure.
