### ISSUE TITLE
Numpad Cancelling Sneak?

### ISSUE THREAD

**Issue by MaxAstro** [FTBTeam/FTB-Interactions#102]
## Modpack Version: 
1.0.1

## Bug Report:
Pressing any of the numpad keys while holding Shift causes me to stop sneaking until I release the key; this did not happen in 1.0.0

## Expected Behavior/Suggestions:
Should be able to press numpad keys while sneaking

## Is It Repeatable? Steps to Reproduce: 
1. Hold shift
2. Press a numpad key
3. Fall off the edge because you were trying to excavate while sneaking

**Comment by Saereth** [comment]
I can confirm this and it only happens with numlock on... no idea what might be causing it tho

**Comment by Saereth** [comment]
was cyclic, fixed in next update
