### ISSUE TITLE
Creepers blow up claimed land no matter what. 

### ISSUE THREAD

**Issue by EAGBCD** [FTBTeam/FTB-Interactions#1020]
## Modpack Version: 
 Latest 

## Bug Report:

Creepers blow up and destroy land regardless of if is claimed by FTB utility or not.

## Expected Behavior/Suggestions:
 Creeper --> boom = land and my house go boom = me sad as I patch my 50th creeper hole. This happened in claimed land even with FTB utility option "enable explosion in claimed chunks" set to false. 
 Creeper should boom as they do but in claimed land they should not destroy the land. This is how it is in most pack and it is better that way. Especially with invisible creepers. Having creeper holes everywhere is ugly and patching them represents no fun gameplay, its just annoying. I hope you can fix this. 

## Is It Repeatable? Steps to Reproduce: 

1. Get close to creeper and have it explode.
2.

## Known Fix: 
 It's an FTB utility thing right?

Thanks so much for the pack! it is so well made, sorry to complain it's just this is frequent and no fun, also I have it set to false but they still destroy the land so I don't know how to fix myself.

**Comment by Saereth** [comment]
https://github.com/FTBTeam/FTB-Utilities/issues/1121 
FTBTeam/FTB-Interactions#932
duplicate

unfortunately this is a mod issue, not something I can fix/change as the pack owner

**Comment by EAGBCD** [comment]
Hey for the post you linked it says fixed in the next update, but here you said you can not fix? 

Just wondering which is it, Fixed next update or not?

Thanks again.
