### ISSUE TITLE
Whittled Fire Stick inventory filling will freeze the game and make that world inoperable

### ISSUE THREAD

**Issue by dpcollier128** [FTBTeam/FTB-Interactions#1022]
## Modpack Version: 
FTB Interactions 1.9.1 (currently the top version in the Twitch launcher and the highest recommended/released build)

## Bug Report:
Upon filling my inventory with Whittled Fire Sticks in an attempt to rectify a similar issue (quest book not registering that two Whittled First Sticks have been crafted), the game will freeze if I am to also press the "Move held item to offhand" button while selecting Whittled Fire Stick and simultaneously pick up a Whittled Fire Stick from the ground. Not only does this freeze the game, but it also makes the world this event takes place in utterly inoperable, crashing the game instance to desktop upon attempting to enter that world (this later symptom may be related to the game freezing and my forcing the process to stop).

## Expected Behavior/Suggestions:
I had expected no such hanging to occur and the new stick to slot itself neatly in my inventory. What I had attempted to do was to force this item to stack somehow and rectify another issue I've been having (quest book not registering that two Whittled Fire Sticks have been crafted). Neither expected event happened.

## Is It Repeatable? Steps to Reproduce: 
1. Fill your inventory with Whittled Fire Sticks.
2. Put a few on the ground and fill your inventory with more.
3. Hold one of the sticks in your hand from the toolbar.
4. Approach the pile of sticks on the ground until you would be able to pick them up.
5. Press your "Move held item to offhand" button on one of the sticks.
6. Observe how your game instance hangs perpetually, forcing you to close it prematurely.

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/cfa1b289

**Comment by anabsolutesloth** [comment]
Sounds like something to report to [Primal Tech Github](https://github.com/vadis365/PrimalTech/issues?q=is%3Aissue+is%3Aopen), even if it is dead/inactive.
I'd also try to recreate it in 2.0.3, you can get it onto Twitch through Importing the .zip pinned in the Interactions channel on the FTB Discord, which should be linked on all FTB pack Curseforge pages.

**Comment by dpcollier128** [comment]
Thank you for the pointer on how to update the pack.
