### ISSUE TITLE
deleted game artifacts

### ISSUE THREAD

**Issue by mikeyrevit** [FTBTeam/FTB-Interactions#1035]
When deleting and starting a new world I have artifacts from the deleted world in my new spawn.  including built platforms, items stored in any Iron chest mod chest are dropped and a few of the GT multi block structures are still operational.

## Modpack Version: 
2.0.2, 2.0.3, and 2.0.4

## Is It Repeatable? Steps to Reproduce: 
1. delete old world 
2.restart new world and when spawning old world artifacts are present

## Link to Log or Crash File Paste**: 
no crash 

## Mod/s Affected: 
unknown 

## Known Fix: 
uninstall and reinstall

**Comment by Saereth** [comment]
shut down your world entirely and then delete /world that should delete everything

**Comment by Saereth** [comment]
guessing this is resolved, if not reopen
