### ISSUE TITLE
Menril Resin amount in a mekanism dynamic tank resets itself

### ISSUE THREAD

**Issue by m-scasserra** [FTBTeam/FTB-Interactions#1037]
## Bug Report:
Menril Resin amount a mekanism dynamic tank resets itself every time i log back in. I did check and the tank is in one chunk 

## Expected Behavior/Suggestions:
It should not happen

## Is It Repeatable? Steps to Reproduce: 
[https://www.dropbox.com/s/8ldnrgyz29qf9oz/2020-07-25%2002-32-05.mkv?dl=0](https://www.dropbox.com/s/8ldnrgyz29qf9oz/2020-07-25%2002-32-05.mkv?dl=0)
Tried to reproduce it in another instance and couldn't do it

## Mod/s Affected: 
Mekanism
Integrated Dynamics

**Comment by m-scasserra** [comment]
I think the problem is with the mekanism tanks. Another tank just ate half a stack of oil cells and has the same problem. They are gone and the oil also gone. I think i notice the particle effects of the creation of tank when i log back in. The problem it seems that it doesnt save the structure as such and it saves the individual blocks so when you log back in it reforms the structure

**Comment by Hekera** [comment]
Dynamic tanks tend to have their contents deleted when they have EnderIO fluid conduits attached to them. This will happen occasionally with Thermal Expansion fluiducts. Stick to Mekanism mechanical pipes when interacting with dynamic tanks.

**Comment by DarkDon** [comment]
I have the same problem and i used mechanical pipes from mekanism, after i log back into my single player world the tank is empty.

**Comment by m-scasserra** [comment]
@Hekera I didn't knew that but i'm not sure. I have a dynamic tank at the back with diesel and ender fluid conduits and it doesn't happens

**Comment by Saereth** [comment]
This issue has been reported to mekanism, its been worked on,it happens less frequently than it used to (unreproducible for myself, but reports do occasionally sitll come in about it ) but its been reported and out of my control to fix from a pack perspective now.
