### ISSUE TITLE
Astral Collector Crystals not respecting chunk loading

### ISSUE THREAD

**Issue by Marzule-90** [FTBTeam/FTB-Interactions#1038]
#710  Modpack Version: 
2.0.4

## Bug Report:
Using the collector crystal to convert ore to dense ore only works when I'm nearby. I have tried both FTBUtil and Weirding Gadget chunk loaders. 

## Expected Behavior/Suggestions:
Expected: collector crystals work when I'm not in render distance

## Is It Repeatable? Steps to Reproduce: 
1. Place down auto placer, breaker and scanner to place iron ore, then break dense iron ore. 
2. Put a stack of iron ore in placer
3. teleport or fly away outside chunk loaded area and outside render distance
4. Teleport back after 20 minutes
Expected result: multiple ores converted and broken
Found result: 1 or 0 ores converted or broken.

## Mod/s Affected: 
Astral Sorcery

**Comment by Saereth** [comment]
we'll have to talk to Hellfire about this

**Comment by madokaorimura** [comment]
Suggestion: Get Floating Crystal and make automation near the base
