### ISSUE TITLE
Bloodstone works as Tier 4 altar caps

### ISSUE THREAD

**Issue by Hekera** [FTBTeam/FTB-Interactions#1039]
## Modpack Version: 
2.0.4

## Bug Report:
Bloodstone (tile and bricks) can be used to upgrade the blood altar to tier 4 and above, in addition to skystone.

## Expected Behavior/Suggestions:
Only skystone works.

## Is It Repeatable? Steps to Reproduce: 
![image](https://user-images.githubusercontent.com/40907168/88467861-b46c1b00-cea9-11ea-8f8d-0db01084af0e.png)

**Comment by TeamDman** [comment]
![image](https://user-images.githubusercontent.com/9356891/88506217-68070500-cfa7-11ea-8c5b-d90fcad2d6f3.png)
(search covers all of `scripts/`)
From what I can tell, we just aren't removing it
@Saereth Can you confirm if I'm missing something?
