### ISSUE TITLE
Early access to stone advanced Tinker tools

### ISSUE THREAD

**Issue by KaseiFR** [FTBTeam/FTB-Interactions#1041]
## Modpack Version: 
2.0.4

## Bug Report:
The "Cheapstake tools" quest is implying that advanced tinker tool cores (like the hammer head) can be crafted easily with "low end and cheap materials" (like stone), and only require machines for better materials.
But it seems that an extruder is required for all materials.

## Expected Behavior/Suggestions:
Either allow stone parts to be crafted normally, or reword the quest.

## Is It Repeatable? Steps to Reproduce: 
Yes, check JEI
![quest](https://user-images.githubusercontent.com/6408124/88478458-c4870780-cf48-11ea-9a3c-45eae6feb78e.png)
![recipe](https://user-images.githubusercontent.com/6408124/88478455-b76a1880-cf48-11ea-8d8b-7edc7e2f8879.png)

## Link to Log or Crash File Paste**: 
N/A

## Mod/s Affected: 
* Tinker construct
* FTB Quests

**Comment by Saereth** [comment]
you can make stone parts in the part builder as you would normally

**Comment by KaseiFR** [comment]
I trusted JEI too much. Sorry for the noise !
