### ISSUE TITLE
Astral Socery step assist "Hiking Boots" not functional

### ISSUE THREAD

**Issue by TherminatorX** [FTBTeam/FTB-Interactions#1042]
## Modpack Version: 
2.0.4

## Bug Report:
Upon unlocking the Hiking Boots perk via the tree, I was still unable to step up single blocks.

## Expected Behavior/Suggestions:
Expected: After leveling up enough in Astral, the Hiking Boots perk allows for smoother movement across the world passively without taking up an inventory slot.
Suggestion: Please just let it work by default

## Is It Repeatable? Steps to Reproduce: 
1. Attune and acquire perk points
2. Select the Hiking Boots perk and walk into a single block difference in height

## Link to Log or Crash File Paste**: 
N/A

## Mod/s Affected: 
Astral Sorcery/basic gameplay, Ice and Fire possible conflict via googling but incredibly hesitant to test with all the ID changes removal could cause

## Known Fix: 
Enable the Cyclic lofty apple and cheat it in, I earned the passive step assist already :)

**Comment by Saereth** [comment]
this is some intermod conflict that likely will not receive a fix from hellfire, what I am gonna do is add the cyclic apple as a craftable attunement tier astral recipe to help address this

**Comment by TherminatorX** [comment]
A note since I saw you comment about adding irradiant stars as consolation rewards: Aevitas is gated behind MV due to fluxed phytogro, so if you're judging things based on constellation access at the tier you can make the attunement altar, that one would not be listed as a choice reward.
