### ISSUE TITLE
Default Binding Reagent recipe still enabled

### ISSUE THREAD

**Issue by anabsolutesloth** [FTBTeam/FTB-Interactions#1043]
Modpack Version:
2.0.4

Bug Report:
The default recipe for Binding Reagent in the Hellfire Forge is still enabled

Expected Behavior/Suggestions:
Expected: For the default recipe to be disabled and the custom one to be enforced as a result.
Reality: Still enabled.

 Is It Repeatable? Steps to Reproduce: 
Check JEI recipes for Binding Reagent in FTB:I 2.0.4

Known Fix: 
Use Crafttweaker to edit out the default recipe.

![image](https://user-images.githubusercontent.com/63694982/88508798-7e579580-cf94-11ea-9cf8-0966786fd498.png)

**Comment by hacatu** [comment]
I think this is intentional because the default recipe requires a higher tier tartaric gem and therefore a higher tier altar.

**Comment by anabsolutesloth** [comment]
It cycles through the gems, as do all recipes, but it requires a Common gem, it could be intentional, but i doubt it.

**Comment by Saereth** [comment]
this is intentional, the alternate recipe (one shown on the bottom) is doable at an earlier progression stage
