### ISSUE TITLE
Edgeless glass blocks can't be cut in ArchitectureCraft sawbench

### ISSUE THREAD

**Issue by Cata-bre** [FTBTeam/FTB-Interactions#1047]
## Modpack Version: 
2.0.3

## Bug Report:
Some glass blocks cannot be cut into wedges using the ArchitectureCraft sawbench. Tinkers Construct glass blocks, Botania glass blocks, and XTones glass blocks (glaxx) cannot be cut into wedges. This is frustrating as I want to be able to build slopes with edgeless glass.

## Expected Behavior/Suggestions:
I would expect to be able to cut different edgeless (textures with no edges) glass blocks into slopes using ArchitectureCraft's sawbench.

## Is It Repeatable? Steps to Reproduce: 
Install FTB: Interactions 2.0.3, place a piece of glass from the listed mods into the ArchitectureCraft sawbench, and see that you cannot produce a sloped block.

Glass blocks tested:
* Managlass (Botania)
* Light gray stained glass (Tinkers Construct)
* Glaxx (Xtones)

## Link to Log or Crash File Paste**: 
N/A

## Mod/s Affected: 
ArchitectureCraft?

## Known Fix: 
Is it possibly a config option? I don't know how ArchitectureCraft determines what blocks can and cannot be cut in the sawbench.

**Comment by Saereth** [comment]
ArchitectureCraft has no config or controls over these blocks sadly, what's available is all that can be.

**Comment by Cata-bre** [comment]
I wonder how ArchitectureCraft decides what blocks can be used in the Sawbench. Time to switch to LittleTiles.
