### ISSUE TITLE
Recipe inconsistency with distilling wood gas -> ethylene

### ISSUE THREAD

**Issue by Flame500** [FTBTeam/FTB-Interactions#1048]
## Modpack Version: 
2.0.3

## Bug Report:
Distilling wood gas in a multi-block distillery gives less ethylene than in a single block distillery.

## Expected Behavior/Suggestions:
They should both give the same amount of ethylene

## Is It Repeatable? Steps to Reproduce: 
![Screenshot (250)](https://user-images.githubusercontent.com/66292601/88580454-39257900-d011-11ea-8f55-c23adb4ce069.png)
![Screenshot (249)](https://user-images.githubusercontent.com/66292601/88580530-565a4780-d011-11ea-9815-25df90774540.png)

**Comment by Saereth** [comment]
This is actually intended, ethylene distillation is one route to get ethylene,if you want all the other byproducts you get let ethylene for it, its a trade off to open up different processing options
