### ISSUE TITLE
Dense Titanium Ore Not Able to Be Processed Like Others

### ISSUE THREAD

**Issue by Flying4ssassin** [FTBTeam/FTB-Interactions#1051]
## Modpack Version: 
2.0.4

## Bug Report:
You can get dense titanium ore from the asteroid mining missions, but the only way of processing them is to pulverizing them into dust. In JEI it shows the native cluster, clump, crystal, and blood shard as unobtainable.

## Expected Behavior/Suggestions:
It should work like the other dense ores.

From:
![image](https://user-images.githubusercontent.com/19353597/88604281-1c0a9d80-d045-11ea-9caa-aa0cc63623e9.png)

To:
![image](https://user-images.githubusercontent.com/19353597/88604327-3b092f80-d045-11ea-9735-7561756536bc.png)

**Comment by MaxNeedsSnacks** [comment]
This might be intentional, might the quest description saying "Not all ores can be purified up to the highest degree!"

**Comment by Saereth** [comment]
This is intended, dense titanium ore is a special snowflake ore, it also gives you dust which you can EBF directly instead of using the standard titanium tetrachloride production method
