### ISSUE TITLE
Questbook icon for 'View Dependencies' is nearly invisible

### ISSUE THREAD

**Issue by Burninate** [FTBTeam/FTB-Interactions#1052]
Get through Steam Age on the power questbook page in v2.04.

Click on 'Time to find some liquid freedom' to begin the diesel progression.  Check the box.  Nothing happens.  No clue why.  Nobody else on the server had any clue why either; All the highly active players are stuck at the same percent completion.

Eventually find out from Discord that there's an icon showing hidden dependencies in the top left of the popup dialog.  It's a darker grey triangle on a dark grey background, nearly invisible unless you know what you're looking for.  Realized that this is why a bunch of other less-essential quest items seem to be misbehaving as well.

Simply changing the color to something that jumps out at you would significantly improve UX for people who reach this level.

**Comment by Saereth** [comment]
this is a UI improvement for FTBQuests/Latvian Modder not something pack specific. I'll pass the suggestion (which I agree with) On to him
