### ISSUE TITLE
Gregtech Flintaxe not working

### ISSUE THREAD

**Issue by TheGriffer99** [FTBTeam/FTB-Interactions#1054]
## Modpack Version: 
1.9.1

## Bug Report:
Gregtech axe not breaking logs, it works only with shift but it breaks one block.
I tried to use the ore excavation with the axe but it doesn't work.
I downloaded the pack today, i saw that this issue was already solved time ago, so it shouldn't be a problem to solve it again. 

## Is It Repeatable? Steps to Reproduce: 
This is not my video but this is the issue i'm having right now
https://www.youtube.com/watch?v=oZ4myIj5iUg

**Comment by anabsolutesloth** [comment]
This is fixed in newer versions of GTCE, Update to 2.0+ with a .zip in the pins of the Interactions channel in the FTB Discord.

**Comment by Cata-bre** [comment]
@TheGriffer99 If you use the new FTB Launcher you can download the newer versions of the pack, or you can go through the discord to get the 2.0+ versions. Like @anabsolutesloth said, this bug is fixed in the newer versions of the pack.

**Comment by TheGriffer99** [comment]
I fixed it, i downloaded the FTB Launcher and downloaded the pack from there, i was using twitch launcher and i think the version there is outdated. Now it's working fine.
