### ISSUE TITLE
crashing with update 2.0.4

### ISSUE THREAD

**Issue by Ultimaheart4** [FTBTeam/FTB-Interactions#1056]
## Modpack Version: 
<ftb interactions -2.0.4>

## Bug Report:
<server random crashing, now unable to load world without crashing>

## Expected Behavior/Suggestions:
<random crash of server>
<continue running without issues?>

## Is It Repeatable? Steps to Reproduce: 
<load up a server with basic settings etc with the 2.0.4 pack>

## Link to Log or Crash File Paste**: 
[crash-2020-07-28_14.47.38-server.txt](https://github.com/FTBTeam/FTB-Interactions/files/4990843/crash-2020-07-28_14.47.38-server.txt)
[crash-2020-07-28_14.26.50-server.txt](https://github.com/FTBTeam/FTB-Interactions/files/4990935/crash-2020-07-28_14.26.50-server.txt)
second one is before the server not being able to run, with constant random crashing on world load. it might be advanced rocketry. but not sure.

**Comment by Saereth** [comment]
These are some OS errors, unable to write files, unable to establish loopback connections etc, this does not at all look like a pack specific issue

**Comment by Saereth** [comment]
closing due to no response, re-open if it persists with more info

**Comment by Crystalined** [comment]
So i was able to fix the error by reinstalling both the server and visual c++ and now it works i think it might have been an issue with visual c++ being wierd.
