### ISSUE TITLE
Tick accelerating Astral Sorcery collector crystals causes some blocks/parts of blocks to "drift"

### ISSUE THREAD

**Issue by Flame500** [FTBTeam/FTB-Interactions#1058]
## Modpack Version: 
2.0.3
## Bug Report:
If you tick accelerate a collector crystal, as long as the crystal is on your screen, certain objects will sway left to right.

## Expected Behavior/Suggestions:
It shouldn't cause other blocks to start moving.

## Is It Repeatable? Steps to Reproduce: 

1. Place a chest near a collector crystal
2. TiaB the collector crystal

## Mod/s Affected: 
AS and Random Things

Note that the lid on the jar is shifting
![Screenshot (264)](https://user-images.githubusercontent.com/66292601/88746871-2b581c80-d113-11ea-85a0-bb7beb1f1145.png)
![Screenshot (263)](https://user-images.githubusercontent.com/66292601/88746888-34e18480-d113-11ea-9cc8-09d23965f6c0.png)

**Comment by Hekera** [comment]
https://github.com/lumien231/Random-Things/issues/477

**Comment by Saereth** [comment]
yeah this has been reported, its not a pack thing I can do anything about nor is it game breaking so we'll just let randomthings deal with it
