### ISSUE TITLE
Ore Multiplication System still partially inconsistent

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [FTBTeam/FTB-Interactions#1059]
## Modpack Version: 
2.0.4

## Bug Report:
A lot of clusters still seem to give incorrect amounts of dust, as mentioned in this comment https://github.com/FTBTeam/FTB-Interactions/issues/952#issuecomment-658166702 . This makes ore multiplication for Redstone effectively useless until Blood Shards, and some like Lepidolite for instance don't start benefiting from the new multiplication system until Clathrates / Ore Clumps (which is in HV)

> Here's what I've found so far:
> Redstone - is: 5, should be: 12
> Lepidolite - is: 2, should be: 10,
> Pyrolusite - is: 3, should be: 6
> Bauxite - is: 3, should be: 6
> Ilmenite - is: 2, should be: 6
> Tantalite - is: 2, should be: 4
> Magnesite - is: 5, should be: 10
> Stibnite - is: 3, should be: 6

**Comment by Saereth** [comment]
these are all fixed now
