### ISSUE TITLE
Deep mob learning mob agonizer

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#106]
If you click the block with a thermal dynamics cresent hammer, it resets the block

Submitter: `FTB Interactions#2470`
Body: `**[Quaxitos]** OwO Issue "Deep mob learning mob agonizer" " If you click the block with a thermal dynamics cresent hammer, it resets the block"`
Attachments:

**Comment by Vyraal1** [comment]
Confirmed in-dev instance, will pass it onto Funk.
https://github.com/xt9/DeepMobLearning/issues/19
