### ISSUE TITLE
Radon quest completes without improved eye of ender

### ISSUE THREAD

**Issue by Marzule-90** [FTBTeam/FTB-Interactions#1062]
#710  Modpack Version: 
2.0.4

## Bug Report:
Quest: Radon \m/ completes without having the Improved Ender Eye

Completed the Spinny Go Fast quest and immediately received completion of the Radon \m/ quest.

**Comment by dominic-jones** [comment]
I can't see any info here as to which version this is fixed in but this occurred for me in 2.0.7 also.

**Comment by desagas** [comment]
In 2.0.7 this happens for me as well.
