### ISSUE TITLE
Controls off the screen at 1080p

### ISSUE THREAD

**Issue by CraftalotReloaded** [FTBTeam/FTB-Interactions#1063]
## Modpack Version: 
2.0.4

## Bug Report:
Controls are outside of the screen and thus cannot be read at 1080p 
![image](https://user-images.githubusercontent.com/39203645/88990068-568e6780-d2dd-11ea-9abf-95c76c6bf674.png)

**Comment by Saereth** [comment]
uhh cant do much about this unfortunately, try out:
https://www.curseforge.com/minecraft/mc-mods/tipthescales
