### ISSUE TITLE
OpenComputers Assembler Recipe Conflicts and Annoyances

### ISSUE THREAD

**Issue by Kortako** [FTBTeam/FTB-Interactions#1066]
## Modpack Version: 
2.0.4

## Bug Report:
This is technically a two parter, with a bug from a recipe conflict and a related suggestion about some annoying OC recipes.  I wouldn't mind so much if you didn't need these OC parts to get into AE2 autocrafting.

**Bug:** 
The Microchip (Tier 1) and Control Unit from OC have a conflicting recipe in the assembler, you cannot make the CU because the T1 Microchip takes precedence.  

**Suggestion:** 
In addition to the above, making T1, T2 and T3 microchips annoyingly require the 3 different (non-oredicted) versions of the LV circuit, which is annoying because if you are progressed past a certain point you're likely only going to be making the most advanced one, the Advanced Circuit Parts.

## Expected Behavior/Suggestions:

**Bug:**
There should be a way to make both the CU and the T1 Microchip in the assembler.  Perhaps have both of them use programmed circuits so that they cannot conflict.

**Suggestion:**
Recipes either shouldn't use different versions of the same oredict chip, and instead use programmed circuits as recipe switchers, or you should provide "circuit downgrade" recipes to turn "Advanced Circuit Parts" into "Basic Electronic Circuit" into "Integrated Logic Circuit" (but not the other way around, as that would break progression).

## Is It Repeatable? Steps to Reproduce: 
![2020-07-31_03 29 06](https://user-images.githubusercontent.com/5300243/89027811-0fee3c80-d2e0-11ea-8b7e-6569737100af.png)
![2020-07-31_03 29 14](https://user-images.githubusercontent.com/5300243/89027814-11b80000-d2e0-11ea-8ba6-97efe67e5db4.png)

## Link to Log or Crash File Paste**: 
N/A

## Mod/s Affected: 
OpenComputers

**Comment by Saereth** [comment]
will try and address this in 2.0.6
