### ISSUE TITLE
Suggestion: Remove Hydrogen sulfide from the sulfuric acid quest in LV Chemistry

### ISSUE THREAD

**Issue by bank7** [FTBTeam/FTB-Interactions#1068]
## Modpack Version: 
2.05

The sulfuric acid unlocks polyethylene quest which gives reward but is gated behind hydrogen sulfide which is an inefficient way to make sulfuric acid and also has more steps.

2b Hydrogen + Sulfur dust = 1b Hydrogen sulfide
2b Hydrogen sulfide + water = 3b Sulfuric acid.
Cost for 3b Sulfuric acid = 4b Hydrogen + 2 Sulfur dust + water.

while water + 1 sulfur dust = 3b sulfuric acid.

**Comment by Saereth** [comment]
Yeah agreed, water and sulfur is how I always make mine, probably just selected the wrong cell tbh
