### ISSUE TITLE
Elixir Of Instant Health itemstack bug

### ISSUE THREAD

**Issue by Vyraal1** [FTBTeam/FTB-Interactions#107]
https://clips.twitch.tv/AuspiciousScaryTruffleFunRun

Raj drank 2 elixirs, it looks like it might've consumed both of them.

**Comment by Saereth** [comment]
I cannot reproduce this, was this on a server?

**Comment by Vyraal1** [comment]
Yeah assuming so since they stream together.

**Comment by TheonlyTazz** [comment]
I've had this happen with healing salves I got from dungeons

**Comment by Saereth** [comment]
probably just some weird desync, removing this off the tracker for now as I dont see it going anywhere
