### ISSUE TITLE
Logistics Pipes Fluid Satellite Issues

### ISSUE THREAD

**Issue by MonsoonMT** [FTBTeam/FTB-Interactions#1072]
## Modpack Version: 
2.0.5

## Bug Report:
Connecting fluid satellite  pipe to an assembler causes the world to crash on startup when closed and reopened, without the satellite pipe connected to anything it becomes a tile.logisticspipes.pipename on reload. ~~The pipe placed before the 2.0.5 update functions as intended.~~ Seems to be unnamed pipes that cause the behavior, naming the pipe with a wrench fixed all the issues.

## Expected Behavior/Suggestions:
Normal behavior expected

## Is It Repeatable? Steps to Reproduce: 
Loading my world backup, placing fluid satellite pipe causes the behavior above. Connecting the pipe to an assembler then saving and quitting causes a exception ticking world crash upon attempting to restart the world

Testing on a fresh world does not seem to cause crashing, but the fluid satellite still becomes a generic tile.logisticspipes.pipename on reload. Once power is connected the pipe crashes on new world startup.

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/e6bd1677

**Comment by Saereth** [comment]
This is a mod issue not a pack issue, literally nothing I can do about it, please report it to Logistics pipes here: https://github.com/RS485/LogisticsPipes/issues

 so they can get a fix out
