### ISSUE TITLE
Iron rods issue

### ISSUE THREAD

**Issue by Modernnecro** [FTBTeam/FTB-Interactions#1073]
## Modpack Version: 
2.0.5

## Bug Report:
Iron ingots don't turn into iron rods when using any file except the aluminium file.
Tried using an Emerald file and a Wrought Iron file, in creative used with lvl 3 files and this also doesn't work.
Tried with all in-game materials at that point gathered.
- emerald
- iron
-  Wrought Iron
- Steel
- bronze
- copper
- tin
- brass

## Expected Behavior/Suggestions:
One (or more) of the materials listed above should be able to make iron rods.
Another option would be to tell the player to use blue steel as their file for this, which currently isn't stated.
(or isn't found easily)

## Is It Repeatable? Steps to Reproduce: 
1. Make a (tier one material) file
2. Try make a rod from an iron plate
3. Change file
4. repeat step 2 and 3.

## Mod/s Affected: 
GTCE

## Known Fix: 
Only fix seems to be using a Blue Steel file for the crafting of the first iron rods.
Blue Steel is a "low tier" item (steel and lapis) and only needs an alloy smelter. 
Currently, there's no quest that leads to Blue Steel, which would make creating an iron rod easier.
It's also never specified that it's only certain material levels that can cut iron.

**Comment by Modernnecro** [comment]
Quick addition to this: The Blue Steel file needs higher tier files and hammers as well to make the file-head, OR an  extruder.
The extruder needs iron rods to produce.

**Comment by Saereth** [comment]
![image](https://user-images.githubusercontent.com/9200909/89419905-fdb93780-d6ff-11ea-9129-004185fb3503.png)
![image](https://user-images.githubusercontent.com/9200909/89419981-19bcd900-d700-11ea-9fc4-65612eeb1459.png)
![image](https://user-images.githubusercontent.com/9200909/89420115-43760000-d700-11ea-838d-2719babc79f8.png)
