### ISSUE TITLE
Dolly breaking battery buffer

### ISSUE THREAD

**Issue by wlsnbilyb** [FTBTeam/FTB-Interactions#1074]
#710  Modpack Version: 
2.0.5

## Bug Report:
Used a dolly to pick up an LV Battery Buffer (with 9 sodium batteries inside). When I replaced the block from the dolly, it was invisible and let me see through the floor below it. Also when I tried to break the block it stayed there and just had broken texture particles fly off. Fixed by relogging back into the server, so probably just a client issue.

## Expected Behavior/Suggestions:
Either shouldn't be able to be picked up, or shouldn't cause an issue when picked up.

## Is It Repeatable? Steps to Reproduce: 
1. Place LV Battery Buffer with some batteries inside
2. Pick the block up with the dolly (block may need to be charging while picked up to cause issue)

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/82f0aa5a

## Mod/s Affected: 
Gregtech, Ender Utilities

## Known Fix: 
Relog client

**Comment by OLavagante** [comment]
Same thing happened to me, but by using a dolly on a gregtech chest

**Comment by Saereth** [comment]
yeah Dont dolly gregtech stuff, this wont be fixed, use at your own risk

**Comment by KaseiFR** [comment]
Would it be possible to add GT machines to the dolly blacklist ?

**Comment by abadger** [comment]
@Saereth Note, the dolly blacklist is new since you commented on https://github.com/FTBTeam/FTB-Interactions/issues/569#issuecomment-49014176   (Added via https://github.com/maruohon/enderutilities/commit/fdc27434617d436951cfa6609d3170169fd0835f )

It appears to be in the pack.  The included config/enderutilities.cfg has this:
```
    # A list of blockstates that are not allowed to be picked up
    # by the Dolly (only effective in survival mode!)
    # Use a blockstate string, for example:
    # 'minecraft:gold_block' or 'minecraft:stone[variant=andesite]'.
    # A block name without properties will match all states,
    # for example: 'minecraft:stone'
    # would match smooth stone and all the granite/andesite/diorite
    # variants that are in the same block.
    S:dollyBlockBlacklist <
     >
```
