### ISSUE TITLE
Suggestion: add a recipe for advanced cable clusters from the Super Factory Manager Mod

### ISSUE THREAD

**Issue by guillej08** [FTBTeam/FTB-Interactions#1076]
Modpack version: 2.05

While Super Factory Manager is diverse in terms of it's use, i cannot help but feel that it is still limited in a sense by the fact the advanced cable clusters are uncraftable, and thus cable clusters cannot also act as inventory cables, i would like a recipe for advanced cable clusters to be added to the modpack, or at least know why this recipe was removed

**Comment by Saereth** [comment]
These are not currently implemented in the mod. They cant be placed in world and have no craft recipe by default go yell at the mod dev @TeamDman :P
