### ISSUE TITLE
xtones lshift+scroll not working

### ISSUE THREAD

**Issue by TheGriffer99** [FTBTeam/FTB-Interactions#1077]
## Modpack Version: 
2.0.5

## Bug Report:
If i press lshift and scroll the mousewheel it moves into the item bar instead of changing the block color.

I tried changing key but i have the same issue.

**Comment by Saereth** [comment]
This is working as intended, xtones are set to chisel mode, not scroll in this pack as we use select blocks for custom multiblocks and the scroll action is not configurable as to which blocks you can or cant use

**Comment by TheGriffer99** [comment]
Oh, didn't know that. Thanks +1
