### ISSUE TITLE
Menril Crystal Cant process in Centrifuge

### ISSUE THREAD

**Issue by Crystalined** [FTBTeam/FTB-Interactions#1078]
## Modpack Version: 
2.0.4

## Bug Report:
Ever since update cant process Menril Crystals in Centrifuge. Can still pulverize it but not Centrifuge it.

**Comment by Saereth** [comment]
I've had multiple people confirm this is working for them. Can you send me your latest.log so I can check for script or mod loading issues

**Comment by Crystalined** [comment]
Which log would u like as its on a server?

**Comment by Saereth** [comment]
latest.log

**Comment by Crystalined** [comment]
So i was able to fix the error by reinstalling both the server and visual c++ and now it works i think it might have been an issue with visual c++ being wierd.
