### ISSUE TITLE
Recipe not usable

### ISSUE THREAD

**Issue by Flame500** [FTBTeam/FTB-Interactions#1082]
## Modpack Version: 
2.0.5

## Bug Report:
Recipe takes 141 dusts despite the mod allowing you to stack over 64 items being removed

## Expected Behavior/Suggestions:
Remove the recipe or replace it with something else

## Is It Repeatable? Steps to Reproduce: 
![Screenshot (312)](https://user-images.githubusercontent.com/66292601/89351941-a7ed7c80-d678-11ea-804d-8ef87fbda8a7.png)

**Comment by Saereth** [comment]
What dust is it? This is a GTCE issue anyway but cant tell from your image what it is

**Comment by Flame500** [comment]
Zeolite dust
