### ISSUE TITLE
Won't spawn in the correct world

### ISSUE THREAD

**Issue by Dogylover200** [FTBTeam/FTB-Interactions#1084]
## Modpack Version: 
2.0.5

## Bug Report:
Currently when I try to create a world I have it set to the void world but for some odd reason I don't spawn in the right one, im either teleported into some wizardry cloud dimension or im just on a bedrock platform

Video of it in action, this might be the correct thing I am unsure as when watching others they had spawned on a completely different platform.
https://youtu.be/rexvG64pzBY

**Comment by Saereth** [comment]
you pack install is messed up from the looks of it, try reinstalling and/or send me your latest.log so I can confirm
