### ISSUE TITLE
Misc. recipe fixes & suggestions

### ISSUE THREAD

**Issue by DrTasslehoff** [FTBTeam/FTB-Interactions#1087]
## Modpack Version: 
2.0.5

## Bug Report:
Primal tech wooden basin only has recipes for 4/8 permutations for crafting dough and because it order matters people can fail to craft because of this and not know why. 

EIO stellar alloy should probably be depreciated in favor of GTCE variant. Only situation currently that requires the EIO variant is AE controller craft and a quest

Vacuum freezer recipe for Hot Naquadah Ingot w/cryotheum returns itself rather than the cooled ingot. Cryotheum enderium recipe also returns the depreciated thermal ingot

blue steel screw recipe for EIO power buffer requires the annoying variant requiring a long crafting loop to actually make. Not sure if intentional or not

Mekanism steel casing (required for digital miner) is gated behind osmium ingots

Neromantic prime recipe has teleposition sigil as a requirement but requires 1500 will to craft and because greater tartaric gem needs t4 slates to craft, this is effectively locked behind skystone and space progress. Ichosic resonator upgrade to find oil deposits locked behind stardust and Iridescent altar. There should probably be a quest on crafting and using these as well, to help people in the right direction. I'm somewhat fine on the gating of this I'm just not sure what tech this is supposed to be set up as, and detailing for clarity. 

Enderium ingots still EBF at 4500k despite previous changelogs

Multi-smelter always give a GTCE variant when available, and this means block of skystone -> block of skystone happens. It's just an extra pointless step towards making usable skystone and feels a bit silly to exist if it doesn't need to though. 

Allow impure draconium to be used to craft the Draconic  item dislocator 

Integrated tunnels fluid exporter->importer and importer->exporter recipe conflicts with the self-craft recipe. Add redstone dust to the recipe similar to the item variants

Quests:
"This collector kinda sucks" quest doesn't complete upon crafting a vacuumulator, likely nbt data. This is not a problem in the similar "collecting the drops" quest
Mineralis quest gated behind BM starmetal ore quest and should not be

**Comment by Saereth** [comment]
There is no fix for the multismelter, gtce prioritizes gt materials outputting from the multi-smelter even when when you specifically set it as a another block. hellfire kiln works though.
