### ISSUE TITLE
quests finish prematurely

### ISSUE THREAD

**Issue by Jagholin** [FTBTeam/FTB-Interactions#1093]
## Modpack Version: 
2.0.5

## Bug Report:
Some quests finish prematurely(before necessary materials are collected/submitted). This happened with diesel ("now you see why they call it black gold"). "Im made of plastic" quest also seems to suffer(this one prematurely completes as soon as basic air collector and ethylene cell quests are completed). Bug with diesel quest also happened on direwolf20's letsplay 

## Is It Repeatable? Steps to Reproduce: 
No info. The diesel one seems to be repeatable as it happened both to me and dw20. Whatever this bug is, seems reasonable that some other quests suffer from the same.
dire's video:
https://youtu.be/7z5QXHO9zRc?t=300

## Known Fix: 
just ignoring the rewards seems to do the trick

**Comment by madokaorimura** [comment]
Exist from 2.0.4 if I weren't wrong
