### ISSUE TITLE
Logisitic Pipes - Crafting Recipes disappearing

### ISSUE THREAD

**Issue by NappingPanda** [FTBTeam/FTB-Interactions#1096]
## Bug Report:
When input recipes into the crafting modules for logistic pipes, the inputs and outputs are disappearing from the recipe after exit. I expect this to be a mod issue unsure as I cannot see another bug report regarding this.

## Expected Behavior/Suggestions:
Recipes should remain after exiting
![Before Crafting Module](https://user-images.githubusercontent.com/47096154/89600159-aaccb500-d8a4-11ea-8b53-611efd007414.png)
![After Crafting Module](https://user-images.githubusercontent.com/47096154/89600161-ad2f0f00-d8a4-11ea-939b-b527d85c4305.png)

## Is It Repeatable? Steps to Reproduce: 
1. The items which are forgotten seem to be random. 
2. Use pipe manager on pipe, click on crafting module.
3. Input recipe
4. exit module
5. Re-enter module - see some items have disappeared from recipie

## Mod/s Affected: 
Logistic Pipes

**Comment by Saereth** [comment]
yeah report this to logistics pipes, nothing I can do about it unfortunately. Luckily it hasnt been reported much so doesnt seem to be a wide spread issue but if you can offer any further troubleshooting feel free to reopen this ticket

**Comment by NappingPanda** [comment]
I will send this through to logistics pipes. thanks!

**Comment by Flame500** [comment]
I've found that saving the recipe then picking up and replacing the module before exiting the pipe fixes this.
