### ISSUE TITLE
Trying to make Nether Stibnite Ore into 'dense'

### ISSUE THREAD

**Issue by Mashiek** [FTBTeam/FTB-Interactions#1098]
## Bug Report:
    Nether Stibnite Ore will have the particle effect from a floating crystal and turn to Bismuth Ore when attempting to make Stibnite dense.  Nether Pyrite has the particle effect and turns into Dense Iron Ore.
Nether Tetrahedite has the particle effect and turns into Dense Copper Ore.

**Comment by Saereth** [comment]
This is actually intended upon further review, nether stibnite is not part of the standard 64x chain and was provided as a method to get bismuth later on since it doesnt spawn naturally
