### ISSUE TITLE
Borosilicate glass pulp loop

### ISSUE THREAD

**Issue by Flame500** [FTBTeam/FTB-Interactions#1100]
Incorrect recipe enables an infinite loop to create more Borosilicate dust for glass fibers

![Screenshot (327)](https://user-images.githubusercontent.com/66292601/89609505-ad47f400-d83d-11ea-86a5-4c4e12954840.png)

**Comment by Saereth** [comment]
we are not modifying this recipe, please report to
https://github.com/GregTechCE/GregTech
