### ISSUE TITLE
new signalum recipe

### ISSUE THREAD

**Issue by faqza** [FTBTeam/FTB-Interactions#1102]
## Modpack Version: 

2.0.5
## Bug Report:

wanted to craft some signalum dust. In the recipe it is 3 copper+1silver+576mb of destabilizedredstone, so I put in there 8 silver and 24copper and 8064mb of redstone. And I've got 10 sterling silver dusts
## Expected Behavior/Suggestions:
 signalum dust should have been crafted instead of sterling silver

return old recipe or make it 3 copper dust+1redstone dust+576mb of destabilized redstone
## Is It Repeatable? Steps to Reproduce: 
1.Put in the mixer all the ingredients for more than one craft
2.get yourself sterling silver dust instead of signalum dust

**Comment by Saereth** [comment]
this is already fixed in next update
