### ISSUE TITLE
clay block missing texture

### ISSUE THREAD

**Issue by faqza** [FTBTeam/FTB-Interactions#1105]
## Modpack Version: 

2.0.5
## Bug Report:

when you craft block of clay using clay dust, block itself doesn't have a texture.
## Expected Behavior/Suggestions:
I expected to get clay block

repair clay block texture for that recipe
![2020-08-07_22 05 35](https://user-images.githubusercontent.com/51283209/89670460-ac28cc80-d8fa-11ea-9e98-169fcc930cc0.png)
![2020-08-07_22 05 39](https://user-images.githubusercontent.com/51283209/89670461-ad59f980-d8fa-11ea-937c-b48c32104989.png)
![2020-08-07_22 05 42](https://user-images.githubusercontent.com/51283209/89670463-ad59f980-d8fa-11ea-8b1b-ac0982678c9f.png)

**Comment by madokaorimura** [comment]
Can't reproduce the issue (same version)

**Comment by Saereth** [comment]
I also can't reproduce this
