### ISSUE TITLE
Autoclave eats sapphire

### ISSUE THREAD

**Issue by sgtkwol** [FTBTeam/FTB-Interactions#1106]
## Modpack Version: 
2.0.5

## Bug Report:
Autoclave (MV if that matters) eats sapphire when water is used as the fluid. JEI shows either starlight or water can be used to create aquamarine.

## Expected Behavior/Suggestions:
If recipe is invalid, would expect nothing to happen and for it not show in JEI. Starlight recipe works as intended.

## Is It Repeatable? Steps to Reproduce: 

Yes, repeated with second sapphire and it was also lost.

## Link to Log or Crash File Paste**: 
no log

## Mod/s Affected: 
GTCE/Astral Sorcery

**Comment by faqza** [comment]
when you use water or distilled water, there is a chance to get gem. When you use liquid starlight, you 100% get a gem

**Comment by sgtkwol** [comment]
Nevermind, derp on my end. Closing.
