### ISSUE TITLE
screen freezing with gregtech steam machines

### ISSUE THREAD

**Issue by iah11** [FTBTeam/FTB-Interactions#1109]
## Modpack Version: 
2.0.6, also happens in 2.0.5
## Bug Report:

a freezing of the screen, seemingly still runs the game because esc hides and shows the cursor. it will eventually go black if you let it sit, or alt tab/windows key to something else

## Is It Repeatable? Steps to Reproduce: 
sort of
1.interact with gregtech steam machines*
2.wait
*they might have to be processing something for the crash to happen, I have had it happen mostly when interacting with them while they were doing something, but some were just while I was waiting for them to finish

## Link to Log or Crash File Paste**: 
none, doesn't technically crash

also it occasionally makes me update the launcher, else it will get stuck on the loading screen

**Comment by Saereth** [comment]
I cant reproduce this at all, gonna need a video or some more info or something

**Comment by madokaorimura** [comment]
It is chance to get that problem tho, although the issue is cause by performance (｀ε´)

**Comment by iah11** [comment]
https://www.youtube.com/watch?v=xH9l2elXBBM (link to video, skip to 24 min) (I apologize about the watermark, couldn't get xbox game bar working)

quick note: I have played enigmatica 2 expert to near endgame without crashes, and am getting 60 fps, so it is probably not solely hardware based
CPU: Intel® Core™ i5-1035G7 Processor
GPU: none (Integrated)
RAM: I'm not 100% sure what model, but I have 1 16 gig stick. (laptop ram)
Storage:16Gig optane, plus a ~250 gig SSD (task manager says 238, product page says 256?)

**Comment by iah11** [comment]
I just had this happen with no machines running (v2.0.9), while right clicking a basic worktable during a lag spike. I can also confirm that at least LV machines (I would assume higher, not tested) also cause this. also, I found it is possible to hide the cursor by clicking the screen where the back to game button would be from the escape screen.

**Comment by iah11** [comment]
actually my centrifuge might have been running in the background, not sure.

**Comment by Saereth** [comment]
well I definitely see your issue from the video, unfortunately I cant reproduce it myself so I suspect it is something with your os environment and/or hardware

**Comment by Saereth** [comment]
this one is beyond me, sorry dude
