### ISSUE TITLE
Clay dust recipe

### ISSUE THREAD

**Issue by Sharkum** [FTBTeam/FTB-Interactions#1113]
## Modpack Version: 
2.0.6

## Bug Report:
Clay dust can be directly from clay blocks in logistics pipes request table and autocrafting tables.

## Expected Behavior/Suggestions:
The clay dust should only be crafted using a mortar or a macerator

## Is It Repeatable? Steps to Reproduce: 
yes
1.copy the recipe of clay dust from clay block from jei
2.use the arrow buttons in the lp table ui to change the recipe to that of clay dust

## Link to Log or Crash File Paste**: 
it doesnt cause a crash

## Mod/s Affected: 
no mods seem to be affected

**Comment by Saereth** [comment]
this is a bug with Logistics pipes, please reopen this if its still happening after 2.0.7 update which updates LP to fix this

**Comment by Sharkum** [comment]
It still works after the update
