### ISSUE TITLE
AE2 Dense Cable Decombining Recipe Bug

### ISSUE THREAD

**Issue by Kortako** [FTBTeam/FTB-Interactions#1117]
## Modpack Version: 
2.0.6

## Bug Report:
There is a typo in the script file such that the Dense Cable (Black) turns into 8 Smart Cable Fluix, instead of Dense Cable (Fluix).  The metadata is 75 instead of 76, off by one.

Also, I believe that Dense cables should be craftable/decraftable with only 4 Smart Cables instead of 8.  The recipe to make dense cables from covered cables still only uses 4 fluix cables, and it makes more sense anyway, since each smart cable gives 8 channels, and a dense cable gives 32.

## Expected Behavior/Suggestions:
**Bug**: Dense Cable (Fluix) should craft into 8 (or 4) Smart cables, not the colored version.

**Suggestion**: Change the conversion ratio from 8 to 4.

## Known Fix: 
**Fix Only**:
Change line 770 of AppliedEnergistics2.zs to:
```
recipes.addShaped(<appliedenergistics2:part:76>, [[<appliedenergistics2:part:56>, <appliedenergistics2:part:56>, <appliedenergistics2:part:56>],[<appliedenergistics2:part:56>, null, <appliedenergistics2:part:56>], [<appliedenergistics2:part:56>, <appliedenergistics2:part:56>, <appliedenergistics2:part:56>]]);
```

**Fix + Suggested Change:**
Change lines 769 and 770 to:
```
recipes.addShapeless(<appliedenergistics2:part:56> * 4, [<appliedenergistics2:part:76>]);
recipes.addShaped(<appliedenergistics2:part:76>, [[<appliedenergistics2:part:56>, <appliedenergistics2:part:56>],[<appliedenergistics2:part:56>, <appliedenergistics2:part:56>]]);
```

**Comment by madokaorimura** [comment]
Look at changelog, thanks
