### ISSUE TITLE
EV Metallurgy Tab Name

### ISSUE THREAD

**Issue by OneStrangeOnion** [FTBTeam/FTB-Interactions#1119]
## Modpack Version: 
2.0.6

## Bug Report:
EV Metallurgy tab name displays incorrectly

![2020-08-08_17 56 54](https://user-images.githubusercontent.com/33072292/89721352-2eb89700-d9a2-11ea-858d-6dee13baa841.png)

**Comment by madokaorimura** [comment]
Duplicate #1107
