### ISSUE TITLE
I can't play multiserver

### ISSUE THREAD

**Issue by igameta** [FTBTeam/FTB-Interactions#112]
## Modpack Version: 
1.0.1

## Bug Report:
My English may be wrong Because I use Google Translate
I opened this modpack Server but there was nothing in the world when it was spawned
I recreated the world but nothing changed
## Expected Behavior/Suggestions:
I don't know

## Is It Repeatable? Steps to Reproduce: 
1.Download serverfile from curseforge
2.Start the server without making any changes
3.https://www.youtube.com/watch?v=OIl-EmLoZn0&feature=youtu.be

## Link to Log or Crash File Paste**: 
All log files are garbled

## Mod/s Affected: 
I don't know

## Known Fix: 
I don't know

**Comment by Ludi87** [comment]
"For server owners, make sure in server.properties that level-type=voidworld as this enables initial island generation and island control commands on servers."

**Comment by TeamDman** [comment]
What ludi said is correct, if setting the level-type doesn't fix then feel free to create another issue.
We don't ship server.propreties files since it would overwrite user changes on updates.

**Comment by igameta** [comment]
Thank you
