### ISSUE TITLE
ME controller quest and craft

### ISSUE THREAD

**Issue by faqza** [FTBTeam/FTB-Interactions#1120]
# Modpack Version: 

2.0.6
## Bug Report:

1. ME controller craft does require GTCE block of stellar alloy instead of both of them(GTCE and EIO);
2.  "Flip your channels" quest doesn't give you 7 ME controllers as it is supposed to do;
3. ME glass fluix cables, which are used in the crafting, drop themselves when craft starts so they don't spend
## Expected Behavior/Suggestions:

1. I expected to use EIO variant of stellar alloy block
2. I wanted my 7 ME controllers!
3. Expected to spend 12 cables, which are used in the recipe

1. ME controller should take both variants of blocks
2. Quest must give written reward
3. remove cables from that craft. They are not that expensive and maybe hard to fix it

Also, there are some screenshots:
![2020-08-09_22 57 33](https://user-images.githubusercontent.com/51283209/89738814-0a89b280-da95-11ea-9e30-6138b2b73f00.png)
![2020-08-09_22 57 44](https://user-images.githubusercontent.com/51283209/89738819-14131a80-da95-11ea-9399-1d4588a2eeca.png)
![2020-08-09_23 03 54](https://user-images.githubusercontent.com/51283209/89738822-15dcde00-da95-11ea-8520-108aba4214d5.png)
![2020-08-09_23 04 33](https://user-images.githubusercontent.com/51283209/89738826-19706500-da95-11ea-93b1-a18211baf3ad.png)
![2020-08-09_23 06 33](https://user-images.githubusercontent.com/51283209/89738829-1b3a2880-da95-11ea-875c-2ffa72351d06.png)

**Comment by faraday326** [comment]
I just hit the quest-reward-bug here. 

repro: finish the quest, and then try to get the reward with an ME controller in your inventory. You'll get nothing.

If you _do_not_ have an ME controller in your inventory, however, you will get the 7 ME controllers.

**Comment by Saereth** [comment]
the quest reward bug has already been reported, the type specific stellar alloy block I cant do anything about. compact machines doesnt accept oredicting and I tried a duplicate recipe with both blocks and the one takes precedence so no good, we're stuck with that but thats why I added an easy recipe to convert between the two types
