### ISSUE TITLE
Native Cobaltite Cluster yield

### ISSUE THREAD

**Issue by KaseiFR** [FTBTeam/FTB-Interactions#1123]
# Modpack Version: 
2.0.0

## Bug Report:
The Native Cobaltite Cluster yields 2 crushed ores instead of 6 when macerated.

## Is It Repeatable? Steps to Reproduce: 
![2020-08-09_20 16 02](https://user-images.githubusercontent.com/6408124/89738976-2c773b00-da7d-11ea-8d71-6ac859dc6028.png)

## Mod/s Affected: 
Gregtech

## Known Fix: 
I got kind of overboard and patched the entire metallurgy script to use the GTCE recipes when possible (see this [patch](https://pastebin.com/XyqzB09e)).

**Comment by madokaorimura** [comment]
Can you update the pack?
Since we have come to 2.0.6 tho

**Comment by KaseiFR** [comment]
I misreported the pack version, I was actually on 2.0.6. My patch should still be usable for 2.0.7.

**Comment by Saereth** [comment]
oh Sorry I didnt run it since I thought you patched way out of date so I only did cobaltite manually
