### ISSUE TITLE
Cannot make Hay Bales in a compressor

### ISSUE THREAD

**Issue by griseouslight** [FTBTeam/FTB-Interactions#1127]
## Modpack Version: 
 2.0.6

## Bug Report:

Technically a duplicate of #909. Compressors can only make a plant ball using wheat. I wasn't sure whether or not to comment there or leave another issue, so I apologize if I chose incorrectly. 

## Expected Behavior/Suggestions:

The compressor will always use 8 wheat to make a plant ball and never use 9 to make a hay bale.

## Is It Repeatable? Steps to Reproduce: 

https://gfycat.com/thornycoldchrysomelid

**Comment by Saereth** [comment]
yeah this is unfortunately too much work to fix because I'd have to remove the base recipe which is a plant oredict and readd everything minus wheat or remove wheat from the plant oredict, neither are attractive options. I am going to just add a forge hammer recipe for the hay bale
