### ISSUE TITLE
Ender Fluid Conduits Round Robin does not work

### ISSUE THREAD

**Issue by rickyjay1990** [FTBTeam/FTB-Interactions#1130]
#710 Modpack Version: 
v2.06
## Bug Report:
I am trying to extract methane from an LV centrifuge to power 2 lv gas turbines. Both are the turbines are the same distance away from the centrifuge, on the same colour and set to the same priority. Rather than splitting equally between both turbines the conduits  prioritises one turbine over the other.

## Is It Repeatable? Steps to Reproduce: 

1. Centrifuge receiving menril and enough power to run correctly without being overclocked
2. Items are extracted from one side and liquids extracted from the front facing side
3. Methane is sent to the gas turbines and bi-product is being sent to a liquid trash can with a fluid filter or a lower priority to the turbines.

## Mod/s Affected: 
Greg Tech
EnderIO

**Comment by Saereth** [comment]
this is an Enderio issue, you'll have to bring it up with them@ https://github.com/SleepyTrousers/EnderIO/issues
if they get a fix for it I'll update the mods accordingly
