### ISSUE TITLE
Mod Request: AE2 Network Visualiser

### ISSUE THREAD

**Issue by Hachuurui** [FTBTeam/FTB-Interactions#1131]
I build large AE2 p2p networks and was missing the lack of the ae2 stuff visualization tool. Then I realized the mod hasn't been updated in ages. While searching for a substitute, I noticed Brandon had been working on a similar item and it appears to be functional even if in a beta state... Could you consider adding it to aid in AE2 automation and p2p networks?

https://www.curseforge.com/minecraft/mc-mods/ae2-network-visualiser

If your wondering its from the same guy who works on Draconic Evolution. Also, I can spend time testing the mod for you ahead of time for stability if you like. Just let me know.

**Comment by Saereth** [comment]
Request approved, will be in 2.0.7
