### ISSUE TITLE
The axe in the tutorial sky block world will not break tree

### ISSUE THREAD

**Issue by Bryophy98** [FTBTeam/FTB-Interactions#1133]
## Modpack Version: 

1.9.1
## Bug Report:

Okay I have been working through the tutorial and I am up to the point where you can make an axe that has the timber mod built in. I was looking forward for that but it bugged out because the percentage keeps resetting at 80% and never breaks the tree block. I can break them with the hatchet so that is why I think it is the axe issue.

## Expected Behavior/Suggestions:
it loops the breaking block progress bare 
it should break the tree block

## Is It Repeatable? Steps to Reproduce: 

1.
2.

**Comment by MaxNeedsSnacks** [comment]
You're using version 1.9.1 of the pack, which is the last version of FTB Interactions published on CurseForge and also severely outdated. Please try to replicate this with 2.0.6 from the new [FTB App](https://www.feed-the-beast.com/), which *should* have fixed this (and probably) some other issues you may be encountering and also has a lot of new features (the exact changelog can be found [here](https://hastebin.com/raw/oyosedajax))

**Comment by Bryophy98** [comment]
Oh thanks for the help

**Comment by Saereth** [comment]
yep newer version of the pack fixes this
