### ISSUE TITLE
Cyclic Fluid Node Transfer Rate does not change with GUI

### ISSUE THREAD

**Issue by bukschr** [FTBTeam/FTB-Interactions#1134]
## Modpack Version: 
2.0.6
## Bug Report:
Cyclic fluid transfer nodes do not transfer at a different rate than 500mB/t

## Expected Behavior/Suggestions:
Changing the transfer rate should change the transfer rate per GPS marker.

## Is It Repeatable? Steps to Reproduce: 
1. Change transfer rate in dluid transfer node GUI.
2. Nothing changes with the transfer rate.

## Mod/s Affected: 
Cyclic

## Known Fix: 
I do not know a fix.

**Comment by madokaorimura** [comment]
Erh, you should report it to mod author instead of report in here →_→

**Comment by Saereth** [comment]
This yeah, there is nothing I can do from a pack perspective to address this, please report to https://github.com/Lothrazar/Cyclic/issues and I'll update the mod as soon as there is a fix
