### ISSUE TITLE
Crash due to TC Crafting Table

### ISSUE THREAD

**Issue by MukizuL** [FTBTeam/FTB-Interactions#1135]
## Modpack Version: 
v. 2.0.6

## Bug Report:
Crash while using TC Crafting table.

## Is It Repeatable? Steps to Reproduce: 
It is repeatable, but I don't know how to reproduce it.

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/65298a16 - Updating screen events
https://paste.feed-the-beast.com/view/6700819b - Error executing task

## Mod/s Affected: 
Minecraft identifies Tinkers' Construct and Mantle as potential problem.

**Comment by madokaorimura** [comment]
Get your game better performance (≧ڡ≦*)

**Comment by MukizuL** [comment]
Is that so? I didn't have such problem on 1.9.1 with the same setup. And if it is a performance issue, what is the solution? Btw I just load the world and keep playing.

**Comment by Saereth** [comment]
this is a long standing bug with tinkers crafting stations attempting to render and item in them that dont have proper rendering implementations, you can search for a bunch of closed issues on their github for it, the dev doesnt seem interested in fixing it so not much I can do about it unfortunately

**Comment by madokaorimura** [comment]
> Is that so? I didn't have such problem on 1.9.1 with the same setup. And if it is a performance issue, what is the solution? Btw I just load the world and keep playing.

Restart game seem to be my solution to this

**Comment by Saereth** [comment]
yes restarting generally solves this
