### ISSUE TITLE
Advanced Rocketry Planet Discovery is disabled, rendering artifacts unnecessary

### ISSUE THREAD

**Issue by Jimmy469** [FTBTeam/FTB-Interactions#1137]
## Modpack Version: 
2.0.6 

## Bug Report:
It is possible to travel to Euclydes/Aurelia without using the artifacts. This is because the planets are "discovered" by default.

## Expected Behavior/Suggestions:
"Planet Discovery" steps should be required to travel to those planets.

## Is It Repeatable? Steps to Reproduce: 
https://youtu.be/Uac1IV1XUgY?t=861

## Link to Log or Crash File Paste**: 
No Crash

## Mod/s Affected: 
Advanced Rocketry

## Known Fix: 
I have not tested this fix. These are the config values I know of that affect planet discovery.

In /config/advRocketry/planetDefs.xml
`37: <isKnown>true</isKnown>`
`54: <isKnown>true</isKnown>`
should both be set to false.

In /config/advRocketry/advancedRocketry.cfg
`685: B:planetsMustBeDiscovered=false`
should be set to true

**Comment by Saereth** [comment]
we have always had planetary discovery off and this should work as per the AR config wiki
![image](https://user-images.githubusercontent.com/9200909/90294613-daeff700-de54-11ea-8007-635be9cf1124.png)

It -used- to work to prevent warping but a recent update broke then, I opened a bug report over at AR and im hoping for a quick fix but its up to that dev, as a temporary work around I'm doing some code on our end to boot players back to overworld that get to a dimension without the correct gamestaging (having crafted the artifact)

https://github.com/zmaster587/AdvancedRocketry/issues/1896
