### ISSUE TITLE
ME Controller quest reward bug

### ISSUE THREAD

**Issue by Jimmy469** [FTBTeam/FTB-Interactions#1138]
## Modpack Version: 
2.0.6

## Bug Report:
The ME Controller quest only grants rewards if you do not have a ME controller in your inventory.

## Expected Behavior/Suggestions:
The ME Controller quest grants rewards regardless of whether or not you have a ME controller in your inventory

## Is It Repeatable? Steps to Reproduce: 
https://youtu.be/y6voYzU2EEU?t=1324

## Link to Log or Crash File Paste**: 
No Crash

## Mod/s Affected: 
FTBQuests

## Known Fix: 
As shown in video (at https://youtu.be/y6voYzU2EEU?t=1365): Set "Only One" to false.
Quest data is in file /config/ftbquests/normal/chapters/a4a70422/f306951c.snbt
`25: only_one: true`
should be set to false

**Comment by Saereth** [comment]
indeed this is meant to be set as a non team reward instead of one only, fixed in next update, ty for the report
