### ISSUE TITLE
Nether Wart Chicken not in dungeon chests

### ISSUE THREAD

**Issue by algul** [FTBTeam/FTB-Interactions#1139]
## Modpack Version: 
2.0.6

## Bug Report:
Nether wart chicken is not found in nether dungeon chest as the quest book suggests. Looking at the config file for nether chests its not listed in there.

## Mod/s Affected: 
Roost
DLDungeons

**Comment by Saereth** [comment]
it spawns in VANILLA nether dungeons/fortresses, this is not a bug

**Comment by algul** [comment]
In that case its quest description error, because it does not says "vanilla" nor "fortress" , just "nether dungeon".

**Comment by Saereth** [comment]
I'll clarify the quest text and actually add them additionally to dml nether dungeons next update, re-opening to remind myself
