### ISSUE TITLE
Nicer fluid ratios

### ISSUE THREAD

**Issue by redcatone** [FTBTeam/FTB-Interactions#1142]
So the standard fluid ratios in modded are 16mb per nugget and thus 144mb per ingot. Using a base 9 or 16 system is ideal to have nicer fluid ratios so you don't end up with weird excess amounts. (Assuming you don't need to bucket stuff in which case the 1,000mb base 10 ratio throws everything for a loop).

The following suggestions should be pretty safe to not interfere with other recipes or overall balance given these fluids don't have many uses. Energy suggestions try keep it similar to the old ratios while also providing nice numbers.

#### Light concrete solidifying
Currently takes 1296mb (144×9) to solidify to 9 light concrete blocks but the mixing recipe makes 576mb (144×4) liquid concrete. Suggestion to change the recipe to 576mb for 4 blocks or 1440mb for 10 blocks. Liquid concrete is also used in 576mb batches to create vanilla concrete blocks in the mixer.

Fluid (mb) | 1296 | 576 | 1440
-- | -- | -- | --
Total EU | 4200 | 1820 | 4760
EU/t | 14 | 14 | 14
Total time | 15s (300t) | 6.5s (130t) | 17s (340t)
EU per block | 466.6667 | 455 | 476

#### Concrete chicken
Currently needs 10,000mb of liquid concrete to make leaving an excess of 368mb. Suggestion to change the liquid requirement to 10,368mb (144×72 or 576×18) or 9,216mb (144×64 or 576×16).

No energy change suggestion given that you will only need a handful of chickens created this way so its energy requirements are pretty insignificant.

#### Concrete enriched egg
Currently makes 100mb of liquid concrete whereas all recipes utilizing liquid concrete use it in 144mb ratios. Suggestion to have the egg make 72mb or 144mb.

Fluid (mb) | 100 | 72 | 144
-- | -- | -- | --
Total EU | 360 | 270 | 540
EU/t | 18 | 18 | 18
Total time | 1s (20t) | 0.75s (15t) | 1.5s (30t)
EU per mb | 3.6 | 3.75 | 3.75

#### Polywhatsit enriched egg
Currently makes 10mb polycaprolactam whereas all recipes utilizing polycaprolactam use it in 144mb ratios. Suggestion to have the egg make 9mb or 16mb.

Fluid (mb) | 10 | 9 | 16
-- | -- | -- | --
Total EU | 48 | 48 | 72
EU/t | 12 | 12 | 12
Total time | 0.2s (4t) | 0.2s (4t) | 0.3s (6t)
EU per mb | 4.8 | 5.333333 | 4.5

#### Plastic chicken
Currently needs 2,000mb of polyethylene to make. Suggestion to change the liquid requirement to  2,160mb (15×144 or 10×216).

No energy change suggestion given that you will only need a handful of chickens created this way so its energy requirements are pretty insignificant.

---

There is also a bunch of weirdness around GTCE chemical processes like ethylene, polyethylene, etc. which switch between base 10 and 9 systems but would require so much rebalancing of various fluid ratios and recipes that it doesn't seem really feasible and instead should be taken to the GTCE devs.

- Ethanol and sulfuric acid are produced in a base 10 system.
- Ethylene is produced from the above chemicals to give a base 10 amount of ethylene.
- Ethylene is used in base 9 amounts to make polyethylene except for the recipe involving plastic eggs which makes polyethylene in base 10 amounts. All other uses for ethylene use it in base 10 amounts.
- Polyethylene is used in base 9 amounts except for polyvinyl chloride in which it needs a base 10 amount.
- Polyvinyl chloride is made in base 10 amounts but only used in 144mb ratios

**Comment by Saereth** [comment]
k fixed all those, the other ratios should goto gtce yeah
