### ISSUE TITLE
Thaumcraft - Ancient & Eldritch Stones Unobtainable

### ISSUE THREAD

**Issue by DracoShadow** [FTBTeam/FTB-Interactions#1144]
## Modpack Version: 
2.0.6

## Bug Report:
Ancient and Eldritch stones are unobtainable, despite their (normally uncraftable) infusion pillars having crafting recipes added in. Unless they worldgen somewhere and I'm unaware of this, they're missing recipes.

## Expected Behavior/Suggestions:
Suggestions: Add a crafting recipe to these stones.

## Is It Repeatable? Steps to Reproduce: 
N/a

## Link to Log or Crash File Paste**: 
N/a

## Mod/s Affected: 
Thaumcraft

## Known Fix: 
See suggestion.

**Comment by Saereth** [comment]
they worldgen in thaumcraft dungeons, this is intended

**Comment by DracoShadow** [comment]
I apologize for my ignorance, could you please tell me where they generate? I have yet to encounter one so far, are they perhaps on the moon or ?

**Comment by Saereth** [comment]
Thaumcraft dungeons in overworld, particularly in swamps and magical forest biomes, they are rare
