### ISSUE TITLE
Probable crash due to interaction with fluid pump (Industrial Foregoing)

### ISSUE THREAD

**Issue by PedroAfonsoAlmeida** [FTBTeam/FTB-Interactions#1145]
## Modpack Version: 
2.0.6

## Bug Report:
Probably this that cause the crash.
Interacted within the fluid pump (Industrial Foregoing) with an empty bucket and reproduced the crash report.

## Expected Behavior/Suggestions:
maybe I should be able to collect the oil that was inside the fluid pump but it didn't 

## Is It Repeatable? Steps to Reproduce: 
right-click a Fluid pump
Click on the fluid( oil in this case)
No idea if it happens again

## Link to Log or Crash File Paste: 
https://paste.feed-the-beast.com/view/dd657af4

**Comment by Saereth** [comment]
this is a rare bug with if pumps pumping, hardly ever happens so hard to pin down get info for etc. Please report to industrial foregoing mod dev as this is not a pack issue I can do anything about
