### ISSUE TITLE
Clay dust still craftable in logistics pipe tables.

### ISSUE THREAD

**Issue by Sharkum** [FTBTeam/FTB-Interactions#1150]
## Modpack Version: 
2.0.7

## Bug Report:
You can still craft clay dust from clay blocks in the logistics pipes crafting table

## Expected Behavior/Suggestions:
suggestions: maybe remove the recipe of clay dust from clay blocks as it is not used for anything.

## Is It Repeatable? Steps to Reproduce: 
Yes
1.Put a clay block in the recipe 
2.select the clay dust output using the arrows
3.You can even autocraft clay dust this way

## Link to Log or Crash File Paste**: 
N/A

## Mod/s Affected: 
N/A

**Comment by Saereth** [comment]
Stop reporting this here. It's a logistics pipes issue, yell at them, literally nothing we can do about it
