### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Sharkum** [FTBTeam/FTB-Interactions#1152]
## Modpack Version: 
2.0.7

## Suggestions:
Could you please add storage drawers to the pack. You can alter their recipes so they might not be accesible as early as barrels or cache so that players still use them. You can even disable the compacting drawers. There isnt much that can be used like a 2x2 drawer or the different upgrades like redstone control and downstack upgrades in the pack.

**Comment by Saereth** [comment]
No

**Comment by Sharkum** [comment]
Lmao

**Comment by Saereth** [comment]
Just to clarify, storage drawers was of course considered many times but there are a ton of reasons its not in the pack, the biggest issues are redundancy, performance, and removing a lot of inventory management challenges. If they were in the pack the storage controller wouldnt be, at which point there is little reason for them over the other options in the pack.

**Comment by Sharkum** [comment]
Yeah, The storage controller can even render AE storage disk useless thanks to the storage bus. I wish there was a better way to store items from farms than 18 barrels with 18 storage busses.

**Comment by Saereth** [comment]
look into the Variable storage unit from ender utilities, you can configure it from up to 1 to 27 stacks and the stack size can be in the thousands, you can also lock each slot type independently to a specific item, doing this you can create a massive cache of all your crops like this with a single block/single storage bus and just a low priority conduit to a trashcan to handle overflow

**Comment by Sharkum** [comment]
Thanks. That solves a lot stuff actually. Haven't played with ender utilities a lot. I will check out other mods while I'm at it to find stuff like this. Also the gregtech in the pack is done really well, I have never gotten this invested into a pack ever.
