### ISSUE TITLE
teletrasporto

### ISSUE THREAD

**Issue by FireSniper03** [FTBTeam/FTB-Interactions#1156]
come mai mi dice che non ho ipermessi per utilizzare il teletrasporto?

**Comment by Saereth** [comment]
welp google translate tells me
"why does he tell me that I don't have permission to use teleportation?" 

You'll need to be more specific, what's telling you that, what are you trying to do etc, this is not really a proper issue report, please create a new issue with the actual problem and more details or reopen this one with edits
