### ISSUE TITLE
Actually Additions Growth Ring not Craftable

### ISSUE THREAD

**Issue by b0bst3r** [FTBTeam/FTB-Interactions#1158]
## Modpack Version: 
2.0.7

## Bug Report:
Actually Additions Growth Ring not craftable, bonemeal which is written in actuallyadditions.zs recipe does not show up in recipe in game.

## Is It Repeatable? Steps to Reproduce: 
1. Try crafting AA growth ring, no output is shown even with max astral aura in starlight crafting altar

## Link to Log or Crash File Paste**: 
N/A

## Mod/s Affected: 
Actually Additions 
Crafttweaker

## Known Fix: 
In ActuallyAdditions.zs the entry is:- 

```
#growth
recipes.remove(<actuallyadditions:item_growth_ring>);
mods.astralsorcery.Altar.addAttunementAltarRecipe("interactions:aagrowthring", <actuallyadditions:item_growth_ring>, 350, 200, [
	<ore:bonemeal>, <botania:manaresource:17>, <ore:bonemeal>,
	<botania:manaresource:17>, <ore:ringBrass>, <botania:manaresource:17>,
	<ore:bonemeal>, <botania:manaresource:17>, <ore:bonemeal>,
	<ore:powderMana>, <ore:powderMana>, <ore:powderMana>,<ore:powderMana>]);
```
However bonemeal is not oredict as that, it's either dustBone or one of the dye ones.  I can't find a custom entry adding bonemeal to a ore:bonemeal entry, so replacing ```<ore:bonemeal> with <ore:dustBone>``` should fix this.

Edit:
Tested with ```<ore:dustBone>``` in place of ore:bonemeal and recipe now works.

**Comment by Saereth** [comment]
this is due to a recent GTCE change, will be fixed in the next udpate of SoG 
also duplicate
https://github.com/FTBTeam/FTB-Interactions/issues/1154

**Comment by b0bst3r** [comment]
It's an entirely different issue to the advanced rings.

**Comment by Saereth** [comment]
Its a different issue to the advanced ring, the bonemeal oredict being broke is effecting several recipes and has been reported to me in a few places, I've already got it fixed in dev though
