### ISSUE TITLE
teletrasporto 

### ISSUE THREAD

**Issue by FireSniper03** [FTBTeam/FTB-Interactions#1159]
ho appena iniziato a giocare a questo modpack è sono inesperto. Voglio teletrasportarmi tramite i waypoints, l’unico problema è che appena schiaccio teletrasporta sulla chat di gioco mi appare la scritta “non hai i permessi per farlo” consigli?

**Comment by madokaorimura** [comment]
You need to open Cheat mode in order to use Waypoint teleport

**Comment by Saereth** [comment]
yeah, you need to turn on cheat mode or be op on a server for that to feature to work
