### ISSUE TITLE
Recipe for nocturnal powder

### ISSUE THREAD

**Issue by Sharkum** [FTBTeam/FTB-Interactions#1161]
## Modpack Version: 
2.0.7

##Suggestions:
There is no way to automate starlight crafting altar. Most of the recipes dont need to be automated but recipes like nocturnal powder needed for blood magic slates cant be automated.
You can maybe add a recipe of nocturnal powder that uses starlight but so that it can be automated.There is also the option of adding a modular machine to allow autocrafting in the altar.

**Comment by Saereth** [comment]
You really dont need nocturnal or illumination powder as part of continuing automation, you can just bulk craft 6-7 stacks and it should last you the entire pack. There really is no great way to ensure the use requirements of both enough starlight production and the altar in a machine so even if it did get a recipe it'd probably require something that is still tied to those progression steps and probably an hv mixer, I'll give it some thought though but being able to fully automate it means it becomes an easy viable and permanent mob spawning solution which is not really desirable here.

**Comment by Sharkum** [comment]
I forgot nocturnal powder could create mob farms. Although it doesn't boost mob spawn and there really isn't much use in creating a mob farm considering how easily you can get into deep mob learning.

**Comment by crusader3456** [comment]
I will say that Illumination powder is needed more.  Especially since shifting Stars are needed for the Cyclic Fluid Transfer nodes.  Perhaps add a method of creating them with the Sky Cauldron multiblock?

**Comment by Sharkum** [comment]
I think the fluid transfer node need that shifting star to be crafted manually just to balance them. You can pipe 9 machines with a fluid and you can even control them with redstone. They are very overpowered in gregtech especially moving all the different chemicals around. So if you could automate them they would make other fluid transfer methods unviable, like LP or AE2.

**Comment by dominic-jones** [comment]
Agree with the transfer node. I got better throughout than a LP Fluid Provider (though I think piping into a Fluid 
Insertion pipe is the better answer throughout wise). However they could not remotely handle the throughput required for a turbine so they do get obsoleted for some things.

One reason for wanting more wireless is arguably for frame rate reasons. With 95% of fluids going through my LP network the game is getting pretty slow.

Also, whilst more expensive, the Dimensional Transceiver is very easy to automate (even more than it's base recipe). But, getting very off topic.

On the one hand I like automating the powders, but I'd also be wary of too much tech-ifying the magic systems.

**Comment by Saereth** [comment]
Im going to be adding a nightmare chicken soon, I'll probably use that and the astral chicken egg in the sky cauldron to create these materials (along with their other materials). This gates it sufficiently but is ultimately automatable should people really want to go that route

**Comment by Sharkum** [comment]
Nice nightmare chicken sounds cool. Thank you for adding it.

**Comment by crusader3456** [comment]
I wasn't suggesting that the Fluid Transfer Node be made autocraftable, rather that having several of its components also be made autocraftable is annoying.  Considering the Illumination Powder is used a bit more than the shifting Star and is easier base to make, allow it to be automatable, leaving the sifting star as the only piece non automatable.

**Comment by Sharkum** [comment]
I am bad with my phrasing, I got your point. I was just trying to add to it.
