### ISSUE TITLE
Crash on server updating from 2.0.5 to 2.0.7

### ISSUE THREAD

**Issue by Gamerbolts** [FTBTeam/FTB-Interactions#1163]
Modpack Version: 
2.0.7

## Bug Report:
I updated the FTB Interactions server to 2.0.7 from 2.0.5 and started receiving crashes

## Is It Repeatable? Steps to Reproduce: 

1. I am pretty sure if you have a 2.0.5 world and upgrade to v2.0.7 it will crash
2.

## Link to Log or Crash File Paste**: 
https://pastebin.com/ueZ3Zm6T

Thank you for the help!

**Comment by Saereth** [comment]
try without worldedit installed and see if it loads

**Comment by madokaorimura** [comment]
Upgrading from 2.0.5 to 2.0.7 seem no problem tho
Reinstall it ( ≧Д≦)

**Comment by Gamerbolts** [comment]
So I took the files from my friends server and created a server on my desktop, ran the world and it worked fine, ran it with worldedit it worked fine... no idea what happened or why it's working on my desktop server but not his server.
