### ISSUE TITLE
Just starting out in FTB Interactions - Void world problems.

### ISSUE THREAD

**Issue by Lexanii** [FTBTeam/FTB-Interactions#1164]
## Modpack Version: 
FTB Interactions
Version: 1.9.1  Minecraft Version: 1.12.2  (modded) forge-14.23.5.2838

## Bug Report:
1)  When using Flint Axe you cannot break the tree like you vein mine it,  it goes from 0%-80% then starts at 0% again never breaking the block.
2)  Then the saw mill quest (I Saw That) doesn't complete.

## Is It Repeatable? Steps to Reproduce: 
Video of what i am having issues with.  I have repeated it in 3 different save files and on both twitch desktop app and GDLauncher for same mod pack. (posted both link and embed code of same video.)

`<iframe width="560" height="315" src="https://www.youtube.com/embed/Xp9wpPrEg1w" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

[https://youtu.be/Xp9wpPrEg1w](url)

## Mod/s Affected: 
i dont know....

**Comment by anabsolutesloth** [comment]
This was a bug that was fixed in newer versions of GTCE, Update to the latest pack version, you can get a Twitch export for said version in the pins of the interactions channel in the FTB Discord server.

**Comment by Saereth** [comment]
yeah your pack is out of date
