### ISSUE TITLE
Spawn Haiku

### ISSUE THREAD

**Issue by KernelDeimos** [FTBTeam/FTB-Interactions#1165]
## Modpack Version: 
1.9.1

## Bug Report:

I fell off the world
This is a brand new server
Why did I spawn here

## Expected Behavior/Suggestions:
Not falling to my demise repeatedly with each new attempt at spawning

## Is It Repeatable? Steps to Reproduce: 
Happens every single time I delete the server and try again... not sure what's up with it

## Link to Log or Crash File Paste**: 
N/A

## Mod/s Affected: 
N/A

## Known Fix: 
N/A

**Comment by KernelDeimos** [comment]
Only other factor I can think of is I'm running this on CentOS 8, which has consistency been a heap of rancid shit, but that the distro couldn't affect world gen or spawn could it?

**Comment by MaxNeedsSnacks** [comment]
By default, you'll need to regenerate just the world file after launching your server for the first time, as the first world generated is not a void world type and void island control doesn't seem to like that much (as in, it'll stop working entirely)

**Comment by Saereth** [comment]
yeah just delete your /world folder and it should work. Also you're on a very out dated pack version, grab the latest twitch export from the interactions ftb discord pins or from the FTBApp launcher
