### ISSUE TITLE
Can't chisel some books*

### ISSUE THREAD

**Issue by madokaorimura** [FTBTeam/FTB-Interactions#1169]
## Modpack Version: 

2.0.7
## Bug Report:

Can't chisel "Material and You" & "Sanguine Scientiem" to other book even JEI show the recipe
## Expected Behavior/Suggestions:

Maybe due to NBT?
## Is It Repeatable? Steps to Reproduce: 

1. Chisel, open then chisel again

## Known Fix: 

Maybe make recipe to clear NBT?

**Comment by Saereth** [comment]
our main concern is you can get every book via chiseling a book, converting back is not really the intent, so it works for some, but if they gain nbt you cant convert back, this would require adding nbt clearing recipes for everybook that gets that which is really not something I really see much value in spending time on. If someone wants to contribute a community script for it however I'll add it
