### ISSUE TITLE
Tiny charcoal in basic worktable

### ISSUE THREAD

**Issue by Plantaeagnus** [FTBTeam/FTB-Interactions#117]
## Modpack Version: 
1.0.1

## Bug Report:
Right-clicking to craft tiny charcoal in basic worktable only produces 1 tiny charcoal

## Expected Behavior/Suggestions:
Expected behaviour is to mimic left-click functionality and produce 2 tiny charcoal.

## Is It Repeatable? Steps to Reproduce: 
Basic worktable, low-grade charcoal, right-click to craft

**Comment by Vyraal1** [comment]
https://github.com/codetaylor/artisan-worktables/issues/156

This has been repoted to the mod dev.
