### ISSUE TITLE
Assembly line not becoming multiblock

### ISSUE THREAD

**Issue by guillej08** [FTBTeam/FTB-Interactions#1170]
## Modpack Version: 
version 2.07

## Bug Report:
the gregtech assembly line multi-block does not form even when all the required blocks are in the right places (keep in mind i followed a video online and put the blocks in the EXACT same locations that the other person put them, except their assembly line turned into the multi-block and mine did not)
          Additionally,i followed the instructions from the JEI instead for building said multi-block, and the same thing occured, it still did not become a multiblock.

## Expected Behavior/Suggestions:
the assembly line should form when all blocks are placed in correct order and orientation

![Front](https://user-images.githubusercontent.com/38258049/90818559-b2587900-e2fc-11ea-91ae-9ec02ab48b2d.jpg)
![Left Side](https://user-images.githubusercontent.com/38258049/90818574-b8e6f080-e2fc-11ea-842d-69ffd2089849.jpg)
![Right Side](https://user-images.githubusercontent.com/38258049/90818587-bc7a7780-e2fc-11ea-9c0c-01db998af062.jpg)
![Bottom](https://user-images.githubusercontent.com/38258049/90818690-e5027180-e2fc-11ea-9f48-b5b5ce02236c.jpg)
![Bottom error](https://user-images.githubusercontent.com/38258049/90818706-e9c72580-e2fc-11ea-8c90-e0326880ed47.jpg)

This last picture is nearly identical to the last one, the issue is that this error is the ONLY error on the entire multiblock, yet i tried every single gregtech block i had (fluid input/output hatches, energy input/output hatches, item input/output hatches, etc.) and nothing worked when placed in that specific spot, yet there was no red block anywhere else on the multiblock

**Comment by Saereth** [comment]
I just built mine yesterday and it formed fine, defniitely cant reproduce this, maybe provide some screenshots/video or something

**Comment by guillej08** [comment]
@Saereth i now added some images hopefully this clarifies the issue a little, sorry about that
