### ISSUE TITLE
Auto anvil + lapis dust causes a crash

### ISSUE THREAD

**Issue by drame123** [FTBTeam/FTB-Interactions#1181]
## Modpack Version: 

V2.0.4

## Bug Report:

Using lapis dust in an auto anvil will cause a crash that is going to occour every time the person loads into their world, also same effect on servers. 

The game will crash, and crash upon loading it up again. 

## Expected Behavior/Suggestions:
Crash should not occour at all.

## Is It Repeatable? Steps to Reproduce: 
1. Place auto anvil
2. put in leggings ( I used silver leggings)
3. add in lapis dust

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/bb35541c

**Comment by Saereth** [comment]
can you confirm if this is still happening in 2.0.9?

**Comment by drame123** [comment]
> can you confirm if this is still happening in 2.0.9?

Booted up my crashed world - did not crash upon loading.

Tried to recreate issue in said world - expected behavior of no crash found.

Bug appears to be fixed - so this bug can be closed 👍
