### ISSUE TITLE
Suggestion:  Add a Quest for the All Infused Ore Vein.

### ISSUE THREAD

**Issue by crusader3456** [FTBTeam/FTB-Interactions#1183]
## Modpack Version: 

2.0.7

Make a quest with most likely in the Less Safe Space Tab for the Magical Forest Only Vein of Infused Ores.  Probably add a hint about the nature compass in the text. No Idea it existed.

**Comment by Saereth** [comment]
it's SUPER rare, if there is a quest for it and people will look for it and get frustrated when they dont find it. Out of the entire development time of this pack and multiple playthroughs I've only seen it once myself. We prefer this to be more of an easter egg. I may drop some hints about it however

**Comment by crusader3456** [comment]
I would agree with you if the Winged Everlasting didn't already have a page.  At least with the Magical Forest only spawn you can extremely limit where you have to look in comparison to that ungodly rare vein.

**Comment by dominic-jones** [comment]
I did find one Winged Everlasting vein, but never knew about the All-infused one. Difficult to say. I'm happier knowing about it, but also agree that even flagging it as super rare might not be enough to avoid frustration.
