### ISSUE TITLE
Minetogether causing crash in server files. (MP)

### ISSUE THREAD

**Issue by Hachuurui** [FTBTeam/FTB-Interactions#1184]
## Modpack Version: 
2.0.8

## Bug Report:
Server crashes on load

## Expected Behavior/Suggestions:
Server does not crash

## Is It Repeatable? Steps to Reproduce: 
Install server file 5_120.exe

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/070cf83c

## Mod/s Affected: 
Minetogether

## Known Fix: 
Removing the file from the server fixed the issue. 

I'm pretty sure this is a client only file.. The server works fine without it and I can connect with the client having it. This post is more a formality in case it is client-side only so you can handle that issue in the server files.

**Comment by PhoenixtheII** [comment]
Can confirm, same issue.

**Comment by madokaorimura** [comment]
erh, why don't you remove it away?

**Comment by madokaorimura** [comment]
New 2.0.9 downgrade MineTogether back to 2.2.5?

**Comment by Hachuurui** [comment]
I personally removed it from our server files for the moment so the community can play. I was more just letting him know something is up with it atm.

**Comment by Saereth** [comment]
this is fixed in 2.0.9 as of last nights hotfix
