### ISSUE TITLE
Blood Magic progression tab not updated with new rtitual diviner progression

### ISSUE THREAD

**Issue by Ketelll** [FTBTeam/FTB-Interactions#1185]
## Modpack Version: 
2.0.9

## Bug Report:
The quest "HIgher tier rituals, yes please!" still requires Demonic Slates

## Expected Behavior/Suggestions:
Tweak the progression tab of blood magic to make the quest for the better ritual diviner accesible before demonic slates

## Is It Repeatable? Steps to Reproduce: 
1. Load a new world
2. Open the quest tab

## Mod/s Affected: 
FTB questing

## Known Fix: 
the command /ftbquests editing_mode
![Untitled](https://user-images.githubusercontent.com/26350313/91028255-80495e80-e5fd-11ea-8ec3-3ca66dcdd650.png)

**Comment by dominic-jones** [comment]
As a side question, why was the Dusk Diviner brought forward to a T2 level recipe? I really don't know much about Blood Magic so far, and the documentation is patchy so I'm learning as I go through this mod.

It looks like the Dusk Diviner helps crafting Dusk-based rituals, but these all require (I think?) Elemental Inscription Tools: Dusk? Those require a T4 altar to craft, so I'm not sure bringing the Dusk Diviner forward changed much. Of course, I could very well be misunderstanding intent or how to use the mod too!
