### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by janbue** [FTBTeam/FTB-Interactions#1187]
## Modpack Version: 
From v2.0.5 to 2.0.9

## Bug Report:
When pressing update in the launcher it shows like it's downloading the new version, but when starting after finished it is still the previous version.

## Expected Behavior/Suggestions:
New version should be installed after update

## Is It Repeatable? Steps to Reproduce: 

1. Press update in launcher (is only bugged on some PCs, running Win10)
2. Wait till finished updating
3. look at installed version

**Comment by madokaorimura** [comment]
Shouldn't you report it to FTBApp instead since this is for the modpack issue

**Comment by Saereth** [comment]
yes please report the issue here:
https://github.com/FTBTeam/FTB-App/issues
