### ISSUE TITLE
Crash/World-corruption when connecting EU-Cable to Compact Machine

### ISSUE THREAD

**Issue by Versalkul** [FTBTeam/FTB-Interactions#1191]
## Modpack Version: 
2.0.9
## Bug Report:
If cable connects
to compact machine with EU
server disappears.

## Steps to Reproduce: 
Video of crash reproduction: 
https://gfycat.com/mammothpoisedayeaye

## Link to Crash File Paste: 
https://paste.feed-the-beast.com/view/b3b8396f

## Mod/s Affected: 
GregTech and Compact Machines

**Comment by madokaorimura** [comment]
Mod issue, report to both mod author

**Comment by Saereth** [comment]
yep this is a mod issue between the two I dont expect will be resolved, you cant use gt cabling through CMS, that is why we provide early access to wireless energy transfer to solve this very issue
