### ISSUE TITLE
Tungsten processing issue

### ISSUE THREAD

**Issue by algul** [FTBTeam/FTB-Interactions#1192]
## Modpack Version: 
2.0.9

## Bug Report:
End Tungstate ore can be processed with starlight infusion into dense Tungsten ore, then either smelted(into native TungSTATE cluster) or chemical bathed(into Tungsten concentrated blood shards). The native TungSTATE clusters have no recipe for further processing. Tungsten blood shard can be processed further (crystal, ore clump) and then smelted into native Tungsten clusters -> pulverize into crusted TungSTATE ore.

## Expected Behavior/Suggestions:
Tungstate should process into Tungstate, not mix it with Tungsten. Native tungSTATE clusters should pulverize into crushed tungstate.

## Mod/s Affected: 
Contentweaker

**Comment by Saereth** [comment]
tungstate doesnt have a dense recipe because its not meant to, it converts to tungsten, so that part is working as intended, the tungsten clusters however should pulverize to tungsten crushed ore so I'll fix that

**Comment by algul** [comment]
That still leaves dense tungsten ore smelting into native tungstate cluster, which has no recipes for further processing.
