### ISSUE TITLE
Incorrect Recipe? HV Recipe for LV Requirement: Graphite Chicken

### ISSUE THREAD

**Issue by GrieverStormborn** [FTBTeam/FTB-Interactions#1196]
##  Modpack Version: 
2.0.9

## Bug Report:
Current recipe for the Graphite Chicken unlocks in the quest book in the LV age, but the recipe requires "Small Pile of Graphene Dust" which is only craftable in the HV age. 

## Expected Behavior/Suggestions:
Change recipe requirement of "Small Pile of Graphene Dust" to "Small Pile of Graphite Dust" OR change questbook dependency to HV age.

## Is It Repeatable? Steps to Reproduce: 
Refer to JEI recipe.

## Link to Log or Crash File Paste**: 
N/A

## Mod/s Affected: 
Roost
GregTech Community Edition

## Known Fix: 
Change Graphite Chicken recipe in `scripts/Chickens.zs` on line 452 to:
```
	mixer.recipeBuilder()
	.inputs(smartChicken, <ore:dustSmallGraphite>, <ore:dustNetherQuartz>, <ore:dustDiamond>)
	.outputs(<roost:chicken>.withTag({Growth: 1, Chicken: "contenttweaker:graphitechicken", Gain: 1, Strength: 1}))
	.duration(1000)
	.EUt(24)
	.buildAndRegister();
```

**Comment by Saereth** [comment]
yeah this is an HV tiered chicken so it should just unlock later in the questbook

**Comment by Saereth** [comment]
reconsidered actually, just made it take 32 piles of graphite
