### ISSUE TITLE
[2.0.9] Eldritch Will chunk coverage reset to 1x1

### ISSUE THREAD

**Issue by TherminatorX** [FTBTeam/FTB-Interactions#1197]
Modpack Version: 
2.0.9

Bug Report:
Eldritch Will was supposedly adjusted to a 3x3 chunk coverage in 2.0.7, it is currently back to 1x1

## Is It Repeatable? Steps to Reproduce: 
1. Open Animus config
2. Check values under line 99

## Mod/s Affected: 
Animus

## Known Fix: 
Edit the value from 0 to 1

**Comment by madokaorimura** [comment]
It was problem with missing "l" letter
