### ISSUE TITLE
Bug supplier logistics pipe + modular storage(rftools)

### ISSUE THREAD

**Issue by PedroAfonsoAlmeida** [FTBTeam/FTB-Interactions#1199]
## Modpack Version: 
2.0.9

## Bug Report:
Used a supplier logistics pipe on modular storage from rftools with 64 electronic circuits to maintain supplied and it crashed the world.

## Expected Behavior/Suggestions:
It should guarantee that there are 64 circuits inside the storage and not crash.

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/3510e765

## Mod/s Affected: 
RFTools
Logistics pipes

**Comment by madokaorimura** [comment]
Mod issue, report to mod author instead

**Comment by Saereth** [comment]
yes thats purely a logistics pipe crash please report to them here:
https://github.com/RS485/LogisticsPipes/issues
