### ISSUE TITLE
mobs spawn regardless of light levels, early game so b4 moon

### ISSUE THREAD

**Issue by Arg737** [FTBTeam/FTB-Interactions#1200]
## Modpack Version: 
2.0.9

## Bug Report:
mobs spawning even when the area is lit, were just into the early overworld game so no moon progressio to trigger this, we've also tried using the peace candles to stop it but no luck

## Expected Behavior/Suggestions:
expeccted to have no mobs in lit area
## Is It Repeatable? Steps to Reproduce: 
yup, just wait till night

## Link to Log or Crash File Paste**: 
doesnt crash

## Mod/s Affected: 
none

## Known Fix: 
none

ps if you want a copy of our save jsut poke
thanks again, awesome mod!

**Comment by Saereth** [comment]
mobs dont start spawning regardless of light level ever, CERTAIN mobs like the laser creepers and jetpack spiders can spawn regardless of light level but they arent ALLOWED to spawn until you visit space. under no circumstances are we changing the vanilla rules for allowing mobs to spawn under certain lighting conditions. You've just got dark spots somewhere or mobs are wandering in most likely.

**Comment by madokaorimura** [comment]
Which mobs spawn?

**Comment by Arg737** [comment]
https://imgur.com/CBYOiMm

Heres a pic of whats happening, those 3 zombies just spawned and haven't moved yet, F7 is pressed to highlight dark spots (theres none) and one has even spawned next to a peace candle, I have since put up a lucerna ritual from astral sorcery and thats worked so not sure whats caused this odd spawning, fixed with AS's lucerna tho so close this pls and cheers for the quick responses.
