### ISSUE TITLE
ı have a problem.I was playing FTB Interactions about 4 months ago. I started the game again yesterday, I created my new world and I saw that vivid grass is not working. Is this a bug or has something changed in the game?

### ISSUE THREAD

**Issue by AngelFa1se** [FTBTeam/FTB-Interactions#1201]
## Modpack Version: 
v2.0.9

## Bug Report:
vivid grass not working

## Expected Behavior/Suggestions:
 If you run on the vivid grass, it provides a rapid growth of the saplings on the vivid grass.

## Is It Repeatable? Steps to Reproduce: 

1.
2.

**Comment by AngelFa1se** [comment]
@

- [ ]

**Comment by Saereth** [comment]
twerksim was replaced with ftbutil mine which has a similar functionality but it doesnt including running around, you need to tap shift repeatedly near them to make saplings grow
