### ISSUE TITLE
Unable to teleport to Space Station using Astral Gateway

### ISSUE THREAD

**Issue by dominic-jones** [FTBTeam/FTB-Interactions#1202]
## Modpack Version: 
2.0.9

## Bug Report:
Finally launched into space!
I launched a station from the starting Void World (dim0) and flew up with it.
Built an Astral Gateway to the Overworld (dim100) and teleported home.
From the Overworld, I cannot teleport back to the space station. The gold star appears, it glows and zooms in when I sneak/right-click. However no teleport happens, and the glow animation resets.
Both sides are chunkloaded.
I attempted to restart both client and server.

I had previously built no other gateways. So then I went testjing. I built various gateways in both the Overworld and the Void world. I could teleport to all Void destinations and Overworld destinations from all (Void, Overworld, Space) gateways. From no worlds could I teleport TO the space station. 

(By contrast, RFTools teleporters could take me to the station, so my progression won't be hindered)

## Expected Behavior/Suggestions:
I should be able to gateway to the space station from any other gateway.

## Is It Repeatable? Steps to Reproduce: 
I kept a backup from before launching my station (I'd only used Advanced Rocketry once before and whilst cool, was very buggy so I was being careful). I reattempted creating a gateway back on the station and could reproduce these steps.

## Mod/s Affected: 
Astral Sorcery and/or Advanced Rocketry

**Comment by Saereth** [comment]
rftools teleporters bypass dimensional staging, astral gateways dont so its almost certainly a gamestaging issue, pick up a guidance computer and it should trigger the gamestage properly.

**Comment by dominic-jones** [comment]
Hmm, interesting! Is there a command that will show me the gamestaging state? I trust you to know your modpack, but I'd also like to verify it (as I thought I'd hit the stage)! I presume it's tied into quest completion. I have certainly done enough to trigger the final tier of mob staging for entering space. Here's a view of my space dimension tab at the time of testing

![image](https://user-images.githubusercontent.com/5888934/91619799-a7958800-e97d-11ea-834d-c637827cc238.png)
