### ISSUE TITLE
Opening Satellite terminal causing a bunch of Errors.

### ISSUE THREAD

**Issue by Codock** [FTBTeam/FTB-Interactions#1204]
## Modpack Version: 
v2.0.5

## Bug Report:
I just launched a couple of satellites from the void world. They seemed to launch fine, but when I click on the satellite terminal, it immediately had 1000 data, and the sat ID chip acted weird and popped into my inventory. I then kept getting a BUNCH of error pop up things that said to click ctrl+I for more information. Now when I click on the satellite terminal, I just get the error messages and the satellite doesn't appear to be producing any more data. Same with the second satellite I launched. The first was an observatory satellite, the second was a composition scanner satellite.

## Is It Repeatable? Steps to Reproduce: 

1. Launch a satellite. I had the satellite terminal already set up with the satellite ID chip already in it. That might be part of it?
2. Open the satellite terminal and then a bunch of errors pop up.

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/711af933

## Mod/s Affected: 
 Unknown

## Known Fix: 
 Unknown

**Comment by Saereth** [comment]
Please report to advanced rocketry, its a mod issue nhttps://github.com/zmaster587/AdvancedRocketry/issuesot a pack issue
