### ISSUE TITLE
Memory Chests from Ender Utilities not locking slots

### ISSUE THREAD

**Issue by Heldenkrieger01** [FTBTeam/FTB-Interactions#1206]
## Modpack Version: 
2.0.9

## Bug Report:
I cannot middle click to lock slots in any the Memory Chest from Ender Utilities. I am playing on a multiplayer server.

## Expected Behavior/Suggestions:
Middle click locks slot to only be occupied by the item currently in this slot. I have removed every keybind and config option to use the middle mouse button.

## Is It Repeatable? Steps to Reproduce: 
1. Remove Middle click from all keybinds
2. Put item in Memory Chest
3. Middle click to lock slot -> nothing happens

## Link to Log or Crash File Paste**: 
no crash

## Mod/s Affected: 
Ender Utilities

## Known Fix: 
none

**Comment by NoxyNixie** [comment]
The locking of slots uses the `Pick Block` keybind.

**Comment by Heldenkrieger01** [comment]
> The locking of slots uses the `Pick Block` keybind.

Yes, thats it, thank you!
