### ISSUE TITLE
Artisan Worktables send a lot of data packets over network

### ISSUE THREAD

**Issue by balthild** [FTBTeam/FTB-Interactions#1209]
## Modpack Version: 

Both 2.0.6 and 2.0.9

## Bug Report:

Sometimes the server would start to send a ton of data to the client when I stay at my island. The traffic rate can even reach 10+ Mbps, and makes me feel extremely laggy.

![1](https://user-images.githubusercontent.com/2662758/91629365-15cc6000-e9fb-11ea-937a-f99f4bd84f55.png)

TickProfiler shows that most packets are sent from `artisanworktables`.

![2](https://user-images.githubusercontent.com/2662758/91629373-31376b00-e9fb-11ea-8372-9969bab6b4df.jpg)

When I destroy the worktables on my island, the network traffic drops to normal instantly.

![2](https://user-images.githubusercontent.com/2662758/91629375-3a283c80-e9fb-11ea-9575-20320ed0033d.png)

BTW, if I logout from the server when the traffic rate is high, VanillaFix would report a lot of crashes from Athenaeum, which is the dependency of Artisan Worktables.

## Is It Repeatable? Steps to Reproduce: 

No. The issues occurs randomly, but also frequently.

## Link to Log or Crash File Paste**: 

[crash-2020-08-29_04.09.15-client.txt](https://github.com/FTBTeam/FTB-Interactions/files/5144812/crash-2020-08-29_04.09.15-client.txt)

## Mod/s Affected: 

- Artisan Worktables
- Athenaeum

## Known Fix: 

N/A

**Comment by madokaorimura** [comment]
Please report this issue to mod author

**Comment by Saereth** [comment]
yeah thats not good, definitely report to the mod author for a fix hopefully.

**Comment by balthild** [comment]
OK, I'll test the mod individually and report the bug to upstrem.
