### ISSUE TITLE
Starmetal oredictionary

### ISSUE THREAD

**Issue by Sharkum** [FTBTeam/FTB-Interactions#1211]
## Modpack Version: 
2.0.9

## Bug Report:
The GTCE starmetal dust and ingot dont seem to have any way to be converted to astral variant of them.

## Expected Behavior/Suggestions:
There are some recipes which use only the astral variant of starmetal. It makes sense as some crafts should be balanced but you need them for ender chests and tanks. Stellar alloy also only accepts the astral variant, which just makes the starmetal dust recipe from space eggs less needed as you have to mine for starmetal anyways which means it is easier to mine for black quartz .  Also could you atleast add an option to smelt the stardust to starmetal directly for the GTCE variant instead of smelting nuggets from tiny piles of stardust. It just seems unnecessary to craft them into tiny piles then smelt them into nuggets then into ingot.

## Link to Log or Crash File Paste**: 
N/A

**Comment by madokaorimura** [comment]
if you would like, please make script for it and post on here
also you can get Astral variant by do macerator starmetal ore them
