### ISSUE TITLE
Gas mining missions bug

### ISSUE THREAD

**Issue by aseccxz** [FTBTeam/FTB-Interactions#1217]
## Bug Report: 
New gas mining misshions were added In a patch 2.0.3:
all solar systems will now generate (and retrogenerate) 5~11 gas giants each
	each of these gas giants now has a chance to provide gas mining missions for these fluids
        oil
        astralsorcery.liquidstarlight
        lava
        helium
        hydrogen
        ender_distillation
        noble_gases
        ethylene
        chloromethane
        glowstone
        tetrafluoroethylene
        carbon_monoxide
        sulfur_trioxide
        butane
        butene
        ammonia
        helium3
        pyrotheum
        cryotheum

But when i build an unmanned vehicle assembler on my space station and a rocket, all gas mining missions are standard with oxygen, nitrogen, and hydrogen on any gas giant. I checked my word config and found that all gas giants generates with those gases. Therefore i'd like to confirm if this is a bug or i'm doing something wrong?

**Comment by Saereth** [comment]
I havent had much luck reproducing this, anyone else?
