### ISSUE TITLE
Crash while loading the world

### ISSUE THREAD

**Issue by davetim101** [FTBTeam/FTB-Interactions#1219]
## Bug Report:
Crashes on attempting to load the single player world, working fine until recently starting upgrading my ore processing abilities. Uses compact machine while using mechinism elite logistical cables to transfer items in and out to either a chest (iron and draconic) or AE interface on the other side. There were a handful of compact machines inside of the main one if thats relevant.

It was working fine without crashing or other issues before I last closed the mod pack.

## Is It Repeatable? Steps to Reproduce: 
Not sure of the exact cause other than something related to above

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/3d4a7ade

## Mod/s Affected: 
Suspected Mods: Compact Machines 3 (compactmachines3), Mekanism (mekanism), p455w0rd's Library (p455w0rdslib)

**Comment by Saereth** [comment]
yeah looks like compact machines doesnt like something thats going on there, to fix your world at least edit forge.cfg and set it to remove erroring tile entities. The crash is specifically happening on CM's side with a null pointer check so please pass the crashlog onto them @ https://github.com/thraaawn/CompactMachines/issues as there is nothing I can do about it from a pack standpoint

**Comment by davetim101** [comment]
@Saereth Just checking, but are these the settings you are refering to

`B:removeErroringEntities=true
B:removeErroringTileEntities=true`
Changing these both to true, launching the game and saving is still erroring out, is there anything else I can do to fix the world outside of restoring a backup

**Comment by madokaorimura** [comment]
Most things iI can recommend is MCEdit althrough....

**Comment by davetim101** [comment]
@madokaorimura no luck with MCEdit, deleting the compact machine blocks, the parts that allow items/liquids throught, the mekanism pipes, same error every time, I dont think I can actually do anything my end to access my world. the error occurs in all the backups aswell. I was able to briefly access the world shortly after ur message for a few hours which allowed me to remove all the relating pipes, but no luck since even after messing with MCEdit

**Comment by madokaorimura** [comment]
Sadly, this is mod issue
Only way to fix it is by report mod author, seem like the issue come from Mekanism capabilities with CM which just fall off tho
btw have you change both "B:removeErroringEntities" and "B:removeErroringTileEntities" to false before restore?
