### ISSUE TITLE
FlimFlam book can be crafted

### ISSUE THREAD

**Issue by Kigstn** [FTBTeam/FTB-Interactions#122]
## Modpack Version: 
1.0.0

## Bug Report:
Don't know if it's a bug, but the FlimFlam enchantment can still be crafted, even though it's not showing in jei (book + emerald). 

To add on this, what's the intended progression to get the first enchanted book? Looting it from chests?

## Expected Behavior/Suggestions:
See above

## Is It Repeatable? Steps to Reproduce: 
Yes:
Book + Emerald = FlimFlam

**Comment by Saereth** [comment]
not a bug, it should show in jei tho we'll fix that
