### ISSUE TITLE
Thaumium Frotress Helmet Recipe Uncraftable

### ISSUE THREAD

**Issue by judicius** [FTBTeam/FTB-Interactions#1220]
## Modpack Version: 
2.0.9

## Bug Report:
Thaumium Fortress Helmet requires Thaumium Fortress Helmet instead of Thaumium Helmet

## Expected Behavior/Suggestions:
Replace Thaumium Fortress Helmet with Thaumium Helmet for the infusion crafting

## Is It Repeatable? Steps to Reproduce: 
N/A

## Link to Log or Crash File Paste**: 
N/A

## Mod/s Affected: 
Thaumcraft

## Known Fix: 
Recipe Update

**Comment by Cata-bre** [comment]
1) Look at the different infusion altar recipes for the Thaumium Fortress helmet. One of the five recipes is for crafting the actual helmet from the Thaumium Helmet.

2) Mouse over the Thaumium Helmet in JEI and press 'U'.

**Comment by madokaorimura** [comment]
Looking recipe for Thaumium Armor first, then check Usage of it

**Comment by Saereth** [comment]
![image](https://user-images.githubusercontent.com/9200909/92498392-9263f900-f1c8-11ea-92de-7fc1feb09bec.png)
