### ISSUE TITLE
Lose everything in your inventory clicking on logic cable with a chisel

### ISSUE THREAD

**Issue by bMeasel** [FTBTeam/FTB-Interactions#1221]
## Modpack Version: 
2.0.9

## Bug Report:
I was about to use the chisel to change a logistics pipe upgrade into another type when I accidentally clicked on the integrated dynamics logic cable with the chisel. Right after this happened, a whole bunch of error messages popped up in the right-hand corner saying ctri-i and my entire inventory, hotbar, baubles, and armor are now missing.

## Expected Behavior/Suggestions:
Suggestions: It should just open up the chisel menu. 

## Is It Repeatable? Steps to Reproduce: 
1. Use the chisel mod's chisel on a working integrated dynamics logic cable
            (To note: The integrated dynamics system I have setup uses lists to filter gregtech mod items into diamond and gold chests, as well as a modular storage)

I will try to get screenshots posted to this crash report in the next few days.

## Link to Log or Crash File Paste**: 
Failed to get the link to the log and I do not know where to find the crash file.

## Mod/s Affected: 
The system said the known cause of the crash was unknown.

**Comment by Saereth** [comment]
I cant reproduce this and no longs so reopen if you get more info

**Comment by madokaorimura** [comment]
Inventory desync issue, relogging is better choice then
