### ISSUE TITLE
Unable to Merge Enchanted Items in Anvil [via Apotheosis]

### ISSUE THREAD

**Issue by lachian** [FTBTeam/FTB-Interactions#1223]
## Modpack Version: 
2.0.9

## Bug Report:
Unable to merge either two enchanted items, or one enchanted item and one non-enchanted item, in the Anvil [via Apotheosis]

## Expected Behavior/Suggestions:
Compatible enchants should be transferable from one item to another, because of the inclusion of the mod Apotheosis. At least this was the way the pack was configured back in 1.9.x. Unsure which version this broke in.

## Is It Repeatable? Steps to Reproduce: 
1. Place an enchanted item in the first slot of an Anvil
2. Place either a second enchanted item, or a non-enchanted item, in the second slot of that Anvil

The arrow of the Anvil has a red X over it telling the player that it can not Merge these items/enchants

## Mod/s Affected: 
Apotheosis 1.12.2-1.12.5

## Known Fix: 
This is due to a config option being flipped back to default.
The config option resides in /config/apotheosis/enchantment_module.cfg
The option is on line 24:
`B:"Item Merging"=false`

This option should be true to resolve this.

**Comment by lachian** [comment]
I may have called this resolvable just by that config option maybe too soon.  :(

With this option set to "true" it that the merge will work. You can take the resulting third item out of the third slot into your inventory and the needed experience appears to have been removed as well.

The moment you leave the anvil UI though, the resulting item turns back into the two previous items. It looks like your experience is not returned, but when you gain some experience (like eat a lotus) the pre-merge experience value comes back.

Nothing shows up on the console log (if playing on a server) or client log when this bug happens.

**Comment by desagas** [comment]
This used to be set to true, my first play through before 2.0. After the update, this function was removed, which means someone must have deliberately gone in and set it to false. Not sure, however, but it was changed.

**Comment by lachian** [comment]
Tested custom pack with just same version of Forge, Apoth, and Placebo, copied over configs from FTBI, tested, and merging works as intended. So definitely a mod conflict with some other mod(s) in the pack.
