### ISSUE TITLE
Large steel boiler fuel inefficency

### ISSUE THREAD

**Issue by algul** [FTBTeam/FTB-Interactions#1226]
## Modpack Version: 
2.0.9

## Bug Report:
The quest "Upgrade !" in Struggling for energy tab suggest upgrading to steel boiler explicitly stating that the whole infrastructure stays the same. I interpreted it as including fueling the boiler(ICOs). That is not the case, 1x ICO for charcoal 2x ICO for coke are not enough to keep it fueled. Even with higher max temperature over bronze boiler the fuel consumption is much higher, Placement of the quest(behind nitro infused diesel) suggest fueling it with diesel, but that seems like a waste of diesel.

## Expected Behavior/Suggestions:
Higher max temperature of steel boiler should increase fuel efficiency so the 3xICO setup is enough.
or
Change the quest description to hint how many ICOs do i need to feed it / say the old setup wont be enough and to fuel it with diesel. 

## Mod/s Affected: 
GTCO

**Comment by madokaorimura** [comment]
Erh, 2 ICOs for coal coke and 1 for Charcoal is enough tho
You just need to build up amount of item before run LBB and use the creosote liquid

**Comment by algul** [comment]
I do use creosote I just fail to mention it. My LBB was working perfectly, I replaced it with steel boiler, let it heat up to max temperature and its not working.

**Comment by madokaorimura** [comment]
make sure you pump water in or bad things happen

**Comment by dominic-jones** [comment]
That's not the issue here.

The quest says you can replace your large bronze boiler with the large steel boiler, and everything works the same. That is not true. The Large Steel Boiler consumes fuel too fast for the original 3x Improved Coke Oven setup to fuel.

**Comment by Saereth** [comment]
LSB does not need to be allowed to constantly consume fuel every tick. That setup will work but you have to regulate the fuel yourself. Either figure out a way to do that (there are severla) or upgrade your fuel production. Added some quest text of this nature for next update
