### ISSUE TITLE
Chests going "drunk" visually with time in a bottle

### ISSUE THREAD

**Issue by PhoenixtheII** [FTBTeam/FTB-Interactions#1228]
## Modpack Version: 
2.0.9

## Bug Report:
After letting the client sit idle for maybe a day on the multiplayer servers screen, you need to re-login.

Re-login for a new auth session.

Idk, if this is a requirement though...

But after multiple logins to the server, usage of the time in a bottle makes Iron Chests, and More Blocks, like Seared Furnace "drunk". What I mean is for the duration of the time in a bottle effect on a block, the chests start to act like the nauseous effect.

## Expected Behavior/Suggestions:
Blocks not going nauseous

## Known Fix: 
Restart the client, until this happens again...

**Comment by PhoenixtheII** [comment]
Oh, this seems related:

**Comment by madokaorimura** [comment]
Mod issues
You should report to mod author then
