### ISSUE TITLE
Logistics pipes crafting module output slot not saving (it seems like people are only having this problem here so i'm reporting it here instead of LP's github)

### ISSUE THREAD

**Issue by NepNep21** [FTBTeam/FTB-Interactions#1229]
## Modpack Version: 
2.0.9

## Bug Report:
Output slot of logistics pipes crafting module not saving after leaving GUI

## Expected Behavior/Suggestions:
All slots in crafting modules should save after leaving the GUI

## Is It Repeatable? Steps to Reproduce: 
https://youtu.be/T0nTqmqAh4U

## Link to Log or Crash File Paste**: 
No crash
## Mod/s Affected: 
Logistics pipes

## Known Fix: 
Unknown

**Comment by Lolicon2110** [comment]
Update: It's possible to avoid the issue by grabbing the items from your inventory, however you can't scroll up to increase the amount of items or it won't work, you need to have the right amount of items in the first place

**Comment by dominic-jones** [comment]
Yea, I encountered this too. These sorts of issues (I've encountered them before with AE2) might be down to interactions with MouseTweaks. You could try playing with its settings to see if they are conflicting with LP. Dire seemed to have it working in his stream I think.

**Comment by Lolicon2110** [comment]
Tried messing around with the wheel related configs but wasn't able to get it to work, could be because i didn't restart my game

**Comment by dominic-jones** [comment]
That's probably not it then, MouseTweaks changes should be instant. It was worth trying.

**Comment by madokaorimura** [comment]
for me by default it is working normal then
and recipe should be save (even you only set output) when you leave the module gui

**Comment by Lolicon2110** [comment]
> for me by default it is working normal then
> and recipe should be save (even you only set output) when you leave the crafting module gui
> make sure leaving crafting gui, you should see module gui then

it seems to work for some things but not for others, i noticed supplier pipes are also affected by this, not sure why this is so inconsistent
