### ISSUE TITLE
Astral Enriched Eggs not producing Liquid Starlight

### ISSUE THREAD

**Issue by Dat-Guy** [FTBTeam/FTB-Interactions#1230]
## Modpack Version: 
2.0.9

## Bug Report:
Astral Enriched Eggs do not produce liquid starlight in a starwell in the void dimension.

## Expected Behavior/Suggestions:
Expected behavior: Eggs should produce 1000mb of liquid starlight, as indicated in JEI.

## Is It Repeatable? Steps to Reproduce: 
1. In the void dimension, place a starwell.
2. Place an astral egg in the liquid starwell.

## Link to Log or Crash File Paste**: 

[2020-09-03-1.log](https://github.com/FTBTeam/FTB-Interactions/files/5174646/2020-09-03-1.log)

## Mod/s Affected: 
ContentTweaker, Astral Society

## Known Fix: 
All other starwell conversions seem to work, and the eggs work as intended in the overworld.

**Comment by elementalistic** [comment]
This works fine for me in the starting void world, using it to power the astral sorcery evershifting fountain.  

Specifically, roost with chicken -> item conduit -> lightwell.

**Comment by Dat-Guy** [comment]
Actually no, it's been producing starlight without being able to see the sky with rock crystals. I tested one with a clear view of the sky, and it produced starlight.
Also, what mod are the conduits from? I've tried EnderIO, but those refuse to connect to the lightwell.

**Comment by Saereth** [comment]
conduits can connect but they must connect on the bottom. Cannot reproduce this issue, they work fine
