### ISSUE TITLE
Bug: The me controller return cable on craft

### ISSUE THREAD

**Issue by Sharkum** [FTBTeam/FTB-Interactions#1231]
## Modpack Version: 
2.0.9

## Bug Report:
The me controller on craft just throws the cables on the ground. The cable i used were covered fluix cables.

## Expected Behavior/Suggestions:
It consumes the cables.

## Is It Repeatable? Steps to Reproduce: 
Yes. I havent tested with the other cables though

**Comment by madokaorimura** [comment]
Can you record when it happen?

**Comment by Sharkum** [comment]
I have a pretty terrible computer so no ig

**Comment by Saereth** [comment]
This is a bug with Compact machines but its not something that is an easy fix and definitely not something I can fix so I mean its whatever, minor thing, you get the cables back, win win
