### ISSUE TITLE
(Suggestion) GPS Self-Craft Recipe

### ISSUE THREAD

**Issue by desagas** [FTBTeam/FTB-Interactions#1235]
## Modpack Version: 
2.0.9

I just thought that, even though the Cyclic mod does not have it, if in Interactions, you could add a self-crafting GPS recipe to clear all NBT data. This way, after changing a system over from the many transport systems in the pack, which are tiered, we don't have to have a hundred GPS that won't/don't stack.

**Comment by Hjaldar** [comment]
You can reset the GPS item (and completely remove its NBT, making them stackable) by sneak right-clicking in the air.

Maybe a loading screen tip could be added or something added to the tooltip for the item.

**Comment by desagas** [comment]
So you can, omg. Okay. HAHAH. I would never have had a clue.

**Comment by Saereth** [comment]
added a tooltip
