### ISSUE TITLE
Tinker book chisel issue

### ISSUE THREAD

**Issue by TheOmegaCarrit** [FTBTeam/FTB-Interactions#1236]
## Modpack Version: 
2.0.9

## Bug Report:
A guide can't be chiseled
From Materials and You
Though can chisel to

## Expected Behavior/Suggestions:
A guide should be chiseled
From Materials and You
Though I am unable

## Is It Repeatable? Steps to Reproduce: 

Chisel to the book
Of Materials and You
Chisel it again

## Link to Log or Crash File Paste**: 

Though issue I found
A crash it did not bring with
This is fortunate

## Mod/s Affected: 
Chisel
Tinker's Construct

## Known Fix: 
Sounds like an easy fix, but what do I know? Just Haikus man.

**Comment by madokaorimura** [comment]
#1169 you can send the script to fix this then

**Comment by Saereth** [comment]
https://github.com/FTBTeam/FTB-Interactions/issues/1169
