### ISSUE TITLE
switch block protector frame for ev machine hull

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#124]
Submitter: `FTB Interactions#2470`
Body: `**[Saereth]** OwO issue "switch block protector frame for ev machine hull"`
Attachments:

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/55563572-35574000-56c4-11e9-8b74-6a7a32426b48.png)

Im fine with either, but did you mean HV?

**Comment by Saereth** [comment]
nah I rethought and the stainless is enough, the circuit is the real killer anyway
