### ISSUE TITLE
Tungsten processing issue... still

### ISSUE THREAD

**Issue by ProgrammasaurusRex** [FTBTeam/FTB-Interactions#1240]
[1192](https://github.com/FTBTeam/FTB-Interactions/issues/1192#issue-685713922)

I believe this is the result of a bad Smelting recipe for Dense Tungstate.

## Modpack Version: 
2.0.9

## Bug Report:
Dense Tungsten Ore smelts to 2x Native Tungstate Cluster, which cannot be processed further

## Expected Behavior/Suggestions:
Expected:
Dense Tungsten Ore smelts to 2x Native Tungsten Cluster, which can be pulverized to Crushed Tungstate Ore

Suggestion:
Change the Smelting recipe for Dense Tungsten Ore to result in 2x Native Tungsten Cluster

## Is It Repeatable? Steps to Reproduce: 
1. Put a Dense Tungsten Ore into a Smelter
2. Note that it results in 2x Native Tungstate Cluster
3. Put a Native Tungstate Cluster into a Pulverizer
4. Note that nothing happens
5. Note that in JEI, there is no way to process Tungstate Cluster
6. Despair

For reference, these steps indicate that the Smelting recipe for Dense Tungsten Ore is bad, by showing a valid, working path for Concentrated Blood Shard processing:
1. Put a Dense Tungsten Ore into a Chemical Reactor with Mana and Life Essence
2. Take the resulting Tungsten Concentrated Blood Shared and put it in a Smelter
3. Note that it results in 4x Native Tungsten Cluster
4. Put a Native Tungsten Cluster into a Pulverizer
5. Note that it results in 2x Crushed Tungstate Ore
6. Rejoice

## Known Fix: 
Just fix the Smelting recipe for Dense Tungsten Ore to result in Native Tungsten Clusters instead of Native Tungstate Clusters.

**Comment by hcardwell** [comment]
I too have this issue.  It looks to me like scripts/modular_machinery/_main.zs:406 should read:

```<contenttweaker:sub_block_holder_4:15>:<contenttweaker:tungsten_ore_cluster> * 2```

It currently is set (I assume incorrectly) to output tungstate_ore_cluster, which as @ProgrammasaurusRex indicated has no processing recipes in JEI.

```<contenttweaker:sub_block_holder_4:15>:<contenttweaker:tungstate_ore_cluster> * 2```

**Comment by Saereth** [comment]
the tungsten dense ore shouldnt be smeltable at all. It must be further processed beyond simple dense ore, the dense ore smelting to native clusters is removed next update
