### ISSUE TITLE
Alchemical Matter Infuser creates Zombie Hearts out of nothing

### ISSUE THREAD

**Issue by SerafEthifeo** [FTBTeam/FTB-Interactions#1244]
## Modpack Version: 
2.0.9

## Bug Report:
The Alchemical Matter Infuser creates zombie hearts without receiving any input, and ignores input I try to give it.
(If you ignore the preview and build it sensibly it seems to work properly)

## What should be done:
The preview should be adjusted to have an item input and output. (Assuming that's possible)

## Is It Repeatable? Steps to Reproduce: 
1. Create Alchemical Matter infuser according to preview. (With two item outputs)

**Comment by madokaorimura** [comment]
Not have that issue tho
