### ISSUE TITLE
warp core not froming using titanium blocks from GregTech

### ISSUE THREAD

**Issue by benediu** [FTBTeam/FTB-Interactions#1245]
## Modpack Version: 
2.0.9

## Bug Report:
warp core is not forming using titanium blocks (from GregTech)

## Expected Behavior/Suggestions:
warp core should be forming using titanium blocks (from GregTech)
probably an oreDict issue?

## Is It Repeatable? Steps to Reproduce: 
build the warp core using the HoloProjector using titanium blocks from GregTech

## Link to Log or Crash File Paste**: 
no crash

## Mod/s Affected: 
AdvancedRocketry

## Known Fix: 
none

**Comment by Saereth** [comment]
it doesnt, convert to AR titanium with a shapecraft, questbook updated to say this in 2.0.10
