### ISSUE TITLE
Dense Tungsten ore smelts into useless Native Tungstate clusters

### ISSUE THREAD

**Issue by DaBlazeHunter** [FTBTeam/FTB-Interactions#1247]
## Modpack Version: 
2.0.9

## Bug Report:
Dense Tungsten ore smelts into Native Tungstate clusters, which can't be used for anything

## Expected Behavior/Suggestions:
I expect that this is an oversight as i would Expect that this to be able to be pulverized into useful ores like the rest of the ores

## Is It Repeatable? Steps to Reproduce: 

1. Improve end tungstate ore or End scheelite ore into dense Tungsten ore through starlight transmutation or chem bath with liquid starlight
2. Smelt result into useless ore

## Known Fix: 
Fix the recipe

**Comment by madokaorimura** [comment]
#1240
