### ISSUE TITLE
Dense Coal Ore/Shard/Crystal/Clump Not able to smelt in Hellfire Kiln

### ISSUE THREAD

**Issue by gold-me** [FTBTeam/FTB-Interactions#1248]
## Modpack Version: 
2.0.10

## Bug Report:
When I tried to smelt my dense coal ore in a hellfire kiln and nothing happened. Figured out the recipes were missing entirely.

## Expected Behavior/Suggestions:
I would recommend to add the recipes into the hellfire kiln considering you can use a furnace to create the clusters.

## Is It Repeatable? Steps to Reproduce: 

1. Obtain Dense Coal Ore
2. Attempt to smelt it inside a Hellfire Kiln
3. Realize it doesn't work

## Link to Log or Crash File Paste**: 
N/A

## Mod/s Affected: 
Modular Machinery
Content Tweaker

## Known Fix: 

Adding this code to the modular machinery main.zs file where the hellfire kiln recipes are seemed to have worked and added the recipes:

<contenttweaker:sub_block_holder_0:0>:<contenttweaker:coal_ore_cluster> * 2,
<contenttweaker:coal_ore_clump>:<contenttweaker:coal_ore_cluster> * 16,
<contenttweaker:coal_ore_shard>:<contenttweaker:coal_ore_cluster> * 4,
<contenttweaker:coal_ore_crystal>:<contenttweaker:coal_ore_cluster> * 8,

**Comment by Aranak** [comment]
I have the same issue with the Dense coal ore, I used the seared Furnace as a workaround

**Comment by Dasavanth** [comment]
same, please make it so that its possible to be smelted in hellfire kiln.
