### ISSUE TITLE
Manyully Ingots are not craftable .

### ISSUE THREAD

**Issue by lilmoefow** [FTBTeam/FTB-Interactions#1250]
## Modpack Version: 
2.0.9

## Bug Report:
Manyullyn Ingots are not craftable when the EBF has multiple fluid inputs..  When i put the Ardite Dust, or Cobalt Dust into the blast furnace it will only cook the individual dusts.  I have my EBF with 4 fluid inputs, one for Oxygen, Nitrogen, and Hydrogen. So it will automatically use the dust with Oxygen recipe.

## Expected Behavior/Suggestions:
Recipe is supposed to make Manyullyn Ingots. 

## Is It Repeatable? Steps to Reproduce: 
Yes.
1.Put Dusts In
2.Only cooks either Cobalt Dust or Ardite Dust depending on which you put in first. 

## Known Fix: 
Change Recipe to use Ingots instead of Dusts.

**Comment by madokaorimura** [comment]
Recommend to make other EBF and just dont do 3 fluid on 1 EBF like that

**Comment by lilmoefow** [comment]
You are able to have multiple fluid inputs on blast furnaces,  "just dont do 3 fluids on ebf like that" is terrible advice.   The recipe needs to be fixed to not cause conflicts seeing as its a custom recipe for the pack.

**Comment by Saereth** [comment]
I guess requiring a configuration chip 11 for the ardite or cobalt should suffice to clear this up
