### ISSUE TITLE
Two OC component recipes in assemblers do not oredict GT processors.

### ISSUE THREAD

**Issue by fluffle** [FTBTeam/FTB-Interactions#1251]
## Modpack Version: 

2.0.9

## Bug Report:

The following recipes only accept <gregtech:meta_item_2:32487> instead of @circuitBasic or @circuitLow:

*   Arithmetic Logic Unit (ALU) <opencomputers:material:10>
*   Control Unit (CU) <opencomputers:material:11>

I think they got missed while you were fixing #1066 / #1056. I can't find crafttweaker scripts for these two, but I can see you've used CT to enforce oredict for the three tiers of microchips. I can see you've attempted to use the oredict in gregtechce.recipes in the opencomputers config folder, but it doesn't seem to be working, at least for me. Maybe it's an OC bug?

## Expected Behavior/Suggestions:

I can use any of the basic LV GT circuits to craft opencomputers components.

## Mod/s Affected: 

opencomputers

## Known Fix: 

I see in the other issues linked above that CT scripts were added to enforce oredicting.

**Comment by Saereth** [comment]
![image](https://user-images.githubusercontent.com/9200909/169626513-1840e0e0-2e59-49c5-be38-ef8cae262f80.png)
