### ISSUE TITLE
Golemancy Iron Plates not working (refer to #796)

### ISSUE THREAD

**Issue by filleadh** [FTBTeam/FTB-Interactions#1252]
Sorry to reopen if i  missed something, spent quite a bit of time checking this out.

## Modpack Version: 
2.0.9

## Bug Report:
There is no shapecraft recipe for Iron plates, so one cannot make Iron Golems using GT Iron plates.  
Referring back to: [Golemancy Iron Plates not working #796](https://github.com/FTBTeam/FTB-Interactions/issues/796 )

## Expected Behavior/Suggestions:
Try and make an Iron Golem using GT iron Plate
Previous bug report indicated to Shapecraft into Thaumcraft plates, however, there is no recipe, and the shapecraft doesnt work.

## Is It Repeatable? Steps to Reproduce: 
Steps listed above.

## Link to Log or Crash File Paste**: 
N/A

## Mod/s Affected: 
Thaumcraft
GTCE

**Comment by Saereth** [comment]
fixed in 2.10+
