### ISSUE TITLE
Bugged Menu and Bugged Quest Titles

### ISSUE THREAD

**Issue by Blacksmith050505** [FTBTeam/FTB-Interactions#1253]
## Is It Repeatable? Steps to Reproduce: 

1.
2.

**Comment by madokaorimura** [comment]
Reinstall your pack

**Comment by Blacksmith050505** [comment]
I have multiple times and it keeps happening

**Comment by Blacksmith050505** [comment]
so basically every time I try to download a pack it stops downloading at 84.17% and wont download anymore so I have to close the FTB app and then when i open it back up the pack is installed but just missing some important stuff. But I just left it overnigth checked it and it was still at 84.17% so i closed to app started the game and everything that i can tell so far works fine I don't know what happened differently this time but thanks i guess

**Comment by madokaorimura** [comment]
It was download issue, not modpack
