### ISSUE TITLE
Mobs spawned in my void base.

### ISSUE THREAD

**Issue by Pseudoreal** [FTBTeam/FTB-Interactions#1254]
## Modpack Version: 
<v2.0.9>

## Bug Report:
<4 Skeletons w/ skeleton horses spawned in my void base. Happened during a thunderstorm, don't know if that's relevant. >

## Is It Repeatable? Steps to Reproduce: 

1. Don't know. This is the first time this has ever happend.

## Known Fix: 

![2020-09-16_02 07 46](https://user-images.githubusercontent.com/71369300/93298662-a8257f80-f7c1-11ea-8d28-63524ba533d2.png)

**Comment by Saereth** [comment]
this is vanilla behavior and happens super rarely, not really a bug just exceedingly rare. From the Wiki: 

A skeleton trap horse is a hostile skeleton horse spawned from a fraction of [lightning](https://minecraft.fandom.com/wiki/Lightning) generated naturally by a [thunderstorm](https://minecraft.fandom.com/wiki/Thunderstorm) (0.75–1.5% chance on Easy, 1.5–4% on Normal, and 2.25–6.75% on Hard, depending on [regional difficulty](https://minecraft.fandom.com/wiki/Regional_difficulty)).
