### ISSUE TITLE
GT Flint Axe is still not working in 2.0.9

### ISSUE THREAD

**Issue by ragequitbrian** [FTBTeam/FTB-Interactions#1255]
This issue is currently back in the latest pack update: https://github.com/FTBTeam/FTB-Interactions/issues/728

**Comment by madokaorimura** [comment]
?1

**Comment by ragequitbrian** [comment]
Sorry I need to write a better ticket up.  I thought that ticket was for my issue.  Currently no users can craft Flint tools in the beginner quest line
