### ISSUE TITLE
Holding right click on a clockwork engine with a redstone torch dupes the torch

### ISSUE THREAD

**Issue by GamersofGold** [FTBTeam/FTB-Interactions#1256]
## Modpack Version: 
 FTB Rebelation 3.2.0

## Bug Report:
 holding right-click on a clockwork engine with a redstone torch dupes the redstone torch (doesn't work with normal torches, idk about others)

## Expected Behavior/Suggestions:
 self-explanatory
self-explanatory

## Is It Repeatable? Steps to Reproduce: 

1. hold redstone torch in hand
2. hold right-click on a clockwork engine

## Mod/s Affected: 
The clockwork engine is from Forestry but idk where the bug comes from

**Comment by madokaorimura** [comment]
wrong pqck
