### ISSUE TITLE
Large steam turbine multi-block not running

### ISSUE THREAD

**Issue by gladrage** [FTBTeam/FTB-Interactions#1257]
## Modpack Version: 
2.0.9

## Bug Report:
Large steam turbine multi-block says that there is no fuel and will not run.

## Description:
 I have made 2 large steam turbines but when making the third the multi-block goes together just fine but when attached to mekanism ultimate mechanical pipes the input hatch fills up and then the turbine says that it does not have any fuel. I have tried moving it, breaking and rebuilding all three, and relocating but it will not let me run anymore than the first two

**Comment by gladrage** [comment]
![Minecraft 1 12 2 - FTB Interactions 9_17_2020 5_25_06 PM](https://user-images.githubusercontent.com/71471820/93538265-ed08fd80-f90a-11ea-9161-570082ee023a.png)
![Minecraft 1 12 2 - FTB Interactions 9_17_2020 5_25_47 PM](https://user-images.githubusercontent.com/71471820/93538271-ee3a2a80-f90a-11ea-8183-8ad1af646c9c.png)
![Minecraft 1 12 2 - FTB Interactions 9_17_2020 5_26_09 PM](https://user-images.githubusercontent.com/71471820/93538273-eed2c100-f90a-11ea-94bb-65290d0653e2.png)

**Comment by bahaynes** [comment]
Double check that you don't have any blocks in front of the turbines. They require ~12 (I don't know the exact amount) blocks of air in front of them to operate, and give no indication that that is the issue when they fail to operate.

**Comment by Saereth** [comment]
can't reproduce this, if anyone else has this issue zip me up a worldsave and reopen
