### ISSUE TITLE
Enhanced shears right click not working

### ISSUE THREAD

**Issue by IvyWoof** [FTBTeam/FTB-Interactions#1259]
## Modpack Version: 
2.0.10

## Bug Report:
When right clicking wisdom tree leaves with enhanced shears from cyclic the user crashes.

## Expected Behavior/Suggestions:
Shears should destroy leaves with right click from a distance

## Is It Repeatable? Steps to Reproduce: 
Yes it is repeatable on single player and in 2.0.09 as well as .10
1. Grow wisdom tree
2. Right click with enhanced shears on wisdom tree

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/cc5b7649

## Mod/s Affected: 
Wizardry and Cyclic

## Known Fix: 
Use fill, setblock, world edit or mcedit to replace the leaves that the item interacts with

**Comment by Saereth** [comment]
cyclic update may fix this, I cant reproduce it post-update, re-open if the issue persists on v2.0.12+
