### ISSUE TITLE
Game crashes when connecting GTCE cables inside compact mahine to tunnel

### ISSUE THREAD

**Issue by Neeqaque** [FTBTeam/FTB-Interactions#1260]
Modpack Version: 
2.0.9

## Bug Report:
Title pretty much says it. When trying to connect power cables from CM to overworld game crushes. Have to use mcedit ro fix it.

## Is It Repeatable? Steps to Reproduce: 
1. Connect powered GTCE cable to compact machines block.
2. Add tunnel inside compact machine
3. Connect power cable to it.

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/5a702d9b

## Mod/s Affected: 
1. Greg Tech Community Edition
2. Compact machines 3

**Comment by madokaorimura** [comment]
#1149 a.k.a. mod issue
