### ISSUE TITLE
Nether portal Not working

### ISSUE THREAD

**Issue by Swennienl** [FTBTeam/FTB-Interactions#1266]
## Modpack Version: 
2.0.9

## Bug Report:
When we step into the formed nether portal, the screen turns swirly purple but it doesnt teleport me.  Multiple users are effected. Single player as multiplayer. 

I have the`quest Highway to hell 

## Expected Behavior/Suggestions:
I would expect to be teleported to the nether.

## Is It Repeatable? Steps to Reproduce: 
Yes 

## Link to Log or Crash File Paste**: 
No errors on the server

## Known Fix: 
Maybe there is another dependecie, but I have no idea what this may be.

**Comment by Devintrainer** [comment]
I have the same issue!

**Comment by Saereth** [comment]
you havent met the pre-requisite staging by crafting the portal most likely
