### ISSUE TITLE
Nether sphaelarite ore cant be further doubled or quadrupled.

### ISSUE THREAD

**Issue by Sharkum** [FTBTeam/FTB-Interactions#1269]
## Modpack Version: 
2.0.9

## Bug Report:
The nether sphalerite ores don't seem to be able to be doubled or any of the ore processes. Its fine if it is intentional but they have their content tweaker dense ore and blood shards in jei. Unlike galena which i think is not given any ore processes to make indium more rare and doesnt have a dense ore form in jei, nether ores like sphalerite have dense forms and the other forms as well. Sphaelarite seems to be the only nether ore with dense forms available but no recipe in jei.

## Expected Behavior/Suggestions:
Sphaelarite could have a dense form or if it isnt supposed to, then remove the dense forms from jei.

P.S.-
Also is 2.0.10 released? i have been hearing about it for some time in discord and what not

**Comment by madokaorimura** [comment]
yes, *Pin*

**Comment by Saereth** [comment]
this is intended
