### ISSUE TITLE
Minecraft Failed to Start

### ISSUE THREAD

**Issue by Pewexxx** [FTBTeam/FTB-Interactions#1270]
## Modpack Version: 

2.0.9
## Bug Report:

Minecraft keeps failing to start.  Also when installing modpack via FTBapp I got info that file sizes doesn't match.

![STARTFAIL](https://user-images.githubusercontent.com/43313140/94366386-2b0adc00-00d8-11eb-90f6-e8a4b31ac150.png)

## Expected Behavior/Suggestions:

 I just want the game to launch
## Is It Repeatable? Steps to Reproduce: 

It is repeatable, but It is nothing special.
1. Turn on FTBapp
2. Instal FTB Interactions modpack
3. Launch the game

## Link to Log or Crash File Paste**: 

 https://paste.feed-the-beast.com/view/3836d708
## Mod/s Affected: 

Pam's HarvestCraft (Minecraft points that mod)
## Known Fix: 

4th reinstalation of pack (just when i started recording to link the video ... lol) helped.

**Comment by madokaorimura** [comment]
FTBApp issue, not modpack

**Comment by Vorsenaux** [comment]
It is the modpack's issue. I launched the same modpack without using the FTB launcher and got the same message.

**Comment by Saereth** [comment]
reinstall your modpack
