### ISSUE TITLE
crash when loading world

### ISSUE THREAD

**Issue by NWBeez** [FTBTeam/FTB-Interactions#1271]
## Modpack Version: 
<2.0.9>

## Bug Report:
<The game crashs with cause "unknow" when loading the save>

## Expected Behavior/Suggestions:
 Bugs: Any backup version of my save has the same crash. the bug has started after a normal "quit and return to title"
Suggestions: it should load properly (?). Would be nice to be able to save at least my void base and player data.

## Is It Repeatable? Steps to Reproduce: 

1. The crash does not happens with a new game
2.

## Link to Log or Crash File Paste**: 

https://paste.feed-the-beast.com/view/3f721016

**Comment by Dexton** [comment]
@NWBeez Having the same issue also, the error references GregTech and opened a issue with them also.
But that got me nowhere, something strange is going on here since this affects all my backups that work previously.

**Comment by NWBeez** [comment]
Yep, that happened AGAIN, I started a new world from scratch and after a NORMAL save and quit to title it wont load again, any backup from the last 24 hours were affected somehow by the same problem, again.

https://paste.feed-the-beast.com/view/dda24949

**Comment by NWBeez** [comment]
@Dexton For you has it started after a log out too? did you had any replys on Gregtech side? I would love to be able to play any of my 2 lost save. both of them i had just broke in to EV/Space :(

**Comment by NWBeez** [comment]
Halleluia saint google! 
I found a fix, apparently the problem is caused because of a bug on FTBUtilities where it cant unload a chunk (there is why that happens after a normal log out where the game tries to close everthing).
So.disable FTButilities chunk loading and voilá!

**Comment by Dexton** [comment]
@NWBeez thank you so much, this fixed my server. Or atleast I can start it up and play now.
