### ISSUE TITLE
Astral Sorcery Evorsio wand + Thaumcraft Destructive enchant = infinite breaking

### ISSUE THREAD

**Issue by Volk101** [FTBTeam/FTB-Interactions#1272]
Hi, just wanted to raise a quick bug report for this, this is a mod interaction issue (between Thaumcraft 6 and Astral Sorcery). Found that when holding Evorsio wand in off-hand (for vein mining ability) and using the Thaumcraft infusion enchantment 'Destructive' on my pickaxe (using the 'jack hammer' given by a quest reward) that I was able to mine out a 100x100 room in a few seconds (and potentially could have kept going except the server froze - I managed to cleared my inventory, not sure where it would have ended).

Looks like the evorsio vein mining can trigger the destructive enchantment, which then daisy chains further evorsio etc. Evorsio is supposed to have a cooldown but didn't appear to trigger in this case.

## Modpack Version: 
FTB:I 2.0.9
MC 1.12.2
Forge 2.6.2.83
Astral 1.10.25
Thaumcraft 6.1.B26

**Comment by Saereth** [comment]
Not a bug, its an INtErAcTion :P With great power....
