### ISSUE TITLE
Hot Osmium cooled in Fluid Transposer Results in useless Mekanism Osmium ingots

### ISSUE THREAD

**Issue by Virgil-the-Freak** [FTBTeam/FTB-Interactions#1273]
## Modpack Version: 
2.10

## Bug Report:
Hot osmium ingots processed with gelid cryotheum in a fluid transposer from Thermal Expansion produce Mekanism osmium ingots instead of GregTech osmium ingots.  The Mekanism ingots have no uses, and cannot be converted to GT as far as I can tell.

## Expected Behavior/Suggestions:
I expected that GT osmium ingots would be produced.

## Is It Repeatable? Steps to Reproduce: 
https://imgur.com/a/35AA1oF

**Comment by madokaorimura** [comment]
Same as for Enderium!
