### ISSUE TITLE
Time in a bottle issue

### ISSUE THREAD

**Issue by CactusCool** [FTBTeam/FTB-Interactions#1276]
## Modpack Version: 
2.0.9

## Bug Report:
Causes items to sway

## Is It Repeatable? Steps to Reproduce: 
Just use a time in a bottle one a tile entity

**Comment by madokaorimura** [comment]
what is the issue?

**Comment by dethstroek** [comment]
@madokaorimura The issue is that tile entities seem to sway at distances from the Time in a Bottle, I assume. This has happened to me in other packs with Time in a Bottle as well

**Comment by Saereth** [comment]
this is a mod issue but I quite like the effect personally haha, either way can't do anything about it and that mod wont be updated to fix it at this point.
