### ISSUE TITLE
Stellar alloy uncraftable with GTCE star metal and there is not a way to convert GTCE star metal into astral star metal

### ISSUE THREAD

**Issue by Sakamoto0110** [FTBTeam/FTB-Interactions#1277]
## Modpack Version: 
2.0.10

## Bug Report:
GTCE Star metal dust can't be used to make stellar alloy and there is not a way to convert gtce star metal into astral star metal
The maceretor recipe seems to only output  the GTCE Star metal dust.

The GTCE manasteel seems to have the same problem, but there is a implicit conversion using hellfire furnace 

## Expected Behavior/Suggestions:
Add some way to convert the versions of some ingots
Suggestion: add a block ( maybe something like a machine ) to explicitly convert some ingots like:
GTCE manasteel -> Botania manasteel 
GTCE starmetal -> Astral starmetal
and maybe other ingots that can have recipe conflicts

## Is It Repeatable? Steps to Reproduce: 
Print of the stellar alloy recipe not working with the GTCE star metal https://imgur.com/a/MS95xQm

## Mod/s Affected: 
- GTCE
- Botania
- Astral sorcery

**Comment by Saereth** [comment]
fixed in 2.11
