### ISSUE TITLE
Storage scanner crashing games

### ISSUE THREAD

**Issue by CactusCool** [FTBTeam/FTB-Interactions#1278]
## Modpack Version: 
2.0.9

## Bug Report:
Crashing

## Is It Repeatable? Steps to Reproduce: 

1.Scan a radius
2.Use the search

## Mod/s Affected: 
Rf tools
[crash-2020-09-29_15.55.17-server.txt](https://github.com/FTBTeam/FTB-Interactions/files/5302062/crash-2020-09-29_15.55.17-server.txt)

**Comment by Saereth** [comment]
I cant reproduce this at all on 2.10+
