### ISSUE TITLE
All Drops turn into Marble Cobblestone

### ISSUE THREAD

**Issue by Draxel34** [FTBTeam/FTB-Interactions#1279]
## Modpack Version:  
2.0.9

## Bug Report:
Every block when broken, even if a tile entity, drops a gregtech marble cobblestone block.

## Expected Behavior/Suggestions:
Should drop the correct item.

## Is It Repeatable? Steps to Reproduce: 
1. break block
2. get marble cobblestone

## Mod/s Affected: 
every block seems to be affected

**Comment by sgtkwol** [comment]
Use silktouch to keep them in their non-cobble state. Then you can chisel and stack them.

**Comment by Saereth** [comment]
something is corrupted with your install
