### ISSUE TITLE
Starmetal ingot recipe doesnt work in GTCE furnaces

### ISSUE THREAD

**Issue by Sharkum** [FTBTeam/FTB-Interactions#1280]
## Modpack Version: 
2.0.10

## Bug Report:
When you smelt GTCE stardust in the gtce furnaces you get a gtce starmetal ingot. The recipe only seems to be for "vanilla" furnaces, like tinkers smelter or the furnace, in which the recipe works. In these gtce stardust does convert into astral starmetal ingots.

## Expected Behavior/Suggestions:
Stardust should smelt into Astral starmetal ingots rather than the GTCE version. 

P.S.- Wrought iron is also not craftable in the gtce furnaces either. I'm not sure if it is intended to only be made in the hellfire kiln or not.

**Comment by Saereth** [comment]
mod issue, nothing I can do about it, I know its annoying.
