### ISSUE TITLE
No mobs spawning in nether

### ISSUE THREAD

**Issue by Dessolate** [FTBTeam/FTB-Interactions#1281]
<
Hi there, 

I have an issue where no mobs are spawning in the nether for me, or anybody else on the server I host. I have tried the basic trouble shooting steps suggested by the FTB Discord, which entails doing a /kill @e command for killing everything, deleting the nether world file from the worlds folder and reloading the nether that way, and restarting the server several times.  I can't seem to get this resolved, any help is appreciated
-->

## Modpack Version: 
<2.0.9>

**Comment by Saereth** [comment]
this is an old report so if anyone else experiences this please send me a copy of your worldsave
