### ISSUE TITLE
Thermal Dynamics 'Covers' cause crash

### ISSUE THREAD

**Issue by Daxtillion** [FTBTeam/FTB-Interactions#1282]
## Modpack Version: 
 2.0.9

## Bug Report:
 Holding any sort of thermal dynamic 'cover' and looking at any type of 'duct' causes black screen crash

## Expected Behavior/Suggestions:

^

## Is It Repeatable? Steps to Reproduce: 

1. Hold ThermalDynamics Cover
2. Look at any duct
3. Crash.

## Link to Log or Crash File Paste**: 

https://paste.feed-the-beast.com/view/28a5145b
## Mod/s Affected: 

Thermal Dynamics

**Comment by lilmoefow** [comment]
Im assuming you have Optifine installed as well, which would be the cause for this crash.   

Download this mod, it will fix that crash.
https://www.curseforge.com/minecraft/mc-mods/unifine

**Comment by Saereth** [comment]
as @lilmoefow this is not something that occurs with the default pack, you can try his mod but I can't offer optifine specific support since we are not allowed to distribute that mod with any packs.
