### ISSUE TITLE
Unable to install with the Linux server downloader

### ISSUE THREAD

**Issue by ananace** [FTBTeam/FTB-Interactions#1284]
I can't find anywhere to properly report this, no issue tracker or reporting information is provided on creeperhost or on feed-the-beast.com, so I'm opening an issue here in the hope that people who might have more information can forward it to where it's best handled.

## Modpack Version:
Broken on all available versions (2.0.4 - 2.0.9)

## Bug Report:
Running the `serverinstall_5_121` binary fails to fully download/install the pack, crashing around file 2500-3400 out of the 3547 files it wants to download.
The final error is: `Fatal error: PosixJavaThreads.start0: pthread_create` along with a massive amount of crash information.

## Expected Behavior/Suggestions:
The pack installs correctly.

## Is It Repeatable? Steps to Reproduce: 
100% repeatable on all systems tested.

Steps;
1. `curl -JO https://api.modpacks.ch/public/modpack/5/121/server/linux`
2. `chmod +x serverinstall_5_121`
3. `./serverinstall_5_121 --auto`

## Link to Log or Crash File Paste: 
Combined stdout and stderr; [combined.log](https://github.com/FTBTeam/FTB-Interactions/files/5324091/combined.log)

**Comment by ananace** [comment]
Found the correct place to report the issue, so closing it here.

**Comment by dasmou** [comment]
and whats the place? cant find it.
