### ISSUE TITLE
Crash when selecting Astral Sorcery Perks

### ISSUE THREAD

**Issue by Nocellus** [FTBTeam/FTB-Interactions#1285]
## Modpack Version: 
v2.0.9

## Bug Report:
Crash

## Expected Behavior/Suggestions:
n/a

## Is It Repeatable? Steps to Reproduce: 
1. Select all nodes up to the highlighted node in the Astral Sorcery perk tree
![image](https://user-images.githubusercontent.com/72361486/95028058-222f8280-0663-11eb-91ed-5d16eca091d7.png)
2. Select the highlighted node
3. Crash
4. Login; see highlighted node selected

Note 1: The crash does mention looking for linked nodes of which I have 2 selected (most common would be one)
Note 2: I do NOT have Gelu researched which means one of the adjacent nodes is not selectable

## Link to Log or Crash File Paste**: 
[crash-2020-10-04_16.50.05-client.txt](https://github.com/FTBTeam/FTB-Interactions/files/5324470/crash-2020-10-04_16.50.05-client.txt)

## Mod/s Affected: 
I expect astral sorcery

**Comment by madokaorimura** [comment]
Mod issue, please report to the mod author instead
