### ISSUE TITLE
Thaumcraft - Crucible not possible to make

### ISSUE THREAD

**Issue by lasiecz** [FTBTeam/FTB-Interactions#1286]
## Modpack Version: 
<2.0.9.>

## Expected Behavior:
< According to the Thauminicon and the quest you should right click the normal Crucible with Salis Mundus to create Crucible. >

## Mod version:
<Thaumcraft-1.12.2-6.1.BETA26>

It just won't turn into the Thaum Crucible, even if i put it above fire and fill it with water/mana. I tried everything.

Thanks for your help.

**Comment by madokaorimura** [comment]
you need to unlock Alchemy before get the Tc Cauldron

**Comment by lasiecz** [comment]
yeah ... found out rn ... ty
