### ISSUE TITLE
[BUG] Incorrect Multi Smelter Preview

### ISSUE THREAD

**Issue by WesMaggs** [FTBTeam/FTB-Interactions#1287]
Bug report mirror from GTCE tracker.
https://github.com/GregTechCE/GregTech/issues/1262

## Modpack Version: 
2.0.9

## Bug Report:
The 'Multiblock Pattern' preview for the Multi Smelter shows a single MV Energy input hatch on the back center bottom layer. If followed exactly this pattern will work for about 30s then 'break' to an "invalid structure" in the GUI. The correct multiblock requires 2 energy inputs, much like the EBF.

**Comment by madokaorimura** [comment]
Update to 2.0.10
Import pack in Pin at #interations
