### ISSUE TITLE
Broken Flare Spawner not Showing in JEI

### ISSUE THREAD

**Issue by desagas** [FTBTeam/FTB-Interactions#1289]
Just an enhancement suggestion:

It would be nice if the Broken flare spawner showed up in JEI, and the broken Chicken or default Broken spawner was removed. And then, a tweak in the Draconic Spawner recipe to use the flare spawner would make it so that we can both see and use the spawners that are craftable. Right now, the only way to see the recipe for the broken spawner is to view the Peace Essence Recipe from RF Tools.

**Comment by madokaorimura** [comment]
can't u use A function?

**Comment by desagas** [comment]
The point is that the way it is currently scripted, people who don’t know how to use functions won’t know that they can craft them. In response to you flippant answer, I’ll take the high road!

**Comment by desagas** [comment]
Most people won’t know how to use a function.

**Comment by Saereth** [comment]
expert pack
