### ISSUE TITLE
Basic Handy bag shows as craftable in a Celestial Altar but requires an Iridescent Altar to craft

### ISSUE THREAD

**Issue by ghzdude** [FTBTeam/FTB-Interactions#1291]
## Modpack Version: 

2.0.10
## Bug Report:

Trying to craft the handy bag in the Celestial altar shows particles and icon but stops the craft immediately. Crafting the bag in an Iridescent altar works as expected. I believe that the Handy bag requires a few too many units of starlight to actually craft.
## Expected Behavior/Suggestions:

Should be craftable in a Celestial Altar. The amount of starlight required to craft should be reduced slightly.
## Is It Repeatable? Steps to Reproduce: 

1. Place the ingredients in the Celestial altar
2. Attempt to craft the bag

What the Celestial Altar Shows
![image](https://user-images.githubusercontent.com/44148655/95539928-7eb4d980-09a4-11eb-85ee-a610b99ed8d4.png)
What the Iridescent Altar Shows
![image](https://user-images.githubusercontent.com/44148655/95540021-b9b70d00-09a4-11eb-94ad-4d46bab117a1.png)

## Link to Log or Crash File Paste**: 

N/A
## Mod/s Affected: 

Astral Sorcery, CraftTweaker, ModTweaker

**Comment by madokaorimura** [comment]
Mod issue, please report to mod author instead.

**Comment by ghzdude** [comment]
Made an issue for Astral Sorcery. What I have learned is that there is a sag in available starlight when the crafting starts, which stops the craft in this case. This behavior is intended by AS devs. Either the starlight required to craft is reduced, or it is moved to the Iridescent altar.
Issue for AS: [https://github.com/HellFirePvP/AstralSorcery/issues/1411](url)

**Comment by sgtkwol** [comment]
Possible solution would be to change the recipe so that the field generators are in the spots opened up by the iridescent altar.

**Comment by Saereth** [comment]
lowered starlight cost slightly in next update
