### ISSUE TITLE
Spellbinding cloth duplicating GTCE tools 

### ISSUE THREAD

**Issue by Jackjrblount** [FTBTeam/FTB-Interactions#1292]
![Video @jackjrblount](https://user-images.githubusercontent.com/72595516/95553893-eb47cc80-09d4-11eb-8a08-90a5511bbc7d.gif)

 Modpack Version 2.0.9

When using the spellbinding cloth from botania on a newly made terrasteel tool from GTCE(Greg Tech Community Edition) to remove the Fortune 3 will create an infinite amount unenchanted Terrasteel tools and leave the Enchanted tool behind.

The Spell Binding cloth should not make free tools.
It is Very repeatable 
1.Take any Terrasteel tool made from GTCE 
2.Put in Player's 2x2 crafting grid with spellbinding cloth as to remove the fortune 3 enchantment
3.Then Left Click on the crafting gird output (should be an unenchanted version of the tool)
4. Infinte Terrasteel tools for GTCE

Mod/s Affected: 
GregTech Community Edition, Botania

**Comment by madokaorimura** [comment]
Mod issue, please report to mod author instead.
