### ISSUE TITLE
GTCE's liquid potions cannot be filled in glass bottles

### ISSUE THREAD

**Issue by artstar234** [FTBTeam/FTB-Interactions#1293]
## Modpack Version: 
2.0.9

## Bug Report:
GTCE's brewery machine can brewing vanilla potions.(ex:potion of harming)
At this time, the potion is generated as a liquid of GTCE.
But GTCE's liquid potions cannot actually be made into vanilla potions because there is no recipe to fill a glass bottle with Thermal Expansion's Fluid Transposer.

## Expected Behavior/Suggestions:
Add a recipe to fill a glass bottle with GTCE's liquid potions.

**Comment by Saereth** [comment]
was a feature that was never fully implemented on gtces side, im not adding a ton of recipes for that
