### ISSUE TITLE
Fluid exporter not crafting

### ISSUE THREAD

**Issue by DaBlazeHunter** [FTBTeam/FTB-Interactions#1295]
## Modpack Version: 
 2.0.9

## Bug Report:
 The fluid exporter recipe from integrated tunnels mod does not appear to be working. It says the crafting recipe is just one to one fluid importer to fluid exporter, but when I try to craft it the resulting item is the Fluid importer.

## Expected Behavior/Suggestions:
Put fluid importer in the crafting grid, get a fluid exporter as a result

## Is It Repeatable? Steps to Reproduce: 

1. Attempt to craft fluid exporter
2. Actually craft fluid importer

**Comment by madokaorimura** [comment]
I can't reproduce the issue tho

**Comment by DaBlazeHunter** [comment]
uhhh, idk, I will upload a screen shot in a couple of minutes, been away from my computer for a while

**Comment by sgtkwol** [comment]
I'm seeing the same issue. Perhaps an assembler recipe to convert between the two?
