### ISSUE TITLE
nether portal stopped working after incorrect saving of the world

### ISSUE THREAD

**Issue by oeldeaf** [FTBTeam/FTB-Interactions#1296]
## Modpack Version: 
2.09

## Bug Report:
my computer shut from external problems and after i loaded my savegame the area in the vois realm where starting island should be reset to that island and all the blocks either disappeared or got replaced with blocks from the starting island. This piece of information was purely to explain the full story. The problem is that my nether portal has stopped working, when i step into it, the screen just spins as it normally would, but thats it, no teleporting at all. For the record, overworld portal works just fine and with some config tweaks i allowed the construction of the vanilla portal and its also not working

## Expected Behavior/Suggestions:
obviously this issue occured after the incorrect exit from the game, this much is for sure.

**Comment by madokaorimura** [comment]
Ưhen you go to nether portal, do your console show any error?

**Comment by oeldeaf** [comment]
how can i access the console?
