### ISSUE TITLE
Recipe conflicts

### ISSUE THREAD

**Issue by Dasavanth** [FTBTeam/FTB-Interactions#1299]
## Modpack Version: 
2.0.10

## Bug Report:
literally the title, steel foil and epmty shape plate share the same circuit and both require steel plates, so its not possible to make empty shape plates in metal bender

## Expected Behavior/Suggestions:
making the shape plate use a different code

## Is It Repeatable? Steps to Reproduce: 

1.
2.
N/A

## Link to Log or Crash File Paste**: 
N/A

**Comment by Dasavanth** [comment]
ive also noticed this recipe conflict
![2020-10-20_15 59 24](https://user-images.githubusercontent.com/69692930/96574701-6c646500-12ed-11eb-8cd9-05ef71f7a3e2.png)

**Comment by madokaorimura** [comment]
it is gregtech recipe handle, so sadly but you can use forge hammer tho

**Comment by Dasavanth** [comment]
wdym? yea im not says its uplayable. i just would like to see it fixed :P

**Comment by Dasavanth** [comment]
another one 
![2020-10-26_02 30 48](https://user-images.githubusercontent.com/69692930/97118997-6201fb00-1733-11eb-886e-b805ac93d3a6.png)

**Comment by madokaorimura** [comment]
the fix need to be on the mod, not modpack :p
