### ISSUE TITLE
bronze rod file crafting recipie is different from other rod file crafting recipies in shape for no reason

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#13]
Submitter: `FTB Interactions#2470`
Body: `**[Lezarius]** OwO issue "bronze rod file crafting recipie is different from other rod file crafting recipies in shape for no reason"`
Attachments:

**Comment by Vyraal1** [comment]
Fixed, we had a legacy script to 'fix' certain rods with weird recipes.Removed those now as they seem to generate properly.
