### ISSUE TITLE
Crafting Harvestcraft's "Fresh Milk" at a Cooking Table does not consume Clay Milk Bucket

### ISSUE THREAD

**Issue by zornor** [FTBTeam/FTB-Interactions#130]
## Modpack Version: 
1.0.1

## Bug Report:
At a Cooking Table, crafting "Fresh Milk" with a Milk Clay Bucket gives 4 Fresh Milks, retains the Milk Clay Bucket and gives a duplicates Clay Bucket. No Milk Jars are in the kitchen.

Video: https://i.imgur.com/H7OYMxG.mp4

## Expected Behaviour/Suggestions:
Should only give one Clay Bucket and 4 Fresh Milks

## Mod/s Affected: 
Pam's HarvestCraft
Cooking for Blockheads
CraftTweaker2
Ceramics

**Comment by Vyraal1** [comment]
Unfortunately had to go with an alternative route, fresh milk and water are removed from shaped crafting recipes. But should be easier to craft and automate.

![image](https://user-images.githubusercontent.com/26587049/55296426-3e57c100-53e7-11e9-9fc0-11656214ee2b.png)

![image](https://user-images.githubusercontent.com/26587049/55296428-41eb4800-53e7-11e9-990a-7df132472d16.png)
