### ISSUE TITLE
/home in a boat will teleport you to the wrong location

### ISSUE THREAD

**Issue by thedragonslayr** [FTBTeam/FTB-Interactions#1300]
## Modpack Version: 
2.0.9

## Bug Report:
I was in a boat on the water when I used /home teleporting me from the overworld to my void base. The boat arrived in the correct location yet I was teleported over 400 blocks away and died in the void

## Expected Behavior/Suggestions:
either both you and the boat will be teleported to the correct location, or the boat will be left behind and you will be teleported to the correct location.

## Is It Repeatable? Steps to Reproduce: 
get in a boat in the overworld while your home is set in the void. type /home.
the second time I tried I was teleport only around 50 blocks off the correct location
https://youtu.be/3hIlHwHX2To

**Comment by Saereth** [comment]
vanilla boat implementation+teleporting mod weirdness, not much I can do about it, get out of your boat before /home I suppose
