### ISSUE TITLE
Game Crash on world startup

### ISSUE THREAD

**Issue by FireGoldsky** [FTBTeam/FTB-Interactions#1301]
## Modpack Version: 
2.0.9

## Bug Report:
Game crashes while loading up a save

## Is It Repeatable? Steps to Reproduce: 
Have no idea.

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/c5cefab7

## Mod/s Affected: 
Not really mods affected but the first time it crashed it happened right after I placed a logistics pipes pipe, and the first crash said the probable mod causing the crash was LP itself

**Comment by Saereth** [comment]
let me know if this happens after update to 2.0.12 comes out
