### ISSUE TITLE
my game keeps not responding and a unknown issue

### ISSUE THREAD

**Issue by Investedrat907** [FTBTeam/FTB-Interactions#1302]
I am playing on a server with a friend and my game keeps randomly not responding for no reason even though 5 seconds ago the game was fine at a smooth 100 fps and this message keeps popping up so I click ctrl+i and click get link and it says failed. my friend think it could be the reason the game keeps not responding v2.0.9
![2020 10 21-19 48](https://user-images.githubusercontent.com/73253197/96771412-84191780-13d9-11eb-9d03-93b1acc4715d.png)

**Comment by Investedrat907** [comment]
![2020 10 24-01 14](https://user-images.githubusercontent.com/73253197/97063229-56c59880-1596-11eb-8139-2cb5d205b514.png)
this is what i'm on about

**Comment by madokaorimura** [comment]
first, mod issue
second, open crash-report folder and upload latest log
