### ISSUE TITLE
Server is Vanilla when it isnt supposed to be

### ISSUE THREAD

**Issue by BillyBobJoe12345** [FTBTeam/FTB-Interactions#1304]
1.Yes its repeatable
2. Don't know the steps other than booting the server ## Modpack Version: ## Modpack Version: 2.0.9
<!--  --!>
## Picture Evidence
[Vanilla when not needed](https://user-images.githubusercontent.com/73456553/97134344-3d455d80-170a-11eb-86ac-9165543f11c0.PNG)
<!-- --!>

**Comment by anabsolutesloth** [comment]
You probably ran the Minecraft Server .jar instead of the Forge server jar or Boot script in the Server Pack.

**Comment by BillyBobJoe12345** [comment]
what do you mean server pack? also what is the difference between Minecraft server jar and forge server jar as there isnt a forge server file but the minecraft one came from the forge installer

**Comment by madokaorimura** [comment]
first, download serverpack from website or FTBApp
then **run .bat** file

**Comment by madokaorimura** [comment]
minecraft_server.jar is pure vanilla 
and forge_.....jar is ***forge***

**Comment by PoolloverNathan** [comment]
yea i found that out the hard way
luckily the chunks that had modded blocks removed didn't save
