### ISSUE TITLE
Fluid Satellite Pipe crash

### ISSUE THREAD

**Issue by Inurta** [FTBTeam/FTB-Interactions#1306]
##  Modpack Version: 
2.0.9

## Bug Report:
Crash on startup, related to Gregtech or Logistics Pipes

## Expected Behavior/Suggestions:
The world should be able to start normally

## Is It Repeatable? Steps to Reproduce: 
1. Have an Electric Blast Furnace setup with an input hatch (LV)
2. Add a Fluid Satellite Pipe onto the hatch
3. Save and quit then load the world back up

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/ca150004

## Mod/s Affected: 
Gregtech Community Edition, Logistics Pipes

## Known Fix: 
I am able to fix it by deleting the Fluid Satellite block in MCEdit and reloading the world

**Comment by Keridos** [comment]
Seems to be a GT issue, I got a similar CME crashlog with a conduit from enderio and a GT machine
