### ISSUE TITLE
Actually Additions advanced rings cannot be crafted into baubles

### ISSUE THREAD

**Issue by superhelicase** [FTBTeam/FTB-Interactions#1308]
## Modpack Version: 
2.0.9

## Bug Report:
Actually Additions advanced rings cannot be crafted into the bauble versions

## Expected Behavior/Suggestions:
The recipe exists to craft the Actually additions rings into the bauble versions as provided by the included mod Actually Baubles, and the item can be shift clicked into a crafting table from JEI, but there is no output item in the table. 

## Is It Repeatable? Steps to Reproduce: 
1. Take recently crafted AA advanced ring
2. Place into crafting table

**Comment by XelfXendr** [comment]
Same here. If you just want to get it, teaching it to Logistic Pipes autocrafter and requesting it did the trick for me.

**Comment by Saereth** [comment]
looks like a mod issue unfortunately and its no longer support :( sad times
