### ISSUE TITLE
Rewiring of Logistic Fluid Satellite Pipe causes inaccessible world.

### ISSUE THREAD

**Issue by OtTerror247** [FTBTeam/FTB-Interactions#1309]
## Modpack Version: 
2.0.9

## Bug Report:
Logistic Fluid Satellite Pipe crashed the game and now I can't open that world anymore.

## Expected Behavior/Suggestions:
The Crafting pipe should show UNKNOWN NAME if the previously connected Fluid Satellite were removed and another, yet unnamed, Fluid Satellite were connected right after, instead of crashing indefinitely.

## Is It Repeatable? Steps to Reproduce: 
1. Place a Fluid Solidifier with a Logistics Chassis Mk1 on top of it and a Logistics Fluid Satellite Pipe in front of it and connect them.
2. Give the Mk1 a module upgrade, a crafting module and a fluid crafting module.
3. Give the Fluid Satellite a name and connect the Mk1 to it via the GUI.
4. Destroy the Fluid Satellite and place a Fluid Satellite behind the Fluid Solidifier, connect it to the Mk1, but don't give it a name.
5. Open the Mk1 and go to the screen to select a Fluid Satellite.
6. Crash.

## Link to Log or Crash File Paste: 
https://paste.feed-the-beast.com/view/2c6e20d7

## Mod/s Affected: 
It has shown Logistic Pipes, GTCE and FastWorkbench upon crashing and reloading the world.

## Known Fix: 
-

**Comment by Vic3Dexe** [comment]
Yep, had the same. Destroy fluid satellite in MCEdit, then the world should load with no problems.

**Comment by ikerm2003** [comment]
> Yep, had the same. Destroy fluid satellite in MCEdit, then the world should load with no problems.

mcEdit doesn't allow me to do it lmao

**Comment by ikerm2003** [comment]
@OtTerror247, i'm going also to reported to LP issue tracker, and because you have the same issue, I will link them also to here, simply because i don't have access to my logs.
if you have any problem, tell me and I delete the link :D
