### ISSUE TITLE
Monocrystalline Silicon Boule recipe not working

### ISSUE THREAD

**Issue by weightmaker** [FTBTeam/FTB-Interactions#1310]
## Modpack Version: 
2.0.9

## Bug Report:
Blast furnace recipe for "monocrystalline Silicon Boule" doesnt work.(Electric Blast Furnace

## Expected Behavior/Suggestions:
Should start crafting 

## Is It Repeatable? Steps to Reproduce: 
according to JEI it should be possible with the lowest tier of the blast furnace (LV versions and Cupreonickel Coils)
1.Put the Items in the input hatch
2.nothing happens. 

## Link to Log or Crash File Paste**: 
No Crash

## Mod/s Affected: 
No additional mods

## Known Fix: 
cheat it in?(according to discord chat). 

## Extra info
tested with different coils and adding fluid in/output hatches which didnt fix it

**Comment by weightmaker** [comment]
tested with both LV and MV Energy Input Hatches*

**Comment by Adharainspace** [comment]
did you try the chip

**Comment by weightmaker** [comment]
yeah i changed the chip number back and forth between testing but nothing fixed it.
Since then i've moved it and made multiple others and havent had a need to make more. Tested it now and it works. I believe what caused it was that the chunk boundry was between the controller and the input-bus but i havent tested by moving it back where it was. 
As i believed the chunk boundry thing only became an issue with chunk loading and would be fixed by breaking/replacing the multiblock, i didnt test this in the start and never made a crafting pattern for it.

**Comment by weightmaker** [comment]
other people i talked to who had this issue just told me they just cheated the items in(like i did) and had not reported it so i did. Im still not sure if its a user error or a bug.
