### ISSUE TITLE
Mutant Steves can break gravestones

### ISSUE THREAD

**Issue by cabmoomoo** [FTBTeam/FTB-Interactions#1311]
Mutant Steves are mean.
They broke my grave like nothing,
leaving me quite sad.

## Modpack Version: 
FTB Interactions 2.0.9

## Bug Report:
Mutant Steves seem to be able to break gravestones. When they do, none of the items drop. It was quite depressing to fall into a ravine next to a Mutant Steve spawner with all my good gear, just to watch as they casually break the gravestone a destroy it all. The first time I fell in the ravine, my shift key malfucntioned. Then I fell in while making stairs to go down as some angry boi shot me. Both graves were obliterated mercilessly. I do not know if it was them breaking a gravestone block, or the block under it; I'm not even sure the gravestones in this pack have a block to be broken.

**Comment by madokaorimura** [comment]
Warning in the quest already!

**Comment by cabmoomoo** [comment]
Nice, I even looked at that before and didn't see it. Big brain time.
