### ISSUE TITLE
Celestial gateway to ISS not working

### ISSUE THREAD

**Issue by Vic3Dexe** [FTBTeam/FTB-Interactions#1313]
## Modpack Version: 
2.0.9

## Bug Report:
Can't use celestial gateway to ISS, it shows particles and nothing happened.
But I can teleport from ISS to main base (DIM100).
Rocket was launched from void world and succesfully returned.

DW20 had this issue, and he fixed it with login/logout, but this not working for me.

What I've tried:
1. Build gateway in void world (DIM0) - same thing. I can teleport between DIM100 and DIM0, but not to the ISS.
2. /tpx -2 - says it teleports me, but nothing happened.
3. Chunkload ISS - not helping.
4. Update AS to 1.10.27 - not helping
5. Make a new world, switched to creative and build gateways and rocket from scratch. Not working.

## Expected Behavior/Suggestions:
It should teleport you to ISS's gateway

## Is It Repeatable? Steps to Reproduce: 
1. Build celestial gateway in DIM100.
2. Build ISS.
3. Build celestial gateway on ISS.
4. Return to DIM100 on rocket or via gateway.
5. Try to go back to ISS via gateway.

## Link to Log or Crash File Paste**: 
-

## Mod/s Affected: 
AS
Advanced rocketry

## Known Fix: 
login/logout, but it doesn't work for me

**Comment by Benjimino** [comment]
I had the same problem, and logout+login didn't work either.
It was related to tracked progression for some reason.
I had to pick up my guidance computer as an item, then got a chat message about progression, then teleporting worked.

(I previously crafted it using the logistics request table so never actually 'picked it up')

**Comment by Vic3Dexe** [comment]
I'll try, but how you can build the rocket without placing guidance computer?

**Comment by Benjimino** [comment]
I mean, just place the guidance computer down and dig it up again. Then put it down again.

AFAIK is the action of picking up the guidance computer that triggers progression, so you have to do that action.

**Comment by Benjimino** [comment]
Also try just dropping it as an item and picking it up again- just to make sure 😅

**Comment by Vic3Dexe** [comment]
OMG it works!! o_O
Needs to disassemble my rocket but that's ok.

Thanks man!

**Comment by Benjimino** [comment]
No worries. I spent ages googling for that solution- glad I could save someone the time haha

Fair warning- from my experience, Advanced Rocketry is great but pretty unstable as far as mods go. Best to backup you world (using '/backup start') before using your rocket to go to New worlds the first time.

**Comment by PoolloverNathan** [comment]
Almost disassembled my gateway before I saw this issue, thanks
