### ISSUE TITLE
Time in a bottle resets time from one SP save to another.

### ISSUE THREAD

**Issue by nala2624** [FTBTeam/FTB-Interactions#1315]
## Modpack Version: 
2.0.9

## Bug Report:
When switching to a test world and back to the primary save, the Time in a Bottle resets in the main save to what is in the test world.

## Expected Behavior/Suggestions:
TiaB expected to keep time saved separate between saves.
TiaB should keep time saved on individual saves, and not interfere with TiaB on other saves.

## Is It Repeatable? Steps to Reproduce: 
Extremely intermittent. Has happened twice now. Can not reliably reproduce issue.
1.
2.

## Link to Log or Crash File Paste**: 
No crash file generated.

## Mod/s Affected: 
Which ever mod TiaB belongs to.

## Known Fix: 
No known fix.

**Comment by Saereth** [comment]
yeah this wont get fixed, its not a pack issue and that mod isnt getting dev work
