### ISSUE TITLE
The One Probe tooltips broken for Gregtech items in containers/barrels etc.

### ISSUE THREAD

**Issue by Keridos** [FTBTeam/FTB-Interactions#1316]
## Modpack Version: 
2.0.9

## Bug Report:
TOP tooltips wrong with Gregtech Items. Seems like the wrong localization string (see image, it should not be the meta items string) is being pulled.

## Expected Behavior/Suggestions:
The One Probe tooltip should show the correct item name

## Is It Repeatable? Steps to Reproduce: 

1. place gregtech ingot. f.ex. in a cache or barrel
2. Press shift to crouch to see the advanced tooltip
![image](https://user-images.githubusercontent.com/2742845/99193781-7d34b900-277b-11eb-81d3-39a4f3edc97f.png)

## Mod/s Affected: 
Gregtech, The one Probe

**Comment by madokaorimura** [comment]
Could you report it to GTCE?

**Comment by Saereth** [comment]
this has been mentioned to gtce dev but its more an issue of how top handles localizations, either way this is out of my hands
