### ISSUE TITLE
sooty marble recipe

### ISSUE THREAD

**Issue by ryeguy859** [FTBTeam/FTB-Interactions#132]
## Modpack Version: 
latest 1.0.1

The sooty marble recipe in jei doesnt work, the correct working recipe is found in the astral sorcery book 8 marble around one coal. 

![image](https://user-images.githubusercontent.com/49115406/55286531-bf24a780-536a-11e9-9c40-d41ddec3857c.png)

![image](https://user-images.githubusercontent.com/49115406/55286535-ccda2d00-536a-11e9-9c8b-2c881a68687c.png)

![image](https://user-images.githubusercontent.com/49115406/55286541-d8c5ef00-536a-11e9-803d-4d7dea3bebfc.png)

**Comment by Doppelganker** [comment]
The intended recipe is the one in JEI, if that one doesn't work, check scripts on the server.

**Comment by Vyraal1** [comment]
What Dopple said
