### ISSUE TITLE
LuV Diesel Generator - too hard to see it's the blue colored frames, and not the normal frames.

### ISSUE THREAD

**Issue by madmacf** [FTBTeam/FTB-Interactions#1321]
## Modpack Version: 
2.0.9

## Bug Report:
It's not really a bug. But building the LuV Diesel Generator is silly. It requires tungstensteel frame COLERED BLUE. It's almost impossible to see in the preview. All the frames in different color has the same name. I had to look in the config, that it requires the frame@11. The normal frame is also blue. Just a tad lighter in color.

## Expected Behavior/Suggestions:
Make it clear it has to be the blue one, or just use the normal one.

**Comment by madokaorimura** [comment]
Sadly, it is mod bug (Modular Machinery)
This also happened to Sky Cauldron multiblock preview

**Comment by Saereth** [comment]
not much I can do about this one, it's on MM's side
