### ISSUE TITLE
world crash. Locked out of game.

### ISSUE THREAD

**Issue by madmacf** [FTBTeam/FTB-Interactions#1322]
## Modpack Version: 
2.0.9

## Bug Report:
Inside compact machine. Placed gregtech cable toucing compact machine tunnel. "Rotated" the tunnel. Game crashed. Game crashes immidiatly upon loading the world again.

## Is It Repeatable? Steps to Reproduce: 
Every time.

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/319c8f69

**Comment by madokaorimura** [comment]
So look like you have done the forrbidden.
This is problem with CMs, so report to mod author instead.

**Comment by Saereth** [comment]
in config/forge.cfg set remove erroring to true and restart it'll nuke the cable, also dont connect gt cables to cms :p
