### ISSUE TITLE
Flask Roulette

### ISSUE THREAD

**Issue by sgtkwol** [FTBTeam/FTB-Interactions#1325]
## Modpack Version: 
2.0.9

## Bug Report:
Flasks randomly disappear from view from ME system. They seem to come back after rebooting. This occurs both with using the filler and with other systems using flasks. Bug is already reported with the mod, itself.

## Expected Behavior/Suggestions:
Remove the quest to indicate that flasks are useful until this bug is resolved.

## Is It Repeatable? Steps to Reproduce: 
There is no way to reproduce this consistently. I've worked with the same flask and crafted with it, then it just stops being seen.

## Mod/s Affected: 
Volumetric Flasks

**Comment by KorewaLidesu** [comment]
No need to remove quest
Issue happen when you play with OpenJ9 only

**Comment by depsylon** [comment]
I have a similar issue, some flask (types) are only usable directly after starting the world and after a few minutes they are still visible but can't be exported via a terminal and can't be used in the filler. I guess this issue has the same origin, but my server console (which is on the same PC as the client) says. 

> [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_281, running on Windows 10:amd64:10.0
so it looks like I have Hotspot but it still doesn't work or I don't have the right version or something like this.

**Comment by Saereth** [comment]
I cant reproduce this

**Comment by KorewaLidesu** [comment]
@Saereth this happen when use OpenJ9 version back then
Don't know if fixed in new OJ9

_Sent from my 2201117TG using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Saereth** [comment]
Thanks for the extra info @KorewaLidesu. Not really sure this is something I could address as the pack dev regardless, maybe something to take up with the developers for those mods.
