### ISSUE TITLE
Chicken Roost Lighting Bug

### ISSUE THREAD

**Issue by YOUJUSTCANTNEMO** [FTBTeam/FTB-Interactions#1327]
## Modpack Version: 
2.09

## Bug Report:
Placing chicken roosts next to each other breaks the lighting for all involved. It just turns some of the side faces of the roost and the chickens black. Roosts that aren't touching are fine though. I currently have optifine installed, but the problem existed before I installed optifine and has persisted.
![Screenshot (181)](https://user-images.githubusercontent.com/75553034/101269967-2f8bea80-3742-11eb-9b4d-cf7c8c542994.png)

## Is It Repeatable? Steps to Reproduce: 

1. Place 2 chicken roosts next to each other
2. ...
3. Profit

**Comment by madokaorimura** [comment]
This is mod issue.
Please report this to mod author instead.
