### ISSUE TITLE
Hellfire Kilns are very laggy

### ISSUE THREAD

**Issue by mtrevor** [FTBTeam/FTB-Interactions#1329]
## Modpack Version: 
2.0.9

## Bug Report:
Hellfire kilns are incredibly laggy even while idle. I suddenly noticed a massive FPS drop from ~180 to ~40, LagGoggles seems to indicate that the kilns are responsible. I have been heavily leaning on running them in parallel due to their overall cheapness, but it seems out there was a secret cost all along.

The three hotspots here are all kiln machine controllers, and all kilns are currently idle. Their lag time is 10x greater than anything else. The multi-block smelter I'm replacing them with is to their left and is significantly less cpu hungry.

![2020-12-13_12 39 03](https://user-images.githubusercontent.com/4484396/102001828-14bd0580-3d42-11eb-90d6-84d05f0a3042.png)

Is this possibly due to them constantly confirming their viability?

## Expected Behavior/Suggestions:
By this stage, replacing them with the multi-smelter isn't a big issue, except there isn't total recipe parity with the hellfire kilns, so it's more of a pita than anything else.

**Comment by Saereth** [comment]
did some optimizations to the recipe list, should help
