### ISSUE TITLE
Thaumic Jei not working properly

### ISSUE THREAD

**Issue by zTotto** [FTBTeam/FTB-Interactions#133]
[2019-03-31-3.log](https://github.com/FTBTeam/FTB-Interactions/files/3026460/2019-03-31-3.log)
## Modpack Version: 
1.0.1

## Bug Report:
Setting "B:enableAspectFromItemStacks=false" to true (to see which items give you a certain aspect) breaks Thaumic Jei, preventing you to see any thaumcraft recipe

## Expected Behavior/Suggestions:
Bugs: I should be able to turn it on

## Is It Repeatable? Steps to Reproduce: 

1. Set "B:enableAspectFromItemStacks=false" to "true"

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/cdfff559

## Mod/s Affected: 
Thaumcraft

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/55335984-2bd29b80-546a-11e9-869e-2f58d097716d.png)

**Comment by zTotto** [comment]
Sorry, I didn't know. Btw I removed emojiful and it now works but I don't know if it's related

**Comment by Saereth** [comment]
@zTotto does it work on servers? thats where the main breaking is occuring, it typically works for me in singleplayer by default

**Comment by zTotto** [comment]
yes, it does

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/55342961-ffbe1700-5477-11e9-880c-13964f45c49c.png)

Might have to test for it ourselves in FTB one

**Comment by Vyraal1** [comment]
Closing this issue, turns out removing Emojiful didn't help.
