### ISSUE TITLE
Summoning Altar 

### ISSUE THREAD

**Issue by gladiio** [FTBTeam/FTB-Interactions#1330]
## Is It Repeatable? Steps to Reproduce: 

1.
2.

## Mod/s Affected: 

Zen Summoning

**Comment by gladiio** [comment]
the crafting recipe is not working have tried searching google for answers none seemed to work, so am now writing a brief ticket.

**Comment by madokaorimura** [comment]
On the altar is catalist (shift-R when there is enough items)
4 cornor is item need to put in the altar
