### ISSUE TITLE
Duplication bug with Copy-paste gadget and mechanical user

### ISSUE THREAD

**Issue by sebastianorizzetto** [FTBTeam/FTB-Interactions#1331]
Hi, today i was trying to automate che creation of compact machines, and i stepped across a very bad duplication bug: if you use a copy-paste gadget inside of a mechanical user, the gadget place the block like usual BUT it does not use the block it is placing.

## Modpack Version: 
2.0.9

## Bug Report:
If you use a mechanical user to paste a block, and you set the inventory to use as the mechanical user itself, the mechanical user will place the block as usual, but the block inside the mechanical user will not be used, resulting in a duplication bug.
I also attach a video showing the bug in action.

[Copy-paste bug.zip](https://github.com/FTBTeam/FTB-Interactions/files/5710484/Copy-paste.bug.zip)

## Expected Behavior/Suggestions:
The expected behavior is that the block placed get used by the copy-paste gadget.

## Is It Repeatable? Steps to Reproduce: 
1. Copy a block with the copy-paste gadget
2. Switch to paste mode
3. Set the inventory as the mechanical user
4. Put a block in front of the user, so it has something to click on
5. Put the gadget inside the user (in the upper left corner), and put the block to duplicate inside the user.
6. At this point the duplication will start, if you place a breaker where the block is placed it is also easily automatable

## Mod/s Affected: 
Building gadget, Extra utilityes 2

**Comment by Saereth** [comment]
report this to building gadgets, its not a pack issue
