### ISSUE TITLE
Server Download From FTB App

### ISSUE THREAD

**Issue by jmpuetz** [FTBTeam/FTB-Interactions#1332]
My friend and I were trying to setup I private server for us to play the pack but when we went to start the server we were getting errors saying that the server did not have the actually additions mod. Eventually I noticed that some of the mods downloaded were size 0 KB I was able to get around this by coping the affected mods from another source(my client game).

## Modpack Version: 
2.0.9

## Bug Report:
Sserver was thinking that a few mods were not installed

## Expected Behavior/Suggestions:
Server crashes saying MissingModsException: Mod actuallybaubles (Actually Baubles) requires [actuallyadditions]

## Is It Repeatable? Steps to Reproduce: 

1.Run the serverinstall_5_121 that is downloaded from the FTB app.
2.Open the mods folder and sort by file size. All with size 0KB are affected.

## Link to Log or Crash File Paste**: 

https://paste.feed-the-beast.com/view/5c845130

## Mod/s Affected: 

Actually Additions
Deadly Monsters
Doom like Dungeons
Ender Storage
STG
Xaeros World Map
![image](https://user-images.githubusercontent.com/24917683/102700053-89df7d80-420f-11eb-8cc5-f958da9dd4b2.png)

## Known Fix: 

Copy the mods affected from another source. I did a client version of the game.

**Comment by KorewaLidesu** [comment]
Make sure to get a clean setup.

**Comment by Saereth** [comment]
this should resolve with the new update
