### ISSUE TITLE
Dense coal unable to be used in a hellfire kiln

### ISSUE THREAD

**Issue by Tw3n7y** [FTBTeam/FTB-Interactions#1333]
## Modpack Version: 
2.0.10

## Bug Report:
Dense coal ore cannot be converted into Native Coal Clusters using a Hellfire Kiln, and coal clumps, crystals, and shards cannot be converted at all.

## Expected Behavior/Suggestions:
Dense coal ore should be able to be converted to native coal clusters using the hellfire kiln, and clumps, crystals, and shards should be able to be converted to native coal clusters.

**Comment by KorewaLidesu** [comment]
You should able to process coal ore tho.....
