### ISSUE TITLE
No recipe for opencomputers cable :<

### ISSUE THREAD

**Issue by Nilixen** [FTBTeam/FTB-Interactions#1335]
## Modpack Version: 
2.0.9

## Bug Report:
There's no recipe for cable from OpenComputers mod.

## Expected Behavior/Suggestions:
There should be a recipe for cables. If there're no cables, then why there's a recipe for switch or relay?

## Mod/s Affected: 
OpenComputers

**Comment by Saereth** [comment]
duplicate
