### ISSUE TITLE
Diploid Polylattice Crystal recipe problem

### ISSUE THREAD

**Issue by Hiold** [FTBTeam/FTB-Interactions#1336]
## Modpack Version: 
2.0.9

## Bug Report:
uncertainty

## Expected Behavior/Suggestions:
Is the recipe for the Diploid Polylattice Crystal supposed to be in the Alloy Smelter? It seems very strange that it consumes the nether star lens, when the majority of similar recipes (Material + Lens for Applied Energistics parts) instead use the Laser Engraver and thus don't consume the lens.

## Is It Repeatable? Steps to Reproduce: 
recipe on Alloy Smelter

## Link to Log or Crash File Paste**: 
not crash

## Mod/s Affected: 
none

## Known Fix: 
none

**Comment by Nilixen** [comment]
Well, I think it's probably intented to consume that lens, since there's a chicken for Diploid Polylattice Crystal. But still it's weird to consume lens; Nether Star Plate would fit better in this recipe.

**Comment by Hiold** [comment]
thanks for your help
