### ISSUE TITLE
Veinmining Chests destroys contents

### ISSUE THREAD

**Issue by Calaheim-Koraka** [FTBTeam/FTB-Interactions#1337]
## Bug Report:
Veinmining chests destroys chest contents

## Expected Behavior/Suggestions:
Items drop from chests or cant veinmine chests at all.

## Is It Repeatable? Steps to Reproduce: 
Get axe and chest with items veinmine chest to be lazy get no items

**Comment by KorewaLidesu** [comment]
Can you send a picture/gif/video how to reproduce the issue?

**Comment by Saereth** [comment]
I havent been able to reproduce this, re-open if you have something more
