### ISSUE TITLE
AE2 Autocrafting Crashing Server

### ISSUE THREAD

**Issue by nickthenickle** [FTBTeam/FTB-Interactions#1338]
## Modpack Version: 
FTB Interactions version 2.0.9

## Bug Report:
I Autocraft with AE2 Co-Processing Unit linked to recipes in logistics crafter and the server crashes

## Expected Behavior/Suggestions:
The expected behavior would to execute the recipe without crashing server

## Is It Repeatable? Steps to Reproduce: 
I was not able to repeat on single player copy of world but crashes consistently on server run on different computer

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/4a2973cf

## Mod/s Affected: 
From reading the crash report it seems to come from AE2 possibly something with the CraftingCPUCluster

**Comment by KorewaLidesu** [comment]
Make sure you dont mess up with your recipe setup.
