### ISSUE TITLE
Wizardry making FTB Interactions crash on mac

### ISSUE THREAD

**Issue by WhatTheCrab** [FTBTeam/FTB-Interactions#134]
## Modpack Version: 
1.0.1

## Bug Report:
The game crashes in the start-up of the Pre-initialzing phase when Wizardry is trying to load in.

## Expected Behavior/Suggestions:
Well it's supposed to load in as normally and go on to the next phase of the start-up.

## Link to Log or Crash File Paste**: 
https://pastebin.com/yHWWmue5

## Mod/s Affected: 
Wizardry

**Comment by Doppelganker** [comment]
Looks like your are using old java version, try to update java and make sure your launcher uses new version.
https://www.reddit.com/r/feedthebeast/comments/80nhie/twitch_launcher_forcing_old_java_versions_on_you/

**Comment by WhatTheCrab** [comment]
I downloaded the lates version and installed MultiMC because the Twitch launcher wasn't working, and it worked! Thank you!
