### ISSUE TITLE
Crash when starting up

### ISSUE THREAD

**Issue by ekaj113** [FTBTeam/FTB-Interactions#1340]
## Modpack Version: 
2.0.9 downloaded via MultiMC

## Bug Report:
It crashes when loading the modpack

## Expected Behavior/Suggestions:
For the modpack to load

## Is It Repeatable? Steps to Reproduce: 
push launch

## Link to Log or Crash File Paste**: 
Console Log: https://paste.feed-the-beast.com/view/ceff8be9
debug.log: https://paste.feed-the-beast.com/view/063a9cd8
It seems no crash report was made

**Comment by Saereth** [comment]
I was unable to reproduce, let me know if anyone runs into this issue after the next update
