### ISSUE TITLE
No recipe for Dense Sphalerite

### ISSUE THREAD

**Issue by DMLON** [FTBTeam/FTB-Interactions#1341]
## Modpack Version: 
2.0.9

## Bug Report:
No recipe for dense Sphalerite nor variants, there is no recipe for that. Can't multiple zinc ore.

## Expected Behavior/Suggestions:
Add recipe for dense Sphalerite from nether sphalerite and variants

**Comment by DMLON** [comment]
Sorry forgot to add that there is also not a recipe for dense sphalerite to native cluster

**Comment by Saereth** [comment]
this was intentionally left out, the quest even says to check useages as not all ores are duplicated the same/have the same option
