### ISSUE TITLE
Duplication Glitch with Conveyors and Strainers

### ISSUE THREAD

**Issue by Meltoria** [FTBTeam/FTB-Interactions#1346]
## Modpack Version: 
2.0.9

## Bug Report:
When items in a stack of 3 or greater are dropped into a strainer, hoppered into a chest and then conveyored from said chest up a ramp, and as the items land they land on a conveyor that has two extraction ports to two diffrent chests on either side of the conveyor piece. The game then places the item in both chests effectively duplicating it.

When dropped by hand it places them in both but when you pick it up from one chest it removes from the other. And when manually placed into the chest it splits the stacks evenly. I have yet to try placing it into a chest with a hoppper instead of a strainer yet.

## Expected Behavior/Suggestions:
<!-- Bugs: It is allowing items to be replicated for free
<!-- Suggestions: It should not duplicate the items as there should only be one copy each

## Is It Repeatable? Steps to Reproduce: 
1. Drop a stack of three or more items into an ampty strainer that has a hopper connected below it
2. Extract the items from the empty chest below with an extraction conveyor upgrade. 
3. Run said items up a ramp (Not sure if ramp is neccessary) and on the conveyor where they land have two insertion conveyor upgrades connected to chests with the "Inserting all items from conveyor" setting on

## Link to Log or Crash File Paste**: 
I am not sure how to do this sadly

**Comment by Saereth** [comment]
you can report it to industrial foregoing dev but I wouldnt expect a fix on an older version. Unfortunately many dupes will always exist in modded, we try to eliminate where we can but it is what it is. This particular issue is out of my hands short of disabling them which would be less than ideal
