### ISSUE TITLE
Digital miner does not mine naquadah/enriched naquadah

### ISSUE THREAD

**Issue by Architectoid** [FTBTeam/FTB-Interactions#1348]
## Modpack Version: 
2.0.9

## Bug Report:
Trying to use digital miner on Aurellia to get lots of naquadah and enriched naquadah but when I program the ore in using the ore dict filter it only mines up the andesite version of the ore.

## Expected Behavior/Suggestions:
Unless this is intended the miner should mine up all of the naquadah ore in the specified area and dump it into a chest. I should also say that the miner works for other ores in the overworld that I have tried to mine.

## Is It Repeatable? Steps to Reproduce: 
1. Go to Aurellia.
2. Find Naquadah vein.
3. Set up miner with flux point/spectre coils and a chest behind it.
4. Set up filter using ore dict and using the name: oreNaquadah and oreNaquadahEnriched
5. Set area
6. Press save and start
7. No naquadah is collected when it should be.

## Mod/s Affected: 
Mekanism

**Comment by Saereth** [comment]
This is a mek bug but seeing as its 1.12 it's beyond the mod's scope of support so we're stuck with it unfortunately
