### ISSUE TITLE
Fire and Ice mobs spawning /w no AI

### ISSUE THREAD

**Issue by Chinthor** [FTBTeam/FTB-Interactions#1349]
## Modpack Version: 
2.0.9

## Bug Report:
Mobs spawning with no AI. Mostly trolls, recently found a hippocampus doing the same. Not moving location, responds to gravity or impact. Playing idle animations on loop, cannot be damaged, registers as having health.

## Expected Behavior/Suggestions:
Spawned mobs should continue active until despawning naturally or being killed. Trolls caught in daylight should die, turn to stone, burn, or whatever scripting it has. Afraid I know nothing about mob AI and spawn rules to offer any suggestions. This "What should happen?" is just what I assume is printed on the box.

Another bug report with this issue was marked "fixed in next version." Not sure, but I'd guess versions have updated since then.

## Is It Repeatable? Steps to Reproduce: 
 
1. Start new world, set up base near enough to a troll environment for spawning. ie: min 20-50 blocks from a forest edge.
2. Wait for spawns while playing.

Here are my frozen mob pics. Found 6 trolls so far, may have missed a few.
![Troll 4](https://user-images.githubusercontent.com/8145428/108800540-0c125800-7559-11eb-8c0c-05ea4f564828.jpg)
![Troll 5](https://user-images.githubusercontent.com/8145428/108800543-0caaee80-7559-11eb-9e2f-31fa72997feb.jpg)
![Troll 6](https://user-images.githubusercontent.com/8145428/108800545-0caaee80-7559-11eb-9df5-4c6508c9032e.jpg)
![Troll 1](https://user-images.githubusercontent.com/8145428/108800546-0caaee80-7559-11eb-8511-4bd976d7408e.jpg)
![Troll 2](https://user-images.githubusercontent.com/8145428/108800547-0caaee80-7559-11eb-997e-7eed1174a6a3.jpg)
![Troll 3](https://user-images.githubusercontent.com/8145428/108800548-0d438500-7559-11eb-9bd1-307c91d9b675.jpg)
![Hippocampus](https://user-images.githubusercontent.com/8145428/108800564-16cced00-7559-11eb-8ca5-937155f9375d.jpg)

## Mod/s Affected: 

So far, only Fire and Ice mobs

## Known Fix: 

Nada. Hope someone here can help. But this seems to happen in other packs that include F&I. Just don't know the cause.

**Comment by Saereth** [comment]
trolls freeze during the day its part of the way they work
