### ISSUE TITLE
[Bug] Mobs have weird Hitbox, having trouble hitting them

### ISSUE THREAD

**Issue by TheonlyTazz** [FTBTeam/FTB-Interactions#135]
## Modpack Version: 
V1.0.1

## Bug Report:
Mobs are really hard to hit, hard to describe. Crits seem to be able to go through more often, but even having a mob captured, its not registering the hits all the time. Hardest mobs are Spiders/Poison Spiders.

## Expected Behavior/Suggestions:
Mobs should be able to be hit whenever you see The One Probe showing that you are facing them, which clearly isnt the case

## Is It Repeatable? Steps to Reproduce: 

1. Try to hit a mob when its in range
2. Fail

## Link to Log or Crash File Paste**: 
N/A

## Mod/s Affected: 
I "Think" its either Apotheosis or Animus? idk just my guess, i will further investigate

**Comment by TheonlyTazz** [comment]
##Append:
after Testing, i did notice, hits wont register AT all when "spamming" the attack button and your Attack indicator isnt fully charged
![image](https://user-images.githubusercontent.com/3908847/55290850-c387a980-53d8-11e9-8fcc-47f1bd7e8dc6.png)

**Comment by WhyNotCthulhu** [comment]
Sounds to me like that's intended.

**Comment by Vyraal1** [comment]
No idea what's causing this, @Saereth did you implement this/did I forget again? Can reproduce singleplayer in dev-instance, was expecting normal vanilla

Only mods that I suspect that could be causing it are RoughTweaks or maybe one of the mob mods. We don't have any combat specific mods that alter vanilla behaviors.
