### ISSUE TITLE
Gregtech Manasteel dust cannot be processed

### ISSUE THREAD

**Issue by mpapushin** [FTBTeam/FTB-Interactions#1352]
## Modpack Version: 
1.9.2

## Bug Report:
GTCE Manasteeldust produced through chicken or otherwise cannot be smelted or otherwise converted into usable Botany Manasteel.
Nuggets of Manasteel are not registered in oredict as $nuggetManasteel as Botany nuggets are, and cannot be used in recipes

## Expected Behavior/Suggestions:
-If possible, just add the oredict registration to GTCE Manasteel dusts and nuggets to make them processable.
-Otherwise, manually add smelting/3x3 crafting/packager recipes to the relevant dusts and nuggets.

## Is It Repeatable? Steps to Reproduce: 
1. Get GTCE manasteel dust, either through manual crafting, or the Vinteum chicken
2. Check JEI recipes for produced manasteel dust

## Mod/s Affected: 
GTCE, Botany

## Known Fix: 
Remove lines from scripts/_oreDict.zs removing nuggetGTManasteel and ingotGTManasteel from the oredict
Alternatively, change Chickens.zs enrichedEggVinteum centrifuge recipe to directly produce Botany dustTinyManasteel

**Comment by Saereth** [comment]
smelting recipe was added in 2.10
