### ISSUE TITLE
Wizardry Underworld Isn't Reachable

### ISSUE THREAD

**Issue by timozel** [FTBTeam/FTB-Interactions#1355]
## Modpack Version: 
FTB Interactions 2.0.9

## Bug Report:
Wizardry Underworld Isn't Reachable

## Expected Behavior/Suggestions:
Following the sourcebook for the mod, falling from a height of 130+ onto bedrock should teleport you to the Underworld. However, this just results in a disappointing splat onto the ground. No armor was equipped so there wasn't any fall protection preventing fall damage, which is also noted in the in-game guide.

## Is It Repeatable? Steps to Reproduce: 
Yes, attempting to fall from 130+ blocks in either the Overworld or Voidworld does not teleport the player to the Underworld DIM.

## Mod/s Affected: 
Wizardry

**Comment by Saereth** [comment]
you need to drop from 500 blocks in this pack, and it must be in the void world and onto that single piece of bedrock
