### ISSUE TITLE
Hazelnut unobtainable item

### ISSUE THREAD

**Issue by rozzythefuzzy** [FTBTeam/FTB-Interactions#1357]
## Modpack Version: 
2.0.9

## Bug Report:
When right-clicking Hazelnuts off of Hazelnut trees, it spawns the hazelnut plant block. Not to be confused with the hazelnut item. I'm talking about the block that grows on hazelnut trees from which you get normal hazelnuts.

## Expected Behavior/Suggestions:
When you right-click the hazelnut block, it goes back to 0% growth and drops the normal hazelnut item. The hazelnut block is supposed to be unobtainable and force you to plant the hazelnut tree in order to grow the hazelnut plant

## Is It Repeatable? Steps to Reproduce: 
https://youtu.be/wDKoKxTD8Tw

Right-click fully grown hazelnut

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/96d091b3

**Comment by Saereth** [comment]
this is a mod issue not a pack issue, and I doubt it will get resolved unfortunately
