### ISSUE TITLE
Can't find Magenta Petals

### ISSUE THREAD

**Issue by obuw** [FTBTeam/FTB-Interactions#1358]
## Modpack Version: 
2.0.9

## Bug Report:
I don't really know what I'm expecting, posting an issue for a pack that was last updated 11 months ago. But here goes nothing.

I can't find *any* of the flowers that are required to craft magenta petals. I've literally spent 3+ hours exploring an enormous amount of the map using a hippogryph. No magenta flowers whatsoever. And without magenta petals, you can't craft the jaded amaranth, which you need for every other petal.

Am I supposed to get them another way? Like using some kind of weird fertilizer bonemeal thing with an obscure name that makes it impossible to find it in JEI?

To make things even better, when I went back to my void base, it decided to re-generate, and completely rip out the entire storage section of my base, basically bricking my world, forcing me to load from the last backup. And for GOD knows why, the game apparently hasn't made any backups for the past 6 hours.

I guess the modpack is not so subtly telling me it's time to delete it and play something else. A shame though, I was enjoying it despite the occasional crashes and impossible exploration tasks.

Sorry, I just had to get that off my chest.

## Expected Behavior:
There should be a way to create the jaded amaranth. If there is, the quest for it should probably give you a hint.

## Suggestions:
I see several other issues from people whose void bases were similarly ripped apart. Since the modpack probably has no control over the buggy state of the void world mod, it should at least give players a warning in the form of a "stay the hell away from the initial starting island, build your base elsewhere".

**Comment by abadger** [comment]
I agree with you that the magenta petals/jaded amaranthus should be guided to better by the quests.  I think there are quests telling you the individual pieces but I've seen many people stumble when they need to remember those quest lessons to make the jaded flower.

IIRC, it's coagulated plantballs on grass to get random flowers.  Eventually you'll get flowers of an appropriate color (oredict: plantMagenta) to be transformed into the magenta petals.

**Comment by obuw** [comment]
Yes, I remembered a couple hours after posting this that you can get random flowers using plantballs. You actually learn about that at the beginning of the game, but it's been like 3 weeks since I last used those plant balls so I kind of forgot about them and couldn't find them in JEI when I searched for "meal" or "fertilizer".

Also, I wasn't aware that they don't actually spawn at all as part of worldgen.

So... anyone from the future stumbling onto this while searching for those magenta flowers: **Use plant balls!**
