### ISSUE TITLE
Crash on mod loading

### ISSUE THREAD

**Issue by deamontemps** [FTBTeam/FTB-Interactions#136]
## Modpack Version: 
v1.0.1

## Bug Report:
Not a bug but unsure where to post this. I cannot load into the game at all

URL https://paste.feed-the-beast.com/view/866b0dac

**Comment by Saereth** [comment]
ehh more patchouli crashes yay. We're aware this can somtimes happen unfortunately we're still waiting on an update from patchouli to address it.
