### ISSUE TITLE
Crash Involving Xaero's Map mods

### ISSUE THREAD

**Issue by Wonka006** [FTBTeam/FTB-Interactions#1365]
Edit:   One out of five crash logs had some info :P
[crash-2021-08-11_16.56.04-client.txt](https://github.com/FTBTeam/FTB-Interactions/files/6972016/crash-2021-08-11_16.56.04-client.txt)

## Modpack Version: 
2.0.9

## Bug Report:
Crash upon opening world after changing a few options for Xaero's MiniMap mod.  Listed as the main issue on the crash screen.  After resetting the options to their default, the entire FTB questline had been reset and the limitations to Project E were lifted, allowing many more items to be produced from EMC.  Unknown what else was affected, nothing else seems to be changed.

## Is It Repeatable? Steps to Reproduce: 
Pretty sure all I changed was the waypoint scale in the world map.  Once I changed it back from 0.5x to 1.0x, the crashing stopped.

## Link to Log or Crash File Paste**: 
Would not produce one.  VanillaFix failed to pull one up and the FTB settings crash log was empty despite several crashes occurring from the same issue.

## Mod/s Affected: 
Xaero's World Map mod, Xaero's MiniMap mod, FTBQuests, Project E

**Comment by Saereth** [comment]
new version has updated xaeros, should fix it
