### ISSUE TITLE
Biomes o plenty instead of traverse??

### ISSUE THREAD

**Issue by queenizzy** [FTBTeam/FTB-Interactions#1367]
## Modpack Version: 
<!-2.0.9

Super curious about whether i could replace traverse with biomes o plenty but doesn’t seem to work with the void world type!!

## Is It Repeatable? Steps to Reproduce: 
all i did was install the mod and delete traverse

## Link to Log or Crash File Paste**: 
obviously no crash log, but when i tried the bop world type i just fell into the void!

**Comment by Saereth** [comment]
no it doesnt work, traverse is hard coded into our biome heatmap custom system it would break worldgen in a significant way
