### ISSUE TITLE
[Suggestion] Global settings mod

### ISSUE THREAD

**Issue by redcatone** [FTBTeam/FTB-Interactions#137]
Keybinds important.
New pack, same process, same binds.
Add [global settings](https://minecraft.curseforge.com/projects/global-settings).

## Modpack Version: 
1.0.1

So we all know the pains of starting a new pack. Spending the first few minutes rebinding keys and setting options. [Global settings](https://minecraft.curseforge.com/projects/global-settings) is a really nice clientside mod that allows players to have a persistent options.txt stored on their computer that can be loaded and updated with a click of the button in the options screen on any pack that has the mod loaded.

**Comment by Vyraal1** [comment]
Hmm I like the idea of this but early on Saereth and I decided that most players should just manage most of their clientside mods. We were thinking of an official clientside mods support list to recommend though, might throw this on there.

**Comment by redcatone** [comment]
Ah, that makes sense. There is that mod by Vazkii called [Player's Choice](https://minecraft.curseforge.com/projects/players-choice) that is supposed to help ship optional mods in packs. I've never really seen it used however so I don't know how well it works.
