### ISSUE TITLE
Opening ME Terminal Sometimes Causes Client Freeze

### ISSUE THREAD

**Issue by ByThePowerOfScience** [FTBTeam/FTB-Interactions#1370]
## Modpack Version: 
Divine Journey 2 - 2.9.1

## Bug Report:
Same issue as https://github.com/FTBTeam/FTB-Interactions/issues/1347
Opening an ME Terminal, ME Crafting Terminal, Wireless Terminal, or Wireless Crafting Terminal (from Wireless Crafting Terminal 2) _sometimes_ causes the client to stop responding until the game is forcibly closed.

This has occurred on:
- OS: OSX and Windows
- Allocated RAM: 5.5 GB and 8 GB
- DJ2 Version: 2.9.0 and 2.9.1

## Is It Repeatable? Steps to Reproduce: 
I have not found any way to reproduce this crash on-demand.  This is one of those dreaded "phase of the moon" bugs, unfortunately.

My storage includes:
- Four ME Drives, each containing 8 16k Storage Cells
- Three Storage Busses attached to different drawer controllers

## Link to Log or Crash File Paste**: 
Game does not crash, and logs don't report any issue.

## Mod/s Affected: 
Applied Energistics 2: Trousers Edition
Wireless Crafting Terminal 2

I don't have any helpful information unfortunately, but I wanted to mark this here so anyone with a similar issue can add their unique circumstances.  For instance, if it happens to someone without drawers connected, that would rule out a Storage Drawers polling issue.

**Comment by Saereth** [comment]
Im afraid I cant reproduce this at all but I've updated many mods since this report so im just gonna close for now and hope the new updates sorted it.
