### ISSUE TITLE
Reliquary Fertility Potion causes Ticking Entity Crash

### ISSUE THREAD

**Issue by Yizim** [FTBTeam/FTB-Interactions#1372]
2.0.9

I tried the Fertile Potion on Canola Seeds and caused a crash that prevents me from entering the world
(May require the addition of Openblocks sprinklers, Rustic Apiaries, or AA Worms, as they were also present)

[crash-2022-02-15_17.01.45-server.txt](https://github.com/FTBTeam/FTB-Interactions/files/8075112/crash-2022-02-15_17.01.45-server.txt)

If anyone knows how to remove the ticking entity in SSP that'd be greatly appreciated

**Comment by Saereth** [comment]
in your config/forge.cfg

look for the lines:
    # Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringEntities=false

    # Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringTileEntities=false

you can set those to true and restart and it will nuke them. after updating reliquary I am no longer able to reproduce this so marking is as fixed in dev
