### ISSUE TITLE
Advanced Item Collector crashes the game!

### ISSUE THREAD

**Issue by gengyunmaster** [FTBTeam/FTB-Interactions#1377]
## Modpack Version: 
2.12.1

## Bug Report:
Advanced Item Collector collects the drops of Tree Beacon.

## Is It Repeatable? Steps to Reproduce: 
Yes.

## Link to Log or Crash File Paste**: 
https://pastebin.ubuntu.com/p/9QJz6WR6Nc/plain/

## Mod/s Affected: 
Astral Sorcery
Random Things

**Comment by TheonlyTazz** [comment]
so whats the issue here?

**Comment by gengyunmaster** [comment]
The server crashed while Item Collector collecting the Beacon Tree.

**Comment by TheonlyTazz** [comment]
im afraid i cannot access you pastebin so you would need to provide that via a diffrent site

**Comment by gengyunmaster** [comment]
Sorry for inconvenience!

https://pastebin.pl/view/fd7a2f61

**Comment by KorewaLidesu** [comment]
> Sorry for inconvenience!
> 
> https://pastebin.pl/view/fd7a2f61

It is Beacon Tree actually
Use world editor and remove Beacon Tree, or just load the old backup that dont have issue
