### ISSUE TITLE
Players can't share the nether portal

### ISSUE THREAD

**Issue by gengyunmaster** [FTBTeam/FTB-Interactions#1378]
## Modpack Version: 
2.12.1

## Bug Report:
In a server, some players are in the same team. One player has established a nether portal, but other players cannot enter the portal, they should reactivate the portal to achieve the status. The situation of the overworld portal is different from the above, as long as one player activates the overworld portal, other players in the same team can enter the portal. Maybe it is a bug of the nether portal.

**Comment by Saereth** [comment]
The players need to sync their stages with togetherforever, there is a quest explaining it on the first page of the questbook. once the players sync their stages they will both be able to go through.
