### ISSUE TITLE
Thaumcraft progression impossible?

### ISSUE THREAD

**Issue by Turmfalke2** [FTBTeam/FTB-Interactions#138]
hi
## Modpack Version: 
1.0.1

## Bug Report:
I can progress in thaumcraft. I have got the book, but I can progress in it because that would require crafting a thaumcraft table. To craft the table I need infused wood from astral sorcery and for that I need a lightwell. However the resonating wand for that against needs alchemical brass from thaumcraft.

## Expected Behavior/Suggestions:
I would expect to be able to progress, maybe change the resonating wand to require bronze instead?

**Comment by WhyNotCthulhu** [comment]
You must be new to TC6. Use Salis Mundus to make the table not a wand.

**Comment by Vyraal1** [comment]
Right clicking on Salis Mundus on a crafting table with the correct research level turns it into an Arcane Crafting Table.

**Comment by Turmfalke2** [comment]
huh? The arcane workbench
