### ISSUE TITLE
Silicon dust quest not triggering

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#14]
Submitter: `FTB Interactions#2470`
Body: `**[Saereth]** OwO issue "Silicon dust quest not triggering"`
Attachments:

**Comment by Vyraal1** [comment]
Requires the MV electrolyser quest (Made it so that a items all over the place aren't immediately lit up when they first visit the page)
![image](https://user-images.githubusercontent.com/26587049/54921527-5a85ca80-4edc-11e9-9d95-fe11d0277e4b.png)

**Comment by Vyraal1** [comment]
Double check that the dependency is met
