### ISSUE TITLE
"Powdering Up" quest isn't recognizing that I have all the required items

### ISSUE THREAD

**Issue by DelfCo** [FTBTeam/FTB-Interactions#141]
## Modpack Version: 
1.0.1

## Bug Report:
I'm holding Tin, Copper, and Bronze Dust, all from GregTech Community Edition, just as specified in the quest. It's not being auto-recognized as completion. Clicking Quick Complete does nothing.

## Expected Behavior/Suggestions:
I expect that when I get all the required items for a quest, they're recognized and I get credit for the quest.

## Is It Repeatable? Steps to Reproduce: 
I just followed the quest chain, putting impure dust into the cauldron (with water) and getting the purified dust out. I combined purified dust to make bronze dust.

## Link to Log or Crash File Paste**: 
n/a

## Mod/s Affected: 
n/a

## Known Fix: 
n/a

**Comment by Vyraal1** [comment]
Screenshot of the Quest UI? It might've been bad design on my part as there is also a squeezer dependency, will have to reorganize quests

**Comment by DelfCo** [comment]
My mistake, you're right. It couldn't be any clearer that the squeezer is also required. Closing.
