### ISSUE TITLE
Moon is attached to the Void world / Dim 0, does not orbit Dim 100/Surface world

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#142]
Submitter: `Vyraal1#0001`
Body: `OwO issue "Moon is attached to the Void world / Dim 0, does not orbit Dim 100/Surface world"`
Attachments:

**Comment by Vyraal1** [comment]
Might have to just inform  that all rocket launches have to occur in the void then unless there is a workaround.

**Comment by Saereth** [comment]
this is not a bug, luna is set as a moon to the void world not overworld, We just need to make sure we note this in the quest book
