### ISSUE TITLE
Ritual Diviner isn't reflecting changes in the altar caps

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#143]
probably ask teamy or sae if they could help with this

Submitter: `Vyraal1#0001`
Body: `OwO issue "Ritual Diviner isn't reflecting changes in the altar caps" "probably ask teamy or sae if they could help with this"`
Attachments:

**Comment by Saereth** [comment]
eh this could be modded, I'll add a suggestion to animus tracker, closing here though
