### ISSUE TITLE
Add oredict support on Lapis for LittleTiles tools

### ISSUE THREAD

**Issue by Jomeaga** [FTBTeam/FTB-Interactions#147]
## Modpack Version: 
1.01

## Bug Report:
LittleTiles tools currently require Lapis Lazuli which is not accessible until LV. 

## Expected Behavior/Suggestions:
Allow other blue dyes to be used inplace of Lapis for the LittleTiles tools.

**Comment by Vyraal1** [comment]
Thinking about just adding all of the tools to a Chisel group originating with the Little Tiles Chisel
