### ISSUE TITLE
"Mana Bucket" quest in Magic tab has different requirements than "Mana Leak" in Overworld tab

### ISSUE THREAD

**Issue by Jomeaga** [FTBTeam/FTB-Interactions#148]
## Modpack Version: 
1.01
## Bug Report:
Got a clay bucket of mana, it completes the overworld quest "Mana Leak" however it doesn't complete the "Mana Bucket" quest as it requires a regular bucket of mana.

## Expected Behavior/Suggestions:
"Mana Bucket" quest should allow clay buckets of mana to complete it as well.

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/55443659-8f032180-5581-11e9-87f5-e9ca73d22fd7.png)
Not the cleanest, FTBQ doesn't have a good detect capability for fluids in multiple containers without consuming.
