### ISSUE TITLE
Ender casing showing no recipe in JEI

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#151]
This makes player interfaces uncraftable

Submitter: `IRSmoh_#5048`
Body: `OwO issue "Ender casing showing no recipe in JEI" "This makes player interfaces uncraftable"`
Attachments:

**Comment by IRSmoh** [comment]
from actually additions*

**Comment by Vyraal1** [comment]
Any reason the AA one is preferable to the Random Things one?

**Comment by IRSmoh** [comment]
no, not really as far as I can tell. I guess the easier/more appropriate course of action would be to just hide/remove the actually additions one. Given some of the parts can't be made, removal from JEI is probably enough.

**Comment by iComputerfreak** [comment]
The Phantom Booster and Item Repairer from AA also require an Ender Casing. You should probably change their recipes or remove those from JEI too.
