### ISSUE TITLE
Ghost pig noises after updating from 1.0.0 to 1.0.1

### ISSUE THREAD

**Issue by 2haloes** [FTBTeam/FTB-Interactions#152]
## Modpack Version: 

1.0.1 (Updated from 1.0.0)
## Bug Report:

Ghost pig oinks play while in the void world from random directions (Checked using the subtitle arrows) without any pigs present on the island

Streamable link to issue: https://streamable.com/jd1gy
## Expected Behavior/Suggestions:

Pig noises don't play during gameplay in the void where pig's don't naturally spawn
## Is It Repeatable? Steps to Reproduce: 
(I have no idea but this was the last set of steps done before this started)

1. Start and play a new world in version 1.0.0
2. Update the pack to 1.0.1 (Before getting to the overworld?)
3. Load back into the world
4. Ghost pig sounds will start playing

## Link to Log or Crash File Paste**: 

https://paste.feed-the-beast.com/view/a83fc52d
## Mod/s Affected: 

Unknown
## Known Fix: 

Unknown

**Comment by Doppelganker** [comment]
It's a joke for April first, don't know from which mod thou. You can disable hostile mobs sound, if it is too annoying.

**Comment by 2haloes** [comment]
Feel a bit dumb in hindsight but thank you for the answer
