### ISSUE TITLE
Cave Illuminator doesn't show recipe in JEI

### ISSUE THREAD

**Issue by Kigstn** [FTBTeam/FTB-Interactions#153]
## Modpack Version: 
1.0.0

## Bug Report:
![grafik](https://user-images.githubusercontent.com/38250010/55317920-ca162f80-5471-11e9-8e20-2dcc6de02777.png)
Cave Illuminator's correct recipe isn't shown in JEI

## Expected Behavior/Suggestions:
![grafik](https://user-images.githubusercontent.com/38250010/55317879-b2d74200-5471-11e9-843f-1876c74aa4df.png)
That showing

The recipe (I looked it up in the scripts) still works.

## Is It Repeatable? Steps to Reproduce: 
For me it is

**Comment by Vyraal1** [comment]
Turn off aspects in Thaumic JEI configs, This was the reason why it was left off.
