### ISSUE TITLE
Stable stone uncraftable

### ISSUE THREAD

**Issue by Doppelganker** [FTBTeam/FTB-Interactions#154]
## Modpack Version: 

1.01

## Bug Report:

Most of block from SonarCore aren't craftable.

## Expected Behavior/Suggestions:

Either there is a new recipe, or they are hidden from JEI.

## Is It Repeatable? Steps to Reproduce: 
Yes

## Mod/s Affected: 
SonarCore

## Known Fix:

**Comment by Vyraal1** [comment]
Stable Stone is uncraftable because it has been reserved as functional blocks in the future. If there are updates to to make additional portal blocks or added as parts of Modular Machinery, and therefore has altered recipes.
