### ISSUE TITLE
Mining a fast object with a Thermal Foundation hammer will destroy items around it with a high mining requirement

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#159]
Submitter: `FTB Interactions#2470`
Body: `**[Sinreous]** OwO issue "Mining a fast object with a Thermal Foundation hammer will destroy items around it with a high mining requirement"`
Attachments:

**Comment by Saereth** [comment]
https://github.com/CoFH/Feedback/issues/1479
 not a bug
