### ISSUE TITLE
debarked wood cannot be run through a water powered saw

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#16]
Submitter: `FTB Interactions#2470`
Body: `**[Rdjrjqouqcu]** OwO issue "debarked wood cannot be run through a water powered saw"`
Attachments:

**Comment by Saereth** [comment]
this is not a bug, and would be an insane amount of work to add all debarked logs to the mill simple due to primal tech not supporting oredict, this wont be changed
