### ISSUE TITLE
Potential fuckery with cyberware chamber

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#161]
Video of it happening: https://www.youtube.com/watch?v=_6I8thwcLRc Basically any time we try to apply an implmant the chamber doesn't cause us to take damage; and it doesn't apply the implants. any body parts removed are phantom parts, and leaving the chamber is rather glitchy

Submitter: `IRSmoh_#5048`
Body: `OwO issue "Potential fuckery with cyberware chamber" "Video of it happening: https://www.youtube.com/watch?v=_6I8thwcLRc Basically any time we try to apply an implmant the chamber doesn't cause us to take damage; and it doesn't apply the implants. any body parts removed are phantom parts, and leaving the chamber is rather glitchy"`
Attachments:

**Comment by IRSmoh** [comment]
given that breaking and moving the entire setup (specifically the chamber) resolved the issue; and the delay is just tps lag... I'm going to place this under nearly impossible to reproduce and should be closed due to difficulty of reproing
