### ISSUE TITLE
Veinmine and claimed chunks

### ISSUE THREAD

**Issue by AmbitionsL** [FTBTeam/FTB-Interactions#162]
## Modpack Version: 
1.0.1

## Bug Report:
Not sure if this is something you can fix, but if you can use veinmine to mine blocks in chunks claimed by other players. For example, I was just digging some sand and used veinmine on a block just outside of someone else's claimed chunk, and it veinmined the sand blocks inside their claimed chunk as well.

## Expected Behavior/Suggestions:
Obviously, veinmine shouldn't mine blocks in claimed chunks that you can't mine from.

**Comment by Saereth** [comment]
I've spoken to lat about this and unfortunately he doesnt think he can fix it, this is similar to pouring lava outside of someones claim and letting it flow in, claims arent foolproof but they do help.
