### ISSUE TITLE
Disconnect on server join/dimension change.

### ISSUE THREAD

**Issue by Buggy123** [FTBTeam/FTB-Interactions#164]
## Modpack Version: 
 1.0.1

## Bug Report:

When playing on a multiplayer server, in some situations you will be disconnected. Sometimes there is no particular disconnect message, just a generic "connection lost: disconnected", but most of the time it gives the following message:
![image](https://user-images.githubusercontent.com/16315400/55371516-80a6fe00-54cc-11e9-96cb-c2dee66b88d1.png)

The disconnect is not immediate; instead, it briefly acts as if the connection to the server has been lost; clientside actions still work for 5-10 seconds before the disconnect, but anything reliant on the server stops as if you unplugged a network cable.

When attempting to reconnect within about ~5 minutes, you will get the following error message:
![image](https://user-images.githubusercontent.com/16315400/55370651-248eaa80-54c9-11e9-8bc7-b195d0b0e465.png)
Waiting long enough will allow you to try again, but the issue frequently occurs multiple times in a row.

Situations where there is more traffic between you and the server seem to cause it more often. By far the most common occurrence is when joining the server, where it happens with something like two thirds of all server joins. Other common causes are teleporting, moving between dimensions, etc. Areas with more stuff in it seems to cause the issue more often; I rarely have the issue on the overworld, but frequently have it at a void dimension base with lots of machinery.

Outside of joining/switching dimensions, the crash almost never occurs.

## Link to Log or Crash File Paste: 
https://paste.feed-the-beast.com/view/ec083768

**Comment by Saereth** [comment]
havent seen anymore about this on later versions so closing for now

**Comment by bushw00kie009** [comment]
This is still happening on the server I am on with 3 others seeing the same thing and we are on. We have tried the 1.2.1 and they rolled us forward to the 1.4.1 as well. We are having it drop us from the game every few minutes. I am simply sitting in front of 3 boilers with several machines being ran. The only difference between what the OP is saying and what I am seeing is the second image keeps my character in there for 5 or so minutes and I have to wait til it dc's before I can return.
