### ISSUE TITLE
Hell Infused Bookshelf Quest Typo

### ISSUE THREAD

**Issue by Shadows-of-Fire** [FTBTeam/FTB-Interactions#165]
![](https://i.imgur.com/GgzTDet.png)

Quest states going beyond level 30, but all sources can reach up to level 60, Hell-Infused shelves are needed to go past *power* 30, which is *level* 60.

**Comment by Vyraal1** [comment]
straight up coping the curseforge description now 
![image](https://user-images.githubusercontent.com/26587049/55443508-ed7bd000-5580-11e9-9cf8-cdca02ab4481.png)
