### ISSUE TITLE
[Suggestion] Allowing resistors to be crafted with lignite coal dust along with regular coal dust

### ISSUE THREAD

**Issue by vishtheshnu** [FTBTeam/FTB-Interactions#168]
## Modpack Version: 
1.0.1

## Explanation:
Currently, the resistor only allows the use of coal dust in its creation. Coal veins are mostly composed of lignite coal, with regular coal being quite rare/difficult to find in such veins compared to lignite. This leads to a lot of time spent mining through a coal vein with a lot of excess lignite that might not be used.

## Expected Behavior/Suggestions:
Allow lignite dust to be used in the resistor recipe.

**Comment by codewarrior0** [comment]
There are two kinds of coal veins - one has mostly coal, the other has mostly lignite. Coal is also found in diamond veins.

**Comment by vishtheshnu** [comment]
Oh right. If only I realized this when making circuits :P
