### ISSUE TITLE
Menril wood not oredicted as logWood

### ISSUE THREAD

**Issue by Xavion3** [FTBTeam/FTB-Interactions#169]
## Modpack Version: 
1.0.1

## Bug Report:
Menril wood isn't oredicted as wood, preventing it from being used to make charcoal in the coke oven or kilns and just generally being used as logs.

## Expected Behavior/Suggestions:
Menril wood should be able to make charcoal

## Is It Repeatable? Steps to Reproduce: 
Yes.

## Known Fix: 
this is like a five second fix in crafttweaker, just add something like `<ore:logMenril>. addAll(<ore:logWood>);` Might have the order wrong, the documentation is throwing me off because it says that's correct but all my instincts are screaming at me it looks wrong.

**Comment by Vyraal1** [comment]
Trying to remember why we left this out, thinking if there was a recipe conflict or if we wanted menril to have a specific GT output in a centrifuge or another machine that conflicted with logWood

**Comment by codewarrior0** [comment]
Menril logs do produce resin in a GT centrifuge, but only 1/4 of what you get in the Squeezer.

**Comment by fGravity** [comment]
Also, you can veinmine them

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/55440855-fff10c00-5576-11e9-9919-bf5cc8d21a4d.png)

Cause we're rockstar developers.

**Comment by DrTasslehoff** [comment]
With Menril wood oredict as logwood in 1.4.1 the Improved coke ovens are prioritizing outputting 50mb of creosote rather than the 100mb creosote recipe when burning menril wood

**Comment by Vyraal1** [comment]
Decided that the bonus from Menril is not really adding anything, going to keep it as as logWood and as 50mb of Creosote.
![image](https://user-images.githubusercontent.com/26587049/57039869-d5ed4100-6c2b-11e9-9d6b-38f173843110.png)

![image](https://user-images.githubusercontent.com/26587049/57039878-dbe32200-6c2b-11e9-81d2-5fb324cf896a.png)
