### ISSUE TITLE
Questbook says "Rudimentary Axe" but should say "Rudimentary Hatchet".

### ISSUE THREAD

**Issue by ryankhart** [FTBTeam/FTB-Interactions#170]
## Modpack Version: 
FTBInteractions-1.0.1-1.12.2.zip

## Bug Report:
The questbook in The Safe Space->The World is Your Table says "Rudimentary Axe" is needed but the item from Tinkers' Construct is actually called "Rudimentary Hatchet". This was an inconvenience for me because I searched JEI for "axe rudi" and it didn't show up.

## Expected Behavior/Suggestions:
Just change "Axe" to "Hatchet" to match what Tinkers' Construct calls it.

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/55441412-cde0a980-5578-11e9-9134-d1f05ec4e2fc.png)
