### ISSUE TITLE
Coke Oven Quest off by one

### ISSUE THREAD

**Issue by cinnamennen** [FTBTeam/FTB-Interactions#172]
## Modpack Version: 
1.0.1

## Bug Report:
For `Not that kind of Coke, you need 23 Coke Oven Bricks, however in order to actually make this multiblock, you need 24. Since the UI of the Coke Oven block shows regardless of validity of formation, this makes it non-obvious that you need another block.

## Expected Behavior/Suggestions:
Make the quest require 24 blocks

Additionally not a bug, but I'd suggest (if possible) making the task non-partial. That way when the quest is complete, you know you have everything to make the oven.

**Comment by Vyraal1** [comment]
Thanks, I can't count
