### ISSUE TITLE
OpenJ9 server crash by mod Apotheosis

### ISSUE THREAD

**Issue by 2001zhaozhao** [FTBTeam/FTB-Interactions#174]
## Modpack Version: 
1.0.1

## Bug Report:
The Interactions dedicated server crashes on load when using OpenJ9 JDK8u202 JVM with crash report pointing to the mod Apotheosis. The server runs fine on the more widespread OpenJDK. Client not tested. I use Ubuntu Mate 18.04.

This could be just a problem with the mod and not the pack. I haven't had time to test the mod alone.

## Expected Behavior/Suggestions:
The server should not crash on load regardless of JVM choice.

## Is It Repeatable? Steps to Reproduce: 
Install the server normally and run the ServerStart.sh with OpenJ9 JVM set as java PATH

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/1b324492

## Mod/s Affected: 
Apotheosis

## Known Fix: 
Use OpenJDK (HotSpot) instead of OpenJ9 for now.

**Comment by Vyraal1** [comment]
https://github.com/FTBTeam/FTB-Interactions/issues/60
