### ISSUE TITLE
Oxygen sealing?

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#179]
we have a sealed oxygen dome, but when we stand inside the same block as a enderio conduit, it counts it as not having oxygen

Submitter: `FTB Interactions#2470`
Body: `**[Quaxitos]** OwO issue "Oxygen sealing?" "we have a sealed oxygen dome, but when we stand inside the same block as a enderio conduit, it counts it as not having oxygen"`
Attachments:

**Comment by Saereth** [comment]
put a facade on it, the conduit isnt a full block so it doesnt seal, this is not a bug
