### ISSUE TITLE
See if its possible to not fully consume scribing tools while crafting AS constellation Papers

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#18]
Submitter: `FTB Interactions#2470`
Body: `**[Saereth]** OwO issue "See if its possible to not fully consume scribing tools while crafting AS constellation Papers"`
Attachments:

**Comment by Saereth** [comment]
not possible currently as scribing tools dont use standard damage values nor is noconsume working properly for AS recipes
