### ISSUE TITLE
(1.1.1) Server still crashes on load

### ISSUE THREAD

**Issue by Buggy123** [FTBTeam/FTB-Interactions#185]
## Modpack Version: 

1.1.1

## Bug Report:

Server crashes on load for a unknown reason. Don't have much more to add to this.
Its a server we've been playing on for a bit, but it's never had crashing issues until this latest update.

## Link to Log or Crash File Paste**: 
I cannot use http://paste.feed-the-beast.com/ right now, because the website is apparently down. Here is the crash log on pastebin: https://pastebin.com/xw9AhzBT

Edit: My mistake, this is not the crash log. However, i'm posting this on behalf of a friend of mine who has stopped working on the issue to get some sleep, so he can't get the actual crash report right now. I'll update this with the crash report as soon as possible.

**Comment by hobnob11** [comment]
Bump, Appear to be having the exact same issue, here is my crash log: https://pastebin.com/deQD2Gy7

Happens on server startup, server was working fine on version 1.0.1, after updating to 1.1.1 by extracting the server files zip into my server folder, it crashes on startup with the above log. 

I tried the enchantments.cfg suggestion thats pinned in the discord, same error.

**Comment by hobnob11** [comment]
Issue resolved, my update method (which i suspect the person who started this thread also used) of extracting the update into my server folder is flawed, as it left the old outdated versions of the mods in the mods folder, causing the error. 

Deleting mods, config, scripts and the libraries folders, and re extracting the zip has fixed my issue.

**Comment by Buggy123** [comment]
Yep, you're right. He basically just told me that's exactly what he did. Remember to update properly!
