### ISSUE TITLE
Zombies(?)causing crash in Overworld, 1.1.1.

### ISSUE THREAD

**Issue by Myster0** [FTBTeam/FTB-Interactions#186]
## Modpack Version: 
1.1.1

## Bug Report:
Game is stable in Void, Crashes in the Overworld

## Expected Behavior/Suggestions:
Shouldn't crash

## Is It Repeatable? Steps to Reproduce: 
Game crashes after loading into the world now.

## Link to Log or Crash File Paste**: 
https://pastebin.com/XajA45FR

**Comment by Hjaldar** [comment]
[The overworld ended](https://paste.dimdev.org/exahasohop.mccrash)
The dead rose but lumbered not
Winter has arrived

Only difference from the above report is I can load back into the world without repeated crashing (until some time later when another such mob spanws).

**Comment by Hjaldar** [comment]
Update: There is a fix for this on the FTB Discord in Interactions #general Pinned Messages until it is fixed in a release.

**Comment by Vyraal1** [comment]
Let us know if this still occurs in v1.1.2

Also how do you update the pack? Wondering if the correct config files got overridden or not.

**Comment by Hjaldar** [comment]
My issue at least may have been caused by a problem during pack update, as the process (direct update, not a new instance) took a couple of attempts (twitch launcher being flaky). The issue seems to be fixed in 1.1.2.
