### ISSUE TITLE
Can't find Garlic Mustard plant (and tin as a result)

### ISSUE THREAD

**Issue by adamcadot** [FTBTeam/FTB-Interactions#190]
## Modpack Version: 
1.0.1

## Bug Report:
Can't find the Garlic Mustard plant used to indicate the location of tin. Searched for hours, everywhere. Searched 40-120 Y-level, several mountains, different biomes, etc. Others have reported the same issue without anyone saying they fixed it: 
https://www.reddit.com/r/feedthebeast/comments/b7ndli/ftbinteractions_searching_for_tin/

## Expected Behavior/Suggestions:
Garlic Mustard & tin world gen.

## Is It Repeatable? Steps to Reproduce: 
N/A

## Link to Log or Crash File Paste**: 
Available if needed.

## Mod/s Affected: 
Mods related to world gen.

## Known Fix: 
None reported.

**Comment by Vyraal1** [comment]
Hard to make a judgement on this one, most of these issues and threads have a huge self-reporting bias, and even when players do find tin, they won't report back that they found it and just continue to move on with the pack. 

Not going to change worldgen weights yet, but will keep on monitoring, my only suggestion is to keep looking, the expected range of exploration is a 3k block radius for all biomes (as some are biome specific and would need to traverse the biome map).

**Comment by adamcadot** [comment]
The self-reporting bias is definitely there, but this is mitigated by these factors:

1. It's a brand-new mod pack which makes us pioneers so some of us behave with precaution.
2. This isn't Stackoverflow, but it's Reddit & Github, easy places to follow up for the better of the community.
3. They would be the first to post a working solution, or at least "I found it after x hours of searching". None of those posts exist currently.
4. Other players (on Reddit) report this plant in abundance.

Currently, our world is about 3x as large as the post on Reddit, searching for this plant. Continuing to search is not really a feasible option at this point as we have invested hours into this and will likely just spawn in tin ore as a workaround. If we don't use this workaround our world is unplayable.

Given the severity of this issue here are a few more things:

1. As per the suggestions in the Reddit thread we have confirmed the configuration files they said to check were all as expected.
2. 2 players flew around in creative for 1hr+ and also looked via horse for 1hr+
3. We generated the world on 1.0.0 and updated to 1.0.1 when it was released. Maybe this has to do it with it?
4. Reviewed the changelog, and noticed a line saying the Master branch was merged in via git... can you review these changes, please?
5. We tried a texture pack that replaced non-ore blocks with invisble textures.
6. We tried using the Scanner, even though it's not avaialble on the current tier. It worked, even with the invisble textures, but didn't help.
7. As per a comment on Reddit, we went into the ground near the Quartz plant with this texture pack and the Scanner, found the 3 Quartz-related ores and didn't find tin with it. 

As a last resort, if you want, I can take a look at the codebase to try and find the error. I work daily as a web developer fixing Drupal sites so I know a few common issues, but I might be in over my head, and I fully understand if you can't give access out willy-nilly, but I figured I'd put that out there.

**Comment by Vyraal1** [comment]
You are entirely welcome to investigate further, in fact you should have just as much access with the pack files (there's nothing really that's obfuscated when the pack files are shipped out). 

Here's some relevant information, feel free to ask any other questions:
1. Dimensional Control handles the overworld biome map, located in dimesionalcontrol config folder. The script is in dimensions.cfg, and the map is in biomeprovider folder under HeatMap.cfg

2. Tin is agnostic to any biome modifications, except it is entirely disabled (a weight below -100 just gets it automatically disabled by GTCE) in Advanced Rocketry biomes. It was easier to filter per biome instead of per dimension due to decisions by the GTCE dev.

**Comment by tyler489** [comment]
Interesting we found lots of tin on our server that started in 1.0.0 but no submits but I suspect thats because how high it spawns not because of it missing

**Comment by Yupie** [comment]
We are having the same issue in the latest version of the pack. We've spent hours searching all around the world. We've even taken suggestions from reddit to search at quartz or biomes that generate very high, but no luck. The config does say alleliaria_p which is Garlic Mustard so that doesn't seem to be the problem.

**Comment by Shadowgar** [comment]
> Edit: I would like to add that we're playing on a server, maybe that has something to do with it?

I am running a new single player world on the latest version. I've found all of the ores except tin. So its not just specific to server. Something is definitely wrong.

**Comment by blanknam** [comment]
I think the flower itself may be part of the issue. If you look at it from straight above, it's almost invisible. So if you're searching in creative flight, you might pass over it. On the ground, it looks pretty similar to the rustic Chamomile flower and doesn't really pop out like the flowers for Magnetite or Lapis.

**Comment by Shadowgar** [comment]
> I think the flower itself may be part of the issue. If you look at it from straight above, it's almost invisible. So if you're searching in creative flight, you might pass over it. On the ground, it looks pretty similar to the rustic Chamomile flower and doesn't really pop out like the flowers for Magnetite or Lapis.
> 
> https://imgur.com/a/woLfw47
> 
> Try and find the Lapis in this picture. Now look for the tin.

I spent 8 hours lastnight looking and still haven't found tin. Is there anyway to actually run the save file through something to count what ores generated?

**Comment by blanknam** [comment]
> I spent 8 hours lastnight looking and still haven't found tin. Is there anyway to actually run the save file through something to count what ores generated? At this point I'm about to just delete the pack and wait for this to be fix and start over again. I can't even get into bronze age.

You can run the /cofh countblocks command to check if the blocks are nearby:

/cofh countblocks <username> 100 100 100  gregtech:ore_tin_0
/cofh countblocks <username> 100 100 100  plants2:cosmetic_1#8

Replace <username> with your Minecraft name. The first one checks for the tin ore blocks and the second checks for the garlic mustard flowers. Adjust the 100s to the desiered x/y/z radius for the search.
