### ISSUE TITLE
Ligma Vein requires "Vanilla" coal ore

### ISSUE THREAD

**Issue by Developaws** [FTBTeam/FTB-Interactions#191]
## Modpack Version: 
1.0.1

## Bug Report:
Ligma Vein requires the "Vanilla" coal ore, which will never spawn, and is instead spawned with GregTech coal ore.

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/55559400-1f458180-56bc-11e9-8545-4b22d55c4903.png)
fixed
