### ISSUE TITLE
Copper Veins requires invalid "Iron Ore"

### ISSUE THREAD

**Issue by Developaws** [FTBTeam/FTB-Interactions#192]
## Modpack Version: 
1.0.1

## Bug Report:
Quest is requesting data value of "3", where only data value of "0" will ever spawn.

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/55559448-3a17f600-56bc-11e9-9ca0-742e25334cfe.png)
fixed
