### ISSUE TITLE
Alumentum Recipe needs fix

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#194]
Input Coalcoke is wrong

Submitter: `Tazz#0001`
Body: `OwO issue "Alumentum Recipe needs fix" "Input Coalcoke is wrong"`
Attachments:
![attachment](https://cdn.discordapp.com/attachments/123194979509207040/563335422529241090/unknown.png)

**Comment by Vyraal1** [comment]
https://github.com/Buuz135/Thaumic-JEI/issues/49
