### ISSUE TITLE
Firebricks recipe not working

### ISSUE THREAD

**Issue by skills697** [FTBTeam/FTB-Interactions#198]
## Modpack Version: 
1.1.1

## Bug Report:
Firebricks recipe not working

## Expected Behavior/Suggestions:
The firebricks recipe is not working as intended. I created a new world and hopped into creative mode to test to make sure that this isn't just some client/server bug of some kind. There appears to be no way to make the firebricks (block), using the 4 firebricks + any of the mallet/hammers in the basic worktable (or any other table for that matter). 

## Is It Repeatable? Steps to Reproduce: 
1. place 4 fire bricks into basic worktable and place any "hammer/mallet" into the tool slot (matches recipe shown in JEI)
2. no item output shows

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/55572515-bec33e00-56d5-11e9-910c-3a28c6deb5e6.png)
Please double check it doesn't work with Creosote.

**Comment by skills697** [comment]
Thanks, sorry for wasting your time. I sincerely apologize and greatly appreciate the fact that you got back to me on this so quickly!

**Comment by Vyraal1** [comment]
This one
