### ISSUE TITLE
Various textures "missing" due to case sensitivity

### ISSUE THREAD

**Issue by thePalindrome** [FTBTeam/FTB-Interactions#199]
## Modpack Version: 
1.0.1

## Bug Report:
Certain textures (such as the Animated Overworld Portal and the Skystone lens) are missing, likely due to the case sensitive nature of all modern filesystems

## Known Fix: 
Manually patching the texture names should do it

**Comment by Saereth** [comment]
all textures are now lowercase completely

**Comment by Babbie** [comment]
In 1.9.1, there are still textures that have this problem, such as the skystone lense. I don't know if this was fixed after 1.9.1 was set for release, but the date of the comment is before the release date on CurseForge.
