### ISSUE TITLE
Cassiterite has two squeezer recipes, but only uses one

### ISSUE THREAD

**Issue by thePalindrome** [FTBTeam/FTB-Interactions#200]
## Modpack Version: 
1.0.1

## Bug Report:
Cassiterite Ore can be squeezed into two tin dust (the correct one), and one tin dust (an auto-genned one). The Squeezer correctly produces two tin dust, but it may be a good idea to remove the one-tin one just in case. (Adding the issue here based on a conversation with Saereth)

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/55576514-84f73500-56df-11e9-8868-677481ea6b47.png)
Fixed already in latest updates
