### ISSUE TITLE
How to stop the rain?

### ISSUE THREAD

**Issue by Artofire** [FTBTeam/FTB-Interactions#202]
The question is only if the impossibility to stop rain in overworld is something wanted? It is very hard on some pc and nearly unplayable and no-fun, we had a great time playing until we discover that even toggledownfall won't stop the rain. Is there a way to stop it?
## Modpack Version: 
FTB Interactions 1.1.2

## Bug Report:
Cannot stop the rain

## Is It Repeatable? Steps to Reproduce: 
Go to the overworld

**Comment by Vyraal1** [comment]
If you are okay with using commands, easiest suggestion is to cheat in a Rain Shield. If you want a more complete solution, this is related to JED's Worldproviders and will have to use JED setting gamerules

**Comment by krakel** [comment]
you can control the rain with Draconic Evolution
