### ISSUE TITLE
structural upgrades for barrels uncraftable

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#203]
even if they were craftable with current mats it'd place them around end tier... long after they're useful.

Submitter: `FTB Interactions#2470`
Body: `**[IRSmoh_]** OwO issue "structural upgrades for barrels uncraftable" "even if they were craftable with current mats it'd place them around end tier... long after they're useful."`
Attachments:

**Comment by Saereth** [comment]
intentional
