### ISSUE TITLE
Crash to desktop while generating chunks in Overworld 

### ISSUE THREAD

**Issue by BradenCradock** [FTBTeam/FTB-Interactions#205]
## Modpack Version: 
1.1.1

## Bug Report:
Game crashes to desktop while in Overworld, I have made a new game an it still happens. The crashes seems to happen in the same locations and did not happen in the previous version. This error is displayed upon CtD: 
The game crashed whilst exception ticking world
Error: com.udojava.evalex.Expression$ExpressionException: Missing operator at character position 3

## Expected Behavior/Suggestions:
The game should continue running and not crash.

## Is It Repeatable? Steps to Reproduce: 
1. Game crashes while in Overworld
2. Reloading save and staying in the same place usually causes the game to crash again, from anywhere between instantly to ~30s.

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/b54d2627

## Known Fix: 
Cross fingers and hope

**Comment by Vyraal1** [comment]
Try updating to v1.1.2, we adjusted a config that should prevent yet.

**Comment by BradenCradock** [comment]
Thanks, I will try that. I'll update if it doesn't crash when I play later today.

**Comment by BradenCradock** [comment]
The update seems to have fixed the issue.
