### ISSUE TITLE
not all primordial pearl bits can be turned back into a full pearl

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#206]
durability 2 and 1 are unavailable.

Submitter: `IRSmoh_#5048`
Body: `OwO issue "not all primordial pearl bits can be turned back into a full pearl" "durability 2 and 1 are unavailable."`
Attachments:

**Comment by Saereth** [comment]
yeah if people let them degrade too far they're junk, that was my thoughts on this
