### ISSUE TITLE
add more advanced plastic sheet recipe for mek pipes

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#208]
Submitter: `FTB Interactions#2470`
Body: `**[Saereth]** OwO issue "add more advanced plastic sheet recipe for mek pipes"`
Attachments:

**Comment by Shadows-of-Fire** [comment]
Current Recipes:
Resin -> Dry Rubber (Drying)
Rubber Bar -> Dry Rubber (Furnace)
Dry Rubber -> Plastic (Furnace)

Proposed Additions:
--MV--
Silicone Rubber Bar -> 3x Dry Rubber (Furnace)
Polyethylene Sheet -> 3x Plastic (Furnace)
--HV--
Styrene-Butadiene Rubber Bar -> 6x Dry Rubber (Furnace)
Polytetrafluoroethylene Sheet -> 6x Plastic (Furnace)
