### ISSUE TITLE
Can't cook coloured cobble

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#21]
cook coloured cobble

Submitter: `FTB Interactions#2470`
Body: `**[Quaxitos]** OwO Issue Can't cook coloured cobble`
Attachments:

**Comment by Saereth** [comment]
This isnt a bug, pickletweaks doesnt provide stone variants of those colored cobbles, if you want to suggest it as a feature you can do it here: 
https://github.com/BlakeBr0/PickleTweaks/issues
