### ISSUE TITLE
Client-side update lag in the void

### ISSUE THREAD

**Issue by Highbeam** [FTBTeam/FTB-Interactions#211]
## Modpack Version: 
1.0.1

## Bug Report:
So this issue is a strange one.  I'm playing on a void island with another player.

Yesterday he built a cactus farm using about 70 wooden hoppers.  Around that time; my client became extremely laggy for my text commands and actions...  However, everything I could see from chat and other player actions was normal.

I go into the OW portal and all the lag was gone.  Back to the island and the issue returned.

The other player was unaffected by this issue.

He took all the hoppers down and replaced them with conveyors and my issue was resolved.

Logging in today I had the same issue for about 1 minute then it cleared and I haven't experienced it since.

My friend was building the Tinkers furnace and then he experienced this issue.  His client chat was lagged, actions were lagged but the actions and chat he could see was real time.

He went into the OW and returned and it cleared up..

It's getting a little strange and I'm wondering if there's something we can do next time to capture and debug this?

We are playing on the Toastworld server.

## Expected Behavior/Suggestions:
Advice to capture logs etc if this keeps occuring?

## Is It Repeatable? Steps to Reproduce: 
Not repeatable, randomly happens at the moment.

## Link to Log or Crash File Paste**: 
no files yet

**Comment by Vyraal1** [comment]
Wasn't able to reproduce this issue (to be honest I didn't even know where to start). Do you by any chance have Nvidia cards?

**Comment by Highbeam** [comment]
Yea I understand its a hard issue to even recreate, unfortunately it happened again today.  This time the servers actions weren't real time.  My whole client was lagged only when in the island dimension and it seemed to affect others while I was there.

I have Geforce GTX 970 yea.

So the issue happened again tonight after a few hours playing. Took a trip to the nether and when I returned to my island dimension I had constant lag.  Once I managed to get to the OW it cleared up, on returning to the island it returned.  I repeated this several times to prove the issue was due to my character's location rather than my connection.

Circumstances for this are going to be hard to detail... 

During my lag; my chat messages were instantly on the servers IRC discord, but my client was still experiencing 5 sec+ lag.

Memory currently set to 6018mb.  (Happened previously when I only allocated 4GB)

Restarted client and still got the problem.  I will need to discuss with server admin tomorrow if its still a problem and see if I can get more info.

**Comment by Vyraal1** [comment]
Do you mind checking this works or you? 
![image](https://user-images.githubusercontent.com/26587049/55767390-b1e07a80-5a46-11e9-96fb-01ade08a457f.png)

**Comment by Highbeam** [comment]
I actually already did this previous as I was having random long lag stutters before.  But that was affecting my FPS and not really causing lag like this.  Logged on again today and it was fine for about 10 minutes then the severe lag returned.  Other players are fine.  I might have to move to the overworld if I can't find whats causing it.

![image](https://user-images.githubusercontent.com/32101225/55787030-b09a6680-5ab5-11e9-98fe-9a47ea4cbe4f.png)

**Comment by Highbeam** [comment]
A little example of the comparison between OW and returning to the island.  Lag now seems to escalate, starts at a few seconds and goes up to minutes...  Starts at a few seconds then gets worse, yet the server can see my text instantly on discord.

I had another player visit my island and they don't have any problems.

Little example:
http://213.48.63.6:5003/issue-211-example-1.gif

Some log extracts which I can see quite a few errors and time out messages:
[latest - Copy.zip](https://github.com/FTBTeam/FTB-Interactions/files/3058170/latest.-.Copy.zip)

I will try to reinstall the pack from scratch next and see if the issue persists.

**Comment by Highbeam** [comment]
Tried reinstall, still bad.  30 sec lag off the bat.  Chat to IRC is still instant but my game is still lagged.

I'm playing on a canadian server from Switzerland but never had big problems like this before.

I tried using a VPN from UK and it still happens.

**Comment by Highbeam** [comment]
[latest - after reinstall.zip](https://github.com/FTBTeam/FTB-Interactions/files/3058369/latest.-.after.reinstall.zip)

**Comment by Highbeam** [comment]
Update:  now the problem seems to be everywhere, not just the void.

It is also affecting a team member from Czech in exactly the same way.

However, it doesn't affect a UK player who visited my base and could play fine.

I will talk to the admins to see when server restart is scheduled and whether they see anything from the logs.

**Comment by Highbeam** [comment]
Update 2:  The UK player now experiences it too.  Unfortunately no admins around yet to check things.

**Comment by Vyraal1** [comment]
Last thing I can think of is installing something like LagGoggles to try and get and fps profile while you are getting lag spikes. This just sounds so weird you are getting performance issuse with your hardware in the void.

**Comment by Highbeam** [comment]
Just to note: our server was having network issues (netty) affecting more people which may have been diluting my particular problems.  After the server was "fixed" of the wider network problems (this affected all players no matter where they were), my individual issue of lagging only while in the void returned.  I removed the chunkloaders and went to/from the OW a few times and the problem went away.  It's like calling your cable company with a problem only for it not to be there when they answer...  I'll continue to monitor but it's a real intermittent issue that only seems to affect my island.

**Comment by balthild** [comment]
@Highbeam 

Hello, do you find out the reason that your server lag? My FTB:I 2.0.6 server is experiencing the same issue. I don't know the cause because the lag behaves very "randomly".

A detail is that when I'm watching the server console, I can see the words I say in the client shows at the console instantly, but the client gets no response from server until seconds/minutes. It seems that there's something preventing data being sent from server to client.
