### ISSUE TITLE
GT Brewery/Biomass issues

### ISSUE THREAD

**Issue by AmishInvader** [FTBTeam/FTB-Interactions#212]
## Modpack Version: 
1.0.1

## Bug Report:
Biomass recipe in GT Brewery uses 2x power and goes 2x more quickly than JEI suggests.

Also, when trying to power 4 breweries making biomass (should be 24 eu/t total, 6 each) the breweries run out of power even when connected to a battery buffer via 2 cables.  I'm not sure what's causing that.

## Expected Behavior/Suggestions:
Either change JEI or the recipe to be the same.  Look into power issues.

## Is It Repeatable? Steps to Reproduce: 
Try powering 4 breweries with 1 generator/battery buffer, watch them lose power and stop.

## Mod/s Affected: 
GTCE

![2019-04-05_11 52 03](https://user-images.githubusercontent.com/9375880/55644311-2becd700-579b-11e9-8c4e-ee4b684b4911.png)

**Comment by Vyraal1** [comment]
Just curious what are the voltage tiers of the machines being shown above? And the generator tiers?

**Comment by AmishInvader** [comment]
all LV

**Comment by Vyraal1** [comment]
Looks like a break from historical precedent, with ULV recipes getting overclocked (whereas the previous floor for overclocking was at LV). asking dev if this is intentional.

**Comment by Vyraal1** [comment]
Seems like this overclocking behavior is  intended for GTCe
