### ISSUE TITLE
Astral Sorcery tree beacon makes 2x2 spruce saplings turn invisible sometimes

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#214]
Submitter: `FTB Interactions#2470`
Body: `**[Nachie]** OwO issue "Astral Sorcery tree beacon makes 2x2 spruce saplings turn invisible sometimes"`
Attachments:

**Comment by Vyraal1** [comment]
Can't really reproduce reliably, but others have mentioned this as well before. Do you happen to have a setup that reproduces this consistently?

**Comment by Doomgull** [comment]
And/or a screenshot?

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/55738035-4d94cb00-59f4-11e9-90f9-7d38b194b962.png)
Also adding this so I don't lose track later on

**Comment by K-Anator** [comment]
Also having this issue in 1.9.1, though mine is with jungle trees, it also happened with greatwood trees from Thaumcraft. 
I've attached my world, simply twerk the trees in to existence, they won't ghost and just disappear. Sometimes I do get saplings in to my system, but that's it.
[New World.zip](https://github.com/FTBTeam/FTB-Interactions/files/3564138/New.World.zip)

**Comment by Kaju-Bubanja** [comment]
Affects me aswell
