### ISSUE TITLE
Questbook stibnite vein rarity

### ISSUE THREAD

**Issue by Envoci** [FTBTeam/FTB-Interactions#216]
## Modpack Version: 

1.0.1

## Bug Report:

Questbook states stibnite is searched for it the overworld and makes it seem its found plenty, but it seems pretty rare and better searched for in the nether which is not stated in the questbook.

## Expected Behavior/Suggestions:

Modify the questbook tooltip to display stibnite can also be found in the nether and with better rates.

## Is It Repeatable? Steps to Reproduce: 

N/A

## Link to Log or Crash File Paste**: 

N/A

## Mod/s Affected: 

N/A

## Known Fix: 

N/A

**Comment by DelfCo** [comment]
This might be a RNG issue. My map generated with multiple Stibnite deposits within 500 units of spawn. I don't think advising people to look in the Nether will always apply.

It might be worth considering giving some general advice in the questbook about different strategies to find mineral deposits when you're having trouble, though. Look in the Nether, look in different biomes N, S, E, and W of spawn, etc.
