### ISSUE TITLE
Entities are sometimes invisible when changing dimensions (Server)

### ISSUE THREAD

**Issue by Goldenlion5648** [FTBTeam/FTB-Interactions#218]
## Modpack Version: 
1.0.1

## Bug Report:
When going into overworld, all entities are sometimes invisible, (spiders, boats, zombies, etc)
This is in multiplayer if that is relevant
These invisible entities can still be heard, relogging makes them visible again

## Expected Behavior/Suggestions:
Entities should be visible 

## Is It Repeatable? Steps to Reproduce: 
1. Go through the overworld portal
2. Look where an entity was known to be left, such as boat
3. If it is not there, relog and it will be there

## Link to Log or Crash File Paste: 
[latest.log](https://github.com/FTBTeam/FTB-Interactions/files/3050068/latest.log)

**Comment by drakkensong21** [comment]
This is an old vanilla bug iirc

**Comment by Goldenlion5648** [comment]
I've never had this issue in any other packs on 1.12, unless they all have a mod that fixes this

**Comment by Saereth** [comment]
what type of mobs and is this a sponge server or vanilla?

**Comment by Goldenlion5648** [comment]
boats, spiders, zombies, cows it what I've seen it happen with. Its a vanilla server (of course with all of the mods in the pack, but not sponge at least)

**Comment by reficulagi** [comment]
Can confirm this issue still exist in  version 1.3.0 of the pack on a normal server

**Comment by Slyklaw** [comment]
Still happening in 1.6.1.

**Comment by melbellrocks** [comment]
Still happening on 1.7.0 also

**Comment by RaggyOne** [comment]
Still happening on 1.9.1

**Comment by Saereth** [comment]
hoping this is fixed by the randompatches update

**Comment by AdrianCollado** [comment]
This still occurs on 2.0.9.

**Comment by BlueDragon709** [comment]
it still happens in 2.0.10

**Comment by MrSataana** [comment]
Still happens on 2.12.1
