### ISSUE TITLE
Add an assembly recipe for turbine blades

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#219]
Submitter: `FTB Interactions#2470`
Body: `**[IRSmoh_]** OwO issue "Add an assembly recipe for turbine blades"`
Attachments:

**Comment by Vyraal1** [comment]
Forwarded this to the mod itself as I think its a benefit that other packs can use. Also that's a lot of scripting if we did it ourselves.

https://github.com/GregTechCE/GregTech/issues/718
