### ISSUE TITLE
Diamonds appear in empty crafting table (Client-Side Desync?)

### ISSUE THREAD

**Issue by hobnob11** [FTBTeam/FTB-Interactions#223]
## Modpack Version: 

1.1.2
## Bug Report:

When ever you put an item in a crafting table and remove it, it appears the client thinks that "nothing" results in a stack of 64 diamonds. I'm on a server and the item dissapears when picked up, causing a desync between server and client. 

## Expected Behavior/Suggestions:

"Nothing" should not be craftable into 64 diamonds

## Is It Repeatable? Steps to Reproduce: 

https://gfycat.com/AnchoredTautAustraliansilkyterrier
1. put any item in a crafting table.
2. taking that item out, leaving "nothing" in the table makes the client think 64 diamonds will come out.

## Link to Log or Crash File Paste**: 

n/a
## Mod/s Affected: 

n/a

**Comment by Vyraal1** [comment]
Still looking to track this down, but really as long as it never results in a stack of diamonds, it hopefully shouldnt be a problem.

**Comment by Talkarcabbage** [comment]
Encountered this in 1.5, but only on the crafting station (not on a regular crafting table). Table is also in the vicinity of some basic worktables, if that matters (and on a server, not single player)
It happened without having put anything in, just opening the table made the diamond stack appear *sometimes* (about 67% of the time) 
Diamonds are indeed client-side ghost, disappears if you try to remove it.

**Comment by Saereth** [comment]
this seems to be fixed now
