### ISSUE TITLE
Client-side crash on joining server:   java.lang.NullPointerException: Unexpected error

### ISSUE THREAD

**Issue by Tonyenike** [FTBTeam/FTB-Interactions#224]
## Modpack Version: 
1.0.1

## Bug Report:
When attempting to join a server, the game crashes.

## Is It Repeatable? Steps to Reproduce: 

1.  Launch the modpack from twitch.
2. Launch the game from the minecraft launcher
3. Attempt to join a server, game crashes.

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/6a4c00af

## Mod/s Affected: 
I'm not sure which mods in specific are responsible for this behavior.

**Comment by Vyraal1** [comment]
Can you try this again after updating your java to the latest?

**Comment by Gunner76th** [comment]
1) Update your java as you are on Update 51, but the most recent is update 211. Use the offline 64-bit option found here: https://www.java.com/en/download/manual.jsp

2) Your memory allocation is insufficient for almost all modpacks post MC 1.10.x According to your crash report your max allocated memory is 6,000mb of memory. What this equals is 5.8 GB of memory. Try increasing your memory allocation to 6144mb either by adjusting the slider in the Tiwtch launcher, or my changing your argument of "-Xmx6000m" to "-Xmx6144" -or- "-Xmx6G"

3) Check and ensure that you are not running MC from within the c:\users\ directory tree structure (My Games, my Documents, My Downloads, Desktop). As of Windows 10, Java 1.8, and Minecraft 1.10.x if Minecraft is ran from within the c:\users\ directory tree structure it causes errors not normally seeing when MC is installed and ran from other locations. The most notable error seen is an hs_pidd Access Violation error when Windows prevents Java from accessing files or memory space while running from the c:\users\ tree structure.

**Comment by Saereth** [comment]
no follow up here after ages so closing
