### ISSUE TITLE
endermen spawned from infinity dust never despawn

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#225]
it appears that they also take damage from infinity dust too; or they just teleport before culling can kill them... This causes chunks that are loaded around a grain farm to have tons of em

Submitter: `FTB Interactions#2470`
Body: `**[IRSmoh_]** OwO issue "endermen spawned from infinity dust never despawn" "it appears that they also take damage from infinity dust too; or they just teleport before culling can kill them... This causes chunks that are loaded around a grain farm to have tons of em"`
Attachments:

**Comment by Vyraal1** [comment]
How would I replicate this? just a pure dust mob farm?

**Comment by Saereth** [comment]
its replicatable, it happens, I ended up adding a vinculotus to my mob farm to keep them from teleporting away. Less of an issue now that culling can kill mobs with potion effects but it still happens if you dont have a vinculotus.
