### ISSUE TITLE
When filling multiple cells with gas from a dynamic tank at a time, they do not become "too light to handle"

### ISSUE THREAD

**Issue by Tofini** [FTBTeam/FTB-Interactions#226]
## Bug Report:
 filling multiple steel cells (possibly others) with gas from a mekanism dynamic tank, they do not become "too light to handle" the one i did was wood gas

## Is It Repeatable? Steps to Reproduce: fill multiple cells with gas from a mekanism dynamic tank, they do not become "too light to handle" making the player float

1.
2.

**Comment by Saereth** [comment]
this has been around ages, most likely wont be fixed as it has to do with the cell nbt data, its not just limited to mek dynamic tanks. that being said, we're actually ok with it being around as a neat interaction for those that find it.
