### ISSUE TITLE
Server Crash Loop After Update to 1.1.2

### ISSUE THREAD

**Issue by Kylar1014** [FTBTeam/FTB-Interactions#227]
## Bug Report:
Server crashes on startup after about 20sec.

## Expected Behavior/Suggestions:
 See above
 Not crash

## Is It Repeatable? Steps to Reproduce: Yes
 Initiate server to start.
1.
2.

## Link to Log or Crash File Paste**: 
https://pastebin.com/h91bmi2A

**Comment by Vyraal1** [comment]
I think we discussed this where it was user error with duplicate jar files on the server.
