### ISSUE TITLE
Quest for Philosopher's Stone is Too Exclusive

### ISSUE THREAD

**Issue by whizzball1** [FTBTeam/FTB-Interactions#230]
## Modpack Version: 
1.01

## Bug Report:
You cannot get to the philosopher's stone quest if you get it the emerald way, rather than the deadly way.

## Expected Behavior/Suggestions:
I expected that getting the philosopher's stone would be sufficient, since there were two methods, one by emerald and one by human heart. But the quest for the philosopher's stone, behind which all other quests are placed, is gated behind a quest that requires the human heart.

My suggestion is to skip the quest about the human heart and go straight to philosopher's stone.

**Comment by Goliaith** [comment]
Quite literally super easy to do. Use the ritual man, summon a villager and give him the regen apple.
