### ISSUE TITLE
Typo in Tip regarding reimplementation of Tier 6 blood magic.

### ISSUE THREAD

**Issue by Wyerden** [FTBTeam/FTB-Interactions#231]
## Modpack Version: 
1.0.1

## Bug Report:
Tip reads as: Tier 6 Blood Magic was reimplementedas a favor for packmakers, for all intents and purposes, it does not exist. Please do not bug the mod authors about it!

Screenshot: http://puu.sh/Db7Mn/b68560d4ee.png

## Expected Behavior/Suggestions:
Should be revised to:

Tier 6 Blood Magic was reimplemented as a favor to packmakers. For all intents and purposes, it does not exist. Please do not bug the mod authors about it!

## Is It Repeatable? Steps to Reproduce: 
Tips displayed are random, thus it may take multiple attempts.

1. Begin loading a game (or switching dimensions) in the modpack.
2. Tip with error is displayed.

## Link to Log or Crash File Paste: 
N/A

## Mod/s Affected: 
N/A

## Known Fix: 
Not relevant.

**Comment by TeamDman** [comment]
![image](https://user-images.githubusercontent.com/9356891/55679541-7a08f400-58db-11e9-9ecc-79a19d61b7fd.png)
There's a space in the string, odd that it rendered without it for you

**Comment by TeamDman** [comment]
Updated tips.cfg with new grammar, hopefully fixes it.
