### ISSUE TITLE
make banded iron smeltable in porcelain melter

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#232]
Submitter: `Saereth#7836`
Body: `OwO issue "make banded iron smeltable in porcelain melter"`
Attachments:

**Comment by Vyraal1** [comment]
Should be smeltable already, it just doesnt show up in JEI cause hiding the smeltery controller apparently auto-hides the the smeltery tab (and tinkers complement for some reason has a redundant porcelain melter tab). 

![image](https://user-images.githubusercontent.com/26587049/55683575-5069c000-590f-11e9-8895-ee233e4e52b9.png)
