### ISSUE TITLE
Wrong Water Eletrolysis Recipe was Removed

### ISSUE THREAD

**Issue by Vyraal1** [FTBTeam/FTB-Interactions#237]
The cheaper water electrolysis recipe is still there while the more expensive one was removed, resulting is a pretty absurd energy positive loop only using water and electrolyzers.

**Comment by thePalindrome** [comment]
Don't forget the distilled water ones

**Comment by Vyraal1** [comment]
If GTCE 382 update goes smoothly, this should take care of itself.
