### ISSUE TITLE
Server crash when going through the overworld portal

### ISSUE THREAD

**Issue by jjenco** [FTBTeam/FTB-Interactions#238]
## Modpack Version: 
1.1.2

## Bug Report:
Shortly after a player walks through the overworld portal from the initial skyblock, the server crashes with "Exception ticking world"

## Expected Behavior/Suggestions:
overworld loads normally

## Is It Repeatable? Steps to Reproduce: 
walk through the overworld portal, let the dimension load in, and within 5 seconds, the server will crash. 

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/04a0651a

**Comment by jjenco** [comment]
This actually might be related to https://github.com/FTBTeam/FTB-Interactions/issues/186. The player who was causing/reporting the crashes in the first place told me that there were several zombies around him when the crash occurs. And when I update my pack, I normally keep the previous version's configs, so the new apotheosis enchantments.cfg (from the discord pinned messages) was not in place

**Comment by Vyraal1** [comment]
Is this updating for a server or for single player? If for server updates, we highly recommend deleting the entire configs folder, saving specific .cfg files like theoneprobe.cfg, JEI, etc.

**Comment by jjenco** [comment]
It's updating for a server. I just reimported all my configs from the 1.1.2 server download, except for the ones I customized myself. Things seem to be working just fine now
