### ISSUE TITLE
Plantballs copying bushes are affected if you place blocks above the plant

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#239]
Submitter: `Vyraal1#0001`
Body: `OwO issue "Plantballs copying bushes are affected if you place blocks above the plant"`
Attachments:

**Comment by Vyraal1** [comment]
https://github.com/Shadows-of-Fire/Plants/issues/115

**Comment by Saereth** [comment]
if this hasnt been fixed by now pretty sure it aint gonna be, eitherway closing out the issue as its not pack breaking and can be worked around quite easily
