### ISSUE TITLE
Mutant Steve breaks too much

### ISSUE THREAD

**Issue by thePalindrome** [FTBTeam/FTB-Interactions#242]
## Modpack Version: 
1.1.2

## Bug Report:
From Xavion on the discord:

> To make bedrock unbreakable a hardness of -1 is treated as such by the game
Mutant Steve doesn't check that
It just checks if it's less than 5
It's special casing vanilla bedrock
That's probably why it can destroy unbreakable blocks
-1 is below the hardness threshold after all
Special cases vanilla concrete too
So that should be immune

Another note is that cobble is hardness 2, so if steve is set to 5 then it can break even more than it should.

**Comment by Vyraal1** [comment]
Hmm looks like the DM wiki confused resistance and block hardness. https://deadlymonsters.miraheze.org/wiki/Mutant_Steve

**Comment by Vyraal1** [comment]
https://github.com/bigbang87/deadly-monsters/issues/26

**Comment by Xavion3** [comment]
Either way the ingame info is wrong and needs to be fixed, as cobble has a hardness of 2 and a resistance of 30, neither of which are close to the current threshold of 5.

**Comment by Sokiri** [comment]
I agree, he just broke my gravestone a moment ago so I won't be able to get my stuff until an operator helps me. https://streamable.com/9d7ih

**Comment by Vyraal1** [comment]
Ouch, Sokiri, that is definitely not part of the original intention of adding the mod. It was supposed to originally cause mild annoyance to encourage Ritual of Lucerna or Peace Candle. This issue looks like it was overlooked in beta testing because 4 teams were in the void, and the last two teams in the Overworld got Lucerna rituals up pretty fast.

**Comment by anonymousPiplup** [comment]
I have some bedrock cobblestone from the dungeon still. Should I delete it because it can be considered "cheese"?
