### ISSUE TITLE
RF tools modular storage tier upgrading voiding content 

### ISSUE THREAD

**Issue by daddy77gaming** [FTBTeam/FTB-Interactions#250]
Just something to consider adding to the questbook for the RF tools modular storage, when upgrading your tier of storage content is deleted. Thought it might so i just put in a stack of dirt when upgrading the first time to check, just dont think most everyone will do that and might result in some furious rections ;)

**Comment by Saereth** [comment]
![image](https://user-images.githubusercontent.com/9200909/55747224-c3576180-5a09-11e9-8bbf-6466d6864e67.png)
Also added a note to the quest now.
