### ISSUE TITLE
[Bug] Requesting Table ignores durability on tools -> ThermalLogistic's Github

### ISSUE THREAD

**Issue by TheonlyTazz** [FTBTeam/FTB-Interactions#251]
https://github.com/Astavie/ThermalLogistics/issues/22

**Comment by TheonlyTazz** [comment]
already fixed in next update of Thermallogistic it seems
![image](https://user-images.githubusercontent.com/3908847/55738367-489d3f00-5a27-11e9-86ac-497ea4b6bd14.png)

**Comment by Astavie** [comment]
Indeed it is!
