### ISSUE TITLE
Shield Bash enchantment has two issues I found

### ISSUE THREAD

**Issue by Sokiri** [FTBTeam/FTB-Interactions#252]
## Modpack Version: 
1.0.1

## Bug Report:
If you have a shield in your offhand with the "Shield Bash" enchantment you get hurt when you shoot a blaze with a bow as well as the 35 durability gets applied to whatever you have in your main hand. 

## Expected Behavior/Suggestions:
I expected not to get hurt because of the fact you're not technically meleeing the blaze and the durability decrease should only be applied to the shield.

## Is It Repeatable? Steps to Reproduce: 
[Yes, Here's a video.](https://streamable.com/ai29h)

## Mod/s Affected: 
Apotheosis

**Comment by Vyraal1** [comment]
Wow even has a video to reproduce, will look into it.
