### ISSUE TITLE
cyberware parts are still getting lost after death

### ISSUE THREAD

**Issue by fGravity** [FTBTeam/FTB-Interactions#253]
## Modpack Version: 
1.1.2

## Bug Report:
cyberware parts are still getting lost after death

## Expected Behavior/Suggestions:
after the update the /gamerule cyberware_keepCyberware value didnt get updated, therefore it was still false

## Is It Repeatable? Steps to Reproduce: 
Yup

## Link to Log or Crash File Paste**: 
N\A
## Mod/s Affected: 
cyberware guy

## Known Fix: 
/gamerule cyberware_keepCyberware true or whatever u decide

**Comment by Saereth** [comment]
yes unfortunately all the cyberware config changes is the INITIAL world gamerule, so even though we now ship with the config set to true, exiting worlds still need to have that game rule set.

**Comment by Vyraal1** [comment]
Updated JED to force update gamerules in next update.
