### ISSUE TITLE
Integrated logic circuit quest also requires a basic electronic circuit, but basic electronic circuit is gated behind mv where you craft good electronic circuits by laser engraver.

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#263]
Submitter: `Anarook#4064`
Body: `OwO issue "Integrated logic circuit quest also requires a basic electronic circuit, but basic electronic circuit is gated behind mv where you craft good electronic circuits by laser engraver."`
Attachments:

**Comment by mtrevor** [comment]
This is still present in 1.9.1. The Integrated Logic Circuit LV age quest is gated behind the MV age Basic Electronic Circuit equivalent.
