### ISSUE TITLE
MV Machine Hull quest awards Basic Electronic circuits, which are LV tier, instead of good circuits.

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#264]
May be intentional but doesnt match the reward for LV Machine Hull.

Submitter: `Anarook#4064`
Body: `OwO issue "MV Machine Hull quest awards Basic Electronic circuits, which are LV tier, instead of good circuits." "May be intentional but doesnt match the reward for LV Machine Hull."`
Attachments:

**Comment by Saereth** [comment]
it is intentional to give a tier prior circuits, I probably should switch the lv reward to basic
