### ISSUE TITLE
Crash in loading

### ISSUE THREAD

**Issue by HotDelphox** [FTBTeam/FTB-Interactions#266]
## Modpack Version: 
<1.0.1>

## Bug Report:
Minecraft Crashes at the sixth stage of loading.

## Expected Behavior/Suggestions:
Minecraft should not crash

## Is It Repeatable? Steps to Reproduce: 
Load up game and wait for it to get to the sixth stage of loading.

## Link to Log or Crash File Paste**: 
https://pastebin.com/ruEPfezM

**Comment by Saereth** [comment]
too little ram, Xmx3072m -Xms256m -XX:PermSize=256m
 pack wont run on 3gb, some people have gotten it to work on as little as 3.5gb, but 4gb is recommended
