### ISSUE TITLE
Galena Veins not generating

### ISSUE THREAD

**Issue by Jukari** [FTBTeam/FTB-Interactions#269]
## Modpack Version: 
1.1.2

## Bug Report:
Cannot find Galena, Lead, or Silver ore veins, or Hydrangea flowers.  Was having problems finding them on the server I play on so loaded a single player world, added bdlib, used /oredistribution 200, every so often, traveling approximately 16,000 blocks south, and 3,300 blocks to the east, total, found every other ore, except Galena, Silver, Lead, and also did not notice Tetrahedrite or Stibnite ore, but was looking more closely for Galena.

## Expected Behavior/Suggestions:
Going to play with the weights to see if that fixes the problem in my single player, but haven't done so yet.

## Is It Repeatable? Steps to Reproduce: 
Generate new worlds, can't find Galena or Hydrangeas?

**Comment by Vyraal1** [comment]
Not familiar with bdlib's ore distribution command, what command inputs did you use? Stibnite has a considerable rarity in the overworld, its intended to search the nether instead for it, but Galena should be more common. Not sure what else to say beyond this other than it seems like poor RNG, started a world on v1.1.2 to test this and found Galena 80 chunks away from spawn.

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/55838104-4dc6c080-5af1-11e9-837b-eeb4a4ef9f6f.png)

**Comment by Jukari** [comment]
The command input I used was as above with /oredistribution 200, which checks a 200 block radius around the player and returns a list of the found ores and the quantity found and percentage.  It was the only thing I knew of to do a quick large radius scan for ores.  I'll generate a couple of more worlds without changing anything and see if I can find it and report back.  And that makes sense on the Stibnite, I just mentioned it, since it was the only other ore I didn't notice when parsing the ore distribution lists returned via the command from bdlib.

**Comment by Vyraal1** [comment]
Hmm I normally just use mekanism digital miner to scan chunks, but assuming if the command is working properly, then it shouldn't be that big of a deal. Lead has a chance in all biomes except jungles, so not sure what else to say. Due to the nature of oregen at one point there might be an issue report for each veins.

**Comment by Jukari** [comment]
Okay, found both Stibnite and Galena on a newly generated world, spawned in a scanner and hydrangea, 2 ranged upgrades, and 1 block module, set it to Hydrangea and flew around in creative for awhile, found 1 vein 1200 blocks out, and another 2300 blocks out, so I guess it spawns, just extremely rare, and was ultra unlucky with the first creative test world I made going 16,000 blocks without finding one, bad RNG is bad RNG I guess.
