### ISSUE TITLE
Thaumic JEI should hide locked recipes by default

### ISSUE THREAD

**Issue by thePalindrome** [FTBTeam/FTB-Interactions#274]
## Modpack Version: 
1.2.1

## Bug Report:
Thaumic JEI displays locked recipes, which has lead to a *lot* of people wasting resources in the crucible, or getting confused as to why the crafting table won't accept it. There's a single config option to change that, and I think we should have it set by default. We could also possibly add a tooltip mentioning it's unlocked via research, and possibly even state the research.

**Comment by Saereth** [comment]
we prefer people to be able to see our recipe changes in advance and prepare for them, it is not our responsibility if people dont learn the mod or read the questbook that explains the need to have research unlcoked for what you're crafting.

**Comment by thePalindrome** [comment]
A better solution is suggested here: https://github.com/Buuz135/Thaumic-JEI/issues/54

That way, we get our "Look ahead," but also (hopefully) don't have to explain that research is locked.

I suggest using this issue as a marker.

**Comment by Saereth** [comment]
Agreed, I like that solution, we'll leave this open and see what buuz says.

**Comment by Vyraal1** [comment]
ThaumicJEI finally updated with the icons.
