### ISSUE TITLE
consider moving steel chest recipie to assembler with 8 plates and a 16 circuit

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#28]
its annoying to accidentally craft it D:

Submitter: `FTB Interactions#2470`
Body: `**[Lezarius]** OwO issue "consider moving steel chest recipie to assembler with 8 plates and a 16 circuit" "its annoying to accidentally craft it D:"`
Attachments:

**Comment by Vyraal1** [comment]
Decided against this, if they mistakenly craft it, they can just melt it down.
