### ISSUE TITLE
[Solved]Exception in server tick loop v.1.2.0 from 1.1.2

### ISSUE THREAD

**Issue by Shadowgar** [FTBTeam/FTB-Interactions#282]
## Modpack Version: 
1.2.0-1.12.2

## Bug Report:
When loading game save after client load, a crash is generated. 

## Expected Behavior/Suggestions:
For the save file to load

## Is It Repeatable? Steps to Reproduce: 
1.Load save file from previous version

## Link to Log or Crash File Paste**: 
https://pastebin.com/SaL6EJUu

Latest Log : https://www.dropbox.com/s/0pqmvvpt2nof4so/latest.log?dl=0

DB to saved world https://www.dropbox.com/s/yxdxdwlopuk1tpd/2019-04-11-03-57-17.zip?dl=0

## Known Fix: 
None at this time

**Comment by ClockwiseGear** [comment]
at a cursory glance, this looks like the same issue as #281, which seems to be related to something in Astral Sorcery.

**Comment by Shadowgar** [comment]
Updated with Save world files and Latest log

**Comment by Shadowgar** [comment]
Found a fix. It appears AS fluid_rarities.cfg being larger than max int causes the crash. The file below used to replace the original config file will fix the issue. 

[fluid_rarities.cfg.txt](https://github.com/FTBTeam/FTB-Interactions/files/3071417/fluid_rarities.cfg.txt)
