### ISSUE TITLE
Thaumium dust useless.

### ISSUE THREAD

**Issue by WhyNotCthulhu** [FTBTeam/FTB-Interactions#286]
## Modpack Version: 

1.2.0
## Bug Report:

GTCE thaumium can be macerated into dust but the dust can not be re-smelted currently.
## Expected Behavior/Suggestions:

It would be nice to be able to recycle thaumium parts that aren't used.
## Is It Repeatable? Steps to Reproduce: 

1. Macerate anything thaumium.
2. Cry deeply.

**Comment by Vyraal1** [comment]
Adding it to PBF and EBF next update.
