### ISSUE TITLE
You cannot make dough with the wooden basin

### ISSUE THREAD

**Issue by ZacharySojnocki** [FTBTeam/FTB-Interactions#287]
## Modpack Version: 
1.2.0

## Bug Report:
Dough recipe using the wooden basin doesn't work

## Expected Behavior/Suggestions:
After stirring 1 salt(Mekanism), 3 flour (Ender IO) and water in the wooden basin (Primal tech), dough should be produced. 

## Is It Repeatable? Steps to Reproduce: 
1. Fill wooden basin with water
2. Add ingredients
3. Stir
4. Nothing happens 
https://gyazo.com/7f022277b1b5553d46d9ec85597d6ac2

## Mod/s Affected: 
Primal Tech
Pam's HarvestCraft

**Comment by Saereth** [comment]
That recipe is disabled in this pack, make dough with pams. The only recipe in the wooden basin that is enabled is obsidian. I'm not seeing that recipe in my jei either (as it's disabled) if you're seeing it in your JEi let me know, otherwise marking this as invalid.

**Comment by Vyraal1** [comment]
I added this recipe, pams dough in the wooden bbasin to prevent the huge amount off shift clicking, it seems like the primaltech basin cares about the ORDER of the ingredients put into it for some god awful reason.

**Comment by Vyraal1** [comment]
Looking for a workaround atm, might just make it one flour, one salt to prevent the order confusion.

**Comment by DrTasslehoff** [comment]
It seems like this is still an issue in 1.2.1 but only with the mekanism salt. 
```

mods.primaltech.WoodenBasin.addRecipe(<harvestcraft:doughitem> * 4, 
	<liquid:water>, [<ore:dustWheat>.firstItem, <ore:dustSalt>.firstItem]);
mods.primaltech.WoodenBasin.addRecipe(<harvestcraft:doughitem> * 4, 
	<liquid:water>, [<ore:dustWheat>.firstItem, dustGTSalt]);
```

The first recipe fails to work, while the second works fine. I'm imagining because the basin wants both items as the first it fails to register either as valid.
