### ISSUE TITLE
Fluxbore (Basic) quest does not trigger.

### ISSUE THREAD

**Issue by tasosalvas** [FTBTeam/FTB-Interactions#288]
## Modpack Version: 
1.2.0

## Bug Report:
The requirement seems to be a Fluxbore (Basic) charged with 40k FE. The quest does not trigger with a full one or an empty one.

## Expected Behavior/Suggestions:
The quest should accept an empty Fluxbore (or a full one, if proof of charging infrastructure is required.

Unless this is a challenge to get the item charged with exactly the right amount, I guess, which should probably be hinted at in the quest description.

**Comment by Saereth** [comment]
probably an nbt detection issue we'll get a fix in for it next update

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/56043002-56deaa00-5d0a-11e9-80f1-70ceefb959ec.png)
