### ISSUE TITLE
Overlapping quests

### ISSUE THREAD

**Issue by Ar4093** [FTBTeam/FTB-Interactions#292]
## Modpack Version: 

1.2.1
## Bug Report:

Some quests in the Quest GUI are in the same spot, which makes them hard to see, or confusing in regards to prerequisites.

### Affected quests:
* Space tab: "H2 4u2" / "O2 H2 Cold4u" (after the Vacuum Freezer quest)
* Overworld tab: "Garlic Mustard" / "Cataplant", and "Tin Veins" / "Aer and Beryllium Veins" (Maybe leftover from #182?)

## Is It Repeatable?
Yes.
### Screenshots:
<img src="https://i.imgur.com/N9Y4Kk7.png">
<img src="https://i.imgur.com/Un98x49.png">
<img src="https://i.imgur.com/4i9bI8d.png">

## Mod/s Affected: 
FTBQuests

## Haiku version:
Quest positions weird.
Two quests are overlapping,
making me confused.

**Comment by Buudeluu** [comment]
What's the items needed for the 02 H2 Cold4U quest? Having the same problem
