### ISSUE TITLE
Pech trading is enabled and can break progression

### ISSUE THREAD

**Issue by merphle** [FTBTeam/FTB-Interactions#294]
## Modpack Version: 
1.0.1 & 1.1.2

## Bug Report:
Thaumcraft Pech trading is enabled. Pechs can randomly trade items that are otherwise gated. For example, Nether Quartz and Ghast Tears were obtained from a Pech in the Overworld, long before the Nether.

## Expected Behavior/Suggestions:
Shouldn't be able to trade with Pechs? Or adjust trading loot tables to ensure only permitted items are tradeable.

## Is It Repeatable? Steps to Reproduce: 
1. Find Pech in the Overworld (or /summon thaumcraft:pech) .
2. Drop gold ingot on the ground to befriend Pech.
3. Open trading interface, give another gold ingot.
4. Click randomizer die and hope for something illicit.

## Link to Log or Crash File Paste**: 
n/a

## Mod/s Affected: 
Thaumcraft

## Known Fix: 
n/a

**Comment by Saereth** [comment]
this is known and is ok/intended to use, similar to the mob randomizer from the philosopher's stone. There are little neat things we know of/thought about and decided not to change in the pack to favor the adventurous. Enjoy your find and thanks for reporting.

**Comment by merphle** [comment]
Thank you for responding @Saereth. It seemed incongruous with having Villager trading disabled, and I didn't see a (closed) issue related to Pechs, so I thought I'd confirm to be certain. We're loving the pack so far! :)
