### ISSUE TITLE
Pam's Toast

### ISSUE THREAD

**Issue by DragonTamr34** [FTBTeam/FTB-Interactions#301]
## Modpack Version: 
1.2.1

## Bug Report:
Cannot create Pam's toast for the thankful dinner. The toast has no recipe.
## Expected Behavior/Suggestions:
Should work like it did in the previous version (1.1.2) where you had bread and butter and it made toast. Or if there was a recipe change that did not carry over.

## Is It Repeatable? Steps to Reproduce: 
1. Search Thankful dinner in JEI
2. Click toast
3. No recipe pop up

**Comment by Rdjrjqouqcu** [comment]
The cooking for blockheads toaster is able to turn bread into toast. I feel a jei tooltip should be added for this if that is supposed to be the only way to make toast.

**Comment by frosko2** [comment]
The one from toaster isn't the right toast

**Comment by Saereth** [comment]
![image](https://user-images.githubusercontent.com/9200909/56136270-72db8900-5f60-11e9-9be7-3e6af62781d6.png)
?

**Comment by setycz** [comment]
@Saereth , the recipe is not working for me, tested with 1.2.1:

![toast](https://user-images.githubusercontent.com/13938932/56147972-9c6cd280-5fa9-11e9-918b-e18c9a8940e2.PNG)

However, I can confirm that cooking for blockheads toaster can do the trick.  No recipe in JEI and It's pretty slow and manual process :/

**Comment by DragonTamr34** [comment]
I have all the ingredients in the fridges and counter, but the recipe does not show up in the cooking for blockheads menu. Hitting R on previously made toast or clicking in JEI does nothing. I am using the latest version of the pack. I have not tried the toaster yet.

**Comment by frosko2** [comment]
I have the toaster as part of my blockheads set up and it still doesn't show in the cooking table

**Comment by setycz** [comment]
@frosko2 , you have to put bread manually into the toaster, right click the toaster with bread in your hand twice and once more to turn it on. It won't show in the cooking of blockheads setup and cannot be automated. Personally, I would considered it as a bug, @Saereth .

**Comment by Vyraal1** [comment]
Toast will be in tomororow's update, apologize for the oversight on my end. 
![image](https://user-images.githubusercontent.com/26587049/56233086-4868f900-6050-11e9-8039-9be9170392f2.png)

![image](https://user-images.githubusercontent.com/26587049/56233090-4dc64380-6050-11e9-8391-4418c6b6d3a3.png)

**Comment by setycz** [comment]
Kudos to @Vyraal1 ! :)
