### ISSUE TITLE
game keeps crashing upon startup 

### ISSUE THREAD

**Issue by IngamECM** [FTBTeam/FTB-Interactions#302]
Version: 1.1.2
the game keeps crashing upon startup 
here is the crash 
[crash-2019-04-13_13.26.41-client.txt](https://github.com/FTBTeam/FTB-Interactions/files/3076627/crash-2019-04-13_13.26.41-client.txt)
here are the fatal errors from the game output 
 
13:16:56_base_Client thread_fatal
Module JourneyMap did not load due to issue: Mod with modid: journeymap was not found

13:19:47_FML_Client thread_fatal
Suppressed additional 1 model loading errors for domain tconstruct

13:19:47_FML_Client thread_fatal
Suppressed additional 61 model loading errors for domain extrautils2

13:19:47_FML_Client thread_fatal
Suppressed additional 15 model loading errors for domain architecturecraft

13:20:27_gregtech_Client thread_fatal
Seems like invalid recipe was found.

13:20:27_gregtech_Client thread_fatal
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

3:20:27_gregtech_Client thread_fatal
Ignoring invalid recipes and continuing loading

13:20:27_gregtech_Client thread_fatal
Some things may lack recipes or have invalid ones, proceed at your own risk

13:20:27_gregtech_Client thread_fatal
Report to GTCE github to get more help and fix the problem

13:20:27_gregtech_Client thread_fatal
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

13:27:03_monitor_Process Monitor_fatal
Process crashed with exit code -1

**Comment by Shadowgar** [comment]
Your crash log indicates OutOfMemoryError: GC overhead limit exceeded. You need to allocate more memory to the client to run.

**Comment by Saereth** [comment]
Memory: 357795744 bytes (341 MB) / 2863661056 bytes (2731 MB) up to 2863661056 bytes (2731 MB

You cannot run this pack on this little amount of ram. Recommended is 4.25gb. The minimum it will run on is 3.5gb.
