### ISSUE TITLE
Major Bug librarian lib(wizardry) causes crash on launch

### ISSUE THREAD

**Issue by maxybaer123** [FTBTeam/FTB-Interactions#303]
First pack crash report sorry if formatting is messy 
## Modpack Version: 
Any i have used although currently using 1.21
## Bug Report:
on the last little bit of stage 2 (preinitialization) game seems to crash regardless of what i do if librarian lib is enabled
## Is It Repeatable? Steps to Reproduce: 
For me yes although i don't 
## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/9f3f2427
## Mod/s Affected: 
Librarian lib seems to cause the issue even when disabling wizardry if its lib is included the crash happens 
## Known Fix: 
disable wizardry

**Comment by jikuja** [comment]
Did you try updating JRE? 8u51 is most used.

**Comment by Saereth** [comment]
Your java is ridiculously out of date and running old java installations have been known to cause issue with several of the mods in this pack. This will not be fixed, update your java please.

**Comment by maxybaer123** [comment]
Ah thanks I don't mess around with java much didn't realize it was out of date.
