### ISSUE TITLE
Keep getting this error when opening the first time.

### ISSUE THREAD

**Issue by ryangg888** [FTBTeam/FTB-Interactions#306]
## Modpack Version: 

1.1.2
## Bug Report:

Keep trying to play the mod pack but I get the same error when I try to open it for the first time. 

## Is It Repeatable? Steps to Reproduce: 

1. Deleted everything, did a clean start. Still get the same error.
2. Deleted everything again and tried a fresh start to get the same error.

## Link to Log or Crash File Paste**: 

Unable to save download. jna-4.4.0.jar
Name: jna-4.4.0.jar
URL: https://libraries.minecraft.net/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
Error details: Attempting to move successful download to C:\Users\coura\Twitch\Minecraft\Install\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar
Cannot create a file when that file already exists.

Filename on disk: 0460-38a8-d2d6-60da
Path: C:\Users\coura\AppData\Local\Temp\0460-38a8-d2d6-60da
Exists: false

**Comment by Saereth** [comment]
this seems to be some kinda os/permissions issue, not a pack issue.
