### ISSUE TITLE
Crash upon entering world

### ISSUE THREAD

**Issue by zornor** [FTBTeam/FTB-Interactions#308]
## Modpack Version: 
1.1.2

## Bug Report:
Crash upon entering world (single player). 
My uneducated guess from reading the crash log:
I placed an Industrial Foregoing Plant Sower and Plant Gatherer in my void world at some point in my last session, saved and quit safely, and now consistently crash on loading the world (game window freezes on "Building Terrain" stage).

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/d9409d24

**Comment by Saereth** [comment]
calling @TeamDman

**Comment by TeamDman** [comment]
https://minecraft.curseforge.com/projects/discord/files/2699556
Update on this should fix it
Caused by client-side Discord mod, either update or remove it

**Comment by zornor** [comment]
World now loads okay with Discord 1.0.9. Thanks!

**Comment by Grandsteal** [comment]
World crashes minecraft - i loged off near a dungeon, well by log off i mean ALT F4 because my keys are broken, 4nd i had lots of stuff on me, the back up world th4t was made is of 3-4 days ago, i need help plz, i dont know how to send crash reports . . .
