### ISSUE TITLE
Satchel enchantment recipe gives wrong enchantment

### ISSUE THREAD

**Issue by Rdjrjqouqcu** [FTBTeam/FTB-Interactions#309]
## Modpack Version: 
1.2.1

## Bug Report:
Satchel enchant recipe gives incorrect enchantment in quest. It gives a satchel enchanted with Insight 4

## Expected Behavior/Suggestions:
expected for the satchel to be enchanted with Holding 4

## Is It Repeatable? Steps to Reproduce: 
craft the enchanted satchel

## Known Fix: 
Fix the enchantment id in the script file

**Comment by maxell45146** [comment]
![2019-05-08 00_56_33-FTB Interactions](https://user-images.githubusercontent.com/2869265/57350469-2ed93f80-712c-11e9-8a07-453069da4bb3.png)
Bug still exists, 1.5 version.
