### ISSUE TITLE
can't craft cyclic sprinkler

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#310]
https://i.imgur.com/UjLXQsp.png right clicking with applicable wand doesn't actually start the craft... server files may be messed up idk

Submitter: `IRSmoh_#5048`
Body: `OwO issue "can't craft cyclic sprinkler" "https://i.imgur.com/UjLXQsp.png right clicking with applicable wand doesn't actually start the craft... server files may be messed up idk"`
Attachments:

**Comment by Saereth** [comment]
server files were out of sync
