### ISSUE TITLE
Frozen-themed Doomlike Dungeons apparently not spawning

### ISSUE THREAD

**Issue by Hjaldar** [FTBTeam/FTB-Interactions#311]
## Modpack Version: 
1.2.1

## Bug Report:
Doomlike Dungeons with the Frozen theme (\config\DLDungeonsJBG\themes\frozen.cfg) do not appear to be spawning due to an error in this config file.

I've flown many tens of thousands of blocks in the cold zone in a test world with B:BuildPole=true set in \config\DLDungeonsJBG\DLDungeonsJBG.cfg to allow dungeons to be easily found. All other Dim 100 dungeons have been seen in both my Survival world and my Creative test world.

## Expected Behavior/Suggestions:
Frozen-themed Doomlike Dungeons should spawn, unless they have been deliberately disabled. This may be the case but from the form of the config file I suspect it is not. This config file also differs in structure from the other theme files in the same directory. 

This behaviour appears to be due to duplicated lines in \config\DLDungeonsJBG\themes\frozen.cfg. Specifically,

(7) biomes =  COLD, SNOWY
(14) biomes =  FROZEN

and 

(9) NotInBiomes =  NETHER, END
(17) NotInBiomes =  NETHER, END, WET, MESA, DESERT

There are no biomes in the biome dictionary with type FROZEN, which would explain why these dungeons are not spawning. It appears this error may have been due to copying the setting from the valid line 18 "Type =  FROZEN", which relates to the type of mobs which can spawn in the dungeon.

Commenting out lines 14 and 9 and re-launching the modpack resulted in frozen-themed dungeons spawning in COLD and SNOWY biomes in Dim 100 in my test world.

## Is It Repeatable? Steps to Reproduce: 
N/A

## Link to Log or Crash File Paste**: 
N/A

## Mod/s Affected: 
Doomlike Dungeons

## Known Fix: 
Delete or comment out the following lines in \config\DLDungeonsJBG\themes\frozen.cfg:

(9) NotInBiomes =  NETHER, END
(14) biomes =  FROZEN

**Comment by Hjaldar** [comment]
If this dungeon is re-enabled it is probably worth doing a pass through \config\DLDungeonsJBG\SpecialChests\frozen.cfg. The current loot table includes a white dragon egg and at least one item from logistics pipes.

**Comment by Saereth** [comment]
dragons are euclydes gated, so no, and this pack doesnt even have logistics pipes, its too unstable atm. The other parts of the config should be good to go next update
