### ISSUE TITLE
Cannot find addon dependency 263884

### ISSUE THREAD

**Issue by TylAshke** [FTBTeam/FTB-Interactions#312]
## Modpack Version: 
FTB Interactions first installation try

## Bug Report:
I wanted to install the pack for the first time and got the msg cannot find addon dependency 263884. I tried it now 4 times and it comes up with the same number everytime.
Help please?! :-)

**Comment by Thmyris** [comment]
Can you explain why you closed this issue? I am still having it.

**Comment by crisisboost** [comment]
Also having this issue as of 5/27/2019.

**Comment by TylAshke** [comment]
bc for some to me unknown reasons it resolved itself later that day
