### ISSUE TITLE
No reciple for ZPM Field generator

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#324]
Submitter: `FTB Interactions#2470`
Body: `**[Wired_4fun]** OwO issue "No reciple for ZPM Field generator"`
Attachments:

**Comment by Saereth** [comment]
@Vyraal1 this should probably be in SoG yeah? do you remember what the original recipe was

**Comment by Vyraal1** [comment]
Pretty cancerous, 
![image](https://user-images.githubusercontent.com/26587049/58054679-4ac7e280-7b29-11e9-9995-416b9afb44af.png)

Will add it in now
