### ISSUE TITLE
Key bindings/ Hot keys / Control panel

### ISSUE THREAD

**Issue by Dragonrenji** [FTBTeam/FTB-Interactions#326]
Hello all, 
Some of my family, friends, I are new to this mod pack. We were having trouble figuring out some of the key bindings, so we went in to the controls panel but can't read what binds are which.... and were hoping that someone could help us.... I've attached a screen shot of what I see when I try to see what my bindings are. We all have the same issue, although for some its worse than others. We're not sure how to move the text over so that we can read what it says, we can hover over the text to see which mod its attached to but that it.... We are using version 1.1.2 of the mod pack. Any and all help is appreciated. 

Thanks for your time,
Dragonrenji

![Control panel](https://user-images.githubusercontent.com/49627767/56104724-979f1480-5efe-11e9-8889-f6583331b45a.png)

**Comment by merphle** [comment]
Hit Escape -> Options -> Video Settings -> change your GUI scale from "Auto" to "Large". All the GUIs will be a bit smaller on the screen. After updating your controls you can decide whether to switch back to Auto, or leave it with Large.

**Comment by Dragonrenji** [comment]
> 
> 
> Hit Escape -> Options -> Video Settings -> change your GUI scale from "Auto" to "Large". All the GUIs will be a bit smaller on the screen. After updating your controls you can decide whether to switch back to Auto, or leave it with Large.

Thank you, So much this fixed the issue.  Now we can work with the bindings, thank you.
