### ISSUE TITLE
Wireless point draws more power than shown

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#327]
the point says it draws 1keu/t fully boosted, but network tool says it draws 10keu/t

Submitter: `FTB Interactions#2470`
Body: `**[Wired_4fun]** OwO Issue "Wireless point draws more power than shown" "the point says it draws 1keu/t fully boosted, but network tool says it draws 10keu/t"`
Attachments:

**Comment by Saereth** [comment]
network tool is accurate, its because ae costs are 10x boosted in this pack. This is more an issue for ae

**Comment by Saereth** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4002

**Comment by Pingger** [comment]
Issue does not lie in AE ... modpack has messed something up. AE2 works without issues when used without the modpack.

**Comment by IRSmoh** [comment]
from discord https://cdn.discordapp.com/attachments/123194979509207040/567386167746494467/unknown.png
https://cdn.discordapp.com/attachments/123194979509207040/567386283215814679/unknown.png
https://cdn.discordapp.com/attachments/123194979509207040/567386312227684361/unknown.png

I want to say that the wireless access point isn't updated for the cost multiplier? I think we're on 10x default cost atm which would coincide conveniently with the viewed deltas.

**Comment by Saereth** [comment]
yep pack is on 10x multiplier

**Comment by Saereth** [comment]
welp ae2 basically instaslcosed the issue and is not responding anymore. Seeing as how this is just a display issue I guess im just gonna close it since we cant do anything about it.
