### ISSUE TITLE
OpenJDK/Apotheosis crash, needs forge update

### ISSUE THREAD

**Issue by ProspectPyxis** [FTBTeam/FTB-Interactions#331]
## Modpack Version: 
1.2.1

## Bug Report:
Modpack fails to launch when using OpenJDK.

## Expected Behavior/Suggestions:
Modpack should launch properly when using openJDK.

## Is It Repeatable? Steps to Reproduce: 
1. Launch modpack in multimc using openJDK java runtime
2. Modpack will crash during startup.

## Link to Log or Crash File Paste**: 
https://gist.github.com/ProspectPyxis/793bd99f45d7243059c9e6e1ba387dd0

## Mod/s Affected: 
Apotheosis

## Known Fix: 
According to https://github.com/Shadows-of-Fire/Apotheosis/issues/34, simply updating forge should solve the issue.

**Comment by Saereth** [comment]
asked shadows which version, awaiting reply

**Comment by Saereth** [comment]
we will be udpating to forge 2836  next update, baring no other mod conflicts
