### ISSUE TITLE
sky cauldron structure display problem

### ISSUE THREAD

**Issue by idyllist123** [FTBTeam/FTB-Interactions#333]
## Modpack Version: 
1.2.1

## Bug Report:
https://imgur.com/a/gNNwIx4
jei say that non-celestial crystal can construct the structure as shown but in fact only the celestial one can be accepted.

## Expected Behavior/Suggestions:
suggestion: tell it in questbook or somewhere

## Is It Repeatable? Steps to Reproduce: 
--

## Link to Log or Crash File Paste**: 
--
## Mod/s Affected: 
--
## Known Fix: 
not sure

**Comment by Saereth** [comment]
the component list specifies celestial, the render issue is a modular machine issue, I cant do much about that, I've already reported it to modular machinery
