### ISSUE TITLE
Ocean dungeons sand roof collapses when it generates 

### ISSUE THREAD

**Issue by Sokiri** [FTBTeam/FTB-Interactions#335]
## Modpack Version: 
1.2.0

## Bug Report:
Ocean dungeon spawns with a roof of sand causing it to fall and lag clients in the area.

## Expected Behavior/Suggestions:
I would suggest replacing the roof with sandstone or another ocean block.

## Is It Repeatable? Steps to Reproduce: 
[Heres an example of what I mean](https://streamable.com/gys6h), the zoom on the minimap is to show the falling sand entities (ignore the background noise, I was watching a stream)

## Mod/s Affected: 
Doomlike Dungeons

**Comment by Vyraal1** [comment]
Intended, that was part of the aesthetic when you start exploring them to have an layer of sand
