### ISSUE TITLE
dough nearly impossible to craft in mixer

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#337]
recipe requires 100mb of water + flour + salt; but 1000mb of water + salt = salt water (and it has priority), only other option is primal tech

Submitter: `IRSmoh_#5048`
Body: `OwO issue "dough nearly impossible to craft in mixer" "recipe requires 100mb of water + flour + salt; but 1000mb of water + salt = salt water (and it has priority), only other option is primal tech"`
Attachments:

**Comment by IRSmoh** [comment]
not convinced its possible to make dough*, the primal tech route doesn't appear to work. 
![image](https://user-images.githubusercontent.com/2626462/56181168-fa151500-5fd1-11e9-9bd0-530a621dda4f.png) 
![image](https://user-images.githubusercontent.com/2626462/56181189-06996d80-5fd2-11e9-8ccf-830ccac4fa18.png)
its not actually possible to add a bucket to the basin making the craft uncompletable (and even assuming that its just taking the fluid type, stirring for 40x does nothing)

**Comment by Vyraal1** [comment]
I think Sae fixed this by moving the salt water to the chemical reactor instead
