### ISSUE TITLE
flux plug uncraftable

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#338]
flux point works oddly enough, but the id=0 for making a flux plug fails.

Submitter: `IRSmoh_#5048`
Body: `OwO issue "flux plug uncraftable" "flux point works oddly enough, but the id=0 for making a flux plug fails."`
Attachments:

**Comment by Saereth** [comment]
You have to manually open the config of the circuit and set it to like 1 and back to zero, has to be actually SET to zero before it will count. 
![image](https://user-images.githubusercontent.com/9200909/56289848-e6f86700-60ef-11e9-9e74-6898c230e731.png)
