### ISSUE TITLE
Netherrack lightwell

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#34]
Recipie shows, but doesn't work to make lava in a lightwell

Submitter: `FTB Interactions#2470`
Body: `**[Quaxitos]** OwO issue "Netherrack lightwell" "Recipie shows, but doesn't work to make lava in a lightwell"`
Attachments:

**Comment by Saereth** [comment]
![image](https://user-images.githubusercontent.com/9200909/54998299-2f66ae00-4fa4-11e9-8711-077bca83029b.png)
cannot reproduce
