### ISSUE TITLE
Switch from Coop to Roost since code is maintaining it now

### ISSUE THREAD

**Issue by KAfable** [FTBTeam/FTB-Interactions#342]
![image](https://user-images.githubusercontent.com/26587049/56232776-887bac00-604f-11e9-8c39-f5ae8df7d8f5.png)

**Comment by Saereth** [comment]
lets slate this for next update so we have a bit more time to verify everything is working

**Comment by Loonacy** [comment]
I just set up a new server for 1.5.0 and downloaded the client, and when i tried to connect to the server it complained that i didn't have Roost installed.  It looks like the modpack has the dependency "Coop" which is deprecated with no downloads available, and suggests you download "Roost" instead.
I couldn't find a 2.0.6 file for Roost, so i copied the 2.0.6 Coop file from my server to get my client working.
