### ISSUE TITLE
Gravity affecting random entities

### ISSUE THREAD

**Issue by DrZoddiak** [FTBTeam/FTB-Interactions#343]
## Modpack Version: 
1.0.1 - But it's caused by bloodmagic which is not updated, so it's effectively all current versions.

## Bug Report:
Random entities such as those in Thaumcraft (flying golems) and armour stands are effected by gravity. This is caused by blood magic.
As shown [here](https://github.com/WayofTime/BloodMagic/issues/1544)

## Expected Behavior/Suggestions:
Flying golems should be able to fly, and armour stands certainly shouldn't be effected by gravity.

## Is It Repeatable? Steps to Reproduce: 
The easiest way to produce this would be to simply throw an armor stand on a block and break a block below it.
There are some other reproduction steps for the golem listed [here](https://github.com/WayofTime/BloodMagic/issues/1544#issuecomment-464401655)

## Link to Log or Crash File Paste**: 
Not applicable.

## Mod/s Affected: 
Bloodmagic.

## Known Fix: 
The PR [here](https://github.com/WayofTime/BloodMagic/pull/1576)
Or more specifically this fix [here](https://github.com/WayofTime/BloodMagic/commit/7c1565a68cddd5cc31660dd51e4d86545bfe9c8d)

It is important to note that while fixed in the mod, the updated version is **not** uploaded to Curse.
This ticket is to serve as a reminder that bloodmagic should be updated at the earliest convenience.

**Comment by Vyraal1** [comment]
Thanks, appreciate the heads up. Whenever the next release makes it's way to Curseforge we'll look into updating it.

**Comment by popcornCZ** [comment]
> Thanks, appreciate the heads up. Whenever the next release makes it's way to Curseforge we'll look into updating it.

New version is up and its **fixed**!! Can you make a hotfix for that please? 
https://minecraft.curseforge.com/projects/blood-magic/files/2713291
