### ISSUE TITLE
Ender Io Conduits crashes pack on launch due to out of date Java, even though Java is up to date. 

### ISSUE THREAD

**Issue by AleaInfinitus** [FTBTeam/FTB-Interactions#345]
## Modpack Version: 
1.2.1

## Bug Report:
Game crashes on launch seemingly due to Ender IO Conduits. Crash seems to be because Java is out of date, but game is set to use the up to date version of Java. 

## Expected Behavior/Suggestions:
Game launches successfully. 

## Is It Repeatable? Steps to Reproduce: 
1. Launch launcher
2. Launch Game
3. Crash during initial loading

## Link to Log or Crash File Paste**: 
https://pastebin.com/11HjMGyp

**Comment by Saereth** [comment]
try updating your forge to 2836 and see if this occurs please

**Comment by AleaInfinitus** [comment]
Still occurs with forge updated, yes.
