### ISSUE TITLE
check default ftbu configs to verify offline chunkloading is off by default

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#352]
Submitter: `Saereth#7836`
Body: `OwO issue "check default ftbu configs to verify offline chunkloading is off by default"`
Attachments:

**Comment by Saereth** [comment]
this no longer has an offline only options so we'll leave it as is, server owners can completely disable ftbu loading if they want and force their players to use weirding gadget if they run into issues
