### ISSUE TITLE
Centrifuging ashes still gives nothing in 1.3.0

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#356]
The issues at Github have been closed but the changelog tells nothing about this. Did you miss something in last update?

Submitter: `lxy1#9766`
Body: `OwO issue "Centrifuging ashes still gives nothing in 1.3.0" "The issues at Github have been closed but the changelog tells nothing about this. Did you miss something in last update?"`
Attachments:

**Comment by Vyraal1** [comment]
```
	#Adding Add to Carbon Dust Centrifurge
spinnyGoFast.recipeBuilder()
	.inputs(<ore:dustAsh>)
	.outputs(<ore:dustCarbon>.firstItem)
```
