### ISSUE TITLE
Coagulated Plant Balls don't copy Cohosh

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#361]
Submitter: `Saber#3492`
Body: `OwO issue "Coagulated Plant Balls don't copy Cohosh"`
Attachments:

**Comment by Saberawr** [comment]
Tested accidentally with a roof, apparently plant balls don't copy anything with a roof over the area

**Comment by Vyraal1** [comment]
Dupe of https://github.com/FTBTeam/FTB-Interactions/issues/239
