### ISSUE TITLE
GT Redstone ore can't be crafted to Vanilla Redstone ore (the recipe is GT->GT)

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#364]
Submitter: `zOwenn#6823`
Body: `OwO issue "GT Redstone ore can't be crafted to Vanilla Redstone ore (the recipe is GT->GT)"`
Attachments:

**Comment by Vyraal1** [comment]
We were planning to migrate to not needing vanilla redstone ore, what was the use case or this again?

**Comment by Saereth** [comment]
I migrated the recipes for AS so this should no longer be used anywhere
