### ISSUE TITLE
Thaumcraft & Astral Sorcery Not Team Friendly

### ISSUE THREAD

**Issue by Orichlol** [FTBTeam/FTB-Interactions#365]
1.20

If you are playing with a group of friends that are on at different times -- the requirement to duplicate efforts across Astral Sorcery and Thaumcraft are game breaking.

There needs to be a "Free" way available at the start to share your progress with your team -- otherwise if you are on at different times, progress can't be made.

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/56372958-02d23a80-61ce-11e9-9d68-e05959524467.png)

There is a knowledge share scroll in Astral Sorcery. As for Thaumcraft, we have provided new quests so players can just unlock wholesale branches of research, reducing the need for syncing.
