### ISSUE TITLE
enderchicken leaves phantom neutronium piles

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#366]
Submitter: `IRSmoh_#5048`
Body: `OwO issue "enderchicken leaves phantom neutronium piles"`
Attachments:

**Comment by Saereth** [comment]
@TeamDman any idea why this may occur? something with the way we're spawning them in via/crafttweaker/zentriggers?

**Comment by TeamDman** [comment]
Probably forgot to disable something client side, will look into it

**Comment by braingkk** [comment]
still happening on latest version 1.6.1 any progress? it has been a month already, and i hate having to swap dimensions every set of chickens or the server packet spams me into oblivion due to thousands of items on the ground

**Comment by braingkk** [comment]
Pretty sure the issue is that the ZenEvents.zs should only be running on the server, not the clients.
simply commenting out the contents of the file fixed it for everyone on my server.

**Comment by Vyraal1** [comment]
Hmm I let Teamy know of this, the issue is that it's impossible to have a script only run on the server, and the wide scale fix I would like is to have the mod handle it only on the server. I pinged him again 
![image](https://user-images.githubusercontent.com/26587049/58192642-3bfb4000-7c8f-11e9-997d-ffff863ca920.png) and hopefully he can get to this. Thanks for confirming btw.

**Comment by TeamDman** [comment]
mb, will get on it

**Comment by TeamDman** [comment]
![image](https://user-images.githubusercontent.com/9356891/58216804-f4e06f80-7ccd-11e9-8681-f54b486b7521.png)

**Comment by TeamDman** [comment]
For future reference, the script could have done `if (event.entity.world.isRemote) return` as a short-circuit to prevent phantom items on the server. It's my fault for not realizing and proposing this solution earlier. Instead, I've chosen to add it to the PredicateBuilder class instead for performance and ease of use in the future.
