### ISSUE TITLE
electrolyzing steam is power positive

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#367]
Submitter: `lthistle#5451`
Body: `OwO issue electrolyzing steam is power positive`
Attachments:

**Comment by hobnob11** [comment]
![img](https://cdn.discordapp.com/attachments/560185294842888222/568317647406759937/unknown.png)

So.. here is a large bronze boiler producing 65,536 eu/tick...
and the bottleneck there is the turbines..

basically, this recipe:
![img2](https://cdn.discordapp.com/attachments/568319159180722206/568319944274739210/unknown.png)

the steam turbine takes 2mb of steam and makes 1 eu
the gas turbine takes 3,000mb of steam, and makes 40,000 eu (-2160 eu for the electrolyzer)
the steam turbine has a steam energy value of 0.5 eu
the gas turbine has a steam energy value of 12.6133 eu

**Comment by Vyraal1** [comment]
What version of the pack is this?

**Comment by LThistle** [comment]
1.3.0

**Comment by InThayne** [comment]
That steam recipe in the electrolyzer is at least available in release version 1.2.1

**Comment by hobnob11** [comment]
tested in 1.3.
