### ISSUE TITLE
bronze chests render funky https://cdn.discordapp.com/attachments/377980842141548546/568408296806154241/unknown.png

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#369]
Submitter: `alex beans you lol goteem#1234`
Body: `OwO issue bronze chests render funky https://cdn.discordapp.com/attachments/377980842141548546/568408296806154241/unknown.png`
Attachments:

**Comment by Isolol** [comment]
I was the one asking about this on discord. The chest is actually on the pink square but it renders off in the distance. It moves with your character as you move about. The chest is interactable at the pink square.

**Comment by Isolol** [comment]
After some messing around with stuff on our world, we found out that if a Tinker's Casting Channel is filled with fluid in render distance of the GTCE Bronze Chest, the chest decides to play whackamole with where it renders.

**Comment by Vyraal1** [comment]
Is this a normal Forge server?

**Comment by Isolol** [comment]
Yup, fresh install. Only change made was adding DiscordIntegration for our discord chat bot. It happened in v1.2.1 and in v1.3.0 it would persist through logouts. Would require the client to be restarted even after removing the channel.

**Comment by Saereth** [comment]
gtce issue, mostly resolved in new update but for them to continue refining, nothing we can do about it from a pack standpoint
