### ISSUE TITLE
GT Machines are using high cpu on servers when they have circuit/mold/partial ingredients

### ISSUE THREAD

**Issue by Highbeam** [FTBTeam/FTB-Interactions#371]
## Modpack Version: 
1.2.1

## Bug Report:
GT Machines with circuits/molds left inside eat a lot of server resources when they are idle.

We have tracked this down so far to Alloy Smelter (with molds in) and Assembling Machine (with circuits).

The Assembling machines (any tier) were eating as much as 4.5%+ and the Alloy Smelter 1.5%+ in the screenshot below (1st and 2nd):

![image](https://user-images.githubusercontent.com/32101225/56371667-cfa79f80-61fd-11e9-81d7-daac5fe235a3.png)

After removing the circuit/mold, things returned to normal...

![image](https://user-images.githubusercontent.com/32101225/56371685-d7ffda80-61fd-11e9-84bb-427c8999f600.png)

The third machine down in the 2nd screenshot (0.5%) is a Mixer that has partial recipe in, waiting for more ingredients.

This can slowly get out of hand if multiple players have many machines with circuits/recipes waiting in them.

**Comment by Vyraal1** [comment]
Going off of what we had earlier in https://github.com/Vyraal1/FTB-Interactions/issues/752

Am still trying to hunt down other issues before asking other mod devs on how to improve this.

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/56382678-efcb6480-61e5-11e9-992a-faadc7396582.png)

**Comment by krakel** [comment]
they can simple reduce the update frequence for incomplete recipes

**Comment by Vyraal1** [comment]
Would you be willing to make an issue on GTCE directly? Either the dev is refusing to implement your simple suggestion, or it might be more complicated than that.

**Comment by krakel** [comment]
I added a pull request for a simple idle time implementation.
https://github.com/GregTechCE/GregTech/pull/815

**Comment by krakel** [comment]
My idea was rejected. :(

**Comment by KaneHart** [comment]
We been facing this issue as well. Pretty much if there is items left in a machine like half baked recipe in the making it overtime builds higher and higher in tick usage it seems.

**Comment by Highbeam** [comment]
This isn’t an issue on GTNH 2 (gregtech 5 on 1.7). This pack is managed by Dreammaster and Alkulus, I’m sure if you reach out for some advice they could help. I know dream may work on 1.12 GTNH 3 next.

**Comment by Highbeam** [comment]
https://github.com/alkcorp/GTplusplus

**Comment by Highbeam** [comment]
https://github.com/GTNewHorizons/NewHorizons

**Comment by krakel** [comment]
Oh, we was playing this mod on our server some months ago and we got the same problem with GTCE on the progress with more and more GT machines.

**Comment by Archengius** [comment]
Fixed in latest gtce
