### ISSUE TITLE
Pulverise Iron Bars = too much iron

### ISSUE THREAD

**Issue by Highbeam** [FTBTeam/FTB-Interactions#372]
## Modpack Version: 
1.2.1

## Bug Report:

It can cost as low as 3 iron ingots to make 8 Iron Bars (in crafting table/assembler = 6 iron rods)

Macerate 1 iron bar = 24 tiny piles (2.65 ingots)

## Expected Behavior/Suggestions:

Change 1 iron bar = 3 tiny piles (8 * 3 = 24 tiny piles so you don't get profit)

**Comment by Vyraal1** [comment]
Confirmed this happens in base GTCE 387, reported here https://github.com/GregTechCE/GregTech/issues/759.

Recipe will be altered manually in the pack.
