### ISSUE TITLE
Thaumcraft EverFull Urns [Lag Issue]

### ISSUE THREAD

**Issue by Highbeam** [FTBTeam/FTB-Interactions#373]
## Modpack Version: 
1.2.1

## Bug Report:

Everfull Urns are causing some serious TPS issues, especially in large numbers:

![image](https://user-images.githubusercontent.com/32101225/56371768-0a113c80-61fe-11e9-8a64-5c0640f810d4.png)

This is on Toastworld server.  We have temporarily providing everyone with ender tanks linked to infinite water and we trust our player community not to use them for now.

The functionality on the urns is different to TC4.  If they didn't have the wireless water (sending to any block within 5x5x3) would it be any better perhaps?

Moved from https://github.com/Vyraal1/FTB-Interactions/issues/751

**Comment by Vyraal1** [comment]
Thanks for moving this Highbeam, during development we were aware of this but our testing on FTBOne showed it that it was as material of an issue (average 5-10 players, 15 at peak times). We did allow for a VERY easy upgrade though with the everful urn to much more lag friendly alternatives to the aqueous accumulator as an alternative (should be available on the same tech level).

**Comment by Highbeam** [comment]
agree but as I understand you can directly pump out water from the everfull urn giving a no limit water supply.

Aqueous and other options are limited to '1B per sec'?

**Comment by Highbeam** [comment]
Considering how severe the impact was for us, I may talk to toast about banning the urn from being placed in world but at least it can be crafted, this way it can still be used to make the aqueous early game.  Shame it's old functionality can't be retained.

**Comment by Vyraal1** [comment]
Everful urn should only have a throughput of 20mb/t, which is far lower than the aqueous accumulators production rate. 
![image](https://user-images.githubusercontent.com/26587049/56372714-850e2f00-61cd-11e9-96a1-0ff15ca29b8f.png)

At most stages players shouldn't need a lot of water anyways, until very late game when setting up fusion reactor fuel production, at which they'll have access to other sources of water.

**Comment by Vyraal1** [comment]
Also wanted to clarify that banning everful urns should NOT affect progression at all, and the pack should for the most part work fine, so that could be an appropriate (if unfortunate) solution on your server. The original intention was to gate water production behind magic, because after all it is pretty magical making water out of nothing so the Everful was both a mechanical and flavorful fit.
