### ISSUE TITLE
crystalized menril chunk quest should not give living rock

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#374]
Submitter: `Saereth#7836`
Body: `OwO issue "crystalized menril chunk quest should not give living rock"`
Attachments:

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/56433387-b99deb80-629e-11e9-955a-5a6e44ac3e03.png)

switched to 16 menril wood instead
