### ISSUE TITLE
Suggestion: Add Osglosglas recipe

### ISSUE THREAD

**Issue by Highbeam** [FTBTeam/FTB-Interactions#377]
## Modpack Version: 
1.2.1

## Expected Behavior/Suggestions:
Osgloglas can't be made as its a 'disabled' smeltery recipe.

Can this be added to the mixer/ebf instead as it has some nice traits to offer tinkers tools?

![image](https://user-images.githubusercontent.com/32101225/56392591-1ca56900-6232-11e9-9904-e1040feffeba.png)

Smeltery recipe is:

1mb Osmium (EBF MV / 3306K recipe + Vac freezer MV)
1mb Molten Refined Obsidian (EBF HV / 3600K recipe)
1mb Refined Glowstone (EBF HV / 3600K recipe)

I've put some suggestions below:

Add Maceration recipe:
Refined Obsidian ingot #7338/0 -> Refined Obsidian dust #7387/5 (the dust exists but currently has no recipes associated with it).

Add Mixer recipe:
1x Osmium dust #6979/2047
1x Refined Obsidian dust #7387/5
1x Refined Glowstone dust #???? (there is no Refined Glowstone dust in JEI - a new item could be created)
Produces = 1x Osglosglas dust #???? (no for Osglosglas dust in JEI - a new item could be created)

Add EBF recipe:
1x Osglosglas dust #???? -> Osgloglas ingot #5015

Running tiers I will leave to suggestion.  This is a high tier ingot from the original ingredients so HV+

Cheers

**Comment by Vyraal1** [comment]
```
	#Osgloglas
blast_furnace.recipeBuilder()
	.inputs([<ore:ingotOsmium>, <ore:ingotRefinedObsidian>, <ore:ingotRefinedGlowstone>])
	.outputs(<ore:ingotOsgloglas>.firstItem)
	.EUt(480)
	.duration(1200)
	.buildAndRegister();
```
Added to this in HV
