### ISSUE TITLE
Remove Mekanism Energy tablets and adjust any recipes still requiring them to use gt tiered variants

### ISSUE THREAD

**Issue by nowifi4u** [FTBTeam/FTB-Interactions#379]
## Modpack Version: 
FTB-Interactions 1.2.1 & 1.3.0

## Bug Report:
GregTech CEU block accepts empty Energy Tablets but no longer accepts them if they are fully charged.

## Expected Behavior/Suggestions:
You should be able to insert a fully charged Energy Tablet into CEU

## Is It Repeatable? Steps to Reproduce: 
1. Put Mekanism's Energy Tablet into any CEU
2. Wait until it fully charges 
3. Grab it from the CEU
4. Try inserting it into CEU

## Mod/s Affected: 
GregTech CEU, Mekanism

## Known Fix: 
Add a recipe for clearing the energy inside a tablet. (Any Energy Tablet as input, empty one as output)

**Comment by Vyraal1** [comment]
Wait, bit confused, why do you NEED to have full energy tablets inside?

**Comment by nowifi4u** [comment]
@Vyraal1 So you can:
- use the CEU as RF energy buffer
- use the CEU to power RF powered machines outside (pumps and stuff)

**Comment by Saereth** [comment]
I will be disabling mekanism energy tablets completely next update so will become a non issue

**Comment by Kanzuke117** [comment]
Dire's Building Gadget still uses an Energy Tablet in it's recipe
