### ISSUE TITLE
Creative worms not really automtable

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#38]
I get it was for the memes, but theres no real way other than strainers to reliably get worms; mining with a trowel in luv age seems... miss placed

Submitter: `IRSmoh_#5048`
Body: `OwO issue "Creative worms not really automtable" "I get it was for the memes, but theres no real way other than strainers to reliably get worms; mining with a trowel in luv age seems... miss placed"`
Attachments:

**Comment by TeamDman** [comment]
Mechanical users with trowel might work

**Comment by Saereth** [comment]
mechanical user and trowel works also, strainers can be automated by piping nets into them and piping products out from the bottom
