### ISSUE TITLE
Bug?: EBF Recipe for Alumite conflicts with Aluminium

### ISSUE THREAD

**Issue by Highbeam** [FTBTeam/FTB-Interactions#380]
## Modpack Version: 
1.2.1

## Bug Report:
Tried to craft Alumite but the recipe conflicts with Aluminium and crafts Aluminium instead.

## Expected Behavior/Suggestions:
Not sure what to suggest here.  Maybe change it to craft Alumite nuggets using Iron Alloy Nugget + Tiny Pile of Aluminium?  1600 EU cost per operation.  Duration 1 sec?

![image](https://user-images.githubusercontent.com/32101225/56393987-39dc3680-6236-11e9-8723-cc2bbd25f3a2.png)

![image](https://user-images.githubusercontent.com/32101225/56393995-3f398100-6236-11e9-9d08-0a474c827ba6.png)

**Comment by Vyraal1** [comment]
https://github.com/FTBTeam/FTB-Interactions/issues/300
