### ISSUE TITLE
ancient stone infusion altars do not form

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#381]
Submitter: `Buggy#1871`
Body: `OwO issue "ancient stone infusion altars do not form"`
Attachments:

**Comment by Vyraal1** [comment]
Use Arcane Stone.

**Comment by Vyraal1** [comment]
Base level Arcane Stone ones work, but the Ancient Stone infusion altars don't seem to form, are these even  implemented yet? Or is there a special way?

**Comment by Vyraal1** [comment]
Implementation of these seem to be broken, they used to work in Thaumcraft Beta 22- not anymore.

**Comment by Saereth** [comment]
yeah this is invalid as a pack issue, take it up with tc
