### ISSUE TITLE
impure draconium (de) -> tiny piles -> draconium dust (gt) -> ingots

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#382]
not sure if you care, but the ingots are technically attainable then by just a ton of island hopping in the end, by passing any fusion/red matter setup

Submitter: `IRSmoh_#5048`
Body: `OwO issue "impure draconium (de) -> tiny piles -> draconium dust (gt) -> ingots" "not sure if you care, but the ingots are technically attainable then by just a ton of island hopping in the end, by passing any fusion/red matter setup"`
Attachments:

**Comment by Vyraal1** [comment]
Oh shit, this was actually a pretty bad oversight, fixed this and cleaned up some DE recipes as well.
