### ISSUE TITLE
cant make ceramic faucet , have to make seared faucet instead

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#383]
Submitter: `alex beans you lol goteem#1234`
Body: `OwO issue cant make ceramic faucet , have to make seared faucet instead`
Attachments:

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/56446144-f1bd2280-62ce-11e9-978e-cad1145adc5e.png)


![image](https://user-images.githubusercontent.com/26587049/56446183-27faa200-62cf-11e9-8da6-4a5cb601ef87.png)
