### ISSUE TITLE
quest book: definitely not safe space quests: glowstone and nether stibnite overlap

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#386]
Submitter: `IRSmoh_#5048`
Body: `OwO issue "quest book: definitely not safe space quests: glowstone and nether stibnite overlap"`
Attachments:

**Comment by Vyraal1** [comment]
Im 100% sure these errors are either due to how Twitch updates or errors not getting properly deleted. There weren't any overlapping quest in the nether section when the pack shipped, i triple checked them after the first report of the cataplant. Not sure how to fix this.
