### ISSUE TITLE
add gt energy produces to holo/flowing time blacklist, as well as gt cables

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#387]
Submitter: `Saereth#7836`
Body: `OwO issue "add gt energy produces to holo/flowing time blacklist, as well as gt cables"`
Attachments:

**Comment by Kanzuke117** [comment]
Aww, is this to nerf the time in a bottle? Or just because people are burning cables?

**Comment by Saereth** [comment]
https://github.com/FTBTeam/FTB-Interactions/issues/402
