### ISSUE TITLE
In for the long haul quest requires a basic mixer but diesel requires an mv mixer.

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#388]
Submitter: `FTB Interactions#2470`
Body: `**[Anaruke]** OwO issue "In for the long haul quest requires a basic mixer but diesel requires an mv mixer."`
Attachments:

**Comment by Vyraal1** [comment]
I just ended up removing the mixer altogether from the quest, they should be able to use JEI to figure it out.
