### ISSUE TITLE
Dying in overworld doesn't respawn you at your crying obsidian set spawn (v1.3.0)

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#390]
Submitter: `lthistle#5451`
Body: `OwO issue "Dying in overworld doesn't respawn you at your crying obsidian set spawn (v1.3.0)"`
Attachments:

**Comment by Vyraal1** [comment]
Couple of questions:
1) where was the crying obsidian set to? in what dimensions
2) What dimensions did you die in?

**Comment by LThistle** [comment]
1. Set to a point in my base (like 20, 20) in void world
2. overworld
gamerules:
![image](https://user-images.githubusercontent.com/26513277/56448954-fb9c5100-62e1-11e9-8cae-54b1b22f862d.png)
