### ISSUE TITLE
cannot craft me controller if block have power

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#395]
this is possible to achieve with anything that charges them.. spectre coils/flux network. gl.

Submitter: `FTB Interactions#2470`
Body: `**[IRSmoh_]** OwO issue "cannot craft me controller if block have power" "this is possible to achieve with anything that charges them.. spectre coils/flux network. gl."`
Attachments:

**Comment by Vyraal1** [comment]
Barring changing the Energy Cell block entirely for another block, don't think this is solvable as Compact Machines is NBT specific. Would just have to tell players automating this to turn off their wireless charging.

**Comment by Saereth** [comment]
actually if you automate them its no issue, its more an isssue if you have a spectre charging bauble or fluxnet that charges stuff in your inventory and are trying to do it manually. But yeah what Vyraal said, you can work around this and its a limitation of compact machines
