### ISSUE TITLE
when using a dolly to pick up a GTCE machine, placing it back down there will be no texture, waila shows it as an unknown block and using a GTCE wrench on it will crash the game (specifically reporting the game crash part)

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#396]
Submitter: `alex beans you lol goteem#1234`
Body: `OwO issue when using a dolly to pick up a GTCE machine, placing it back down there will be no texture, waila shows it as an unknown block and using a GTCE wrench on it will crash the game (specifically reporting the game crash part)`
Attachments:

**Comment by Vyraal1** [comment]
Mod issue, nothing we can do about it and GTCE machines are not intended to be picked up by dolly in this way.

**Comment by Saereth** [comment]
This shouldnt even be possible unless you're in creative mode
