### ISSUE TITLE
Aesthetic Options

### ISSUE THREAD

**Issue by Omegapsychosis** [FTBTeam/FTB-Interactions#398]
Pack is amazing so far, but is it possible to add some more aesthetic mods to the pack at all in the future?

I was thinking perhaps DecoCraft2, and Cosmetic Armour reworked.

Ading DecoCraft2 would allow for a more aestheticly pleasing looking base design without really adding anything that would break progression.

Cosmetic Armour Reworked simply allows for an armour set to be worn that only shows visually so players can look however they want while still having the benefits of the armour set the need to wear for progression.

## Modpack Version: 
1.2.1

## Bug Report:
Not a bug; just a suggestion for improvement when it comes to pack aesthetics.

**Comment by Vyraal1** [comment]
Hard no on DecoCraft2, the RAM usage is already high and we are close to the block id count normally allowed in Forge 1.12.2, the extra blocks and models isn't enough of a payoff to justify it.

Can consider cosmetic armor reworked, for some reason I thought it was in the pack already, but this is unlikely to be added.

**Comment by Saereth** [comment]
we have cosmetic armor already in the pack, and decocraft would push us over the blockid limit as Vyraal said unfortunately. its a good mod though just cant fit it in without alot of negative consequences.

**Comment by Vyraal1** [comment]
Yeah I'm dumb, just realized it is in the pack already.

**Comment by Omegapsychosis** [comment]
Then I am infact the dumb one, my apologies.

What about Chisels and Bits? Does that too affect the blockid limit as much as Decocraft?

**Comment by Vyraal1** [comment]
Little Tiles was chosen over Chisel and bits as it has a better performance impact.
