### ISSUE TITLE
Ungrown (0% growth stage) pams crops when broken drop the fully grown crop, not the seed

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#40]
Submitter: `FTB Interactions#2470`
Body: `**[Rdjrjqouqcu]** OwO issue "Ungrown (0% growth stage) pams crops when broken drop the fully grown crop, not the seed"`
Attachments:

**Comment by Saereth** [comment]
this is not really an issue, you can replant the crop/craft to a seed
