### ISSUE TITLE
add generators/ceus to blacklist for time in a bottle

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#402]
Submitter: `FTB Interactions#2470`
Body: `**[IRSmoh_]** OwO issue "add generators/ceus to blacklist for time in a bottle"`
Attachments:

**Comment by Saereth** [comment]
holorgium black list as well, as well as cables, this will be alot of work, leaving this just open for now

**Comment by Saereth** [comment]
I think I actually like this interaction, gonna leave it
