### ISSUE TITLE
infinity egg centrifuge outputs not actually a perecent chance

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#405]
in a luv machine we're hitting 100% outcome rates even though the chicken for example, is supposed to be 5% (50x in a row)

Submitter: `IRSmoh#5048`
Body: `OwO issue "infinity egg centrifuge outputs not actually a perecent chance" "in a luv machine we're hitting 100% outcome rates even though the chicken for example, is supposed to be 5% (50x in a row)"`
Attachments:

**Comment by Saereth** [comment]
thats due to the multipler on output chance since you're using an luv machine. I will probably look into tweaking this a bit but not a huge deal
