### ISSUE TITLE
Game freezes/crashes upon entering new world

### ISSUE THREAD

**Issue by z-Tau** [FTBTeam/FTB-Interactions#410]
## Modpack Version: 
1.2.1

## Bug Report:
After loading the pack, I go to create a new world with the default settings.  This works fine, until the point where I get to see the skybox and the UI.  I am able to look around for a few seconds until a bunch of books appear in my hotbar.  Then the game either freezes indefinitely, or crashes to desktop.

I have tried with both 10GB and 6GB RAM allocated in the Twitch launcher, as well as creating a default world instead of the Void? World.

## Expected Behavior/Suggestions:
The world should load and not crash.

## Is It Repeatable? Steps to Reproduce: 
Yes, the only difference being whether the game crashes or freezes.
1. Load pack
2. Create new world

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/0464315a

**Comment by Saereth** [comment]
this is an os/configuration/java problem not a pack issue as far as I see nothing related to the pack specifically in your log here.

**Comment by 10935336** [comment]
I ran into the same problem on the server, but I found that it would be normal to enter a single-player server before entering the server.

**Comment by z-Tau** [comment]
I just wanted to add that having tried the current latest version of the pack - 2.0.9, this is no longer an issue.  I was able to create and join a new world and the game worked fine.
