### ISSUE TITLE
cooking gtce Block of Skystone in a multi smelter outputs the same block of skystone instead of processing it to ae2 skystone

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#462]
Submitter: `Totto#2810`
Body: `OwO issue "cooking gtce Block of Skystone in a multi smelter outputs the same block of skystone instead of processing it to ae2 skystone"`
Attachments:

**Comment by Saereth** [comment]
this cannot and will not be fixed, just use something other than the multismelter for that block. There is no way for us to fix it and gtce wont fix it

**Comment by a3626a** [comment]
In 1.9.1, Block of Skystone (gregtech) is smelted into block of Skystone (gregtech) in electric furnace and kiln. This makes orbital laser completely useless. Every one in Discord is talking about dungeons for skystone.

One of two things should be fixed: smelt recipe or the quest
