### ISSUE TITLE
Mekanism Dynamic consumes all but one GregTech Cell if liquids are different

### ISSUE THREAD

**Issue by nowifi4u** [FTBTeam/FTB-Interactions#466]
## Modpack Version: 
1.3.0

## Bug Report:
Mekanism Dynamic consumes all but one GregTech Cell if liquids are different

## Expected Behavior/Suggestions:
Nothing should be done in this case (liquids are different)

## Is It Repeatable? Steps to Reproduce: 
1. Build Mekanism Dynamic Tank of any size
2. Fill it with any amount of any Liquid #1
3. Open the Tank and insert multiple cells filled with any Liquid #2
4. All the filled cells but one just vanish

## Mod/s Affected: 
- Mekanism
- GregTech CE

## Known Fix: 
None as of yet

**Comment by Saereth** [comment]
this should be resolved  with mek update
