### ISSUE TITLE
Astral Sorcery tree beacon double Gregtech Multi Maschine Blocks

### ISSUE THREAD

**Issue by krakel** [FTBTeam/FTB-Interactions#468]
## Modpack Version: 
1.2.1

## Bug Report:
when your gregtech multi block was placed in range of the beacon and you modify the multi block the becon restore the structure

## Is It Repeatable? Steps to Reproduce: 
1. place the Beacon
2. create a multi block (Pyrolyse Oven) in range
3. remove the control block
4. the Beacon restore this block, you have a second block in your inventory

**Comment by Saereth** [comment]
this has been reported to hellfire

**Comment by Vyraal1** [comment]
Posting here for reference: https://github.com/HellFirePvP/AstralSorcery/issues/1060

**Comment by Saereth** [comment]
this should be fixed now in new versions of AS, if not please turn on logging for the tree beacon in the config and let us know
