### ISSUE TITLE
Chisel books

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#47]
Can't chisel out of the cyclic book

Submitter: `FTB Interactions#2470`
Body: `**[Quaxitos]** OwO issue "Chisel books" "Can't chisel out of the cyclic book"`
Attachments:

**Comment by Vyraal1** [comment]
unfortunately side effect of this system, after opening the Cyclic book it gains an nbt tag and the Chisel ends up treating it as an entirely different item
