### ISSUE TITLE
get bismuth processing working again or change steam turbine recipe to not require it

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#472]
Submitter: `Saereth#7836`
Body: `OwO issue "get bismuth processing working again or change steam turbine recipe to not require it`
Attachments:

**Comment by Saereth** [comment]
latest gtce has no bismuth byproduct, needed for steam turbines

**Comment by Vyraal1** [comment]
assuming turbines doesn't need bismuth anymore
![image](https://user-images.githubusercontent.com/26587049/56682785-48917600-669a-11e9-85db-4cdcb77301de.png)
