### ISSUE TITLE
tinkers and GTCE glass measurement standards

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#476]
undefined

Submitter: `Vyraal1#0001`
Body: `OwO issue "tinkers and GTCE glass measurement standards"`
Attachments:

**Comment by Saereth** [comment]
what? @Vyraal1

**Comment by Vyraal1** [comment]
GTCE Fluid extractor output 144mb of glass, tinkers has it at 1000mb, going to lower tinkers requirements and output to 144mb

**Comment by Saereth** [comment]
yeah sounds good, always been more a fan of the 144
