### ISSUE TITLE
Large Gas Turbine structure does not recognize any Input Hatches

### ISSUE THREAD

**Issue by nowifi4u** [FTBTeam/FTB-Interactions#478]
## Modpack Version: 
1.3.0

## Bug Report:
Large Gas Turbine structure does not recognize any Input Hatches making structure useless (multiplayer only, no matter inside or outside a claim)

## Is It Repeatable? Steps to Reproduce:
1. Build Lag Gas Turbine with any tier blocks
2. Feed it some gas
3. Notice that not only turbine is not working, but also controller block says "Fuel amount: 0L"

## Mod/s Affected: 
GregTech CE

**Comment by Saereth** [comment]
reported to gtce

**Comment by Saereth** [comment]
gtce just removed them entirely rather than fix them
