### ISSUE TITLE
Item Ducts

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#48]
Dense itemduct recipie creates normal item ducts

Submitter: `FTB Interactions#2470`
Body: `**[Quaxitos]** OwO issue "Item Ducts" "Dense itemduct recipie creates normal item ducts"`
Attachments:

**Comment by Saereth** [comment]
this is not actually a bug with the recipe but it is something we need to look into. Whats going on here is we dont have recipes for the dense and vacuum ducts, people should be graduating onto enderio conduits/ae/other logistics for more advanced routing. The item is the same nbt though so we cant hide it from jei and it shows with the same recipe. basically all 3 types of itemduct recipes that show in jei as the same recipe but all you'll ever get is the basic item ducts/opaque.
