### ISSUE TITLE
thaumcraft stone too expensive.

### ISSUE THREAD

**Issue by ppoozl** [FTBTeam/FTB-Interactions#480]
## Modpack Version: 
1.3.0
## Bug Report:

![DH2(TFLRA@TQWTKZ``6O%}A](https://user-images.githubusercontent.com/7188938/56540241-b48cb500-659a-11e9-8320-1392f911e18f.png)
Is this right? I think it's too expensive.

**Comment by Vyraal1** [comment]
Intended. Nacre is easy to automate
