### ISSUE TITLE
Quest Book doesn't recognize Sand versions of ore

### ISSUE THREAD

**Issue by staticlando** [FTBTeam/FTB-Interactions#481]
## Modpack Version: 
Latest on Curse

## Bug Report:
Sand versions of ore not recognized in quest book

## Expected Behavior/Suggestions:
The book should recognize them. Found a few ore veins in a desert biome but in order to complete the quests I need to find them elsewhere

**Comment by Saereth** [comment]
this wont be fixed until ftbquests can properly support oredicts.
