### ISSUE TITLE
Forge Hammer has 2 recipes using Blaze Mesh blocks

### ISSUE THREAD

**Issue by TomyLobo** [FTBTeam/FTB-Interactions#484]
## Modpack Version: 
1.3.0

## Bug Report:
![image](https://user-images.githubusercontent.com/963797/56564997-97161600-65af-11e9-9206-b5710baf4491.png)

## Expected Behavior/Suggestions:
I'd expect there to be only one forge hammer recipe using Blaze Mesh blocks :)

## Is It Repeatable? Steps to Reproduce: 
1. Open JEI
2. Search for Blaze Mesh
3. Right-click Blaze Mesh
4. Switch to "Forge Hammer" tab
     - Expected: 1 recipe
     - Actual: 2 recipes

**Comment by Vyraal1** [comment]
```
	#Blaze Rod Removal from Mesh
mods.gregtech.recipe.RecipeMap.getByName("forge_hammer").findRecipe(24,
	[<botania:blazeblock>],
	[null])
	.remove();
```
