### ISSUE TITLE
Crying Obsidian (Decorative) Oredicts with Obsidian

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#49]
Making an EMC loop by melting it into normal Obsidian, only takes 1 Obsidian + 4 Lapis to create 4 Obsidian

Submitter: `Tazz#0001`
Body: `OwO issue "Crying Obsidian (Decorative) Oredicts with Obsidian" "Making an EMC loop by melting it into normal Obsidian, only takes 1 Obsidian + 4 Lapis to create 4 Obsidian"`
Attachments:

**Comment by Saereth** [comment]
This is not a bug, enjoy :p The rationale is you're using a non renewable material to inflate your limited use emc
