### ISSUE TITLE
GT Block of Aluminium can't be chiseled into Chisel variants

### ISSUE THREAD

**Issue by ToasterKoishi** [FTBTeam/FTB-Interactions#490]
## Modpack Version: 
1.3.0

## Bug Report:
Gregtech's Block of Aluminium can't be chiseled into Chisel's Block of Aluminum variants due to spelling problems. One is blockAluminium (with two `i`s) and the other is blockAluminum (with one `i`).

I did check many other Chisel metal block variants and they seem to work fine

## Expected Behavior/Suggestions:
Everything that has "aluminium" or "aluminum" in its oredict should probably also have the other variant

## Is It Repeatable? Steps to Reproduce: 
1. Get any chisel from the Chisel mod and a Gregtech Block of Aluminium
2. Attempt to chisel, it will show no chiselable variants

## Mod/s Affected: 
GregTech Community Edition
Chisel

**Comment by Vyraal1** [comment]
Script doesn't seem to work as expected, will have to investigate for next update

**Comment by Vyraal1** [comment]
```
	#Letting Aluminium Blocks get Chiseled
furnace.addRecipe(<chisel:blockaluminum:2>, <ore:blockAluminium>);
furnace.addRecipe(<ore:blockAluminium>.firstItem, <chisel:blockaluminum:2>);
```
Adding a workaround, will have to smelt in a chiselable form of aluminium first and then can use that.
