### ISSUE TITLE
create a magic stick quest for the TC research table

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#491]
undefined

Submitter: `Saereth#7836`
Body: `OwO issue "create a magic stick quest for the TC research table"`
Attachments:

**Comment by Saereth** [comment]
people seem to getting confused as to which table they should create so we should add a quest with a turn in for the correct table.

**Comment by Saereth** [comment]
https://github.com/FTBTeam/FTB-Interactions/pull/877
