### ISSUE TITLE
replace buckets of starlight in all starlight altar recipes with a fluidstack, hellfire says this will fix the buckets being consumed

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#492]
undefined

Submitter: `Saereth#7836`
Body: `OwO issue "replace buckets of starlight in all starlight altar recipes with a fluidstack, hellfire says this will fix the buckets being consumed"`
Attachments:

**Comment by Vyraal1** [comment]
changed for 3 custom recipes, not sure if there were others

**Comment by Saereth** [comment]
got the rest of them
