### ISSUE TITLE
Mod addition: Gregs Construct

### ISSUE THREAD

**Issue by SuperSandro2000** [FTBTeam/FTB-Interactions#499]
Did you consider adding [Gregs Construct](https://minecraft.curseforge.com/projects/gregs-construct) to the pack?

It's main purpose is to add all of Gregs materials to tinkers.

**Comment by Saereth** [comment]
No this mod does alot of undesirable things we'd have to put in extra work to deal with such as adding all alloyer recipes to tinkers. We already add all currently used tinkers materials to gt machines, We dont want to add gtce melting of ores, so we'd have to disable all that for the next gain of being able to use a few gt materials as tinkers materials, none of which have unique traits, they are all copy/pastas of existing materials with tweaked durabilities and speeds.

We can already also add materials like that to tinkers with crafttweaker so a better approach would be to just suggest some specific tinkers materials for us to add if there's some you think would make good tinkers tools.

**Comment by SuperSandro2000** [comment]
Thanks for the long explanation. Appreciate it.
I need to start with the pack before I can make a meaningful addition to the tinkers materials but I always go 100% tinkers as soon as I can so you probably hear something from me again.
