### ISSUE TITLE
Xaero's Mini map feature request

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#5]
https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2379024-xaeros-minimap-forge-1-13-2-1-12-2-1-12-1-1-12-1?page=86

Submitter: `Vyraal1#0001`
Body: `OwO issue "Xaero's Mini map feature request" "https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2379024-xaeros-minimap-forge-1-13-2-1-12-2-1-12-1-1-12-1?page=86"`
Attachments:

**Comment by Vyraal1** [comment]
Xaero added this feature and was included as of v1.2.0 of the pack.
