### ISSUE TITLE
Crash while attacking Blaze

### ISSUE THREAD

**Issue by tjsd** [FTBTeam/FTB-Interactions#500]
## Modpack Version: 
v1.4.1

## Bug Report:
Everytime someone melee a blaze in the nether the server crashes, might be related to the "fix" with blazes not exploding anymore.

## Expected Behavior/Suggestions:
No server crash while fighting blaze

## Is It Repeatable? Steps to Reproduce: 
1. Go to nether
2. Find blaze
3. Fight blaze with something (bow/sword)
4. Server crash!

## Link to Log or Crash File Paste**: 
https://termbin.com/6q6w
https://termbin.com/9s8b
https://termbin.com/cd9h

## Mod/s Affected: 
Deadly Mobs

## Known Fix: 
Not sure, but Im pretty sure it has something to do with the config change regarding blazes not exploding on kill anymore.

**Comment by Saereth** [comment]
This is actually Rough Mobs 2, we've created a ticket with the mod developer. 
 
additional crashlogs reported from others:
https://termbin.com/9s8b

so it looks like the blaze reflect on attack is bugged and the expolding on death was canceling that event so it was covering up the crash bug
temporary work around is just edit config/roughmobs.cfg and set the line that says 

`S:blazeDeathExplosionStrength=0 
`
to 

`S:blazeDeathExplosionStrength=1`

We will most likely hotfix this tomorrow until we can get a proper fix from the developer.
