### ISSUE TITLE
Removing the Crying Obsidian mod will also remove all its linked mob spawn points

### ISSUE THREAD

**Issue by Neeve01** [FTBTeam/FTB-Interactions#501]
Hi.

The Crying Obsidian mod adds a feature to link entities to an Advanced Crying Obsidian block to make them respawn on it once they die. This applies to any mob including mounts (hippogryphs), potentially saving a lot of situations.

![DB0E1D14-67A7-499B-8E78-8CAB15A2F1B0](https://user-images.githubusercontent.com/22255622/56770618-2f0a3e80-6800-11e9-82d5-98f67d00ba7c.jpeg)

Would it be possible to keep this feature? Or, by a chance, replace it with another mod?

Thanks.

**Comment by Saereth** [comment]
Seeing as the mod is only a single block and fulfills a need no other mod in the pack provides I think we can keep it. In fact I'll leave this open for now to remind me to create a quest explaining this functionality as I didn't even know about it.

**Comment by Vyraal1** [comment]
Works for me, agreed as well.
