### ISSUE TITLE
Botania Mana Enchanter Doesn't Use Apotheosis Tomes

### ISSUE THREAD

**Issue by Numorphan** [FTBTeam/FTB-Interactions#502]
## Modpack Version: 
1.4.1

## Bug Report:
When using an Apotheosis tome (of Helmets, Weapons, etc) in the Botania mana enchanter, the mana enchanter will ignore the tome and not apply the enchant to the central item.

## Expected Behavior/Suggestions:
The mana enchanter should treat the tome as a regular enchanted book.

## Is It Repeatable? Steps to Reproduce: 
1. Place any number of apotheosis tomes (of the right type) in the mana enchanter.
2. Activate the mana enchanter.
3. Nothing happens.
4. Add a regular book.
5. Activate it.
6. The regular book's first enchant will be applied, with all the tome's enchants ignored.

## Mod/s Affected: 
Botania
Apotheosis

## Known Fix: 
Not a fix, but a workaround that *should* work (not progressed enough to test it): You should be able to enchant an item with the tome, then use the Ritual of Unmaking to put it back on a regular book and then use it that way. This is gated behind space however, as you need T3 Blood Magic, whereas the mana enchanter is earlier. It also seems like a pain to do.

**Comment by Saereth** [comment]
this is not really the place you wanna create this sort of an issue, it'll be a feature request to either botania or apotheosis.There is nothing we can do packwise to address this
