### ISSUE TITLE
Satchel^3 giving wrong enchantment.

### ISSUE THREAD

**Issue by KelpTheShark** [FTBTeam/FTB-Interactions#503]
## Modpack Version: 
1.3.0

## Bug Report:
Combining 5 basic satchels gave me a satchel with Insight IV instead of Holding IV. Quest did not complete.

## Expected Behavior/Suggestions:
The Quest for 'Satchel^3 says to combine five basic satchels to create a satchel with the enchantment Holding IV. I combined five basic satchels and got a satchel with the enchantment Insight IV.

For me, hovering over the enchanted satchel listed in the quest also shows it having Insight IV.

**Comment by KelpTheShark** [comment]
![proof](https://user-images.githubusercontent.com/32068665/56789688-b5eaf700-67bf-11e9-8aa6-397a9a9a1ff9.png)

**Comment by Saereth** [comment]
duplicate https://github.com/FTBTeam/FTB-Interactions/issues/406
