### ISSUE TITLE
Possible Typo in recipe for electric pumps

### ISSUE THREAD

**Issue by MatthewCOwen** [FTBTeam/FTB-Interactions#504]
## Modpack Version: 
1.4.1

## Bug Report:
Assembling Machine recipes for the electric pumps (item) require 628mb worth of the respective metal. 628 does not factor nicely from 144. The lcm of the two numbers is 157, meaning that if you wanted to automate making any electric pump in the assembler, you'd need to make 36 pumps (157 ingots worth of metal) just to avoid having to break the machine or plunger the input tank.

If you change 628 to 648, the math works out much more nicely as 648mb works out to 4.5 ingots of material.
![2019-04-26_10 29 31](https://user-images.githubusercontent.com/16054364/56825516-320c2b80-680e-11e9-9ea9-3cf3caeba814.png)

**Comment by Vyraal1** [comment]
Seems like a fine enhancement to me, all it does is really remove the soldering alloy requirement from the rotors that go into pumps. I guess that's why I had the math wrong earlier.
