### ISSUE TITLE
Pump cover with fluid filter extracts nothing.

### ISSUE THREAD

**Issue by Turmfalke2** [FTBTeam/FTB-Interactions#505]
hi,
Without the filter the fluid pump extracts everything, if I insert and configure the fluid filter it extracts nothing.  

![2019-04-27_11 54 44](https://user-images.githubusercontent.com/5174562/56848113-23447800-68e5-11e9-9744-b85d6d3e8258.png)

I would expect it to either extract the oxygen or the nydrogen. Depending on whether the filter is white or black list. Finding any documentation on how this particular version of gregtech is supposed to work is nigh impossible, in any case extracting nothing seems wrong.

Modpack version:
1.3.0

**Comment by SuperSandro2000** [comment]
FYI the current version is 1.4.1 if I am not mistaken.
You should try replicating it in there first.

**Comment by AmishInvader** [comment]
Use a screwdriver on a machine side to specify what tank it interacts with, otherwise, I think it only checks tank 0, then moves to 1 when that's empty.

**Comment by Turmfalke2** [comment]
Found it.
Turns out even 1.4.1 is using an oudated version of gergtech that is appearently bugged regarding fluid pumps covers.
From the 1.7.1 changelog ( https://minecraft.curseforge.com/projects/gregtechce/files/2704359 ):

* Remove output tank index filter mechanic (replaced by fluid filters for more precise control)
* Fixed fluid filter upgrade in pump not working properly.

Do you see anything that would break the pack if I were to update gregtech? There is 

* Fix certain ore deposits not generating.

But I have no idea what those certain ore deposits would be, is the oregen in this pack handled by gregtech?

**Comment by SuperSandro2000** [comment]
Just give it a try and do a backup before hand.
If there are no issues it probably gets updated in the next week with 1.4.2.

**Comment by Turmfalke2** [comment]
crashes with shadows of greg.

**Comment by Vyraal1** [comment]
> Turns out even 1.4.1 is using an oudated version of gergtech that is appearently bugged regarding fluid pumps covers.

Yes, I deeply apologize that we couldn't get an up-to-date version of gregtech that only came out 2 days ago on our WEEKLY update schedule.

Regardless, this might stuck around for a  bit longer, we're usually careful to update GTCE slower than other mods due to its importance to the pack and mod author's previous update behavior.

**Comment by Turmfalke2** [comment]
Apology accepted, I found a workaround with about twice as many pipes and the screwdriver tank filter.
