### ISSUE TITLE
Space Raced Quest issue

### ISSUE THREAD

**Issue by MBacon15** [FTBTeam/FTB-Interactions#509]
## Modpack Version: 
1.3.0

## Bug Report:
Space Raced Quest cannot be completed

## Expected Behavior/Suggestions:

Going to space (Dimension -2) via space station does not trip the quest

As shown below, NBT for the quest looks for Dimension 3 instead of Dimension -2

## Is It Repeatable? Steps to Reproduce: 

[Album outlining issue](https://imgur.com/a/qt6pR5v)

## Link to Log or Crash File Paste**: 
No Crash

**Comment by SuperSandro2000** [comment]
Did you test it in 1.4.1?

**Comment by MBacon15** [comment]
No, we're on 1.3.0 and I didn't see the issue addressed in the change logs for 1.4.0 or 1.4.1. I can check when our server updates

**Comment by MBacon15** [comment]
Same issue persists in 1.4.1

**Comment by SuperSandro2000** [comment]
I am asking about 1.4.1 cause even if the issue is not mentioned in the changelog it could be fixed anyway.

**Comment by Vyraal1** [comment]
Long story short, there is a difference between ID and Dimension Type ID. The ID is really -2, and seems like FTBQ might be using the DimensionType ID.

https://gist.github.com/Vyraal1/25bf9a59ef545ece6d50d634526e0539

**Comment by Vyraal1** [comment]
Lame fix until update happens or I get clarification from Latvian, going to make it a checkmark quest. Either way the dimension staging still works properly anyways.

![image](https://user-images.githubusercontent.com/26587049/57021874-6bbca800-6bfb-11e9-9b76-860153f7a3be.png)
