### ISSUE TITLE
add a daily repeatable quest to replace the tome of knowledge

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#51]
Submitter: `Saereth#7836`
Body: `OwO issue "add a daily repeatable quest to replace the tome of knowledge"`
Attachments:

**Comment by Vyraal1** [comment]
No way to make it daily, repeatable seems a bit too abusable with EMC. Made it just one more backup as a checkmark quest instead, and beyond that I'm not so sure if we should try too hard to fix stupid.

**Comment by TeamDman** [comment]
Could probably set the tomes emc to 1 and have it repeatable
