### ISSUE TITLE
can veinmine copperGem gems

### ISSUE THREAD

**Issue by Rdjrjqouqcu** [FTBTeam/FTB-Interactions#511]
## Modpack Version: 
1.4.1

## Bug Report:
You can veinmine all three types of gems in copperGem veins.
Jasper Ore, Topaz Ore, and Red Garnet Ore

Also not sure if it's intentional but you can smelt Jasper ore directly into Jasper and Topaz Ore directly into Topaz.

**Comment by Vyraal1** [comment]
These ores were disabled previously before we added in creation of the copper gem vein, thanks for the bug report. They will be properly incorporated into the Metallurgy process in next update and blacklisted.
