### ISSUE TITLE
Beacons can be pulverized to Nether Star Dust

### ISSUE THREAD

**Issue by iComputerfreak** [FTBTeam/FTB-Interactions#514]
## Modpack Version: 
1.3.0

## Bug Report:
Beacons can be pulverized and yield a Nether Star Dust, although they don't require a Nether Star to craft.

## Expected Behavior/Suggestions:
Beacons should probably pulverize into components more fitting to the crafting recipe.

## Known Fix: 
Remove the Pulverization recipe of the beacon or change it to something else.

**Comment by Vyraal1** [comment]
Made it glass dust, mana powder, and diamond dust, so essentially its components.
