### ISSUE TITLE
Picking oxygen up with a bucket gives an Adv. Rocketry Tank of Oxygen

### ISSUE THREAD

**Issue by merphle** [FTBTeam/FTB-Interactions#515]
## Modpack Version: 
1.4.1

## Bug Report:
Picking oxygen up with a bucket gives an Advanced Rocketry Tank of Oxygen

## Expected Behavior/Suggestions:
Should receive the original bucket filled with oxygen.

## Is It Repeatable? Steps to Reproduce: 
1. Fill a bucket with oxygen from any machine (or cheat it in).
2. Place the oxygen in-world from the bucket.
3. Pick up the oxygen with the bucket.
4. Receive instead an Advanced Rocketry "Tank of Oxygen".

**Comment by ggkhs** [comment]
This is also happening in 1.4.2 version of the pack in Singleplayer and Multiplayer worlds with Nitrogen.

The bucket gets converted to nitrogen tank when it is filled from Nitrogen placed in the world.

Video Evidence of the bug happening in Multiplayer World :

[https://www.youtube.com/watch?v=teo0C7-ClcE](url)

**Comment by Saereth** [comment]
This needs an issue created over at AR's github https://github.com/zmaster587/AdvancedRocketry/issues
