### ISSUE TITLE
Menril wood not giving 100mb of Creosote Oil since ore dict change to Menril Wood.

### ISSUE THREAD

**Issue by KaneHart** [FTBTeam/FTB-Interactions#516]
## Modpack Version: 
1.4.1

## Bug Report:
Menril wood not giving 100mb of Creosote Oil since ore dict change to Menril Wood.
Gives 50mb's as it seems to conflict and use the first recipe.

## Expected Behavior/Suggestions:
Should give 100mb of creo.

**Comment by Vyraal1** [comment]
Hm this one is a bit awkward. Since technically Menril logs also need logWood so it can be used in other basic crafting recipes like for apiaries and or in GTCE Pyrolyse Oven. Will probably end up making special case recipes for all logWood occurences for Menril.

**Comment by Vyraal1** [comment]
Going to stay as logWood and the bonus doesn't really mean anything. Going to revert it back to 50mb of creosote.
