### ISSUE TITLE
Chemical Reactor produces Liquid Oxygen instead of Polyethylene

### ISSUE THREAD

**Issue by Neeve01** [FTBTeam/FTB-Interactions#518]
## Modpack Version: 
1.4.1

## Bug Report:
Putting Titanium Tetrachloride, Ethylene and Oxygen into a reactor with circuit set to 1 first produces some Polyethylene, then starts producing Liquid Oxygen only, despite having the correct recipe for Polyethylene.

## Expected Behavior/Suggestions:
It should produce Polyethylene, duh.

## Is It Repeatable? Steps to Reproduce: 
1. Pour Titanium, Ethylene and Oxygen into a Chemical Reactor
2. Insert a circuit set to 1
3. Get some Polyethylene
4. Get an absurd amount of Liquid Oxygen until there’s no oxygen left

## Mod/s Affected: 
GTCE, Mekanism and CraftTweaker.

## Known Fix: 
Liquid Oxygen should have its own configuration ID which wouldn’t intersect with GT recipes.

Thank you.

**Comment by Vyraal1** [comment]
#mekanism hydrogen and oxygen
chemReactor.recipeBuilder()
	.fluidInputs([<liquid:oxygen> * 1000])
	.fluidOutputs([<liquid:liquidoxygen> * 1000])
	.property("circuit", 5)
    .duration(20)
    .EUt(28)
    .buildAndRegister();

chemReactor.recipeBuilder()
	.fluidInputs([<liquid:hydrogen> * 1000])
	.fluidOutputs([<liquid:liquidhydrogen> * 1000])
	.property("circuit", 5)
    .duration(20)
    .EUt(28)
    .buildAndRegister();

fixed
