### ISSUE TITLE
Guideance quest page

### ISSUE THREAD

**Issue by Torrenal** [FTBTeam/FTB-Interactions#520]
## Modpack Version: 
FTB Interactions 1.2.1

## Bug Report:
The existing quests can at times be overwhelming and for a player unfamiliar with some or many of the modpacks the player may have difficulty identifying a path forward.

## Expected Behavior/Suggestions:
Suggestion:
Create a 'high level' view of the quests, or high level progression map.
EG:
Create a quest tab (or update the existing 'Gods Plan' quests) to guide the player through the A then B type dependencies at a high level, and to express broad goals that will meet those dependencies.

Specific examples:
* Visiting the nether requires steel (to make Thaumium), which requires access to the overworld (to obtain iron).  You'll also need flawed quartzite, which I believe requires steam power (Steam Forge Hammer).  Express these as Overworld -> steel -> Nether and Overworld -> Steam Age -> Nether

* Visting space requires unlokcing the MV age, finding a source of aluminum, obtaining chlorine... possibly a few other either broadly scattered or landmark goals.  Express these as all dependencies on the space age.

The point here isn't to give the user more super detailed quests (those exist already, and I'm drowning in them).  It's to express longer term goals than 'craft next item FOO' that are smaller scope than 'win the game', and present them to the user in a hierarchy they can actually follow without getting lost in all the fine print.  This will server to break the content down into manageable chunks for the player, and at the same time provide hints to 'things to try next'.

## Is It Repeatable? Steps to Reproduce: 
N/A

## Link to Log or Crash File Paste**: 
N/A

## Mod/s Affected: 
FTB Quests

## Known Fix: 
N/A

**Comment by Saereth** [comment]
added a progression guide to the book
