### ISSUE TITLE
Allow more Orientations for Modular Machines

### ISSUE THREAD

**Issue by Kanzuke117** [FTBTeam/FTB-Interactions#522]
The Gregtech Multiblocks are great in their handling of input and outputs blocks, making it easy to define positions where any hatches or busses are allowed, and then requiring a minimum number of input slots or volume in order for the multiblock to form. This allows players to customise their machines while still keeping a helpful recipe which shows the default number of inputs and outputs.

Currently for Modular Machines like the Improved Coke Oven, the Fluid Output must always be to the right, Input always to the left, and Item Output always behind the controller, exactly matching the blueprint, and leaving no room to swap output sides or otherwise reorient the machine. Although not as advanced a system as GTCE's, machine blueprints can be cahnged to accept a list of possible blocks for each position, like so:
```javascript
"elements": [
	"modularmachinery:blockfluidoutputhatch"
]
``` 
Changed to:
```javascript
"elements": [
	"modularmachinery:blockfluidoutputhatch",
	"modularmachinery:blockinputbus",
	"modularmachinery:blockoutputbus"
]
```
Once applied to all three positions, players can then freely swap input and outputs, but with the caveat of a much less user friendly blueprint:

!["Gif!"](https://thumbs.gfycat.com/ShadowyPlasticKrill-size_restricted.gif)

Perhaps this could be remedied in the quest book or with a tooltip on the blueprint to clarify you need one of each? I personally will be using the modified recipe as it allows me to have symmetrical towers of coke ovens without making the piping required a gargantuan mess.

Modified recipe: (needs to be renamed from .txt to .json because github has an upload whitelist) 
[ImprovedCokeOven.txt](https://github.com/FTBTeam/FTB-Interactions/files/3128056/ImprovedCokeOven.txt)

**Comment by tyler489** [comment]
YES PLEASE ... also if u could make the controller change positions to that would be great...

**Comment by Vyraal1** [comment]
Unfortunately controller cannot change positions as everything MM looks at is relative to the controller. Can look into making the outputs all modular, people should hopefully be smart enough to realize they'll need an output block despite valid multiblock.
