### ISSUE TITLE
Failure to complete first-time initialization

### ISSUE THREAD

**Issue by sadoskik** [FTBTeam/FTB-Interactions#523]
## Modpack Version: 
1.3.0
## Bug Report:
Failure to initialize the modpack on first run. It runs through 7 broad 'steps' and on 6/7 it starts eating up to 98% processor and periodically hangs on 'Not responding'. This I have noticed begins when it starts editing the Model Manager.

## Expected Behavior/Suggestions:
The modpack should run through an initial setup process on the first run, then launch relatively quickly on subsequent launches. 

## Is It Repeatable? Steps to Reproduce: 
From the Twitch application, I choose the 'FTB Interations' modpack. After downloading the necessary files, I am able to select a 'Play' option. Here it brings up a classic Minecraft Launcher where I can choose the appropriate profile (FTB interactions plus some version numbering). After clicking the green launch button, I am brought to a loading screen with three progress bars and an animated cat. It gets through the first ~6 steps with relative ease but start struggling though the finishing up phase.

The modded version of Minecraft is installed under ~userDirectory/Twitch/Minecraft/Instances/

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/e3d2c22d

## Mod/s Affected: 
[Unconfirmed] Model Manager

**Comment by Hubry** [comment]
>`Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded`

>`Memory: 377225424 bytes (359 MB) / 3008888832 bytes (2869 MB) up to 3008888832 bytes (2869 MB)`
Give the game more memory, the pack description recommends at least 4 GB while you have around 3 allocated.

**Comment by sadoskik** [comment]
Changing my Twitch settings (and confirming the change reflected in the Launcher profile settings) to be above 4GB (but within the limits of my host) doesn't seem to change the GUI's displayed memory allowance (around 3600MB). Is there another place where I need to set it to use more?

**Comment by sadoskik** [comment]
UPDATE: I changed it now to 6079MB max allowance and now the GUI is reflecting that it can now use 5399MB. Will update on if this initialization works

**Comment by Vyraal1** [comment]
Does it work?

**Comment by sadoskik** [comment]
Yes. Increasing the allotted RAM fixed it though i guess the long loading time comes each time.

**Comment by Vyraal1** [comment]
Unfortunately that's just the nature of modded minecraft considering the size the pack. Glad to hear it works now.
