### ISSUE TITLE
Broken Chickens?

### ISSUE THREAD

**Issue by tyler489** [FTBTeam/FTB-Interactions#524]
## Modpack Version: 
1.4.1

## Bug Report:
Alot of chickens produce items that cannot be used in ANY way
- [x] Platinum clumps Can't Be Pulverized
- [ ] Zinc Clump Can't Be Pulverized
- [ ] Calcum Clump Can't Be Pulverized
- [ ] Scheelite Clumps Can't Be Pulverized
- [ ] Cobalt Clumps Can't Be Pulverized

- [x] Grossular enriched eggs have no use
- [ ] Magnesium Enriched Eggs have no use
- [ ] Spessartine Enriched Eggs have no use
- [ ] Soapstone Enriched Eggs have no use
- [ ] Stibnite Enriched Egg Have no use
- [ ] Phosphor Enriched Egg Have no use
- [ ] Tantalum Enriched Egg Have no use
- [ ] Manganese Enriched Egg Have no use
- [ ] Bentonite Enriched Egg Have no use
- [ ] Sulfur Enriched Egg Have no use
- [ ] Monazite Enriched Egg Have no use
- [ ] Graphite Enriched Egg Have no use
- [ ] Tanzanite Enriched Egg Have no use
- [ ] Glauconite Enriched Egg Have no use
- [ ] Osmium Enriched Egg Have no use

- [ ] Silicon Chickens Lay machine chassis?"
- [ ] Enderium Chickens Lay Nuggets

## Expected Behavior/Suggestions:
Considering the Custom recipies for said chickens i would they they should have a use

## Is It Repeatable? Steps to Reproduce: 
 Press U on a chicken egg
press U on the Byproduct
Keep Pressing U untill either u get to pulverzed ore or it stops

## Link to Log or Crash File Paste**: 
N/A
## Mod/s Affected: 
Chickens/MoreChickens
## Known Fix: 
Do more Crafttweaker work ;p

**Comment by Saereth** [comment]
im just gonna go ahead and close this since im majorly redoing chickens place in the pack
