### ISSUE TITLE
A Suggestion

### ISSUE THREAD

**Issue by tyler489** [FTBTeam/FTB-Interactions#525]
## Modpack Version: 
1.4.1
Add an Easier Way to obtain Debarked Wood for builders that would like to use it in Large Quanitys

Also IronWood Debarked Wood 
and Olive Debarked Wood are unobtainible

**Comment by Vyraal1** [comment]
Open to this, just need to think of a machine. Tempted to make a troll recipe with the Precision Laser Engraver.

**Comment by tyler489** [comment]
I believe @Saereth  said a chisel group would be an option and also not expensive

**Comment by Vyraal1** [comment]
Chisel group would be awkward, since that would just get around the early hunger progression since Chisels also have EMC. Can do artisan worktables with an axe (versus saws to make planks) or the early game, later on automation will require another machine.

**Comment by Torrenal** [comment]
As a suggestion (if possible) feed a cutting saw a different liquid to signal debarking?  Say water?
While it may not entirely make sense, in the real world, high pressure water can be used to debark logs.
That would leave the non-hunger recipe locked until LV tech

**Comment by Vyraal1** [comment]
I'm dumb and you're smart. Totally forgot that since we removed the log crafting recipe, there isn't any water based recipes to turn logs to planks. This should work.

**Comment by tyler489** [comment]
Will debarked ironwood and debarked olive wood also be obtainable
