### ISSUE TITLE
can't download FTB interactions 

### ISSUE THREAD

**Issue by 1java** [FTBTeam/FTB-Interactions#527]
## Modpack Version: 
 FTBInteractions-1.4.2

## Bug Report:

i mean i think i should be able to download it
## Is It Repeatable? Steps to Reproduce: 

1. as i said when ever i try to download it it times out
2. and it keeps happening
![ftb interactions](https://user-images.githubusercontent.com/49294887/56937050-153d6400-6b3e-11e9-9cba-fa341174cc2f.PNG)

**Comment by 1java** [comment]
i know its kind of a useless issue report but its the best i could do with the issue i am having...im not a very technical person and i am just looking for a for some insight into this issue

**Comment by Vyraal1** [comment]
How are you downloading it

**Comment by 1java** [comment]
im downloading thru the twitch launcher

**Comment by 1java** [comment]
i just dont know why i cant get the pack

**Comment by Vyraal1** [comment]
Not really sure without any more relevant information. Maybe you country is blocking it, maybe try using another launcher, maybe check if there is a firewall or antivirus. But I can download the pack just fine on two different computers, and didn't see others having issues.
