### ISSUE TITLE
Copper Veins don't have Malachite

### ISSUE THREAD

**Issue by hyodocraft** [FTBTeam/FTB-Interactions#529]
## Modpack Version: 
1.4.2

## Bug Report:
The quest for Copper Veins includes Malachite, but the actual veins don't.

![image](https://user-images.githubusercontent.com/48426079/56940787-7ae41d00-6b4b-11e9-81e5-a37feaec4cde.png)
![image](https://user-images.githubusercontent.com/48426079/56940765-4f613280-6b4b-11e9-82fc-04e4231c055f.png)

## Known Fix: 
Remove 'Malachite Ore' task from the quest

**Comment by Vyraal1** [comment]
Jungle veins have additional copper through malachite, similar to the iron jungle veins have different composition.

**Comment by hyodocraft** [comment]
oh I'm sorry for the mistake.
Thank you for the information.
