### ISSUE TITLE
distillation tower giving reduced ethelene from wood gas

### ISSUE THREAD

**Issue by braingkk** [FTBTeam/FTB-Interactions#530]
## Modpack Version: 
1.2.1

Been making wood gas into ethylene using my distillery, and noticed that for all the recipes i could be bothered to look at, the distillation tower gives the same return as distillery on ALL possible outputs. however for some reason the ethylene from wood gas in distillation tower gives 20 instead of the 200 from standard methods.

## Expected Behavior/Suggestions:
The purpose of the distillation tower is to get ALL of the possible outputs from distilling a liquid as their normal output volumes

## Is It Repeatable? Steps to Reproduce: 
look in JEI ethylene recipes
1. https://puu.sh/DlZtB/84de39540a.png
2. https://puu.sh/DlZtZ/ebab763b8d.png

## Known Fix: 
likely a missing zero somewhere in the config

**Comment by Vyraal1** [comment]
Didn't alter any of the distillation tower recipes, this is either an issue with Shadows of Greg or GTCE. Will override with a script in the meantime.

**Comment by Vyraal1** [comment]
good news: fixed in next update
bad news: it was never meant to be that good, the correct amount is 20mb in both recipes.
