### ISSUE TITLE
Porcelain faucet can not be cooked without furnace.  in  Apparently at some point you changed the recipe from porcelain ingots to raw.  It should cook in the clay kiln. 

### ISSUE THREAD

**Issue by Urban-Redneck** [FTBTeam/FTB-Interactions#532]
Porcelain faucet can not be cooked without furnace. 

## Modpack Version: 
14.23.5.2836 and some prior

## Bug Report:
Crafting the faucet as usual with 3 raw porcelain the unfired faucet can not be cooked in the clay kiln.  I tried creating a new world and upgrading to the latest beta without change.

## Expected Behavior/Suggestions:
It should cook and become usable.

## Is It Repeatable? Steps to Reproduce: 

1.  Create a faucet 
2.  Put in Clay Kiln and wait (forever)

## Known Fix: 
Use a vanilla furnace.  I found one in the overworld and it works great.

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/57004152-84e13c80-6b9a-11e9-9df8-aba76b34713a.png)
