### ISSUE TITLE
Nitrogen Dioxide conflict Liquid Oxygen

### ISSUE THREAD

**Issue by krakel** [FTBTeam/FTB-Interactions#534]
## Modpack Version: 
1.4.0

## Bug Report:
at the Chemical Reactor the 2 recipes conflict
1. Circuit 1 + Nitrogen + Oxygen -> Nitrogen Dioxide (30 EU/t)
2. Circuit 1 + Oxygen -> Liquid Oxygen (28 EU/t)

## Expected Behavior/Suggestions:
change one recipe to a other Programmed Circuit Nr

## Is It Repeatable? Steps to Reproduce: 
I got on different machines different results

**Comment by krakel** [comment]
recipe 2 starts with 1 bucket Oxygen, recipe 2 starts with 2 buckets Oxygen, so you get both result on less Oxygen filling

**Comment by Vyraal1** [comment]
Moved to circuit #5 in dev.
