### ISSUE TITLE
GT brewery crashes on brewing non-vanilla potions

### ISSUE THREAD

**Issue by DrTasslehoff** [FTBTeam/FTB-Interactions#535]
## Modpack Version: 
1.4.1

## Bug Report:
Trying to brew potions in the GT brewery works fine and creates fluid variants of all of the normal minecraft potions. For anything else it just immediately crashes if you put an ingredient that will create a different potion

## Is It Repeatable? Steps to Reproduce: 
Put awkward potion fluid in first slot, and any other secondary that would create a non-vanilla potion (such bottle o' enchanting for ancient knowledge potions) and the game crashes. 
 

## Link to Log or Crash File Paste**: 
https://pastebin.com/44b5LFGJ

**Comment by Saereth** [comment]
reported to gtce
