### ISSUE TITLE
Wrong fluid as "Explosive!" quest reward

### ISSUE THREAD

**Issue by tasosalvas** [FTBTeam/FTB-Interactions#538]
## Modpack Version: 
1.3.0

## Bug Report:
The quest requires GT Rocket fuel, but rewards a cell of the uncraftable Advanced Rocketry kind.
EDIT: Oh also there are two quests for cryogenic gases, one requiring buckets and one unlinked to anything that wants cells.

## Known Fix: 
I plan to build a marble shrine on the moon and store the impossible cell there.

**Comment by Vyraal1** [comment]
Should give correct rocket fuel cell now, the other quest was removed as of 1.4.0 if I recall correctly.

**Comment by tasosalvas** [comment]
Just got 1.4.2 through the ftb launcher, the duplicate quests are still there. "H2 4u2", and "O2 H2 Cold4u", in the space tab.

**Comment by Vyraal1** [comment]
Hmm How are you updating the pack?

![image](https://user-images.githubusercontent.com/26587049/57115597-d6fe9b00-6d1d-11e9-9a39-61eeab0f1afa.png)

![image](https://user-images.githubusercontent.com/26587049/57115603-dfef6c80-6d1d-11e9-987b-b394bef17ab0.png)

It's now showing up for me so now I'm thinking there might be issues with updating.

**Comment by tasosalvas** [comment]
I'm using the FTB Launcher on Linux. Haven't customized anything, and I'm upgrading to recommended whenever u guys release, leaving "backup saves" and "backup configuration" unchecked.

It does seem my questbook is a bit out of whack in general after this upgrade, in previous ones I could get changed quests completed and be back on course, but this time my space tab has a few with checkmarks on both rewards and requirements that still appear as incomplete and block further progress. The selected "Cold4u" mystery quest displays this behavior in the screenshot.

Also seen in the screenshot:
"Foundations of Flight" is overlapping with "Clone Space".
"I'm Givin' Her All She's Got, Captain!" overlaps with "I'm bulletproof, nothing to lose, fire away, fire away" v2 In Space".

Welp on the good side, I think I might be in a position to cheese building a space station without triggering enemy progression ;)

Dang, all's I wanted was to contribute and now it seems I actually need teh support, too. I'll be happy to provide any feedback you need.
![2019-05-03_12 33 22](https://user-images.githubusercontent.com/245478/57131459-16bc9580-6da5-11e9-9b4e-67337bd169ff.png)
