### ISSUE TITLE
Disconnect on server while doing random activities

### ISSUE THREAD

**Issue by bushw00kie009** [FTBTeam/FTB-Interactions#539]
## Modpack Version: 
1.2.1 & 1.4.1

## Bug Report:
 When playing on a multiplayer server, several of us (3) will be disconnected while simply standing around or putting/removing machines or relocating items in chests. When this happens we receive:
![image](https://user-images.githubusercontent.com/50179201/57031330-18535580-6c0d-11e9-8997-54d36e4344e9.png)
 Then we wait for several seconds to several minutes before rejoining and depending on when we are able to re-enter we receive this message: 
![image](https://user-images.githubusercontent.com/50179201/57031421-4fc20200-6c0d-11e9-90db-3d327e2df8fb.png)
 Then we have to wait until the player has completely disconnected from the server even though we are technically not there. Its almost like our ghost is still standing around. Once the character/toon disconnects then we rejoin. Only issue is upon rejoining we receive the first image again followed by the second one shortly after. The server owner is rolling it back to 1.3.0 to see if this fixes the issue but highly doubtful that this does fix the issue.

**Comment by Vyraal1** [comment]
Strange that this is happening, we specifically added this mod: https://minecraft.curseforge.com/projects/bigger-packets-please
to help alleviate the issues that GTCE has with this historically. Can you get a copy of a log when a player gets kicked from both client and server?

**Comment by bushw00kie009** [comment]
Will get that to you when I get back. Are you wanting all of them? From each person or just one will do?

**Comment by Vyraal1** [comment]
Just one is fine, both at least one from server and one from client, although to be honest I'm not sure if it's going to be anything new/anything we can do about it. It's pretty hard to replicate, and throughout all of testing, we thought recent optimizations in GTCE would've been enough.

**Comment by bushw00kie009** [comment]
Going to hold off on posting anything since I am still waiting for their logs but we are trying to see if its related to the satchels because one of us doesnt have it and seen far less crashes than the other two.
