### ISSUE TITLE
Metallurgy Quests for Aluminium shouldn't recommend an LV Thermal Centrifuge

### ISSUE THREAD

**Issue by Kanzuke117** [FTBTeam/FTB-Interactions#540]
## Modpack Version: 
1.4.1
## Bug Report:
The Aluminium quests are misleading, advising players to use the Thermal Centrifuge for their first aluminium dusts, even though there are no LV recipes for the Thermal Centrifuge

## Expected Behavior/Suggestions:
The LV Sources that should be suggested are Ore Washing Blue/Green Sapphire and Centrifuging Emerald Dust

**Comment by Vyraal1** [comment]
LV Centriuge needs 2A, but can still work in LV for aluminium dust. 
![image](https://user-images.githubusercontent.com/26587049/57039807-a8a09300-6c2b-11e9-933c-27908a23d1c7.png)

Will look into adding additional routes.

**Comment by Kanzuke117** [comment]
Wow I had no idea it could take more than an amp. Maybe add that as a quest description to 'Basic Thermal Centrifuge'?

**Comment by Vyraal1** [comment]
It says it in JEI that it can take amperage of 2, which is why it was left out in quests.
![image](https://user-images.githubusercontent.com/26587049/57040313-05e91400-6c2d-11e9-9a51-126c829233c9.png)
