### ISSUE TITLE
Can't teleport to space station.

### ISSUE THREAD

**Issue by hobnob11** [FTBTeam/FTB-Interactions#541]
## Modpack Version: 

1.4.0
## Bug Report:

Can't teleport to space station, I'm on a multiplayer server (not sponge), a friend is standing in the station so the area is loaded properly, I can use /advancedRocketry goto station 2 to manually tepeort there using commands.. but the astral tele doesn't work :/ I can use the tele to go to a bunch of other places including across dimensions to the void world and back for example without issue..
![gif](https://thumbs.gfycat.com/AthleticGoodFlyingfox-size_restricted.gif)
![alt gif link](https://gfycat.com/athleticgoodflyingfox)

## Is It Repeatable? Steps to Reproduce: 

I've tried restarting my game, the server, my friend is able to use the astral teleporter just fine yet it refuses to let me use it.

**Comment by Orichlol** [comment]
You need to unlock space by holding a navigation computer block.

**Comment by Saereth** [comment]
just need to get your gamestage set yeah, as Orichlol said
