### ISSUE TITLE
Default Salis Mundus recipe works even though not in JEI

### ISSUE THREAD

**Issue by Kelmey** [FTBTeam/FTB-Interactions#542]
## Modpack Version: 
1.42

## Bug Report:
Default Salis Mundus recipe works even though not in JEI

## Expected Behavior/Suggestions:
Either the recipe shouldn't work or should show in JEI

## Is It Repeatable? Steps to Reproduce: 
https://cdn.discordapp.com/attachments/560185294842888222/573380671117066240/unknown.png

## Mod/s Affected: 
Thaumcraft

**Comment by Karthas077** [comment]
Thaumcraft's default recipe for Salis Mundus has ALWAYS shown up as an informational dialogue and not an actual recipe. This informational dialogue is still present as usual.

**Comment by Kelmey** [comment]
Oh. Could have sworn they were in JEI/NEI in previous Thaumcraft versions. First time using TC6. 

I guess it isn't an issue then.
