### ISSUE TITLE
Suggestion: Add "Vials" mod to the pack

### ISSUE THREAD

**Issue by Faeliere** [FTBTeam/FTB-Interactions#547]
I added it myself and it works well, haven't had any crashes
It adds bottles of "ingot" capacities like 144mb etc. It would be useful in my opinion
Hot or Not effects still apply

**Comment by Saereth** [comment]
this mod looks ok, we'll have to review capacities/recipes

**Comment by Saereth** [comment]
yeah I played with this for a bit, dont really see a need though, pack is already very heavy unfortunately so adding more even small qol stuff is unlikely
