### ISSUE TITLE
Potentially unintended Tungsten source pre-space

### ISSUE THREAD

**Issue by braingkk** [FTBTeam/FTB-Interactions#551]
## Modpack Version: 
1.4.2

## Bug Report:
By centrifuging lava, you can acquire tungstate, potentially earlier than intended; the questbook puts it past the end in the metallurgy tab.

## Expected Behavior/Suggestions:
If the Questbook placing tungsten post space is correct, the tungstate dust may need to be removed from centrifuging lava. if this IS intended, perhaps the quest should not be gated behind space.

## Is It Repeatable? Steps to Reproduce: 
1. build EV molecular separator
2. centrifuge some lava
3. enjoy your tungsten and tungstensteel before space age

## Known Fix: 
remove tungstate from lava centrifuge recipe, or if intended, maybe put the tungsten dust quest before space as it seems confusing.

**Comment by Saereth** [comment]
this is actually fine, but the quest doesnt need to be before space because frankly you dont need it before space and it doesnt do you a whole bunch of good either. Tungsten is a softgate material, not a hardgate. Nor is the lava centrifuging route the primary route people should take, its woefully inefficient.

**Comment by braingkk** [comment]
> frankly you dont need it before space
so Tungstensteel coils for the EBF which gates enderium and as a result dimensional transcievers [earliest cross dim fluid] is not needed? Tungstensteel boilers for steam powered bases are not needed? i guess i totally misunderstand my power and resource needs.

> Nor is the lava centrifuging route the primary route people should take, its woefully inefficient.

in a pack where plutonium is a 2% drop from centrifuged uranium238, i find it funny that tungstate from lava: an easily automated process is considered 'woefully inefficient'
