### ISSUE TITLE
Astral Sorcery Mantle attunement recipe

### ISSUE THREAD

**Issue by Marzule** [FTBTeam/FTB-Interactions#554]
## Modpack Version: 
1.5

## Bug Report:
I crafted the base mantle of stars from Astral Sorcery, and then went to upgrade it with one of the attunement recipes (I tried Vicio and Armara, specifically, neither worked). The attuned mantle was uncraftable, despite being able to shift click in from JEI. When I cheated in an already attuned mantle, I was able to make the recipe work.

## Expected Behavior/Suggestions:
Base mantle of the stars should be able to be attuned into one of the upgraded versions, or the recipe should be removed if it's not intended.

## Is It Repeatable? Steps to Reproduce: 

1. Create base mantle of stars
2. Place items for recipe for attuned mantle of stars (for example, Vicio)
3. No valid recipe is detected.

## Mod/s Affected: 
Astral Sorcery

## Known Fix: 
Damaging and then repairing the mantle does fix the issue

**Comment by Saereth** [comment]
Those recipes are all stock astral recipes sooo passing onto hellfirepvp then

**Comment by Saereth** [comment]
This should be resolved now that AS is updated
