### ISSUE TITLE
Infused Wood Planks Recipe

### ISSUE THREAD

**Issue by FirstYouDie** [FTBTeam/FTB-Interactions#556]
## Modpack Version: 
1.4.2

## Bug Report:
Infused Wood logs obtained by throwing logs into liquid starlight can be crafted into 4 infused wood planks in the vanilla Minecraft unshaped recipe.

## Expected Behavior/Suggestions:
Making planks should be restricted to using saws like with other logs. It doesn't make sense that this log should be different.

## Is It Repeatable? Steps to Reproduce: 
1. Throw any log into Liquid Starlight
2. The log becomes Infused Wood
3. Put the Infused Wood into any standard crafting table or your own 2x2 inventory crafting and pull out 4 infused wood logs.

## Mod/s Affected: 
Astral Sorcery

**Comment by Saereth** [comment]
you cut them only with starlight now, no vanilla crafting
