### ISSUE TITLE
Gorgon's Gaze and Endermen

### ISSUE THREAD

**Issue by Karthas077** [FTBTeam/FTB-Interactions#557]
## Modpack Version: 
1.5.0

## Bug Report:
Enderman is stone
Transformed by the Gorgon's gaze
Still teleports me

Not sure if it's just a weird interaction or if the mod adding the "teleport on attack" is just being over-zealous, but when a mob has been turned to stone by a gorgon from Ice and Fire, it leaves a statue of the mob which can be picked up. Attempting to do so to the enderman statue teleports the player. Can be gotten around using the recommended method of carrying an enderpearl but feels like that shouldn't be needed since every other mob gets fully disabled.

## Expected Behavior/Suggestions:
Expected behaviour: An enderman which has been turned to stone loses their teleportation abilities just like creepers (which no longer explode).

## Is It Repeatable? Steps to Reproduce: 
1. Kill a Gorgon
2. Use their head to turn an enderman to stone
3. Attempt to pick up the statue
4. Be teleported

## Mod/s Affected: 
Ice and Fire

**Comment by Saereth** [comment]
probably not gonna do anything about this, its a pretty funny interaction, will pass the info on to ice and fire tho
