### ISSUE TITLE
Wrong amount of liquid glass when processing sand in melter.

### ISSUE THREAD

**Issue by MaciejJaromin** [FTBTeam/FTB-Interactions#558]
## Modpack Version: 
1.5.0

## Bug Report:
Melting down sand in the melter (fuelled by lava) produces 1000 mb of liquid glass, which is equivalent to a bit over 6 blocks of glass.

## Expected Behavior/Suggestions:
Melting down sand in the melter should produce 144 mb of liquid glass.

## Is It Repeatable? Steps to Reproduce: 

1. Make a porcelain melter and fuel it with lava.
2. Insert sand.

## Haiku (for bonus points):
Sand in the melter
Makes one thousand em bee glass
Should be one four four

**Comment by rxiv** [comment]
Believe it gets worse, melting sand gives ~6 tinkers clear glass. Each clear glass put in the melter melts down to ~6 additional glass blocks.

**Comment by Vyraal1** [comment]
Turns out another mod is adding the glass recipe, trying to figure out what might be causing it right now.

**Comment by noobnoobnub** [comment]
Destabilized redstone also have wrong ratio. Signalum and flux need 1000 mb while one redstone produce only 144 mb
