### ISSUE TITLE
couple progression issues/bugs/suggestions

### ISSUE THREAD

**Issue by algul** [FTBTeam/FTB-Interactions#559]
## Modpack Version: 
1.5.0

## Bug Report:
1. Dandelifeon is suggested as early mana generation, but it requires magenta petals, Those petals seems to be only obtainable as a quest reward for ethanol bucket( hardly early game imo). Jaded amaranthus requires magenta petals to craft and artisan worktable recipe require any magenta flower from plants mod and they don't spawn naturally afaik.

2. Weak blood orb require fengarum gem from astral sorcery, but the type you get is random. I actually got it on my 11th try.  I would suggest any astral gem should be usable.

3. Dungeon loot schematics could use better description on where exactly are they obtainable, I spent way too much time exploring overworld dungeons before I realized that some are from different dimensions. 

4. Furnace should be craftable, no village I found had blacksmith and they spawn quite rarely, I actually had to loot it from a igloo. Too much of a hassle for something so small.

5. Gas and diesel turbine quest description could mention what are valid fuels and their value, I didn't find any information for the community edition and i'm not sure if any gt5/6 info is applicable for community edition.

6. Basic electronic circuit is not craftable in bronze age or LV age as it require MV laser.

7. It seem that the different stage triggers didn't work for me after visiting ow/nether. Haven't seen any of the stronger mobs. In fact is quite easy to survive in ow. Is there a command I could force those stages just to be sure?

**Comment by FirstYouDie** [comment]
With regards to the furnace issue, the seared furnace works well as an early-game smelting apparatus. It is a good-sized resource hurdle to make the whole multiblock, but that hurdle is consistent with the difficulty of the pack.

**Comment by Karthas077** [comment]
1 - Magenta petals can be crafted almost as soon as you explore the Overworld. I know I didn't use any ethanol when I made mine.
2 - Astral gems aren't exactly expensive to make? Just a tiny bit time consuming? And once you have the first blood orb you should be fine.
3 - Agreed here.
4 - Prioritize getting yourself an Ice and Fire hippogryph with the rabbits feet from the ground traps it recommends you make. Makes overworld exploration laughably easy.
5 - JEI has a fuel production panel, but I agree it's tricky to find. Maybe a description suggesting to check the JEI uses of diesel and natural gas to find the alternatives?
6 - True, but it's an alternative LV age component for once you get good production/automation going
7 - No clue.

**Comment by algul** [comment]
> 1 ... 

 Ok found it. I forgot that plant balls can be used on grass to spawn plants.
> 2 ...

 I disagree somewhat. Rockcrystals are kinda tedious to get to just throw away. It just feels wrong even considering the packs over-all difficulty. 
> 4 ...

 I didn't even know that was an option. I'm not familiar with ice and fire, but I did noticed the hippogryph armors in jei. I just assumed that it has been disabled. Well, too late now:)
> 5 ...

 I have no idea how I missed that. I'm 99% sure that when I checked uses for gasses in jei the fuel production panels didn't show up.

**Comment by Saereth** [comment]
1. invalid
2. invalid
3. - dungeon loot schematics are already listed on the dimension tab in the questbook where you're told to get them
![image](https://user-images.githubusercontent.com/9200909/57317641-9361b380-70c6-11e9-891a-309adc64bedf.png)

4. invalid, we dont want people using vanilla furnaces, if people loot some they're mostly a trophy absolutely not intended as part of your progression and we'll do nothing to support it as such

5. check fuel uses, its all in jei, we can only do so much hand holding here and jei usage is kinda one of those things people are gonna just have to learn. A quest tip on the diesel gens in ayo technology is fine tho I'll add it in.

6. yeah you make integrated logic circuits till then, 

7. /gamestage add playername stagename
valid stages are:
moboverworld
mobbronze
mobnether
mobspace

**Comment by gattsuru** [comment]
The Fuel Production panel is somewhat confusing because it doesn't count as a (U)se for all engines, only the large boilers.  For diesel, gas, and plasma, you have to start from liquid and then you can see the production recipes, and even then the use of varying amounts of material per recipe leave a lot of room for confusion.

Additionally, beyond the limited documentation available for GregTech non-Boiler power to start with on the internet, the changes to fuel processing dramatically change how early Diesel and Gas generation can be useful.  That processing chain makes sense in the All Good Titles Argon page (if perhaps a little confusing), but having a strip of progression on Ayo under Diesel Generation, similar to the Salt-Lithium-More Lithium chain would help encourage people to try using them early, instead of just polishing off completion.

**Comment by algul** [comment]
3. Actually I was referencing the tip on loading screen that suggests dungeon loot schematics. Based on that tip I looked up the blueprints in jei and then went hunting for them. I didn't examine nether quests before I was even considering going there.
