### ISSUE TITLE
EnderIO Cleanup

### ISSUE THREAD

**Issue by Kanzuke117** [FTBTeam/FTB-Interactions#561]
*Silly me, wasting resources before making sure I can make every part*

## Modpack Version: 
1.5.0

## Items that should be hidden from JEI or have their recipes fixed
- Slice'N'Splice (No recipes using it)
- Farming Station/Killer Joe (no z-logic controllers)
- Big Item Filters/Ender Bow (no Skeletal Contractor)
- All Grinding Balls and SAG mill (SAG mill has no recipe)
- Crafter/Lights (no Silicon)
- Cold Fire Igniter/Staff of Levity (no Vat)
- Weather Obelisk (no Vat)
- Rod of Return (no Vat)
- Endergetic/Endergised/Crystalline/Melodic/Stellar/Totemic Capacitors (ingots have no recipes without smeltery)
- Impulse Hopper/Wireless Charging Antenna/*All* of Funky Locomotion (no Industrial Machine Chassis)

Last one there must be unintentional, unless the mod is only usable from dungeon loot or something, so I hope some of the others are. I'd love to use this Weather Obelisk I made :c

**Comment by Saereth** [comment]
the vat fluids are being added in probably update 1.7 to be obtainable via planetary gas mining missions, vat will not be returning but the items will remain. All other issues here addressed in 1.6

**Comment by Kanzuke117** [comment]
Sounds good. I was kind of imagining stuff like maybe Liquid Sunshine could be Sunflower/ ExUtils2 Sun Crystal in a lightwell, Dew of the Void maybe with Pristine Ender Matter in the alchemical infuser, Cloud Seed Concentrated in the vacuum freezer, just as all over the place as possible for maximum *Interactions*

**Comment by Saereth** [comment]
yeah thought about that, but we're pretty much entirely under utilizing gas missions right now so gonna get those added first and if we have futher demand for more access to those we'll readdress then
