### ISSUE TITLE
Placing redstone on GTCE machines corrupts the world

### ISSUE THREAD

**Issue by BunnyHelp** [FTBTeam/FTB-Interactions#562]
## Modpack Version: 
1.5.0 (Beta)

## Bug Report:
Placing redstone dust on top of GTCE's steam machines, like the forge hammer or solar boiler crashes the game and corrupts the world.

## Expected Behavior/Suggestions:
Don't allow redstone dust on top of a machine

## Is It Repeatable? Steps to Reproduce: 

https://youtu.be/T1rcagnFEeE

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/b9fb6ec3

## Mod/s Affected: 

I believe it's just GTCE - may want verification
## Known Fix: 

none

**Comment by tyler489** [comment]
Update GTCE to the version released last week to fix

**Comment by tyler489** [comment]
https://github.com/GregTechCE/GregTech/issues/757

**Comment by Vyraal1** [comment]
Delay on this update, multiple gamebreaking changes in GTCE were made that make this more trouble than it's worth atm.

**Comment by KaneHart** [comment]
Could you explain witch ones? I thought things like the Battery were fixed and we really need to get updating.

**Comment by Saereth** [comment]
Turbine issues, glass issues and a couple other reports we're looking into, needless to say we wont have it stable enough to our satisfaction this round of updates so we'll be looking to get it in next update
