### ISSUE TITLE
Distillation Tower consuming at least 64 times the energy stated in JEI

### ISSUE THREAD

**Issue by MaskedCritic** [FTBTeam/FTB-Interactions#563]
## Modpack Version: 
1.5.0

## Bug Report:
When using a distillation tower, processing Steam-Cracked Refinery Gas is taking at least 64 times more energy than the amount stated in JEI. It also seems to apply to Steam-Cracked Naphtha. I had to hook up two HV Battery Buffers (16 slot versions, both full of sodium large batteries) to get enough energy into the distillation tower. This only applies when the tower has at least one EV Output Hatch.

## Expected Behavior/Suggestions:
Expected: a power consumption of 120EU per tick.

## Is It Repeatable? Steps to Reproduce: 

1. Build a distillation tower using EV Output Hatches. The other parts don't affect it.
2. Attempt to process Steam-Cracked Refinery Gas or Naphtha.
3. Stare befuddled as your power vanishes at a speed similar to attempting to run something on LuV tier EU.

**Comment by Saereth** [comment]
needs an issue opened with gtce

**Comment by Vyraal1** [comment]
What tier of energy input hatch did you use?

**Comment by MaskedCritic** [comment]
It happened with LV, MV, HV, and EV. Input hatch doesn't seem to matter,
only fluid output.

**Comment by Vyraal1** [comment]
Energy input hatch

**Comment by Vyraal1** [comment]
Would you also be able to confirm the multiblock isn't overclocked via the GUI? Like this.

**Comment by MaskedCritic** [comment]
It does say the max EU/t is 4096. I'd have to recheck the lower tier input hatches. The EU usage was still ramped up with all of the hatches, though.

As for reproduction: did you build the tower to be 11 output hatches tall (so 12 blocks tall total)? I forgot to include that in the description, that I only tried it with a Distillation Tower that was 12 blocks tall.

**Comment by Vyraal1** [comment]
It was a 12 block tall tower, so since it is 4096 eu/t, you are overclocking all of the recipes 16x since most of them are MV recipes. 

You need to use MV energy hatches and only one at that, using higher tiered energy input hatches or multiple energy hatches will overclock multiblocks, hence the issue you had.

**Comment by MaskedCritic** [comment]
So, I'm not trying to be condescending, but I know I can seem it when I start talking math, and have no idea how not to seem so. Just a disclaimer.

Doing the math, with the recipe overclocked 16x it would require 1920 EU/t to run it. This is correct, and after switching out the fluid outputs for HV tier instead of EV tier outputs is what I appear to be experiencing based on the power drain. At the same time, I am providing a total of 8192 EU/t at 16 amps with a single HV battery bank. There should be more than enough to run the tower at that output, assuming it will take the amps, although I think the multiblock should only be able to take 2 amps regardless (I could be wrong). In spite of that it still took two battery banks to run the tower, meaning it's being overclocked far more than 16 times. In fact, it would need to be overclocked 68.267 times in order to require more than a single HV battery bank. The 16x overclocking does not account for this discrepancy, nor does it explain why tiering down to an HV energy input did not resolve the issue. It also does not account for the change to HV fluid outputs bringing the required energy back to within the range of a single HV battery bank.

There is still something odd going on with the HV fluid output hatches that's causing the math to be all screwy. I'll do some more reproduction testing tomorrow, because it's really bugging me.

**Comment by MaskedCritic** [comment]
After some extensive testing, I have determined that the only bug here is the _opposite_ of what I thought it was.

1. A battery buffer can only output 1 amp per machine. Because THAT makes perfect sense /sarcasm
2. EV tier distillation towers only seem to overclock 5-8x on an MV tier recipe, rather than the expected 16x.
3. Swapping out the Energy Input Hatch with a lower tier while a recipe is running doesn't seem to change the overclocking amount. Breaking and replacing the machine's controller afterwards will, though.

With this, I am closing the issue.
