### ISSUE TITLE
GTCE blocks do not respect input shorcuts

### ISSUE THREAD

**Issue by Torrenal** [FTBTeam/FTB-Interactions#564]
## Modpack Version: 
Interactions 1.4.? (Release)

## Bug Report:
GTCE blocks do not respond to input shortcuts for moving inventory.

## Expected Behavior/Suggestions:
Open its UI like normal, mouse over the object you want to move, and spin the mousewheel - one direction will move the item into the block, the other direction will remove it.
*Hold down shift and click the stack to move the entire stack.
*Hold down ctrl and click the stack to move a single block.
*Hold down ctrl and shift together while clicking the stack to move all stacks of the same item.
(multi-stack Behavior is different for items in the hotbar)

## Is It Repeatable? Steps to Reproduce: 
Yes.  For expected behaviors, place a Vanilla chest or furnace.  Even the vanilla crafting table exhibits these behaviors.
Put in your inventory multiple stacks of an item that can be placed in the other object.

To recreate, use gregtech items instead.  What I see using a Bronze Chest (Gregtech Community Edition):
* Mousewheel actions from either inventory are ignored
* Shift-click actions work to move full stacks (color me surprised, one of these worked)
* Ctrl-click actions to move single objects from a stack instead will pick up the stack (not-working)
* Ctrl-shift-click actions to move all stacks only move a single stack.
Observed with other GTCE blocks, grinders, electrolyzers, etc

## Link to Log or Crash File Paste**: 
N/A
## Mod/s Affected: 
Gregtech Community Edition

## Known Fix: 
???

**Comment by Saereth** [comment]
This is a gtce specific issue, please report on their tracker
https://github.com/GregTechCE/GregTech/issues
