### ISSUE TITLE
Gem Refiner: No Matching Recipe Found

### ISSUE THREAD

**Issue by BradenCradock** [FTBTeam/FTB-Interactions#565]
## Modpack Version: 
1.5.0

## Bug Report:
I can't get the Gem Refiner to craft anything, using suggestions from the Discord still hasn't helped.  The heater has been left connected for more than 30mins.
Heater: 
![image](https://user-images.githubusercontent.com/24211788/57203238-7499e900-7002-11e9-9d78-e71906e9ef38.png)
![image](https://user-images.githubusercontent.com/24211788/57203247-87142280-7002-11e9-94ad-1b64556d9214.png)
Mana Spreader:
![image](https://user-images.githubusercontent.com/24211788/57203250-92674e00-7002-11e9-9e35-c68cd52ea714.png)

There are 2 Diamonds in the item input and the controller UI is this:
![image](https://user-images.githubusercontent.com/24211788/57203275-b4f96700-7002-11e9-9b2d-39d226cb53b1.png)

Restarting the modpack, my PC and reinstalling the mod pack has not helped.

## Expected Behavior/Suggestions:
The Gem Refiner should take 2 normal tier gems, a lot of heat and mana as inputs. The output should be a single higher tier gem. This crafting recipe is not being executed.

## Is It Repeatable? Steps to Reproduce: 
1. Get 2 diamonds.
2. Put diamonds in input of Gem Refiner.
3. ????
4. No flawless diamond in output :(

## Link to Log or Crash File Paste**: 
N/A

## Mod/s Affected: 
N/A

## Known Fix: 
N/A

**Comment by Saereth** [comment]
right click on the mana input hatch and mek input hatch to see their current values, also show a screen shot of your input hatch for items, currently cannot reproduce so need more info

**Comment by BradenCradock** [comment]
Ok, I played around with it on a test world and it seems I needed to feed it a lot more heat to get it to work. Thanks for your suggestions.

**Comment by Vyraal1** [comment]
My final advice would be to put it next to the hatch itself, there might be throttling with the cable (or some mechanics I'm not familiar with regarding the heat conductors from Mekanism)
