### ISSUE TITLE
transmutation tablet suggestion

### ISSUE THREAD

**Issue by Rdjrjqouqcu** [FTBTeam/FTB-Interactions#566]
## Modpack Version: 
1.5.0

## Suggestions:
Allow the transmutation tablet to be craftable from the transmutation table with obsidian instead of dark matter blocks. Because the transmutation tablet is only a portable version of the easily obtainable transmutation table this change would allow the ability to use the table anywhere without having to place the table down and pick it back up once done.

**Comment by Saereth** [comment]
nope we discussed this, vyraal wanted to leave it gated.
