### ISSUE TITLE
Bedrock. There is none.

### ISSUE THREAD

**Issue by twothe** [FTBTeam/FTB-Interactions#567]
## Modpack Version: 
1.4.2

## Bug Report:
For Infinity Grain I am required to hit Bedrock with Flint. However there is no Bedrock on the void spawn plattform and there is no hint on how to get/find some.

## Expected Behavior/Suggestions:
If there is Bedrock somewhere (available), there should be a hint in the quest book on how to find it.

**Comment by twothe** [comment]
Notice: Bedrock is below the initial tree, however still there should be a hint.

**Comment by xinyuan-liu** [comment]
Actually there are hints in the tips when entering a world.

**Comment by twothe** [comment]
Entering and leaving the world until you get the necessary tips is not something people would do.
