### ISSUE TITLE
Endermite warning would be great

### ISSUE THREAD

**Issue by twothe** [FTBTeam/FTB-Interactions#568]
## Modpack Version: 
1.4.2

## Bug report
When crafting the infinity grain there is a suggestion to use it to spawn mobs. Building the mob farm out of cobble (which is what every player would do) will make potentially spawning Endermites almost impossible to kill (they are invisible yet apply wither to you). Therefore launching a few infinity dust smoke clouds can easily end the pack at this point for the player, as there is certain death in the form of withering Mites, which will drain your hunger bar and cause you to run out of food.

## Expected behavior
There should be a warning in the quest book to not use that dust near (cobble-)stone.

**Comment by Saereth** [comment]
if people are making their mob farm out of cobble they're gonna have a much bigger issue when the primed TNTs spawn from the infinity clouds and blow it all up anyway.

**Comment by twothe** [comment]
Actually explosions were the reason I built it out of cobble initially. It is much more explosion-proof than dirt. ;)

**Comment by Saereth** [comment]
https://github.com/FTBTeam/FTB-Interactions/pull/877
