### ISSUE TITLE
Dolly from Ender Utilities can not be used with Gregtech

### ISSUE THREAD

**Issue by krakel** [FTBTeam/FTB-Interactions#569]
## Modpack Version: 
1.5.0

## Bug Report:
if you try to use the Dolly with a Gregtech Machine/Drum/... you destry this block on reuse

**Comment by Saereth** [comment]
There is no blacklist for us to stop this so wont be fixing this, its meant to be used to move chests, if people decide to move other TEs with it, thats on them. Moving Tes in that manner is always a risky move regardless the mod enabling you to do it.
