### ISSUE TITLE
Botania shedding page crashes the client

### ISSUE THREAD

**Issue by twothe** [FTBTeam/FTB-Interactions#570]
## Modpack Version: 
1.4.2

## Bug Report:
Opening the Botania ingame manual, Shedding explanation, page 2 will crash the game.

## Is It Repeatable? Steps to Reproduce: 
1. Open Botania manual
2. Select index, navigate to Shedding
3. Forward to page 2

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/a79bf1d2

## Mod/s Affected: 
Botania

**Comment by Saereth** [comment]
https://github.com/Vazkii/Botania/issues/2909

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/57339109-38e44980-70fe-11e9-83c8-a9bc474f11d4.png)
Cannot replicate

**Comment by Saereth** [comment]
I was able to replicate the crash myself, havent tried since we did all our mod udpates tho, will try again this evening
