### ISSUE TITLE
missing block AE2 Cable and/or Bus

### ISSUE THREAD

**Issue by krakel** [FTBTeam/FTB-Interactions#573]
## Modpack Version: 
1.5.0

## Bug Report:
The ME Controller is not craftable. The block AE2 Cable and/or Bus (#5804) (appliedenergistics2:cable_bus) is missing. Or I do'nt understand the multiblock structure for minimaturization.

**Comment by Neeve01** [comment]
You have to use ME Glass Cables.

**Comment by krakel** [comment]
I was using the ME Glass Cable - Fluix with no effect!

**Comment by krakel** [comment]
I was hearing I have to visit Aurelia first. Is this correct? Where on the questbook can I read this information?

**Comment by Saereth** [comment]
I have successfully crafted the controllers in 1.5 I cannot reproduce this issue, please provide screenshots or video of your setup, this appears to be user error.

**Comment by krakel** [comment]
[screenshot](https://doerl.de/zip/2019-05-07_15.48.36.jpg) what do I wrong on this construction (I play on a server)

**Comment by krakel** [comment]
Oh sorry I found it. I was using the Crafting Unit and not the Crafting Monitor. Sorry!!!
