### ISSUE TITLE
Arcane Ashes - Infinite Repair for free

### ISSUE THREAD

**Issue by Bang257** [FTBTeam/FTB-Interactions#574]
## Modpack Version: 
1.4.2

## Bug Report:
Arcane Ashes can be repaired infinitely at no cost, no enchants, etc.

## Expected Behavior/Suggestions:
Breaking the Arcane Ash Circle should return an ash of the same or lesser durability than what was originally used.

## Is It Repeatable? Steps to Reproduce: 
1.Use Arcane Ash on the ground to draw a circle
2.Use Arcane Ash on the circle (same one)
3.Break the circle
4. You get a repaired Arcane Ash back
5. This can be repeated to fully repair the arcane ash and end up net-positive

## Mod/s Affected: 
Blood Magic: Alchemical Wizardry

**Comment by Saereth** [comment]
already reported to bloodmagic, nothing we can do about it pack wise, but also not really a major issue
