### ISSUE TITLE
Spontaneously Regenerating Starting Platform

### ISSUE THREAD

**Issue by Karthas077** [FTBTeam/FTB-Interactions#575]
## Modpack Version: 
1.5.0

## Bug Report:
Starter island was regenerated in-place upon reloading a world, destroying a large number of machines and chests and dumping their contents into the void.

## Expected Behavior/Suggestions:
The blocks for the starting island should never come back and certainly not destroy placed blocks.

## Is It Repeatable? Steps to Reproduce: 
No clue what caused it as it's never happened before but my save or install appears to be corrupted in some way as even loading a backup does not stop this.

## Known Fix: 
No clue, currently trying to duplicate the instance and migrate my save over to see if it's something in the save itself or something else.

Edit: Letting the world break, then replacing just the data for the void world and my inventory appears to have stopped it from happening again, but a copy of the save into a fresh install still causes it, so it's something in the save itself that is causing the starter island to regenerate.

## Haiku:
Island in the void
Reappeared in it's old place
Much of my stuff gone

**Comment by Vyraal1** [comment]
Not really sure how to fix this, or even reproduce this. I can still log into all my dev worlds just fine. Can you provide a concrete way to reproduce it? Also bravo for the haiku.

**Comment by Karthas077** [comment]
The only concrete way I could think of to "reproduce it" would be to send the backup file of my world which contains the problem, but I'm not even sure where you would begin looking for the cause or how to send that.

I honestly wasn't really expecting this to be something that could have a cause identified, but wanted the issue to exist on the off-chance that anyone else encountered it so they could see my "solution".

**Comment by Tinlake** [comment]
Not sure how to reproduce it either, but this exact same thing happened to me upon loading up my world, in singleplayer.
