### ISSUE TITLE
Missing alloy recipes for EnderIO Capacitors

### ISSUE THREAD

**Issue by Buggy123** [FTBTeam/FTB-Interactions#577]
Most higher-tier EnderIO capacitors are uncraftable, because the ingot recipes require materials from the (disabled) sag mill.

These include the Crystalline Capacitor, the Melodic Capacitor, and the Totemic Capacitor. The Stellar Capacitor would be craftable, however it requires the uncraftable Melodic Capacitor.

The two ingots which would need new recipes to enable crafting these capacitors would be Crystalline Alloy Ingots, and Melodic Alloy Ingots. Totemic Capacitors would require a new recipe. Alternatively, allowing various EnderIO crystals to be pulverized to their powder counterpart in a macerator, as a substitute for a sag mill, would also enable the crafting of all of these.

It may be intended for this to be disabled for balancing purposes, as these capacitors serve no purpose except for upgrading EnderIO machines. However, if that is the case, then it should be noted that randomly-generated loot capacitors that can be found in various vanilla loot chests (such as woodland mansions) can be as strong as even the highest-tier capacitors, and are obtainable. If you wish to disable these capacitors to limit the strength of EnderIO machines, you should also disable randomly-generated loot capacitors.

**Comment by Vyraal1** [comment]
Looking over this right now: It seems like the only machines that will benefit from these capacitors are:
- soul binder
- farming station

We're perfectly fine with those machines being incredibly op. More wood or crops from a large range farming station isn't particularly worrying. Let us know if I'm missing anything in my analysis, otherwise I'm going to just disable the Endergy capacitors to prevent any confusion.

**Comment by Buggy123** [comment]
There are more craftable EnderIO machines, which can be boosted with capacitors, than what you've listed there.

The Aversion Obelisk is disabled in preference to other methods of preventing mobs from spawning, which unfortunately also makes the useful Relocator Obelisk uncraftable. However the Attractor and Inhibitor Obelisks are both craftable and useful for mob farms and similar, and to my knowledge both can be upgraded with capacitors.

Those are it, as far as I'm aware.

**Comment by Vyraal1** [comment]
Sorry forgot to mention I'm in a later dev instance, right now the majority of those were already disabled.

**Comment by Saereth** [comment]
yeah I just disabled all those, not really needed the existing/craftable caps should be fine

**Comment by noobnoobnub** [comment]
How can you make enderio farming station? You can't craft zlogic gate
