### ISSUE TITLE
[Recipe conflict ? ] Aluminium Frame and Machine Structure

### ISSUE THREAD

**Issue by hyodocraft** [FTBTeam/FTB-Interactions#578]
## Modpack Version: 
1.5.0
SSP / Twitch App

## Bug Report:
If I try to craft Aluminium Frame after I have crafted Machine Structure, the machine produces Machine Structure.

## Expected Behavior/Suggestions:
I can craft the desired items without storing the recipe on the machine.

## Is It Repeatable? Steps to Reproduce: 
1. Craft the machine structure.
2. Try to craft the aluminium frame with STACK of ingredients on same assembling machine.

## Video: 
https://streamable.com/lh53n

## Mod/s Affected: 
N/A

## Known Fix: 
Machine Structure recipe should also contain Programmed Circuit (not Configuration:1).

**Comment by Vyraal1** [comment]
```
	#New Machine Structure recipes
recipes.remove(basicMachineStructure);
assembler.recipeBuilder()
  .inputs(<ore:plateAluminium> * 4, <ore:stickAluminium> * 4)
  .notConsumable(integratedCircuit.withTag({Configuration: 2}))
  .outputs(basicMachineStructure * 4)
  .duration(200)
  .EUt(68)
  .buildAndRegister();```
