### ISSUE TITLE
Mana Pearl does not trigger quest

### ISSUE THREAD

**Issue by TomyLobo** [FTBTeam/FTB-Interactions#579]
## Modpack Version: 
1.5.0

## Bug Report:
Mana Pearl does not trigger the quest "Mana Pearl".
Yes, I finished the quest "Unstable Mana Bucket".
Yes, the Mana Pearl was freshly crafted.

## Expected Behavior/Suggestions:
Mana Pearl should trigger the quest "Mana Pearl".

## Is It Repeatable? Steps to Reproduce: 
1. Get ingredients
2. Build Mana Pearl from the ingredients

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/57393852-fec48780-7191-11e9-980c-6ddcf9974682.png)

Set it to ignore, but issues like these keep popping up, part of me is starting to wonder if there's an issue with the file system FTBQ asnd git uses.

**Comment by Vyraal1** [comment]
Also did it for mana pearl 
![image](https://user-images.githubusercontent.com/26587049/57394227-f02aa000-7192-11e9-81fa-142e9047c91c.png)
