### ISSUE TITLE
Server/Client Crash Blazes and Blaze Charms

### ISSUE THREAD

**Issue by Selway00** [FTBTeam/FTB-Interactions#580]
## Modpack Version: 
1.5 -Single player test world. 

## Bug Report:
Server Crash in both Single and multiplayer when hitting Blazes.

*Edit It appears to be an interaction between Rough Mobs 2 and Reliquary's blaze charm.  When the blaze charm is in the inventory or Hotbar, the client/server will crash upon hitting a blaze.

I did some more testing in a single player world.  What I found is it may have something to do with the blaze charm and Rough Mobs 2.  Here are my steps.

- recreated gear/baubles/inventory from #576 in creative.  
- Went to nether.  Killed Blazes.  No crash
- Switched to Survival - Instant crash without even hitting a blaze.
- Reloaded and began removing gear one by one.  Still crashes on first hit of a Blaze. 
- Updated to Rough Mobs 2.0.15.
- Same issue.   
- Removed Rough Mobs 2.  No crash when hitting Blazes.
- Reinstalled Rough Mobs 2.  Killed blazes naked with only gold sword.  No crash.
- Gradually added back original enchanted diamond sword, then 9 heal fragments, and Repair Talisman.  No Crash.
- Added back Blaze charm and got a crash on first hit.

## Expected Behavior/Suggestions:
No server crash

## Is It Repeatable? Steps to Reproduce: 
Yes.  Repeat gear/inventory/baubles in issue #576.  Go to nether.  Kill one or two blazes and then it will happen.  

## Link to Log or Crash File Paste**: 
Log working up to the crash when the Blaze charm was added: 
[2019-05-08-7.log.gz](https://github.com/FTBTeam/FTB-Interactions/files/3158959/2019-05-08-7.log.gz)

Last crash with Blaze charm loaded. https://pastebin.com/FpiMeJ0n

Last log where blaze charm was move to a bag with no crash.  Then added back to the HOTBAR slot with NO Crash.  Then Added to INVENTORY slot and instant crash upon hit of a blaze.

[latest.log](https://github.com/FTBTeam/FTB-Interactions/files/3158979/latest.log)

## Mod/s Affected: 
Rough Mods and Blaze charm mod

## Known Fix: 
Edited to fix.  It also crashes in the Hotbar position.  Dont have blaze charm in Inventory or hotbar.  I have not tested to see if other charms cause issues.  Hope this helps.

**Comment by Saereth** [comment]
possibly related:
https://github.com/P3pp3rF1y/Reliquary/issues/355

**Comment by Selway00** [comment]
It also crashes on the toolbelt but for some reason, not as often.  Here is the crash report.

https://pastebin.com/DcFwQ5W8

**Comment by Vyraal1** [comment]
Rough Mobs 2 did nothing wrong. Free Rough Mobs.

**Comment by Beetrootmonkey** [comment]
Can confirm that [Reliquery#355](https://github.com/P3pp3rF1y/Reliquary/issues/355) is most propably related. Everything points to Blaze and Zombie Charms being the reason for server crashes. The only fix we found so far is simply not being under the effect of those two charms. Other charms seem to be just fine, since the problem seems to be the unique way Zombies and Blazes react when taking damage from a player (they call for help).

**Comment by nullsoap** [comment]
Still an issue as of 1.6.1 stable.

**Comment by Sanavixx** [comment]
Still a problem for our server
[crash-2019-05-24_23.08.07-server.txt](https://github.com/FTBTeam/FTB-Interactions/files/3220028/crash-2019-05-24_23.08.07-server.txt)
[2019-05-24-3.log.gz](https://github.com/FTBTeam/FTB-Interactions/files/3220029/2019-05-24-3.log.gz)

**Comment by Yakameen** [comment]
Tested this out, and it seems to be fixed on the current version, Reliquary-1.12.2-1.3.4.796
