### ISSUE TITLE
Iron Hammer Head Crafting "Quirk"

### ISSUE THREAD

**Issue by BrotherLeon** [FTBTeam/FTB-Interactions#581]
## Modpack Version: 
1.4.2

## Bug Report:
To make an iron hammerhead, you use an aluminum hammer and nothing else.

## Expected Behavior/Suggestions:
To make it using 6 iron ingots, arranged as per the other hammer heads' recipe.

## Is It Repeatable? Steps to Reproduce: 

1.
2.

## Known Fix: 
Change the recipe of the iron hammer head using CraftTweaker 2.

**Comment by Vyraal1** [comment]
Having trouble tracking this recipe down, was this part of the replacements? At a loss on where to find it elsewhere, our scripts are so huge at this point I feel like taking a two week break and you forget everything.

**Comment by BrotherLeon** [comment]
This is still present in 1.6.1.
