### ISSUE TITLE
Flux Crystal transposer recipe not disabled

### ISSUE THREAD

**Issue by DrTasslehoff** [FTBTeam/FTB-Interactions#583]
## Modpack Version: 
1.5

## Bug Report:

Chemical bath recipe requires mana diamond and 1000mb redstone fluid. Transposer recipe is a regular diamond and 500mb (default TE). Probably intended to be removed or made in-line with the chemical bath

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/58049455-e6058b80-7b1a-11e9-8896-277f241a28be.png)
