### ISSUE TITLE
Gregtech electric tool can not be charged in battery buffer

### ISSUE THREAD

**Issue by noobnoobnub** [FTBTeam/FTB-Interactions#584]
## Modpack Version: 
1.5.0

## Bug Report:
Gregtech electric tool can not be charged in battery buffer
Lv wrench...etc
Trying to craft gregtech electric tool with full battery, it turn the battery from full to empty (just place on the crafting table)

## Expected Behavior/Suggestions:
It should be charged in that tier of machine and battery buffer

## Is It Repeatable? Steps to Reproduce: 
1.Craft a electric tool with charged battery
2.Put the electric tool in the buffer or machine charging slot, it will not go in

**Comment by Saereth** [comment]
you need at least an MV battery buffer to charge it. I know it doesnt make sense, but the GTCE dev says working as intended.

**Comment by gattsuru** [comment]
At least in 1.6.1, I was able to charge LV Electric Wrench (both Thamium- and Titanium-tipped) in an LV Battery Charger.  They did not charge on a Battery Buffer of any size, or on any consuming device of any size.

Apologies if this is intended behavior, but this was one of the first relevant search results.
