### ISSUE TITLE
Arcane stone uncraftable

### ISSUE THREAD

**Issue by lemonbarking** [FTBTeam/FTB-Interactions#585]
## Modpack Version: 
1.5.0

## Bug Report:
Vis crystal shown in crafting recipe is unobtainable as it has no associated aspect.

## Expected Behavior/Suggestions:
A vis crystal surrounded by nacre blocks should craft 4 arcane stone

## Is It Repeatable? Steps to Reproduce: 
Attempt to craft arcane stone with any vis crystal.
Jei shows "%s Vis Crystal" as the required item but that item links to Salis Mundis in JEI.
Salis Mundis is not able to be used in the crafting of arcane stone either.

## Mod/s Affected: 
ALLTEHMODS (requiring arcane stone)

## Known Fix: 
I dont know anything at all about coding so I'll leave that to the bigbrains

**Comment by Neeve01** [comment]
Just place any vis crystal in the middle and surround it with nacre blocks. JEI not being able to auto-fill the recipe doesn’t mean it’s uncraftable.

**Comment by lemonbarking** [comment]
I only attempted filling from jei after manually placing them didnt work. I was manually placing both the nacre block and the vis crystal. I tried half a dozen different types of crystals and I tried different crafting benches in case that was the issue. None of which worked.

**Comment by lemonbarking** [comment]
I restarted the pack and this is no longer an issue. Something must have just loaded wonky the first time.
