### ISSUE TITLE
Extreme FPS loss on entites

### ISSUE THREAD

**Issue by Ioncloud9** [FTBTeam/FTB-Interactions#586]
## Modpack Version: 
1.5.0

## Bug Report:
Fps is unplayable around 5-10. I installed LagGoggles and ran the fps profiler and it's all from mob entites. looking at entites by type I see 5085606 ns/F from EntityPig followed by 3101867 ns/F from EntitySheep... somethings seriously wrong with MOBs at the moment

 [LagGoggles ScreenShot](https://imgur.com/YnUUlZN)

## Is It Repeatable? Steps to Reproduce: 

1. it's constant on my system... whether it is on others, I have no idea
2.

**Comment by Saereth** [comment]
this is not reproducible by us, appears to be a system/OS issue configuration issue. if you have an nvidia card verify in your nvidia control panel the correct video card is being utilized for MC, common issue.
