### ISSUE TITLE
Suggestion: I18n support in FTB Quests

### ISSUE THREAD

**Issue by xinyuan-liu** [FTBTeam/FTB-Interactions#587]
## Modpack Version: 
1.5.0

## Bug Report:
Texts in the quests are hardcoded in English and that is not friendly for localization. 

## Expected Behavior/Suggestions:
FTB Quests has good support for localization now. The hardcoded texts can be replaced with language keys and external language files.

## Mod/s Affected: 
FTB Quests

## Known Fix: 
Update FTB Quests and FTB Lib to the newest version.
Replace the text in quest title or description with {lang.key} and build a lang file with these keys.
This could be a heavy work so I've written a python script to automate this.
Here is the script and the generated nbt files from the 1.5.0 modpack:
[ftbquests.zip](https://github.com/FTBTeam/FTB-Interactions/files/3167833/ftbquests.zip)
Note that the generated language keys are made up of the IDs of chapters and quests, which may lack readability.

**Comment by Saereth** [comment]
This would unfortunately just be way too much work for me to implement, if someone wants to volunteer let me know.
