### ISSUE TITLE
Crash when changing windows

### ISSUE THREAD

**Issue by Ludi87** [FTBTeam/FTB-Interactions#59]
## Modpack Version: 
1.0.0-1.12.2 (Release version)

## Bug Report:
Had a few crashes when changing windows (I was streaming with OBS, switched from MC in windowed mode to chrome/discord).

## Expected Behavior/Suggestions:
No crash? :P

## Is It Repeatable? Steps to Reproduce: 
I'll do more testing if I get different errors, but so far I had 4 crashes in 1 hour.

## Link to Log or Crash File Paste**: 
https://pastebin.com/1eP3DFR2

## Mod/s Affected: 
Xaero Minimap? At least thats the first thing the error points to.

Changes I made to the pack: 
I added Faithful32&Faithful32Modded as a resourcepack. Using the same without issues in Enigmatica2 Expert and Sky Odyssey.

PC Specs:
Ryzen 5 2600
16GB Ram (8 allocated)
Nvidia 1060
Windows 10
MultiMC Launcher

**Comment by Vyraal1** [comment]
Forwarded it to the moddev: https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2624027-xaeros-world-map-forge-1-13-2-1-12-2-1-12-1-1-12-1?page=28#c586

Sorry about this crash, if it get too bad, you can just remove the World Map mod (which is separate from  the minimap mod).

**Comment by Ludi87** [comment]
Yea I like Xaero, had no issues in odyssey and sky adventures (but I'm not sure if it was only the minimap there). Thanks for the reply, forgot to mention that I reported it on the xaero minimap tracker on curseforge as well, I'll see what happens :)

**Comment by Ludi87** [comment]
Update: It *could* be a memory issue on my end, but I'm not sure yet.

A memory test showed an errormessage, did a biosupdate and will see if the crashes disappear now.

(history here: https://minecraft.curseforge.com/projects/xaeros-minimap/issues/18 )
