### ISSUE TITLE
Lava waders = infinite Mitts, also cause fps nuke when holding something "hot"

### ISSUE THREAD

**Issue by Xetaxheb** [FTBTeam/FTB-Interactions#590]
## Modpack Version: 
1.5.0

## Bug Report:
Pretty straightforward, equip Lava Waders (randomthings) and hold a lava bucket or in my case a tungstensteel drum with lava in it, huge fps nuker as the "this item is hot" tries to apply fire/damage but can't because lava waders are op.

## Expected Behavior/Suggestions:
Either Lava Waders shouldn't stop the damage or shouldn't cause fps nuking, maybe a hotornot issue? I don't know what mod adds "this item is hot" if it's not that.

**Comment by Saereth** [comment]
just a mod interaction, hot or not just sets you on fire with vanilla mechanics, lava waders cancels it so they fight each other constantly. Easy work around is to just not use them both together. You can goto the respective mods and ask a feature request to add compatibility but its not a pack specific issue we can do anything about.
