### ISSUE TITLE
server.start executable getting stuck at "Stopping aura thread for dim -2" when trying to launch server.

### ISSUE THREAD

**Issue by crysis107** [FTBTeam/FTB-Interactions#591]
## Modpack Version: 
1.5.0

## Bug Report:
Every time I run the server.start executable, it get stuck at;
.......
[01:43:50] [Thread-21/INFO] [THAUMCRAFT]: Stopping aura thread for dim 33
[01:43:50] [Thread-22/INFO] [THAUMCRAFT]: Stopping aura thread for dim -11325
[01:43:50] [Thread-24/INFO] [THAUMCRAFT]: Stopping aura thread for dim -2

## Expected Behavior/Suggestions:
As above

## Is It Repeatable? Steps to Reproduce: 
Execute Server.start file

## Mod/s Affected: 
Believe its Thaumcraft?

## Known Fix: 
N/A

**Comment by Saereth** [comment]
gonna need full logs

**Comment by derksthename** [comment]
> gonna need full logs

I am having the same issue, https://paste.feed-the-beast.com/view/f759255b
