### ISSUE TITLE
Uncraftable alloys

### ISSUE THREAD

**Issue by sironin** [FTBTeam/FTB-Interactions#593]
## Modpack Version: 
1.4.2

## Bug Report:
Mekanism refined glowstone recipe conflicts with Osmium blast furnace recipe and is therefore unattainable.
PlusTic smeltery alloy material Mirion is unattainable

## Expected Behavior/Suggestions:
Suggest using an osmium ingot for refined glowstone instead of dust to remove conflict.
Suggest adding an ingot based blast furnace, runic altar or infusion crafting recipe.

## Mod/s Affected: 
Mekanism, PlusTic

**Comment by noobnoobnub** [comment]
Ender utilities ender alloy basic can't be made also. And enderio zlogic gate can't be made. Most of enderio machine is useless

**Comment by Saereth** [comment]
basic alloy from ender utils isnt intended to be craftable and wont be, the other alloys should be fixed in next version

**Comment by christofferson** [comment]
Mekanism glowstone ingots are still uncraftable in 1.9.1-1.12.2: putting all items (4 glowstone dust, 1 osmium dust, 500mb Helium) into an HV blast furnace with Tungstensteel coil blocks simply processes the osmium dust into an osmium ingot, ignoring the other inputs.
