### ISSUE TITLE
Infinite Radon production chain (radon duplication)

### ISSUE THREAD

**Issue by nyronium** [FTBTeam/FTB-Interactions#595]
## Modpack Version: 
1.5.0

## Bug Report:
Radon can be produced infinitely by using 3x plutonium 244 ingot:
1. Place 3x ingot in the chemical reactor,
    -> obtain 3x dust + 50mB Radon
2. Smelt 3x dust to 3x ingot in a normal furnace
3. Repeat at 1.
4. ???
5. Profit

## Expected Behavior/Suggestions:
Disable normal plutonium dust -> ingot smelting recipe,
Instead use a blast furnace recipe which additionally uses 50mB of radon.

## Is It Repeatable? Steps to Reproduce: 
Trivial, see above.

## Known Fix: 
See suggestions.

**Comment by Kanzuke117** [comment]
It's intentional.

That's why it takes so much work to get 3x plutonium 244, why the recipe for producing it takes 50 minutes at base speed for only 50mb, and why the only other way to produce radon is with 32kEU/t in a Mark 3 Fusion Reactor.

**Comment by Saereth** [comment]
yep this is intentional
