### ISSUE TITLE
Mending moss modded tinkers tool does not collect XP when on hotbar

### ISSUE THREAD

**Issue by butterflo** [FTBTeam/FTB-Interactions#596]
## Modpack Version: 
1.5.0

## Bug Report:

* Hotbar case:
  * **Condition:** Have a mending moss modded tinkers pickaxe on **hotbar.**
  * **Action:** Pickup an xp orb or eat a lotus blossom.
  * **Result:** Player XP is increased. Pickaxe is not repaired. Tinkers tool station reveals the stored xp is not increased.

* Offhand case:
  * **Condition:** Have a mending moss modded tinkers pickaxe on **offhand slot.**
  * **Action:** Pickup an xp orb or eat a lotus blossom.
  * **Result:** Player XP is not increased. Pickaxe begins repairing. Tinkers tool station reveals the stored xp is increased.

These are not consistent with page 165 of in-game book "Materials and You", where it says the modified item "has to be in hotbar or offhand to repair."

## Expected Behavior/Suggestions:

Two options: 
* Change the hotbar case to trigger repairing.
* Keep the current behavior for both cases, and change page 165 of the book to "has to be in offhand to repair".

## Is It Repeatable? Steps to Reproduce: 
Repeatable. See above.

## Link to Log or Crash File Paste**: 
Doesn't leave anything useful but provided anyway.
[https://paste.feed-the-beast.com/view/d432c821](https://paste.feed-the-beast.com/view/d432c821)

## Mod/s Affected: 
Tinkers' Construct

**Comment by Rdjrjqouqcu** [comment]
This is likely intentional as it mirrors vanilla's mending enchant. XP is only absorbed by the tool when the item is in an armor slot, main-hand,  or off-hand. If the wording says that it absorbs xp anywhere in the hotbar, then you probably want to have this issue be on the Tinkers construct issue tracker.

**Comment by Saereth** [comment]
indeed this is a non pack specific issue and I believe intended behavior
