### ISSUE TITLE
5 x Satchel gets Insight IV not Holding IV

### ISSUE THREAD

**Issue by ian-barlow** [FTBTeam/FTB-Interactions#597]
## Modpack Version: 
1.5

## Bug Report:
Combine 5 satchels and get satchel with Insight IV

## Expected Behavior/Suggestions:
Combine 5 satchels and get satchel with Holding IV

## Is It Repeatable? Steps to Reproduce: 
1. Place 5 satchels on crafting station or table and craft
2. https://imgur.com/Q7AqvJE

## Link to Log or Crash File Paste**: 
n/a

## Mod/s Affected: 
n/a

## Known Fix: 
n/a

**Comment by Ozzymud** [comment]
I think this is similar to https://github.com/FTBTeam/FTB-Interactions/issues/370 which looks like it might be fixed.

**Comment by Saereth** [comment]
recipe removed in next update
