### ISSUE TITLE
Wrong titanium block in quest for Warp Core

### ISSUE THREAD

**Issue by nyronium** [FTBTeam/FTB-Interactions#599]
## Modpack Version: 
1.5.0

## Bug Report:
The Quest for the warp core ("To boldly go where no steve has gone before...") requires
15x Titanium blocks from the libvulpes mod, but when building the structure, you actually
need the gregtech blocks for it to form the multiblock.

## Expected Behavior/Suggestions:
Either the multiblock should use the blocks from the quest, or the quest should be changed to trigger on normal gregtech titanium blocks.

## Is It Repeatable? Steps to Reproduce:
Try to build the warp core with vulpes blocks, and find it only works with gregtech blocks.

## Known Fix: 
See suggestions.

**Comment by MainSame** [comment]
Same problem, but with titanium blocks from gregtech. While the rest of the titanium blocks are alloys so they wouldn't work either way.
