### ISSUE TITLE
crash while launching

### ISSUE THREAD

**Issue by chrisluissanc** [FTBTeam/FTB-Interactions#60]
## Modpack Version: 
1.0

## Bug Report:
crash while launching 

## Expected Behavior/Suggestions:
no crash

## Is It Repeatable? Steps to Reproduce: 

1. launch
2. crash while load

## Link to Log or Crash File Paste**: 

https://pastebin.com/hJprJ1Uc

**Comment by Vyraal1** [comment]
Please put the crash log (found in the modpack directories crash reports folder) in a hastebin or a pastebin.

**Comment by chrisluissanc** [comment]
https://pastebin.com/hJprJ1Uc

**Comment by Saereth** [comment]
This appears to be a very specific issue with the jvm, the mod dev is aware and working on a work around

**Comment by chrisluissanc** [comment]
neat good enough for me should i close the issue?

**Comment by Saereth** [comment]
nah we'll leave it open until its fixed in case others have the same problem

**Comment by Shadows-of-Fire** [comment]
For now anyone with this issue should switch to the oracle JRE (if possible).
This appears to be an jvm implementation issue between oracle's JRE and OpenJDK.  I'm resolving it now.

**Comment by Hubry** [comment]
Isn't this just MinecraftForge/MinecraftForge#5254? I would try updating Forge to build 14.23.5.2815 or newer.

**Comment by fGravity** [comment]
Having similar issue with the latest FTB Interactions update (1.2.0) - https://pastebin.com/0VQfUuYt
