### ISSUE TITLE
Cardboard box turns Bronze Chest to Small Steam Coal Boiler

### ISSUE THREAD

**Issue by ShaneCourtrille** [FTBTeam/FTB-Interactions#601]
## Modpack Version: 
1.5

## Bug Report:
Used a cardboard box on a Bronze chest and the chest became a Small Steam Coal Boiler.  Tried with a Copper chest and it doesn't do the same thing.

## Is It Repeatable? Steps to Reproduce: 
Yes, it happens every time.  Just use a cardboard box on a Bronze Chest

**Comment by Saereth** [comment]
no support for this. Forcibly moving tile entities is problematic, use at your own risk.
