### ISSUE TITLE
crash in offline mode

### ISSUE THREAD

**Issue by kotelkonrad** [FTBTeam/FTB-Interactions#602]
[crash-2019-05-13_17.16.33-client.txt](https://github.com/FTBTeam/FTB-Interactions/files/3173645/crash-2019-05-13_17.16.33-client.txt)

repeatable:
yes

**Comment by xinyuan-liu** [comment]
I have the same issue. It is caused by Emojiful. Game will always crash on loading when there is no access to network.

**Comment by xinyuan-liu** [comment]
You can just delete the Emojiful mod as a walkaround.

**Comment by kotelkonrad** [comment]
okay

**Comment by Saereth** [comment]
yeah we dont really support offline mode but you can remove emojiful
