### ISSUE TITLE
Feature request Grains of infinity joke/redirect

### ISSUE THREAD

**Issue by jcaldwell02** [FTBTeam/FTB-Interactions#605]
Feature request Grains of infinity joke/redirect to correct method

## Modpack Version: 
1.5.0

## Bug Report:
Not a bug but a suggestion, new feature idea

Would be funny if you tried to light bedrock on fire it just popped out with a note that said "use the dust then kill the mob stupid" or I'm sure someone can come up with a more comical note. Maybe "you should really read the quest book" or even a quest that gets completed called "You tried" and then tells you to do it the right way.

**Comment by Saereth** [comment]
thats pretty funny i'll add this as a feature request for later lol

**Comment by Saereth** [comment]
neat idea but its a little complicated for a joke, would need to make a new mod for it ;p
