### ISSUE TITLE
Suggestion - Add recipes to use lower GT tier machines rather than Hulls.

### ISSUE THREAD

**Issue by cardinalsrulejd** [FTBTeam/FTB-Interactions#606]
## Modpack Version: 
1.5

I suggest creating recipes to use old GT machines to convert into higher tiered versions. For example. An LV turbine can have a recipe to convert to an MV turbine. You could gate it, make it a little bit less expensive than the main MV turbine recipe, but at least allow us to take advantage of the work that was done with machines that we are just going to throw into chests.

**Comment by Saereth** [comment]
we're not gonna do this. It's a nice idea, but its something that should belong in gtce core with a recycler machine or something instead of using trying to manually make literally thousands of lines of scripts just to recover some resources
