### ISSUE TITLE
Large Handybag Uncraftable

### ISSUE THREAD

**Issue by braingkk** [FTBTeam/FTB-Interactions#607]
## Modpack Version: 
1.4.2

## Bug Report:
when attempting to craft the large handybag with the correct attuned crystal, power and relays around, the altar will play the sound, but never prompts to place items in the relay not progressing

## Expected Behavior/Suggestions:
upon hitting the altar with a wand, the crafting should prompt with relays lighting up to craft the bag

## Is It Repeatable? Steps to Reproduce: 
https://youtu.be/LFszD9JhjFE
1. craft a holo attuned crystal, and a t1 handybag
2. place appropriate items in the altar and verify the icon appears on the right
3. right click with a wand and listen to the sounds but cry that there are no particles

## Link to Log or Crash File Paste**: 
NA

## Mod/s Affected: 
Astral Sorcery crafting, and Ender utils handybag

## Known Fix: 
in scripts EnderUtilities.zs on line 166 changing from
mods.astralsorcery.Altar.addTraitAltarRecipe("interactions:shaped/internal/altar/handybaglarge", <enderutilities:handybag:1>, 8000, 200, [
to
mods.astralsorcery.Altar.addTraitAltarRecipe("interactions:shaped/internal/altar/handybaglarge", <enderutilities:handybag:1>, 7500, 200, [
fixes the issue

**Comment by Vyraal1** [comment]
```
recipes.remove(<enderutilities:handybag:1>);
mods.astralsorcery.Altar.addTraitAltarRecipe("interactions:shaped/internal/altar/handybaglarge", <enderutilities:handybag:1>, 7500, 200, [
    <ore:plateTitanium>, null, <ore:plateTitanium>, 
    null, <enderutilities:handybag>, null,
    <ore:plateTitanium>, null, <ore:plateTitanium>,
    <metaitem:field.generator.hv>, <metaitem:field.generator.hv>, <metaitem:field.generator.hv>, <metaitem:field.generator.hv>,
    null, null,
    null, null,
    null, null,
    null, null,
    <enderutilities:enderpart:2>, <enderutilities:enderpart:2>, <enderutilities:enderpart:2>, <enderutilities:enderpart:2>,
    //Outer Items, indices 25+
    <minecraft:chorus_fruit_popped>, <extrautils2:klein>, <enderutilities:enderpart:50>, <bhc:red_heart>,],
	"astralsorcery.constellation.horologium");
```
Switched it to 7500, were the internal buffers of altars changed? Looks like I put in too high of a passive amount.

**Comment by braingkk** [comment]
i think you picked the max buffer, and with drain from crafting it kept on failing on power. it may have been fine with 7800 or so, i just picked 7500 out of a hat
