### ISSUE TITLE
Game crashed as i used my ebf with 2 UV energy input hatch

### ISSUE THREAD

**Issue by zTotto** [FTBTeam/FTB-Interactions#608]
## Modpack Version: 
1.5.0

## Bug Report:
Game crashed as i put an item to be processed in my ebf, it had 2 uv energy hatches

## Expected Behavior/Suggestions:
It shouldn't crash

## Is It Repeatable? Steps to Reproduce: 
1. attach 2 uv energy input hatches to your ebf
2. put something in your ebf

## Link to Log or Crash File Paste**: 
[crash-2019-05-14_18.24.29-server.txt](https://github.com/FTBTeam/FTB-Interactions/files/3178856/crash-2019-05-14_18.24.29-server.txt)
## Mod/s Affected: 
Gregtech

**Comment by Saereth** [comment]
reported to gtce
