### ISSUE TITLE
Enchiridion Quest

### ISSUE THREAD

**Issue by Ludi87** [FTBTeam/FTB-Interactions#61]
## Modpack Version: 
1.0.0-1.12.2 (Release version)

## Bug Report:
Quest "Having fun isn't hard when you got your library card." on the first Questpage tells me to reconfigure the key for the Enchiridion. Can't find a control for it, or the item, or the mod in the folder. Was the mod removed, but not the quest?

## Expected Behavior/Suggestions:
Find Enchiridion in controls to set a key for it.

## Is It Repeatable? Steps to Reproduce: 
Yup, look at controls.

## Mod/s Affected: 
Enchiridion

**Comment by Vyraal1** [comment]
Our bad, we noticed this almost 1 hours after the pack was shipped to twitch. We switched the Enchiridion system to using chisel, you should be able to chisel your books and your FTB Questbook into other guides.

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/55118234-0ccbb680-50c4-11e9-8add-bed0a2db59c5.png)
