### ISSUE TITLE
Internal server shutdown

### ISSUE THREAD

**Issue by TheLeadPrince** [FTBTeam/FTB-Interactions#610]
## Modpack Version: 
FTB Interactions 1.5.0

## Bug Report:
internal server shutdown when trying to join or make singleplayer world

## Expected Behavior/Suggestions:
should not crash to desktop

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/81a4f611

**Comment by Saereth** [comment]
update your java, its very out of date, if the issue persists beyond that reopen

**Comment by TheLeadPrince** [comment]
updated still having the same problem
