### ISSUE TITLE
Crash when using a rocket to reach the moon

### ISSUE THREAD

**Issue by Matt8898** [FTBTeam/FTB-Interactions#611]
## Modpack Version: 
1.6.0-1.12.2

## Bug Report:
Upon launching a rocket from the void world and reaching the world height limit the game crashes, now i crash whenever i attempt to login. This is on a server.
## Is It Repeatable? Steps to Reproduce: 
The game crashes every time i login. Resetting my position manually and rebuilding the rocket crashed again.
## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/5ce74207
## Mod/s Affected: 
The crash seems to be related to Xaero's minimap

Removing xaero's worldmap and minimap fixes the issue

**Comment by Saereth** [comment]
updated xaeros, should hopefully fix
