### ISSUE TITLE
Can't link blood altar to agonizer

### ISSUE THREAD

**Issue by hobnob11** [FTBTeam/FTB-Interactions#613]
## Modpack Version: 

1.6 (also happening on 1.5)
## Bug Report:

Cannot link DML Agonizer to blood altar, even after clearing the linker, replacing the machines, power and mob datamodel etc..
## Expected Behavior/Suggestions:

it linking :(
## Is It Repeatable? Steps to Reproduce: 

https://gfycat.com/ConventionalFinishedAmmonite
![gif](https://thumbs.gfycat.com/ConventionalFinishedAmmonite-size_restricted.gif)

## Mod/s Affected: 

Deep Mob Learning, Blood Magic.
## Known Fix: 

none :(

**Comment by xinyuan-liu** [comment]
Deep Mob Learning - Blood Magic only allows ONE linked alter every 50 blocks by default. I think you could take the altar far away and have a try again.

**Comment by Vyraal1** [comment]
Forwarded it to IterationFunk
