### ISSUE TITLE
Basic Fluid Solidier Quest Requires 4x Gelled Toluene Quest (Backwards)

### ISSUE THREAD

**Issue by Skid-Inc** [FTBTeam/FTB-Interactions#614]
## Modpack Version: 
1.5.0

## Bug Report:
Basic Fluid Solidifier quest currently requires the 4x Gelled Toluene quest, Gelled Toluene is not required to craft the Solider, infact the Solider can be used to make Gelled Toluene. This effectively locks the Basic Fluid Solidifier (A LV machine) quest behind Pyrolyse Oven (a MV machine) quest chain.

## Expected Behavior/Suggestions:
The Gelled Toluene quest should require the Basic Fluid Solidifier quest, the TNT quest should then be linked to Gelled Toluene quest.

## Additional
TNT can't be crafted with the Basic Fluid Solidifier anyway, so that link is incorrect, it's made with a Chemical Reactor.

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/58045744-5a3b3180-7b11-11e9-8f8a-aaa07d2b6571.png)
