### ISSUE TITLE
EIO farming station crashes when using GT tools

### ISSUE THREAD

**Issue by DrTasslehoff** [FTBTeam/FTB-Interactions#617]
## Modpack Version: 
1.6

## Bug Report:
Placing any GT tools into the farming station will crash the game

## Expected Behavior/Suggestions:
It should either reject being placed into it, or not crash and use the tools as normal. Non-GT tools work fine.

## Is It Repeatable? Steps to Reproduce: 
1. Place farming station
2. Put tool inside

## Link to Log or Crash File Paste**: 
https://pastebin.com/q5bkKFzq

**Comment by Saereth** [comment]
same crash with updated ei and gt
https://hastebin.com/ulopanepel.rb

**Comment by Saereth** [comment]
yeaah.... this bug is on gtce's implemention will require some code work and pr to GTCE to resolve just added a warning tooltip on the farming station not to use GT axes in it for now
