### ISSUE TITLE
Suggestion to Start a Player with 1 free torch.

### ISSUE THREAD

**Issue by KaneHart** [FTBTeam/FTB-Interactions#618]
## Modpack Version: 
1.6.0

## Suggestion:
I'm not sure if this happens in SP as well but for sure in MP when players join their island is totally dark. Sadly placing blocks around the light sources don't seem to always update the light source and keeps their island totally dark.

Suggestion is to either start the player with a torch or give them a quest reward with a torch explaining it can fix island light issues when placed but maybe even when in your hand it can give you dynamic light effect as well.

**Comment by nowifi4u** [comment]
There is a little bug where when you create you island for the first time you have to relog in order for the light to properly work. I dont think it's worth Devs efforts to fix this little issue.

**Comment by Vyraal1** [comment]
Torch is available soon as you as get flint, that's partially why the torch by bark recipe variant was there. Reloading the chunks (usually pre-empted by logging out, waiting, and then logging back in) has been known to fix it as well. 

We think those fixes are good enough atm before granting the players a torch, not closing this issue though until we think about it some more.
