### ISSUE TITLE
Can't user Pam's HarvesCraft Flour to make dough in Primal Tech mixer

### ISSUE THREAD

**Issue by acanady** [FTBTeam/FTB-Interactions#619]
ModPack Version: 1.5.0

So the recipe for dough in the GregTech CE mixer uses the oreDictionary variant of flour, so anything labled flour works, so that includes pam's harvestcraft and any other mod. However, in the pirmal_tech basin the only flour that works is from GTCE. If this was intentional then please disregard this, if not I wanted to make sure that it was brought to light in case it was missed.

**Comment by Vyraal1** [comment]
Should only be GTCE flour, right now my idea for balancing was that since the Pams flour can be made from so many other crops, I wanted a higher form of processing to turn it into dough. It does seem clunky in hindsight, am open to suggestions.

**Comment by Rdjrjqouqcu** [comment]
How about adding a sifting recipe or some other recipe to convert from Pams flour to gregtech flour? I'd also suggest giving a higher yield for gregtech flour. Pulverizing wheat could give 2 or 4 gregtech flour per wheat while grinding materials into pams flour can stay 1:1.

**Comment by Saereth** [comment]
fixed via 3119e5b8793474f441989f2cdd915c9723ff8079
