### ISSUE TITLE
Clutter. Same items from different mods.

### ISSUE THREAD

**Issue by Uthael** [FTBTeam/FTB-Interactions#621]
## Modpack Version: 
14.23.5.28.36

## Bug Report:
There are 3 "mortar & pestle" items. 4 if you include Apothecary Mortar.

## Expected Behavior:
https://www.feed-the-beast.com/projects/ftb-interactions
I remembered reading the modpack overview from this site. I was impressed with "who needs 10 furnaces from 10 mods?". Some ingots from earlier modpacks had a bunch of variations. It was annoying having to convert them in-game just to have them stacked in the same place. I expected only one variant of each item throughout the modpack. 

## Some additional feedback:
Right from the start, I was told I should use both, a TiC hatchet and a GTCE axe. Later, I found out about salt and flour and now I see 4 different mortars, all used for crafting different stuff.

Sorry for making it look like a big deal. I thought the modpack is trying to be as clean as possible while including all these mods. I'm just trying to help prevent some OCD issues. It's nothing game-breaking, but annoying enough to have to write this.

On a side note, I'm happy to be able to craft normal chests from birch wood, Thanks for that. This feeling occured several times already, but remembering small good stuff is harder.

## Suggestions:
1. --the "important" thing-- Make Pam's Mortar & Pestle able to make GTCE and Botania recipes. OR make GTCE mortars usable in Cooking for Blockheads and its Tool Rack.
2. Optionally, make the chosen mortar upgradable (top middle, with 3 Creeper Glands around and 5 Quartz blocks below them). It would remain as the same icon in JEI, but gain the "enchanted" item effect and the placability as a block (-->Reliquary mortar).
3. Consider adding GTCE functionality (tree chopping for example) to Tinkers' Construct tools and hiding the GTCE versions. I hope that recipes which contain tools (such as knives) won't be too big of a problem. I love moddable tools from TiC.
4. Slowly get rid of duplicates everywhere you find them. 

## Is It Repeatable? Steps to Reproduce: 
1. Type "mortar" in JEI
2. Check which recipes is each of them used in

## Mod/s Affected: 
Botania
GregTech Community Edition
Pam's Harvestcraft
Reliquary

**Comment by Cata-bre** [comment]
Additionally, there are multiple knives in the modpack. Actually Additions adds a knife used exclusively for several food recipes, GTCE adds knives for several crafts that are ore-dicted as craftingToolBlade and craftingToolKnife. Why not remove the knife from Actually Additions, and ore-dict its' food recipes?

**Comment by Saereth** [comment]
while I am and will clean this up a bit, the knives are done.. the mortars not so much, there are almost 40 recipes from pams which need to be manually removed and migrated over to GT mortar for the sake of a single item displaying in jei, it's a nice goal but not high priority at all
f477d5529b090abc63a845cd2fdf0a8a37cd5e28

**Comment by Saereth** [comment]
cleaned this up as best I can for now
