### ISSUE TITLE
Botania elementium block unuseable

### ISSUE THREAD

**Issue by braingkk** [FTBTeam/FTB-Interactions#623]
## Modpack Version: 
1.4.2

## Bug Report:
the botania elementium block crafted from tossing 2 manasteel blocks in the alfheim portal is a beautiful decoration, but that is all.

## Expected Behavior/Suggestions:
the block should be craftable down to ingots/plates for use in armor and whatnot
botania manasteel block https://puu.sh/Dtgy5/ebe6a88c6c.png
'GTCE' elementium block https://puu.sh/Dtgz6/19d4886a7d.png

## Is It Repeatable? Steps to Reproduce: 
1. toss 2 manasteel blocks through an alfheim portal
2. admire your useless pink decoration

## Mod/s Affected: 
botania

## Known Fix: 
i know an attempt was made in 1.4.0 to fix this, but it is still an issue https://github.com/FTBTeam/FTB-Interactions/issues/375

**Comment by Vyraal1** [comment]
That was my fault, going to just add in a strict recipe conversion with CraftTweaker, the only worry is that if GTCE metaitem ID's shift, this might end up allowing players to make Terrasteel blocks or something.

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/58044840-c6686600-7b0e-11e9-83c5-12ed031d4e9f.png)

**Comment by Vyraal1** [comment]
![image](https://user-images.githubusercontent.com/26587049/58044846-cbc5b080-7b0e-11e9-9406-cb632999dcfd.png)

**Comment by braingkk** [comment]
awesome, thnx
