### ISSUE TITLE
Inactive Ender Core (Basic) and Ender Alloy uncraftable

### ISSUE THREAD

**Issue by iComputerfreak** [FTBTeam/FTB-Interactions#626]
## Modpack Version: 
1.4.0

## Bug Report:
The Inactive Ender Core (Basic) and Ender Alloy Ingot doesn't have a crafting recipe and therefore makes many items, like the Handy Chests, Junk Storage Unit, Mob Harness and Ender Bucket uncraftable.

## Mod/s Affected: 
Ender Utilities

## Known Fix: 
Provide a recipe for the Inactive Ender Core and the Ender Alloy Ingots and re-add them to NEI or replace them with something else in the crafting recipes.

**Comment by bookerthegeek** [comment]
This also leaves the Barrel Structure Upgrade uncraftable. I would request to either come up with alternative recipes for things that require disabled items or hide the disabled items please.

**Comment by Saereth** [comment]
this is not a bug/oversight this was intentional, most of the endercore reliant items are loot items
