### ISSUE TITLE
Empowered Oil conflicting distillery recipes 

### ISSUE THREAD

**Issue by Dr-Turtle** [FTBTeam/FTB-Interactions#629]
## Modpack Version: 

1.6.0

## Bug Report:

Putting Empowered Oil in a distillery with a config of 1 creates diesel. A config of 1 is able to create both diesel and sulfuric naphtha. Diesel can also be created on config 0.

## Expected Behavior/Suggestions:

The recipe for diesel on config 0 should be removed as it takes longer than config 1 which causes players to use config 1 as opposed to 0 and it would halt many player's automated diesel production. The empowered oil to sulfuric naphtha should be changed to config 0.

**Comment by Vyraal1** [comment]
Mistake on our part, there was a distillery and distillation tower recipe. Turns out distillery inherits distillation tower recipes hence the redundancy.
![image](https://user-images.githubusercontent.com/26587049/58040793-5f45b400-7b04-11e9-9a16-9412ac712c6f.png)
