### ISSUE TITLE
Questionable behavior with browsing enchants in JEI

### ISSUE THREAD

**Issue by Githubaccountlol** [FTBTeam/FTB-Interactions#630]
Disclaimer: I know next to nothing about the enchanting system, particularly how all things get cobbled together under the hood. These are my observations.  I thought it might have been related to the patch so I started writing and investigating, but it appears not to be, so instead here is some information.  It may not be news to you but this is the first time I've seen it.

## Modpack Version: 
1.6.1

## Bug Report:
Checking enchants in JEI shows some anomalies.  For example, looking up enchanted books and then viewing the anvil recipes page for those books always shows the correct item types, but sometimes the incorrect enchant being applied to those items.  In my world which I have been playing since 1.0.1, for example the shield bash enchantment is wrong.  If I make a new world and check the same enchantment, it appears correctly, but with a different enchant ID number.  In the new world both the book in JEI and the anvil usages pages for said book show the same number.  In my current world, those numbers are the same numbers that show up on the anvil usage pages for that same enchant name, but the name of the enchant on the anvil pages is wrong for the same ID number, and looking up the enchant by name in JEI shows a different ID number for the correct enchant name.

I loaded up my 1.6.0 instance to see if this was new to the patch and it appears the same behavior exists there.  I cheated in some items to test there and the items enchanted correctly, even though JEI usages were wrong.  Therefore it seems this is only cosmetic, and particular to world saves.

It doesn't seem to be strictly related to numerical ID ordering, some IDs higher and lower are affected, while some in between are fine.

**Comment by Vyraal1** [comment]
This might be related to when GTCe removed its radiation enchantment without adding in a blank placeholder. We went forward with this update anyways because it had important bugfixes. 

Would it be possible if you could download TellMe and do an enchantment dump with its commands and post that here?

**Comment by Githubaccountlol** [comment]
Main world:
https://pastebin.com/6iHHpp53

Fresh world:
https://pastebin.com/HASdHurF

Quite a few mismatches.
