### ISSUE TITLE
Holding enchantment on portable tank resets to Holding IV after breaking

### ISSUE THREAD

**Issue by AndromeHyperion** [FTBTeam/FTB-Interactions#631]
## Modpack Version: 
1.6.1

## Bug Report:
higher portable tank holding enchants resets to holding IV after being broken.
This even happens when I create a new profile for Interactions and test it there.

## Expected Behavior/Suggestions:
The portable tank keeps the enchant it got in the enchanting table

## Is It Repeatable? Steps to Reproduce: 
https://youtu.be/cHKd_tVZ3iY

Here you can see it reset after breaking it with a crescent hammer.

## Link to Log or Crash File Paste**: 
No crash
## Mod/s Affected: 
Apotheosis, Thermal Expansion

**Comment by Vyraal1** [comment]
Forwarded it to TeamCoFH
