### ISSUE TITLE
9Amp CEF

### ISSUE THREAD

**Issue by jeytee84** [FTBTeam/FTB-Interactions#635]
## Modpack Version: 
1.5.0

## Bug Report:
One of the CEF tiers are emitting 9Amps instead of the regular 8Amps

## Expected Behavior/Suggestions:
Right now the only way to make 8A powerlines with CEFs is using 2x4A CEFs. Or run a 16A cable from a 9A CEF. But that doesnt make sense. It would be fine if they worked the way battery buffers work (8 bats, 8 Amps), but they dont, they output the 9A even with an empty inv, and they burn 8A cables.

## Mod/s Affected: 
GTCE, CEU

## Known Fix: 
It was probably made because the 3x3 battery grid in the CEFs inventory. It just has to be set to 2x4 and an 8A output.

**Comment by Saereth** [comment]
this is a known issue part of the cable overamping issue thats been reported, closing as a duplicate
