### ISSUE TITLE
Add tooltip to Thaumcraft Celestial Notes to warn scanning the sky doesn't work

### ISSUE THREAD

**Issue by TomiBelan** [FTBTeam/FTB-Interactions#639]
## Modpack Version: 
1.5.0

## Bug Report:
It's not possible in FTB:Interactions to get Thaumcraft Celestial Notes by scanning the sun, the moon or the stars with a Thaumometer. The only way to get them is with a custom recipe in the Starlight Crafting Altar. It would be good to add a JEI tooltip that points it out.

## Expected Behavior/Suggestions:
Something like: `addTooltip("Craft it in a Starlight Crafting Altar. Scanning the sky won't work!")`

## Is It Repeatable? Steps to Reproduce: 
1. Start a new creative world
2. Use the cheater's thaumonomicon to unlock everything
3. Set time to night
4. Get a thaumometer
5. Look at the sky and right click

It says: "Nothing new can be learned from this". Normally it would give you the item, or say "You are unable to take notes of your studies." when you don't have scribing tools and paper.

## Link to Log or Crash File Paste**: 
None.

## Mod/s Affected: 
Thaumcraft 6.1.BETA26
Just Enough Dimensions 1.6.0-dev.20190407.19

## Known Fix: 
So uh... the story behind this bug report is that I tried to get the Celestial Notes the normal way, couldn't get it to work, googled if anyone else has this problem, found a single [reddit post](https://www.reddit.com/r/feedthebeast/comments/be2i3r/ftb_interactions_how_to_do_thaumcraft_celestial/) with no answer, spent way too much time delving into the source code and class files to debug why exactly it doesn't work... and then I finally noticed the custom crafting recipe. :blush: 

It feels like a waste to throw that research away so here we go, in overwhelming detail:

* In Thaumcraft, ScanSky.checkThing() returns false if `world.provider.getDimensionType() != DimensionType.OVERWORLD` (sorry Azanor)
* Just Enough Dimensions registers its own overworld-ish DimensionType [here](https://github.com/maruohon/justenoughdimensions/blob/3d87f8d0fbc8d451ee4b3d29191f5c242256901f/src/main/java/fi/dy/masa/justenoughdimensions/JustEnoughDimensions.java#L173)
* They both have `id == 0`, but they are not the same Java object :(
* This is a known issue from 2018: https://github.com/Azanor/thaumcraft-beta/issues/801

To fix this properly, one possible strategy would be to change Thaumcraft to check `...getDimensionType().getId() != 0`. Thaumcraft is not developed anymore so this will probably never happen.

It might also be possible to fix it in JED... I wonder if there has to be a 1:1 correspondence between WorldProvider and DimensionType - maybe this dimension can keep using WorldProviderSurfaceJED, but that class's getDimensionType method could return OVERWORLD. But I don't know enough about Forge to tell if anything would break.

But anyway, that's not really relevant to FTB:Interactions - the custom crafting recipes are a perfectly acceptable workaround, I just wish I found them earlier ;)

**Comment by Vyraal1** [comment]
Well at least you had an amusing story to tell, yeah the tooltip or quest should've been there to avoid players from having this issue in the first place, that was my fault. Should be added in next update.

**Comment by TomiBelan** [comment]
Nice, thanks!
