### ISSUE TITLE
Help wanted w/crafttweaker & fluid extractor

### ISSUE THREAD

**Issue by Githubaccountlol** [FTBTeam/FTB-Interactions#640]
I'm on 1.6.1 and the incomplete conversion to glass fluid recipes was making life annoying so I figured I'd dive in and figure out how to finish those off and maybe provide the patch if I was happy with how things turned out.

First off, wow, I have no idea how anyone gets things done with the current state of having to reload a pack for recipe changes.  Yikes.

Anyway, several hours later I'm finally bending this bizarre mishmash of java/notjava mixed with greggy-implementation to my will and I've hit a strange issue: despite having allegedly removed all the recipes from the fluid extractor, and fluidExtractor.recipes.length reporting zero, in game the fluid extractor still has one recipe: sand to liquid:glass.  The stupid thing is mocking me with the very thing I intend to remove.  I tested the machine and it does indeed process.

I was attempting to finesse just the recipes I wanted but debugging has led to the revelation that the nuclear option doesn't work as expected:
```
for recipe in fluidExtractor.recipes { recipe.remove(); }
print(fluidExtractor.recipes.length); // reports 0
```
What am I missing here?

**Comment by Vyraal1** [comment]
Yep that's the issue we were encountering. certain removals wasn't working, and we suspect GTCE does something that causes Tinkers CT plugin to fail (hence why our original scripts didn't work). Either way, unfortunately it is a mess atm, and still trying to figure out what's not cooperating.

**Comment by Githubaccountlol** [comment]
I found existence of the offending entry, but I'm on windows and my grep-fu is nonexistent so I gotta figure out how to find out which file it's in.

Issue as written is almost certainly invalid once I find it.

**Comment by Githubaccountlol** [comment]
80-85 in Minecraft.zs

```
fluidExtractor.recipeBuilder()
    .inputs(<ore:sand> * 1)
    .fluidOutputs([<liquid:glass> * 144])
    .duration(80)
    .EUt(28)
    .buildAndRegister();
```
