### ISSUE TITLE
Couple more progression issues/suggestions

### ISSUE THREAD

**Issue by algul** [FTBTeam/FTB-Interactions#643]
## Modpack Version: 
1.6.0

1. Plutonium/radon quests are locked behind Aurellia, but radon is needed for the improved ender eye way before that. I would move those 2 quest towards the improved ender eye quest. 

2. Vinteum ore quest require stone variant, but there is plenty of marble variant on the surface. I think marble should be valid.

3. The oregen quests in space tab seem to be incomplete or maybe they are valid only for moon. There is no mention that chromite ore is generated on Euclydes in diamond veins. And chromite is very useful.

4. Tungstate dust quest is locked behind Tungstate ore quest, but there doesn't seems to be a way to get it until Aurellia. Tungestate ore from the End is Endstone variant and doesn't count. The Tungstate ore quest should either hint to where to get it or not be prerequisite for the dust quest.

5. Moving to EV require Neodymium rods for the motors, but quest book doesn't mention anything about it. Ore seem to be locked behind Aurellia so the only way to get it(at my level of progression) seems to be redstone->rare earth->chance for small pile. Something in the quest book about it would be nice.

Generally I would suggest more hints about metallurgic progression. If some ores are obtainable only by orbital laser drill or asteroid mining mission, quest book should be clear about it. I have build them, but had no reason to use them yet.

6. Advanced chemical bath quest in metallurgy tab is pointless, there is no need for it and you can skip right to mk2 version. Only recipe that require more that 32eu is improved ender eye so I would suggest changing the quest to require mk2 version.

7. Human brain is required for the cheaters thaumonomicon, so I need to either kill myself extracting my own or turn into a cyborg. I'm not gonna lie, I don't like those options.  I would prefer third option, sacrificing villager in some way perhaps. 

8. There is lack of quest guiding progression at this point(just killed chaos dragon), yet there is still much to be done. Get antimatter, use antimatter to melt mighty chicken to get neutrornium, get draconium->awakened draconium, get infinity ingots use all of that for infinity chicken and so on. Is there plan to add more quests?

If all of this comes of as being too negative about the pack, I apologize, that's not my intention at all. English isn't my first language so it may look that way, but I actually totally enjoy this pack. In fact I didn't have this much fun playing minecraft in a long time, so well done developers. Time played 178h, number of death still 0.

**Comment by krakel** [comment]
to 1.
Plutonium/radon can you get from Thorium. Thorium can you get from Blood Magic meteor ritual.

**Comment by krakel** [comment]
to 4.
Tungstate dust can you get from End Stone. End Stone can you make with Astral from Moon Torf.

**Comment by Bang257** [comment]
To 1, you can get radon from coal processing + botania. Takes about 8k coal for enough plutonium that route
