### ISSUE TITLE
Unstable ingots duplicate items

### ISSUE THREAD

**Issue by HalfThere** [FTBTeam/FTB-Interactions#645]
## Modpack Version: 
1.5.0

## Bug Report:
Dying to unstable ingots duplicates worn items and other inventory

## Expected Behavior/Suggestions:
Unstable ingot should be usable in creating moon stones (it isn't despite showing it does in JEI)

## Is It Repeatable? Steps to Reproduce: 
1. Insert iron, stick and diamond to create an unstable ingot. Have Lapis handy, and it probably helps to have some gear equipped to duplicate.
2. Try to create moon stones. You can't. JEI fooled you. You die now.
3. Cancel out of the crafting table in a last-ditch effort to save yourself.
4. Explode. Twice.
5. Behold as there are now two of your grave, with nonsensical items inside (I tried taking off my stuff and trying again, only to still get a copy of the equipment I had on earlier? maybe it's using previous death rather than that one). Soulbound/anchored items were not duplicated

## Link to Log or Crash File Paste**: 
N/A

## Mod/s Affected: 
Interaction between whatever gravestone mod this is and Extra Utilities 2

## Known Fix: 
N/A

**Comment by HalfThere** [comment]
Closer inspection of the items confirms it's using data from my previous death to decide contents of the duplicate gravestone. Simplest solution seems to be disabling the unstable ingot, and giving a different recipe for moon stones - avoiding the issue altogether.

**Comment by Saereth** [comment]
This is an issue for the gravestone mod to fix,unfortunately I dont think active devopment is still being done  on it. Feel free to report it here, https://github.com/M4thG33k/TombManyGraves2/issues otherwise it's not something we can fix pack wise.
