### ISSUE TITLE
Invalid ore name in the uranium mark of the fallen tower ritual

### ISSUE THREAD

**Issue by DrTasslehoff** [FTBTeam/FTB-Interactions#647]
## Modpack Version: 
1.7

## Bug Report:
The uranium (black quartz) mark of the falling tower config lists "orePhosphore" when it should be "orePhosphor" resulting in regular stone blocks spawning rather than phosphor ore
https://i.imgur.com/fWnnwD9.png

## Known Fix: 
Adjust name in bloodmagic meteors config to "orePhosphor"

**Comment by AmishInvader** [comment]
It's probably supposed to be "orePhosphor" with no e at the end.  I've also noticed no oreTerraInfused and oreAerInfused seem to spawn, but they're in the config.
