### ISSUE TITLE
Game crashes when putting Greg cells into Rustic brewing barrel

### ISSUE THREAD

**Issue by xinyuan-liu** [FTBTeam/FTB-Interactions#651]
## Modpack Version: 
1.7.0

## Bug Report:
Game crashes when putting Greg cells into Rustic brewing barrel

## Expected Behavior/Suggestions:
Greg cells work well like buckets.

Or prevent Greg cells to be placed into brewing barrel.

## Is It Repeatable? Steps to Reproduce: 
Put a non-empty Greg cell, such as a honey cell, into a Rustic brewing barrel.

## Link to Log or Crash File Paste**: 
[crash-2019-05-23_18.04.16-server.txt](https://github.com/FTBTeam/FTB-Interactions/files/3211606/crash-2019-05-23_18.04.16-server.txt)

## Mod/s Affected: 
Rustic

## Known Fix: 
None

**Comment by Kanzuke117** [comment]
I've done this on a server, was a TickingEntityException so we had to use the forge commands to clean it up and keep that world version

**Comment by Saereth** [comment]
this is a mod issue, not a pack issue, please report it to rusitc
https://github.com/the-realest-stu/Rustic/issues
