### ISSUE TITLE
Super Factory Manager's whitelist/blacklist Missing GTCE metaitems.

### ISSUE THREAD

**Issue by Senbotsu** [FTBTeam/FTB-Interactions#653]
## Modpack Version: 
1.5.0

## Bug Report:
All Gregtech meta items/dusts are missing from the Super Factory Manager's whitelist in the Machine Inventory Manager.  Spessaratine Ore exists, but not the dust. Same for Topaz, Blue Topaz, Aluminum, Carbon, etc.

## Expected Behavior/Suggestions:
As the issue exists for all gregtech:meta_item_# items from Almandine to Quartzite, I'm not sure it's easily fixable. 

## Is It Repeatable? Steps to Reproduce: 
1. Open Machine Inventory Manager
2. Select Create Input
3. Expand Box and select Items Submenu
4. Click on any ? box, then type in item to be added to whitelist, EG Spessartine
5. See gregtech_ore_spessartine_0 in all its variations, but no gregtech:meta_item_1 dust.

## Link to Log or Crash File Paste**: 
n/a

## Mod/s Affected: 
Super Factory Manager

## Known Fix: 
You can use another method to move these items, such as itemducts + servos with whitelists, but it would be nice to be able to use SFM to automate my electrolyzers Instead.

**Comment by Kanzuke117** [comment]
Victim of metadata abuse, as a workaround you can use the special search `.inv` to list items in your inventory, and select the dust/plate/rod/etc if you're holding it

**Comment by Saereth** [comment]
yeah use .inv and/or ask @TeamDman to implement on SFM
