### ISSUE TITLE
Cluster mill recipes disabled in config, but not the machine itself

### ISSUE THREAD

**Issue by braingkk** [FTBTeam/FTB-Interactions#654]
## Modpack Version: 
1.6.1

## Bug Report:
the cluster mill is currently craftable ingame, but serves no purpose as foil crafting in them is disabled.

## Expected Behavior/Suggestions:
either cluster foil is a recipe, or the block should not be craftable

## Is It Repeatable? Steps to Reproduce: 
1. craft a cluster mill
2. look at your powered decoration
3. try not to sob at the wasted 6 motors

## Mod/s Affected: 
GTCE
SoG

## Known Fix: 
either disable the machine, or give them a use

**Comment by Rdjrjqouqcu** [comment]
The same issue exists for the microwave

**Comment by braingkk** [comment]
microwave still works, it is just a food smelter
