### ISSUE TITLE
Composer ignores essence phial types

### ISSUE THREAD

**Issue by tasosalvas** [FTBTeam/FTB-Interactions#655]
## Modpack Version: 
1.6.1

## Bug Report:
The composer chicken recipes ignore the phial's type.

## Is It Repeatable? Steps to Reproduce: 
* Try to craft a Lapis Blue or Graphite chicken, get Copper chicken instead.
* Try a phial of herba, get Copper chicken still.

**Comment by tasosalvas** [comment]
Behavior persists in 1.7.0

## Mods Affected
(just cause I felt I cut off too much of the template)

* Soulus (Where the crafting is done)
* Thaumcraft (Source of the misbehaving essentia phials)
* FTB Quests (Iron enriched egg unobtainable)

**Comment by TomyLobo** [comment]
The same happens with the iron chicken. You get a zinc chicken instead.

**Comment by Saereth** [comment]
wont matter since solus is getting removed
