### ISSUE TITLE
LV solar panel OP

### ISSUE THREAD

**Issue by AndromeHyperion** [FTBTeam/FTB-Interactions#659]
## Modpack Version: 
1.7.0

## Bug Report:
If you place a battery buffer, fill it with batteries and put a solar panel (lv) on it, it will charge the batteries with a faster rate then a naquadah reactor.

## Expected Behavior/Suggestions:
It should generate 32eu/t instead of the amount it does now.

## Is It Repeatable? Steps to Reproduce: 
https://youtu.be/UQn1FwI00GE

## Mod/s Affected: 
gregtech

**Comment by braingkk** [comment]
it is easy to test, all 3 tiers of solars give the same power rates, tho they are gated by infinity chicken making them VERY late game. i feel like they are intended to be op, but there is no point in even the lv one, as the base one is the same power

**Comment by AndromeHyperion** [comment]
High end

**Comment by braingkk** [comment]
is interesting that they drop as early as Eucl prime in dungeons.
might have left the issue open until a pack dev said something, hopefully they still see it and respond

**Comment by AndromeHyperion** [comment]
True, was a bit quick with closing it.

**Comment by Saereth** [comment]
the battery buffers are fixed in the new version of gtce
