### ISSUE TITLE
Cyberware Death Loop

### ISSUE THREAD

**Issue by EtZone** [FTBTeam/FTB-Interactions#660]
## Modpack Version: 
1.5.0

## Bug Report:
Cyberware can cause the player to enter an endless deathloop if they remove their human heart with no replacement. The surgery will kill the player. Upon respawning, the player has a few seconds to act before immediately being killed due to having no heart. This repeats forever, forcing the player to enter creative mode or otherwise cheat to continue to play in that world.

## Expected Behavior/Suggestions:
Removal of a vital organ should kill the player, but only once (the organ is replaced inside the player body on respawn). The concept of a death loop seems extremely punishing and would be very problematic if a player cannot access creative mode (is on a server, no admins/mods/op'd players are online).

## Is It Repeatable? Steps to Reproduce: 
Place robosurgeon on top of surgery chamber. Open robosurgeon and remove the heart. Enter the surgery chamber and close it. 

## Link to Log or Crash File Paste**: 
N/A

## Mod/s Affected: 
Cyberware

## Known Fix: 
Not using Cyberware or having to know this issue exists before playing with the mod.

**Comment by krakel** [comment]
There exist also a problem with legs. If you remove your legs and go outside the chamber you can not move anymore. Also I thing if you remove your arms you can not interact with inventories. This mod is very dangerous!

**Comment by braingkk** [comment]
tried, was unable to trigger a death loop https://youtu.be/-hBc0VxAZK0

**Comment by Saereth** [comment]
yep no development happening on that mod so wont be fixed.
