### ISSUE TITLE
Fusion Reactor mk 2 and 3 quests require too many casings to be crafted.

### ISSUE THREAD

**Issue by Giovanni-NL** [FTBTeam/FTB-Interactions#662]
## Modpack Version: 
1.7.0

## Bug Report:
The requirements in the quest for the fusion reactor mark 2 tell you to make 121 Fusion Machine Casings,  Only 79 casings are actually needed to build the multi block structure.  The rest of the structure can consist of input hatches, output hatches, energy input hatches, coils and the fusion reactor block, none of which can be made with a Fusion Machine Casing.  So to ask for 42 extra (rather expensive) blocks to be crafted is not needed at all. 

N.B. The same goes for the fusion reactor mark 3 quest and the required 121 Fusion Machine Casings MK II.

## Expected Behavior/Suggestions:
Change the quest requirement so that only 79 Fusion Machine Casings need to be crafted for the quest to complete.

## Is It Repeatable? Steps to Reproduce: 
n/a

## Link to Log or Crash File Paste**: 
n/a

## Mod/s Affected: 
Quest book

## Known Fix: 
See suggestions.

**Comment by braingkk** [comment]
just my 2 cents, i am not a dev of the pack.

i am not sure if there is a good method for quests, there is the base recipe, and then the stupid things you can do with multiblocks. technically you don't NEED to put in the 16 power inputs and loads of input/output hatches in the reactor, even if it makes the multiblock cheaper.

here are some other multiblocks and stupidity you can technically do.
Large Boiler only needs the controller and 2pipe casings, as technically every other block can be input/outputs
The freezer only 14 casings and the controller as you can have up to 11 hatches/buses on it.
The blast furnace only needs 10 heat casings total, as the rest of the bottom can be hatches/buses.
Even the turbine multiblocks can have additional inputs/outputs installed.
