### ISSUE TITLE
Dynamic tanks loosing contents in single player

### ISSUE THREAD

**Issue by MCChiter** [FTBTeam/FTB-Interactions#663]
## Modpack Version: 
1.6.1

## Bug Report:
after leaving and logging back into single player world dynamic tank becomes empty 

## Mod/s Affected: 
Mekanism

I do have optifine installed.

**Comment by tjsd** [comment]
break and replace a block and it shows up again.
The solution is to move the dynamic tank to somewhere else in the chunk.
