### ISSUE TITLE
Server stuck on "Stopping aura thread for dim -2"

### ISSUE THREAD

**Issue by FrankyixH** [FTBTeam/FTB-Interactions#665]
## Modpack Version: 
1.6.1

## Bug Report:
When starting a server by executing the ServerStart.bat or the FTBserver-1.12.2-14.23.5.2836-universal.jar both on my pc or on a rented server the loading gets stuck at:
"[INFO] Stopping aura thread for dim -2"

When executing the jar on my PC the whole PC started lagging heavily at this point until i terminated the process.
When running it on the rented server it terminated the process on its own after a few minutes.

## Is It Repeatable? Steps to Reproduce: 
1. Download the server zip file and extract in target folder

2a. run FTBinstall.bat
3a. run ServerStart.bat
4a. switch eula to true
5a. run ServerStart.bat (or FTBserver jar)

2b. run ServerStart.bat
3b. switch eula to true
4b. run ServerStart.bat (or FTBserver jar)

both lead to the same outcome

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/f010c0a5

## Mod/s Affected: 
maybe thaumcraft (visible in the cmd version of the log, which i didnt upload because ist incomplete)

**Comment by cughtagh** [comment]
Have you tried connecting to the server? I'm pretty sure that is just the last line of output and it's done loading.

**Comment by FrankyixH** [comment]
when trying to connect it says something like: "Disconnected. server is starting."

**Comment by cughtagh** [comment]
Interesting, because my console stops on the same line, but the server works after that. So either your's freezes on the last line, or there's a problem somewhere else.

**Comment by Saereth** [comment]
yeah we'll need to see some logs or profiling, seems like your system is running out of resources or something else is causing it to crash.

**Comment by Saereth** [comment]
too long with no logs, closing
