### ISSUE TITLE
Excessive Network traffic

### ISSUE THREAD

**Issue by Cruddly** [FTBTeam/FTB-Interactions#666]
## Modpack Version: 
1.7 and prior

## Bug Report:
Client is consuming 4-5Mb/s to talk with remote server (a whole heck more than I have ever seen before with other packs or vanilla) and server is kicking client with timeouts every few minutes despite that. Seems that there is excessive cross-talk between the two.

## Expected Behavior/Suggestions:
Client <-> server under 2Mb/s with less booting as a result of the reduced traffic.

## Is It Repeatable? Steps to Reproduce: 
Problem started at LV, increased into MV, modest void base.

## Link to Log or Crash File Paste**: 
No crash file, just D/C's and lots of netty.io errors.

**Comment by tjsd** [comment]
have you tried disabling minetogether mod and see if that affects it?

**Comment by Saereth** [comment]
gtce sends a ton of packet data, no work around for it
