### ISSUE TITLE
Migrate Creative key to assembly line instead of Fusion Crafter

### ISSUE THREAD

**Issue by braingkk** [FTBTeam/FTB-Interactions#671]
## Modpack Version: 
1.61.

## Bug Report:
when crafting the creative key, despite JEI saying wehatever it says, you only need 1 item in each injector. if oyu have the shown amounts [32, 16 etc] only 1 of each item is consumed

## Expected Behavior/Suggestions:
recipe should require all shown items and consume them all

## Is It Repeatable? Steps to Reproduce: 
https://youtu.be/54lMMu_uMGU

## Known Fix: 
no idea, not sure if this recipe is possible with DE crafting

**Comment by skingnet** [comment]
I just completed the modpack on version 1.7 (the previous release) and noticed the same thing. I also updated to the latest release (1.9.1) and verified the problem still exists there too.

To clarify, this is the final step at completing the modpack...  "Congratulations!" quest...

The following items are "what is currently"/"what should be" required:
2/2 Chaotic Core
2/64 Infinity Block
2/32 Neutronium Block
2/16 Awakened Core
2/2 Wetware Mainframe
1/1 Euclydes Prime Artifact 
1/1 Aurellia Artifact

I spent many gathering the above items only to have them clog my inventory now, lol..

**Comment by Saereth** [comment]
This is an issue with draconic evolution... hopefully the mod update fixes it

**Comment by Saereth** [comment]
https://github.com/brandon3055/Draconic-Evolution/issues/1426

**Comment by Saereth** [comment]
this is apparently an internal limitation of fusion crafting, assembly line will do it without an issue however
