### ISSUE TITLE
[Suggestion] Allow Infused Nitro-Diesel use in Basic Diesel Generators

### ISSUE THREAD

**Issue by gattsuru** [FTBTeam/FTB-Interactions#672]
## Modpack Version: 
1.7.0

## Bug Report:
Infused Nitro-Diesel is an MV-tier recipe, and as a result, can not be inserted into LV-tier consumers.  

## Expected Behavior/Suggestions:
This may be intentional and it's not unrealistic to have certain octanes or power densities of fuel usable in better-designed engines, but right now it's the only fuel for any engine that has that restriction.  Relatively few players are going to look into building Diesel power before MV-tier (and even fewer will have a big Infused Nitro-Diesel setup before EV-tier), but with the Empowered Oil recipes it is viable to bootstrap into a Bio Diesel fuel loop early enough to justify making eight or nine of them, and this eventually results in having to run two fuel lines through your base, or move a lot of equipment to handle the transformers.

## Is It Repeatable? Steps to Reproduce: 
1.  Place a Basic Diesel Generator.
2.  Try to put Infused Nitro-Diesel into it.

## Mod/s Affected: 
GregTechCE/CraftTweaker.

## Known Fix: 
Content of GregTechFuels.zs to :
import mods.gregtech.recipe.RecipeMaps;

print("---------------Gregtech Start------------------");
	var infusedFuel = mods.gregtech.recipe.FuelRecipe.create(<liquid:infused_nitrofuel> *2, 60, 32);
	RecipeMaps.DIESEL_GENERATOR_FUELS.addRecipe(infusedFuel);

print("----------------Gregtech End-------------------");

**Comment by Saereth** [comment]
this is intended, people should just be transforming power as needed with the higher tier fuel
