### ISSUE TITLE
Celestial Altar quest requires Stellar Alloy Quest, but Iridescant Altar needs Stellar Alloy

### ISSUE THREAD

**Issue by thePalindrome** [FTBTeam/FTB-Interactions#676]
## Modpack Version: 
1.7.0

## Bug Report:
The Celestial Altar quest requires the Stellar Alloy quest, despite not using Stellar Alloy,
however the Iridescent Altar requires Stellar Alloy, but only depends on Sky Stone

## Expected Behavior/Suggestions:
The Stellar Alloy Quest should be moved near the Iredescent Altar quest, and should be a prereq of that, not the Celestial Altar

**Comment by MCChiter** [comment]
Hey, someone was three days quicker than i am to mention it! as a proud member of "OMFGHDIGTA" or OH MY FLIPPIN GOD HOW DO I GET THIS ACHIEVEMENT i am highly bamboozled by it. also with the fact that mob agonizer requires specific CEU with one slot to be complete
