### ISSUE TITLE
Rocket disappears on trip to Aurelia from space station.

### ISSUE THREAD

**Issue by ggkhs** [FTBTeam/FTB-Interactions#677]
## Modpack Version: 
1.7.0 (it had the same issue on 1.6.1)

## Bug Report:
When you try to access Aurelia with a rocket from your station after you reach the maximum
altitude of y:1000 the rocket disappears and you are stuck there, without being teleported.

## Expected Behavior/Suggestions:
It should transfer you to the planet.

## Is It Repeatable? Steps to Reproduce: 
https://www.youtube.com/watch?v=eSk3L2bde98

Also I would like to add that this is on a Sponge server. We tried to force load it at startup as seen [here](https://i.imgur.com/umcMZUj.png) but it would still cause the same issue, it also seems we cannot teleport there by commands.
Euclydes and rest of the advRocketry dimensions work as intended.

It does **not** happen in **SinglePlayer**

Any suggestions on what we can do to fix it?

**Comment by Saereth** [comment]
I cant imagine why you cant use /cofh tpx to teleport there, sponge issue?

**Comment by Saereth** [comment]
I cant produce this on a non sponge server, and even successfully went there on a sponge server as well, try taking this over to the AR dev for further investigation, nothing we can do to reproduce/help with it from a pack perspective. https://github.com/zmaster587/AdvancedRocketry
