### ISSUE TITLE
Ender utilities handy bag FTB Utils buttons

### ISSUE THREAD

**Issue by Aphenon** [FTBTeam/FTB-Interactions#678]
## Modpack Version: 
1.7.0

## Bug Report:
When a Ender Utilities Handy bag is in the inventory, the FTB Utils buttons are hidden.

## Expected Behavior/Suggestions:
The buttons show up

## Is It Repeatable? Steps to Reproduce: 
1. Have a Bag in inventory

## Mod/s Affected: 
FTB Utilities
Ender Utilities

## Known Fix: 
Compatibility issue, devs needs to work it out.

**Comment by Saereth** [comment]
yea this is for those devs to work out, not a pack specific issue
