### ISSUE TITLE
Recipe conflict between GTCE and Pickle Tweaks

### ISSUE THREAD

**Issue by Azarhiel** [FTBTeam/FTB-Interactions#679]
## Bug Report:
Recipe conflict between GT Flint Axe and Pickle Tweaks Flint Axe

## Expected Behavior/Suggestions:
Crafting GT flint axe ending with pickle tweaks flint axe. Not valid for quest.

## Is It Repeatable? Steps to Reproduce: 
 3 flint and 2 sticks + crafting table =  Pickle Tweaks flint axe instead of GT flint axe

## Mod/s Affected: 
GTCE and Pickle Tweaks

**Comment by Saereth** [comment]
cannot reproduce, verify your scripts are new borked (reinstall them)
![image](https://user-images.githubusercontent.com/9200909/59520332-b63a7100-8e97-11e9-8770-e5fb2b28516c.png)
