### ISSUE TITLE
Oil doesn't generate for AS fountain.

### ISSUE THREAD

**Issue by maskota** [FTBTeam/FTB-Interactions#680]
## Modpack Version: 
1.7.0

## Bug Report:
Bad config file for Astral Sorcery fountain fluid generation.
config/astralsorcery/fluid_rarities.cfg line 12, char 36 has extra comma
Right now gregtech oil doesn't generate in the world, only water and AA crystalized oil.

## Known Fix: 
Remove comma.

What about retrogen? I have quite big world generated without oil.

**Comment by ShaneCourtrille** [comment]
I'm on 1.7.0 as well and the specified section looks like this for me..  I don't see an extra comma?

    S:data <
        oil;200000000;50000000;7500,
        crystaloil;20000000;5000000;2500
     >

**Comment by maskota** [comment]
The one comma there is is a extra one, there shouldn't be any. Like this:

S:data <
    oil;200000000;50000000;7500
    crystaloil;20000000;5000000;2500
 >
