### ISSUE TITLE
Game Crashes upon World Load and Hotbar Filling with Items (With Video)

### ISSUE THREAD

**Issue by dels0l** [FTBTeam/FTB-Interactions#686]
- VIDEO
https://www.youtube.com/watch?v=x4SWFTCnlkE&feature=youtu.be

- Modpack Version: 
1.7.0 (Recommended)

- Bug Report:

Game loads into a sort of laggy, frame-skippy title screen which I assume is due to memory leaks.
I then try to create a single player world; it loads, I see the skyblock, skybox, and my hotbar fills with the expected items. Immediately following this the game crashes. Duplicatable every time, no success. I am able to play ANY other FTB pack.

- Expected Behavior/Suggestions:

The game should continue to load until I am able to play normally.

- Is It Repeatable? Steps to Reproduce: 

1. Open launcher
2. Launch Interactions
3. Singleplayer
4. Create world
5. World loads, almost fully, then crashes.

- Log

LOG: https://paste.feed-the-beast.com/view/b336cd9b

**Comment by dels0l** [comment]
If there's anymore information needed to help diagnose the issue, I'll be glad to share! Just let me know.

**Comment by dels0l** [comment]
I have tried many different things, including reverting to the original version of Interactions.
It appears to me that my computer might be shutting the game down as there is no indication of fatal errors in the log file. I am still concerned and would like to find a fix, as my computer runs all of the other modpacks at full graphics with no issues whatsoever. It may be a software issue, but I just can't think of anything to try. Any suggestions would be hugely appreciated.

**Comment by Saereth** [comment]
your actual java is crashing not minecraft specifically, look for a file named hs_err_pidxxxx that'll be your jvm crashlog file, we'll need to see that to help. Make sure you're memory allocation is good (enough ram but still leaving enough for your os) obviously and consider reinstalling java. we'll go from there once you provide to log but this doesnt seem to be a pack specific issue
