### ISSUE TITLE
FTB Interactions freezes after connecting to server (video)

### ISSUE THREAD

**Issue by doctorluk** [FTBTeam/FTB-Interactions#689]
## Modpack Version: 
1.7.0

## Bug Report:
When joining my server, the game starts to stutter until it completely freezes. The music is still audible in the background. Interaction with the game is nearly impossible. One frame approx every minute.

## Expected Behavior/Suggestions:
Join the server, get some loading stuttering that resolves itself and play.

## Is It Repeatable? Steps to Reproduce: 
https://www.youtube.com/watch?v=SC-8RGB-76s

The way you see it in this video is 1:1 the same as it happens without recording.

Start game, connect to server.
I tried this with a clean installation. This has been happening since yesterday.

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/0889c72a

## Mod/s Affected: 
unknown

## Known Fix: 
unknown

**Comment by Saereth** [comment]
there is alot this could possibly be. We need latest.logs from you and preferably the server at the time you connect to see whats going on. What are the system specs for you and the server specifically ram etc.

**Comment by doctorluk** [comment]
I'll see if I can generate those logs soon.

Fun fact is that I am unable to even play singleplayer as it freezes, too, even after completely deleting and reinstalling the mod.

Are there cache files or anything like this produced by Java that could cause this?

**Comment by for-lack-of-a-better-name-j** [comment]
I have this exact same problem, would anyone like my logs??? I could get those in a jiffy
