### ISSUE TITLE
Thermal Logistics Crashes And World Corruption

### ISSUE THREAD

**Issue by Xela10001** [FTBTeam/FTB-Interactions#690]
## Modpack Version: 
1.5.0

## Bug Report:
Crashes with thermal logistics

## Expected Behavior/Suggestions:
Just trying to create an automated polyethelene setup in a test world but my worlds randomly crash and become corrupt when using them.

## Is It Repeatable? Steps to Reproduce: 

I'm not sure if its repeatable, the first crash happened when i broke an itemduct with a crafter and the second one just happened randomly.

## Link to Log or Crash File Paste**: 
[2nd crash](https://pastebin.com/T31HGwwN)
[1st crash](https://pastebin.com/SELjXt1G)

## Mod/s Affected: 
Thermal Logistics

**Comment by Saereth** [comment]
new update should resolve this
