### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by mtrevor** [FTBTeam/FTB-Interactions#691]
## Modpack Version: 
1.7.0

## Bug Report:
Minecraft crashes during initial load (around stage 4), throwing back to the launcher.

## Expected Behavior/Suggestions:
The game loads

## Is It Repeatable? Steps to Reproduce: 
1. Install FTBI and play for several days
2. Exit
3. Try to start FTBI again
4. Crash

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/911ffd9e

## Known Fix: 
The problem appears to be a corrupted JSON file. Reinstalling FTBI fixes the issue temporarily, but it returns on the next run.

**Comment by Saereth** [comment]
not sure why your json is corrupting, seems weird. Any steps to reproduce beyond just time? Perhaps a hardward/os issue on your end?
