### ISSUE TITLE
Sponges soaking up my damage.

### ISSUE THREAD

**Issue by Grim-Wolfblood** [FTBTeam/FTB-Interactions#692]
Weapon has sponge parts
Does not hurt with stab or lunge
So much disappoint

So I've made a few TiCon weapons (boradsword x2, longsword), and gave them all spongy bits; handles or tangs (never the "head"). They do no damage. Other materials used in conjunction were flint, iron, bronze, and bone.

I was having such fun imagining myself smashing faces with a rubber ducky of doom.

*squeak squeak*

**Comment by Neeve01** [comment]
This is an intended TiCon feature. You should only use sponge parts on tools (e. g., to give them the Silk Touch modifier), not on weapons.

**Comment by Grim-Wolfblood** [comment]
Thank you for the quick response.
