### ISSUE TITLE
Doomlike dungeons on the moon are not generating

### ISSUE THREAD

**Issue by colin342** [FTBTeam/FTB-Interactions#694]
## Modpack Version: 
1.7.0

## Bug Report:
Doomlike dungeons does not generate on the moon although it is supposed to be according to the configs if I am not mistaken. The chest spawn empty but the dungeon does not spawn.

<img width="1920" alt="Schermafbeelding 2019-06-09 om 22 14 26" src="https://user-images.githubusercontent.com/30210823/59163657-33ff2500-8b04-11e9-9391-203c77673867.png">

**Comment by nowifi4u** [comment]
Same thing happends on Stellaria planet: Lots of chests in the water, but absolutely no dungeons whatsoever

**Comment by Saereth** [comment]
this is a known issue with doomlike dungeons, dungeons sometimes dont full generate within 1km of spawn, nothing we can do about it as DLD is no longer under development, just explore out farther and you'll find them
