### ISSUE TITLE
Moon has wrong biomeIDs, also has no moon's ores and moon dirts

### ISSUE THREAD

**Issue by nanmumc** [FTBTeam/FTB-Interactions#695]
## Bug Report:
 When I first reach the Luna (moon), there are only Stones and Overworld's ores. (But has moon dungeons). Then I compared the old version of FTB interaction (1.5.0), I found there are some wrong config in the 

...\FTBInteractions-1.7.0-1.12.2\minecraft\saves\New world\advRocketry\planetDefs.xml

For FTB v1.7, the biomeIDs of moon (or Luna) was set as wizardry:wizardry_torikki, and the truely moon was set in Aurellia (Mars DIM147). 

**planetDefs.xml for FTB v1.7** ：
```
<galaxy>
	<star name="Celesta" temp="100" x="0" y="0" size="1.0" numPlanets="0" numGasGiants="0" >
		<planet name="Terra" DIMID="0" dimMapping="" customIcon="earthlike">
			<isKnown>true</isKnown>
			<fogColor>1.0,1.0,1.0</fogColor>
			<skyColor>1.0,1.0,1.0</skyColor>
			<gravitationalMultiplier>100</gravitationalMultiplier>
			<orbitalDistance>100</orbitalDistance>
			<orbitalPhi>0</orbitalPhi>
			<rotationalPeriod>24000</rotationalPeriod>
			<atmosphereDensity>90</atmosphereDensity>
			<planet name="Luna" DIMID="145" customIcon="moon">
				<isKnown>true</isKnown>
				<fogColor>1.0,1.0,1.0</fogColor>
				<skyColor>1.0,1.0,1.0</skyColor>
				<gravitationalMultiplier>16</gravitationalMultiplier>
				<orbitalDistance>100</orbitalDistance>
				<orbitalPhi>0</orbitalPhi>
				<rotationalPeriod>72000</rotationalPeriod>
				<atmosphereDensity>0</atmosphereDensity>
				<biomeIds>wizardry:wizardry_torikki</biomeIds>
			</planet>
		</planet>
		<planet name="Nova" DIMID="100" dimMapping="" customIcon="earthlike">
			<isKnown>true</isKnown>
			<fogColor>1.0,1.0,1.0</fogColor>
			<skyColor>1.0,1.0,1.0</skyColor>
			<gravitationalMultiplier>100</gravitationalMultiplier>
			<orbitalDistance>110</orbitalDistance>
			<orbitalPhi>0</orbitalPhi>
			<rotationalPeriod>24000</rotationalPeriod>
			<atmosphereDensity>100</atmosphereDensity>
		</planet>
	</star>
	<star name="Stellaria" temp="105" x="5" y="7" size="1.0" numPlanets="0" numGasGiants="0" >
		<planet name="Euclydes Prime" DIMID="146" customIcon="earthlike">
			<isKnown>true</isKnown>
			<hasRings>true</hasRings>
			<ringColor>0.4,0.4,0.7</ringColor>
			<fogColor>1.0,1.0,1.0</fogColor>
			<skyColor>1.0,1.0,1.0</skyColor>
			<gravitationalMultiplier>104</gravitationalMultiplier>
			<orbitalDistance>90</orbitalDistance>
			<orbitalPhi>0</orbitalPhi>
			<rotationalPeriod>28000</rotationalPeriod>
			<atmosphereDensity>110</atmosphereDensity>
			<biomeIds>wizardry:wizardry_underworld,advancedrocketry:deepswamp,minecraft:ocean</biomeIds>
			<artifact>contenttweaker:overworldessencer 0 1</artifact>
			<oceanBlock>gregtech:fluid.blue_vitriol_water_solution</oceanBlock>
		</planet>
	</star>
	<star name="Xoal" temp="150" x="0" y="-19" size="2.5" numPlanets="0" numGasGiants="0" blackHole="true">
		<planet name="Aurellia" DIMID="147" customIcon="MarsLike">
			<isKnown>true</isKnown>
			<fogColor>1.0,1.0,1.0</fogColor>
			<skyColor>1.0,1.0,1.0</skyColor>
			<gravitationalMultiplier>200</gravitationalMultiplier>
			<orbitalDistance>30</orbitalDistance>
			<orbitalPhi>30</orbitalPhi>
			<rotationalPeriod>2400</rotationalPeriod>
			<atmosphereDensity>80</atmosphereDensity>
			<biomeIds>advancedrocketry:moon,advancedrocketry:space</biomeIds>
			<artifact>contenttweaker:overworldessencel 0 1</artifact>
			<oceanBlock>tconstruct:molten_obsidian</oceanBlock>
		</planet>
	</star>
</galaxy>
```

## **Solution(for Temporary)**
Replace the planetDefs.xml with the version of FTB v1.5 as followed.**(WARNING: do not responsible for the further BUGS)**
And then you can enjoy the moon in the newly formed chunks:
![image](https://user-images.githubusercontent.com/25528572/59172255-a52cef80-8b79-11e9-9667-0620f50c81a9.png)

```
<galaxy>
	<star name="Celesta" temp="100" x="0" y="0" size="1.0" numPlanets="0" numGasGiants="0" >
		<planet name="Terra" DIMID="0" dimMapping="" customIcon="earthlike">
			<isKnown>true</isKnown>
			<fogColor>1.0,1.0,1.0</fogColor>
			<skyColor>1.0,1.0,1.0</skyColor>
			<gravitationalMultiplier>100</gravitationalMultiplier>
			<orbitalDistance>100</orbitalDistance>
			<orbitalPhi>0</orbitalPhi>
			<rotationalPeriod>24000</rotationalPeriod>
			<atmosphereDensity>90</atmosphereDensity>
			<planet name="Luna" DIMID="145" customIcon="moon">
				<isKnown>true</isKnown>
				<fogColor>1.0,1.0,1.0</fogColor>
				<skyColor>1.0,1.0,1.0</skyColor>
				<gravitationalMultiplier>16</gravitationalMultiplier>
				<orbitalDistance>100</orbitalDistance>
				<orbitalPhi>0</orbitalPhi>
				<rotationalPeriod>72000</rotationalPeriod>
				<atmosphereDensity>0</atmosphereDensity>
				<biomeIds>advancedrocketry:moon</biomeIds>
			</planet>
		</planet>
		<planet name="Nova" DIMID="100" dimMapping="" customIcon="earthlike">
			<isKnown>true</isKnown>
			<fogColor>1.0,1.0,1.0</fogColor>
			<skyColor>1.0,1.0,1.0</skyColor>
			<gravitationalMultiplier>100</gravitationalMultiplier>
			<orbitalDistance>110</orbitalDistance>
			<orbitalPhi>0</orbitalPhi>
			<rotationalPeriod>24000</rotationalPeriod>
			<atmosphereDensity>100</atmosphereDensity>
		</planet>
	</star>
	<star name="Stellaria" temp="105" x="5" y="7" size="1.0" numPlanets="0" numGasGiants="0" >
		<planet name="Euclydes Prime" DIMID="146" customIcon="earthlike">
			<isKnown>true</isKnown>
			<hasRings>true</hasRings>
			<ringColor>0.4,0.4,0.7</ringColor>
			<fogColor>1.0,1.0,1.0</fogColor>
			<skyColor>1.0,1.0,1.0</skyColor>
			<gravitationalMultiplier>104</gravitationalMultiplier>
			<orbitalDistance>90</orbitalDistance>
			<orbitalPhi>0</orbitalPhi>
			<rotationalPeriod>28000</rotationalPeriod>
			<atmosphereDensity>110</atmosphereDensity>
			<biomeIds>advancedrocketry:alien forest,advancedrocketry:oceanspires,minecraft:ocean</biomeIds>
			<artifact>contenttweaker:overworldessencer 0 1</artifact>
			<oceanBlock>gregtech:fluid.blue_vitriol_water_solution</oceanBlock>
		</planet>
	</star>
	<star name="Xoal" temp="150" x="0" y="-19" size="2.5" numPlanets="0" numGasGiants="0" blackHole="true">
		<planet name="Aurellia" DIMID="147" customIcon="MarsLike">
			<isKnown>true</isKnown>
			<fogColor>1.0,1.0,1.0</fogColor>
			<skyColor>1.0,1.0,1.0</skyColor>
			<gravitationalMultiplier>200</gravitationalMultiplier>
			<orbitalDistance>30</orbitalDistance>
			<orbitalPhi>30</orbitalPhi>
			<rotationalPeriod>2400</rotationalPeriod>
			<atmosphereDensity>80</atmosphereDensity>
			<biomeIds>advancedrocketry:hotdryrock,advancedrocketry:crystalchasms</biomeIds>
			<artifact>contenttweaker:overworldessencel 0 1</artifact>
			<oceanBlock>tconstruct:molten_obsidian</oceanBlock>
		</planet>
	</star>
</galaxy>
```

**Comment by Saereth** [comment]
I have a fresh install of 1.7 and the planetarydefs.xml file does not look at all like yours. We hardset the biome ids, we arent even using mapped ids so I'm not sure where thats coming from for you

`
<galaxy>
	<star name="Celesta" temp="100" x="0" y="0" size="1.0" numPlanets="0" numGasGiants="0">
		<planet name="Terra" DIMID="0" dimMapping="" customIcon="earthlike">
			<isKnown>true</isKnown>
			<fogColor>1.0,1.0,1.0</fogColor>
			<skyColor>1.0,1.0,1.0</skyColor>
			<gravitationalMultiplier>100</gravitationalMultiplier>
			<orbitalDistance>100</orbitalDistance>
			<orbitalTheta>0</orbitalTheta>
			<orbitalPhi>0</orbitalPhi>
			<rotationalPeriod>24000</rotationalPeriod>
			<atmosphereDensity>90</atmosphereDensity>
			<planet name="Luna" customIcon="moon">
				<isKnown>true</isKnown>
				<fogColor>1.0,1.0,1.0</fogColor>
				<skyColor>1.0,1.0,1.0</skyColor>
				<gravitationalMultiplier>16</gravitationalMultiplier>
				<orbitalDistance>100</orbitalDistance>
				<orbitalTheta>0</orbitalTheta>
				<orbitalPhi>0</orbitalPhi>
				<rotationalPeriod>72000</rotationalPeriod>
				<atmosphereDensity>0</atmosphereDensity>
				 <biomeIds>72, 81</biomeIds>
			</planet>
		</planet>
		<planet name="Nova" DIMID="100" dimMapping="" customIcon="earthlike">
			<isKnown>true</isKnown>
			<fogColor>1.0,1.0,1.0</fogColor>
			<skyColor>1.0,1.0,1.0</skyColor>
			<gravitationalMultiplier>100</gravitationalMultiplier>
			<orbitalDistance>110</orbitalDistance>
			<orbitalTheta>180</orbitalTheta>
			<orbitalPhi>0</orbitalPhi>
			<rotationalPeriod>24000</rotationalPeriod>
			<atmosphereDensity>100</atmosphereDensity>
		</planet>
    </star>
	<star name="Stellaria" temp="105" x="5" y="7" size="1.0" numPlanets="0" numGasGiants="0">
		<planet name="Euclydes Prime" customIcon="earthlike">
			<hasRings>true</hasRings>
			<isKnown>true</isKnown>
			<fogColor>1.0,1.0,1.0</fogColor>
			<skyColor>0x#59cadb</skyColor>
			<oceanBlock>gregtech:fluid.blue_vitriol_water_solution</oceanBlock>
			<gravitationalMultiplier>105</gravitationalMultiplier>
			<orbitalDistance>90</orbitalDistance>
			<orbitalTheta>0</orbitalTheta>
			<orbitalPhi>0</orbitalPhi>
			<rotationalPeriod>28000</rotationalPeriod>
			<atmosphereDensity>110</atmosphereDensity>
			<biomeIds>73,80,0</biomeIds>
			<artifact>contenttweaker:overworldessencer 0 1</artifact>
		</planet>
    </star>
	<star name="Xoal" temp="150" x="0" y="-19" size="2.5" numPlanets="0" numGasGiants="0" blackHole="true">
		<planet name="Aurellia" customIcon="MarsLike">
			<isKnown>true</isKnown>
			<fogColor>1.0,1.0,1.0</fogColor>
			<oceanBlock>tconstruct:molten_obsidian</oceanBlock>
			<skyColor>0x#2f023d</skyColor>
			<gravitationalMultiplier>200</gravitationalMultiplier>
			<orbitalDistance>30</orbitalDistance>
			<orbitalTheta>0</orbitalTheta>
			<orbitalPhi>30</orbitalPhi>
			<rotationalPeriod>2400</rotationalPeriod>
			<atmosphereDensity>80</atmosphereDensity>
			<biomeIds>74,77, 0</biomeIds>
			<artifact>contenttweaker:overworldessencel 0 1</artifact>
			</planet>
    </star>
	
</galaxy>
`

If you find some way to reproduce this let me know otherwise I cant currently. I also verified the files are correct and identical on the gitlab repo we use as well.

**Comment by bigfootbrz** [comment]
I also have this exact issue. The planetDefs.xml file under the world gets replaced.

`[23:18:25] [Server thread/INFO] [advancedrocketry]: Checking for config at C:\Games\FTB Server.Interactions\.\world\advRocketry\planetDefs.xml
[23:18:25] [Server thread/INFO] [advancedrocketry]: Advanced Planet Config file Found!  Loading from file.
[23:18:25] [Server thread/WARN] [advancedrocketry]:  81 is not a valid biome id or name
[23:18:25] [Server thread/WARN] [advancedrocketry]: Invalid sky color specified
[23:18:25] [Server thread/WARN] [advancedrocketry]: Invalid sky color specified
[23:18:25] [Server thread/WARN] [advancedrocketry]:  0 is not a valid biome id or name
`
