### ISSUE TITLE
Neuropozyne 

### ISSUE THREAD

**Issue by Officialy** [FTBTeam/FTB-Interactions#696]
## Modpack Version: 
1.7.0

## Issue Report:
Issue: No way to craft Neuropozyne except getting from the quest reward.

## Suggestions:
Suggestion: Add a crafting recipe for Neuropozyne, as people will eventually run out of it after 64 in-game days. Causing people death, or a really annoying non-harming damage twitch every 2 seconds >.<

Steps to Reproduce:
1. Get under 25 tolerance level
2. Go in survival, and take Neuropozyne. Then think what would happen if would run out.

## Mod/s Affected: 
Cyberware

## Known Fix: 
Add a way to craft the Neuropozyne Shot. Could be along-line with the creative capacitor or lower.

**Comment by Saereth** [comment]
there is normally no way to craft it, its lootable in dungeons as per the mod's design. Cyberware is pretty powerful, the tolerance mechanic is its limiting factor
