### ISSUE TITLE
2 quest rewards give crescent hammer, Cache Me Outside How About That and the left side Servo on the Supply Chain Managment page

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#70]
Submitter: `DearDeathDay#1116`
Body: `OwO issue "2 quest rewards give crescent hammer, Cache Me Outside How About That and the left side Servo on the Supply Chain Managment page`
Attachments:

**Comment by Vyraal1** [comment]
Deleted the one from the servo quest since you can pickaxe ducts and servos but not a cache.
