### ISSUE TITLE
UU matter bucket quest gives UU amplifier

### ISSUE THREAD

**Issue by TomyLobo** [FTBTeam/FTB-Interactions#703]
## Modpack Version: 
1.7.0

## Bug Report:
For the UU matter bucket quest, I get a steel cell full of useless UU amplifier.

## Expected Behavior/Suggestions:
Steel Cell full of UU matter

**Comment by TomyLobo** [comment]
also, UU matter is useless as well. maybe the entire thing should be removed?

**Comment by Saereth** [comment]
@Vyraal1 not sure what your plans were for this one
