### ISSUE TITLE
Requesting an update to LibrarianLib to 4.19.2

### ISSUE THREAD

**Issue by BransonD** [FTBTeam/FTB-Interactions#707]
## Modpack Version: 
1.8.0

## Bug Report:
SpongeForge will still crash with updated LibrarianLib

## Expected Behavior/Suggestions:
LibrarianLib 4.19.1 should have fixed SpongeForge compatibility issue; however, it did not and will still crash on startup.

LibrarianLib released a new version, 4.19.2, which fixes the SpongeForge crashes; updating LibrarianLib in FTB Interactions should fix any startup crashes. 

## Is It Repeatable? Steps to Reproduce: 
1. Install 1.8.0 FTB Interactions Server files
2. Install latest version of SpongeForge
3. Boot up the server and crash.

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/02cb6371

## Mod/s Affected: 
LibrarianLib 4.19.1

## Known Fix: 
Update LibrarianLib to 4.19.2

**Comment by Vyraal1** [comment]
including 4.19.2 update in Interactions v1.8.2
