### ISSUE TITLE
Battery buffers void energy in GTCE 1.8.2

### ISSUE THREAD

**Issue by SuperIronBob** [FTBTeam/FTB-Interactions#708]
## Modpack Version: 
1.8.1 

## Bug Report:
GTCE 1.8.2 introduced a bug for battery buffers where they would void energy, this was fixed in 1.8.3.

Commit introducing the bug:
https://github.com/GregTechCE/GregTech/commit/379e033579c6b480dc1aa57c53f6cffcf24ac9d9

Commit with the fix:
https://github.com/GregTechCE/GregTech/commit/41f9c5eb64e74dcf63e1ebcd8bf5df87cd69a689

## Mod/s Affected: 
GTCE 1.8.2 

## Known Fix: 
Bug as fixed in 1.8.3 GTCE

**Comment by SuperIronBob** [comment]
Transformers were also broken in 1.8.2 and were fixed in 1.8.3

**Comment by Vyraal1** [comment]
including GTCE 1.8.3 in interactions v1.8.3

**Comment by SuperIronBob** [comment]
Thanks!
