### ISSUE TITLE
Thaumcraft elements no longer showing in JEI

### ISSUE THREAD

**Issue by Uber2013** [FTBTeam/FTB-Interactions#709]
## Modpack Version: 
1.81

## Bug Report:
The elements of Thaumcraft no longer show in JEI, as in which items contain which amoumt of vis.

## Expected Behavior/Suggestions:
Prior on version 1.7.0, these still showed and were quite usefull. Not sure if bug or feature though.

## Mod/s Affected: 
Thaumcraft

**Comment by mfkG** [comment]
For me JEI shows no Thaumcraft Recipe (atleast not Thaumcraft specific Crafting), for example it's not showing how to craft the "Peace Candle" anymore, and for the "Alchemy Table" it show's the Recipe in normal Workbenches (which dont work, needs the ArcaneWorkbench i found out looking in the script).

**Comment by narwhalfire** [comment]
I also have this problem. My temporary solution is to go into the scripts folder and look for the zen script for the mod that the block is from and search for the recipe in there. Kind of tedious but you can use `ctrl` + `shift` + `F` to search files in a folder in vs code. You don't get the convenience of jei but it works well enough for a temporary solution.
