### ISSUE TITLE
GT Flint Axes

### ISSUE THREAD

**Issue by Littlebear90** [FTBTeam/FTB-Interactions#711]
## Modpack Version: 
1.8.2

## Bug Report:
When chopping a tree with the GT Flint Axe. The tree log displays the progress bar as it normally should but when reaching 100%, the progress bar resets to 0% and starts over. The tree has nothing happen to it and no durability is used from the ax.

## Expected Behavior/Suggestions:
I would expect that ax to actually break the block

## Is It Repeatable? Steps to Reproduce: 
1. Get 9 pieces of gravel and turn them into flint using the crafting table 3 for 1 recipe
2. Take the 3 pieces of flint and 2 sticks and craft the GT Flint Axe
3. Go to the tree and start chopping
4. Receive no wood and use no durability

## Link to Log or Crash File Paste**: 
N/A

## Mod/s Affected: 
GT Community Edition

## Known Fix: 
N/A

**Comment by RolaRoul** [comment]
Same issue is occurring with GregTech Invar Axes.

**Comment by lilPwny** [comment]
Same Issue here

**Comment by Summpot** [comment]
Same Issue here

**Comment by Saereth** [comment]
yep last update broke gt axes, should be fixed in this new update

**Comment by WessonChen** [comment]
It is not fixed in 1.9.1

**Comment by BitsBytesGaming** [comment]
@Saereth This issue is still not fixed in 1.9.1, nor was it mentioned in the changelog anywhere.
