### ISSUE TITLE
Just Enough Calculations would improve resource planning significantly

### ISSUE THREAD

**Issue by SuperIronBob** [FTBTeam/FTB-Interactions#713]
## Modpack Version: 
1.8.3

## Bug Report:
Suggestion for adding a new mod that is centered around planning resources for crafting, and adds an ingame regular math calculator.

## Expected Behavior/Suggestions:
Scheduling resources in game for crafting requires a lot of out of game calculations and note taking. Just Enough Calculations adds a gui that can store planned recipes and produce a bill of goods for a planned craft.

As an example here's a list of materials for the infinity chicken (not all recipes completely entered and possibly a few misentered):
https://imgur.com/a/uv1rJRL

## Is It Repeatable? Steps to Reproduce: 
N/A

## Link to Log or Crash File Paste**: 
N/A

## Mod/s Affected: 
N/A 
or
Suggesting adding Just Enough Calculation by Towdium

## Known Fix: 
Just a suggestion

**Comment by Saereth** [comment]
it's clientside, feel free to add it. We had it before and got too many complaints about its lack of documentation and people just generally not using it. Since we try to keep the pack as light as possible and its not required server side it one of those mods people can just add at their leisure
