### ISSUE TITLE
Ender IO conduits disconnecting from GregTech Coke Oven hatches when chunk is unloaded

### ISSUE THREAD

**Issue by RolaRoul** [FTBTeam/FTB-Interactions#714]
## Modpack Version: 
1.8.2

## Bug Report:
When Ender IO conduits (tested with Item Conduits and Fluid Conduits) are placed next to a GregTech Coke Oven Hatch (not the Improved Coke Oven), the conduits initially behave as expected, attaching to the hatch and inserting/extracting items/fluids. However, when the chunk they are in is unloaded, the conduits "disconnect" from the hatch and have to be broken and placed again to reconnect them.

## Expected Behavior/Suggestions:
Ender IO conduits should not disconnect from the hatch when the chunk they are in is unloaded.

## Is It Repeatable? Steps to Reproduce: 
1. Build a Coke Oven from GregTech with at least one Coke Oven Hatch
2. Place an Item Conduit so it is attaching to a hatch
3. Unload the chunk the Coke Oven and Conduit are located in
4. Reload the chunk. The Conduit should now be detached.

## Mod/s Affected: 
GregTech
Ender IO

**Comment by A-UNDERSCORE-D** [comment]
confirming this for 1.7.*

**Comment by Saereth** [comment]
this should be fixed in the new update

**Comment by JgamerJ** [comment]
Having the same issue in 1.9.1, should I submit a new issue or will this suffice?
