### ISSUE TITLE
pachouli: soulus book - client crash

### ISSUE THREAD

**Issue by philipp8101** [FTBTeam/FTB-Interactions#716]
## Modpack Version: 
FTBInteractions-1.7.0-1.12.2

## Bug Report:
Client crashing when clicking on any of the entrys in the book

100% Repeatable
1. get the item /give @p patchouli:guide_book 1 0 {"patchouli:book":"soulus:soulus"}
2. open, click any category, click any entry
3. crashing: Updating screen events
![](https://puu.sh/DJfJo/d8cba318b0.gif)

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/ee6d5f44

## Mod/s Affected: 
- Patchouli-1.0-19
- Soulus-1.12.2-4.2.1-4e33621

unfortunately the bug can't be reproduced with only these mods installed. it only happens within the modpack. :/

**Comment by Saereth** [comment]
known issue, duplicate, its on patchouli's end, we've been waiting on a fix for 4+ months
