### ISSUE TITLE
[1.8.2] Constant Spam in console and horrible TPS lag

### ISSUE THREAD

**Issue by tjsd** [FTBTeam/FTB-Interactions#721]
## Modpack Version: 
1.8.2

## Bug Report:
Performance and TPS is down with 1.8.* update, and console get spammed with 100 of lines very second from gregtech api capability

## Link to Log or Crash File Paste**: 
[01:09:55] [Server thread/INFO] [STDOUT]: [gregtech.api.capability.impl.EnergyContainerBatteryBuffer:acceptEnergyFromNetwork:31]: east 126 15 BlockPos{x=1111, y=74, z=183

Lines like that spams non stop 24/7 with maybe 100 lines per second.

https://pastebin.ubuntu.com/p/gzgwvRrR34/

**Comment by RolaRoul** [comment]
Had this same issue when I connected a Low Energy Battery Buffer to a Steam Turbine.

**Comment by jag0k** [comment]
Same issue here too.

**Comment by jag0k** [comment]
I installated the updated GTCE version and it appears to have resolved the issue, and nothing obvious seems to be newly broken.

**Comment by Saereth** [comment]
this is fixed in the new gtce version
