### ISSUE TITLE
Satchel Duplication Bug

### ISSUE THREAD

**Issue by Xela10001** [FTBTeam/FTB-Interactions#723]
## Modpack Version: 
1.7.0

## Bug Report:
I shift right clicked my Signalum Satchel With Holding IV onto a double chest, the game freezed for a moment and then my satchel still had all my items while the chest also had all my items.

## Expected Behavior/Suggestions:
The intended mechanic worked in the next chest i tried dumping all my stuff in, so i dont know why this happened

![image](https://user-images.githubusercontent.com/47480171/59981316-3f207d80-95f9-11e9-8e03-19f17aba19a4.png)

![image](https://user-images.githubusercontent.com/47480171/59981318-42b40480-95f9-11e9-8ac8-479342f47e24.png)

**Comment by Saereth** [comment]
cofh updated, this should be fixed
