### ISSUE TITLE
Glitch to infinite of whatever you want.

### ISSUE THREAD

**Issue by vexeen** [FTBTeam/FTB-Interactions#725]
## Modpack Version: 

1.7.0
## Bug Report:

duplication of any item to infinity number
## Is It Repeatable? Steps to Reproduce: 

1.take 2/3 stacks of cobblestone, have at least 3 of the items you want to duplicate in your inventory.
2. get to a crafting table and open crafting grid.
3. take 2 stacks of cobblestone and add them into the grid for the stairs recipe (with 2 stacks you have enough for 2o recipes worth), but dont turn them into stairs yet.
4. arrange the rest of the items in your inventory so that you have only 1 free slot.
5. now shift right click the stairs in crafting grid to craft them. You get a full stack into the empty slot, but 4will remain in the grid.
6. remove the cobblestones from crafting grid and you will notice that the crafting table can still make stairs.
7. insert 3 of the desired items into the crafting grid.
8. the grid still shows you can make stairs, BUT, if you try taking those stairs while the random items are in the grid, those items in the grid get doubled each time you try taking stairs out. thus leading to have hundreds of thousands of whatever you had in the grid. No, this is not just visual glitch, those items are real.

https://i.imgur.com/M9zuPFU.png
## Link to Log or Crash File Paste**: 

leads to no crash
## Mod/s Affected: 

no glue which mods issue it is, im just a simple player that accidentally discovered this.
## Known Fix: 

no knowledge in that field

**Comment by vexeen** [comment]
Forgot to add, that reopening the crafting grid leads to resetting the process.

**Comment by Saereth** [comment]
which version of the pack are you on?

**Comment by vexeen** [comment]
https://i.imgur.com/r9YtcHW.png

that 14.23.5.2836 is the pack version right? though im not too sure :o

**Comment by Cata-bre** [comment]
@vexeen 14.23.5.2836 is the version of forge that you're currently running. IIRC, you can find the FTB: Interactions version number from the main menu.

**Comment by vexeen** [comment]
version 1.7.0
