### ISSUE TITLE
List of poor questbook designs

### ISSUE THREAD

**Issue by Dr-Turtle** [FTBTeam/FTB-Interactions#727]
## Modpack Version: 
1.9

## Bug Report:
Not a bug, just places that corrections can be made

### 1) Space
1. The discord channel is constantly filled with people asking about advanced rocketry, generally explaining this more clearly within the questbook would be appreciated.
2. A checkmark is required to continue progression, this may be forgotten or overlooked by the player causing an inability to progress until completed.
3. Use of the falling tower ritual is not required to obtain thorium for Plutonium 244, refining coal will work, but will not complete the quest. Simply reccomending the falling tower ritual and changing the quest to thorium dust would be better.
4. The Plutonium 244 quest and Radon quest are both gated by Aurellia when required to have to create the crafting injectors for the artifact.
5. Molybdenite Ore is obtainable in the end, but seems to be very scarce (possibly non-existant) on Aurellia
6. Skystone quest is gated by the laser drill, causing players to believe that the otherwise useless drill is required to obtain skystone which can be found in dungeons.
Vinteum ore is more commonly marble than stone (if stone vinteum ore even exists), and the quest should be replaced with marble vinteum ore.

### 2) Ayo Technology
1. Thermal Evaporation multiblock should be prior to the resistive heater/fuelwood heater quest as it can function without either
2. Lithium is obtainable through multiple other methods other than the thermal evaporation multiblock, one example is electrolyzing clay, which seems to be something most players do prior to making the thermal evaporation multiblock.
3. The EV pulverizer quest states that it is the first macerator with byproducts when both MV and HV have byproduct slots (latest GTCE update added 1 byproduct slot for MV macerator).
4. The title on the Multi-Smelter quest is displayed in a straight line, causing both the quest requirements and rewards to not be visible.
5. Primitive Blast furnace Quest cannot be completed as there are no tasks 

### 3) Metallurgy
1. Copper ingot is gated by copper, tin, and bronze dust, when none of these are required to obtain copper ingot (smelting impure copper dust), this goes for brass as well.
2. Two methods of refining ore are required for the copper, tin, and bronze dust quest; the squeezer and hammer refining - only one is necessary.
3. The Infernal steel (infernal furnace) quest description states"smelt it in the infernal furnace with 3 bellows for 12 steel nuggets." - a 4th bellow can be added on the bottom to acquire 15 steel nuggets/crude iron. It is stated/implied in both the infernal steel and easier steeling quests that use of an EBF is a better way of making steel, when the infernal furnace is the best method as far as I know.
4. The suggested methods of obtaining aluminium are all required for the quest. There are additional easier methods such as electrolyzing sapphire dust that are not even mentioned.
5. The Tungstate Ore quest requires ore that is only found on Aurellia, blocking the quest line until that point, when the rest of that quest line is obtainable once reaching the end.
6. The Draconium quest should state that a Mk1 reactor is required to obtain.
7. The ore duplication section requires submitting both 1 bucket of blazing pyrotheum and 1 bucket of gelid cryotheum when there are no rewards in the section.

### 4) All good titles Argon
1. This tab is far too complex and should really only contain the milestones with no prerequisites as it is unrealistic to expect the player to remember to bucket every fluid when producing it. Many of the items required through quests are obtainable without the questline leading up to it. JEI is far more useful than this tab.

### 5) Fake Electrical Engineering
1. The top row of checkmarks for "items in this column can be crafted in X age" ends with a requirement of a UV machine hull

### 6) Party Equipment
1. use of tinkers tools should not be encouraged beyond early game due to lack of enchantability.
2. The Rotary condenser and jetpack quests should be merged as to prevent the player from creating an armored jetpack (Like I did) prior to completing the rotary condenser quest.
3. The No Slime Islands quest should clarify that colored slimeballs are a rare drop from the corresponding tree, and to use fortune to increase chances.
4. "Steel the show" states that "Mekanism Dynamic tanks hold 16 buckets per block" although they can hold 64 buckets per block 

### 7) God's Plan
1. The majority of the bottom row of quests is gated by the orbital laser drill which is not necessary for any of these.

### 8) Less Safe Space
1. Salts Veins are mentioned and given a related flower despite not spawning in the Overworld, this is no longer necessary to mention as most players that played when overworld salt veins existed have likely learned of the change.  
2. Infused Veins (spawn under Star of Bethlehem in Magical Forests) aren't mentioned 
----
This list is far from complete, I hope this helps.

**Comment by Folanlron** [comment]
new world decided too start over (baddd Taint biomes all over old world lol)

but this...

![2019-06-26_14 44 36](https://user-images.githubusercontent.com/1880741/60217851-8178d300-9822-11e9-8365-210b5a04e409.png)

**Comment by RolaRoul** [comment]
The quest Steel The Show says that Mekanism Dynamic Tanks hold 16 buckets per block, they actually hold 64 buckets per block.

**Comment by RolaRoul** [comment]
In Ayo Technology, the quest Primitive Blast Furnace is impossible to complete because it doesn't have a checkmark.
Also, the quest to make a Basic Steam Turbine is gated behind the quest to make a Large Bronze Boiler. even though the turbine can be powered by small steam boilers and the boiler requires components that are much more efficient to craft using machines. (e.g. Wiremill for wire, Metal Bender for plates)

**Comment by Dr-Turtle** [comment]
I've added some of the commented issues to the post (with credit in comments) - I will continue to do this while the issue remains open.

**Comment by RolaRoul** [comment]
The Less Safe Space: Salts Veins are mentioned and given a related flower despite not spawning in the Overworld, while Infused Veins (spawn under Star of Bethlehem in Magical Forests) aren't mentioned.

**Comment by RolaRoul** [comment]
This is more of a mod issue, but the new FTBQuests interface (in modpack versions 1.8+) doesn't show prerequisites for quests except by the lines between quests, which is annoying when some quests have prerequisite quests in different pages and it's impossible to figure out how to unlock the quest.

**Comment by Trostan** [comment]
Also the new layout is worse. In pack-version 1.7 i could click on a quest an see all items with names. Now they pop up and i have to hover over every item to see the name. Makes looking for an ore in the overworld tab a lot harder.

**Comment by TomiBelan** [comment]
I'm glad to see the pack is actively developed again! Here are some other quest issues I noticed. If you'd prefer, I can put them a new github issue. I don't know if any of them were already reported somewhere else, but I checked that they're still present as of 441327450ecae8976ba82272e498caaf533d9f57.

* Overworld

    * The Salts Vein quest still exists in the Overworld tab, even though salts veins were removed from the overworld even before the first official release of the pack.

* Space

    * The Space tab starts with a "MV Assembly" checkmark quest, but you actually need an HV assembler to go to space (to make Atomic Alloy for a Vacuum Freezer).
    * "Foundations of Flight" requires 9 Structure Towers when its recipe makes 8. Or is it annoying on purpose? ;)
    * "Anybody for a barf bag?" requires 7 Liquid Fuel Tanks even though 6 can be enough depending on the rocket.
    * There are 10 quests for Moon ore veins but only 9 files in gregtech/worldgen/moon/. The "Starmetal Ore" quest should be removed, because there is no ore vein that only has Starmetal Ore, it's always found together with some other ores.

* Ayo Technology

    * "Amp it up" description still refers to 2A recipes in thermal centrifuges, which were removed from GTCE long ago. As I understand it, all single-block GTCE machines are able to consume 2A (e.g. to refill their power buffer) but actively use 1A.
    * "Welcome Ohm" and "Vanilla or shock-a-lot?" also mention per-recipe amperage.

* Chemistry

    * The "Resistance is Rutile" description is kind of misleading. Electrolyzing bauxite dust is far from the best way to get rutile. Pulverizer + ore washer + centrifuge gives you much more. Fortunately, this is mitigated by GTCE's lovely new tooltips and "Ore Byproduct List" JEI tab.

* Fake Electrical Engineering

    * The circuits tab shows Basic Electronic Circuit in the steam age column (together with Integrated Logic Circuit) but that's wrong. Basic Electronic Circuit needs a MV Cutting Saw in order to craft an Integrated Circuit, so it should be moved to the MV column.
    * The circuits tab shows Good Electronic Circuit in the steam age column, but that's also wrong, because it needs a Diode which needs a Tiny Pile of Gallium Dust which needs a LV Centrifuge. So it should be moved to the LV column. (Unless you can get it earlier with a mana pool... I'm not 100% certain. But usually you'd craft it during the LV age.)
    * The glowstone quest in the circuits tab has a dependency on some nether quest(s), even though you can (and must) get some glowstone before the nether.

* Magic Stick

    * The Void Seed quest gives you two Destructive Will Crystal Clusters and zero raw Demon Will Crystal Clusters.
    * Suggestion: Add a quest or a tip that says Rock Crystal splitting doesn't work and you must mine more Rock Crystal Ore if you want more Rock Crystals. Or add it to the description of the existing Rock Crystal quest.

* Supply Chain Management

    * The reward from the "Chest" quest immediately completes the "Wood to Iron Chest Upgrade" quest. I think there are some other "zero effort needed" quests like this, but I forgot where.
    * The "Item Translocator" quest has a typo "nugger".
    * The "Liquid Translocator" description is wrong - diamond nuggets only work for item translocators, and liquid translocators can't be regulated.

* Bonus: Tips

    * There is still a tip that refers to Soulus.
    * A tip claims that GTCE overclocking is 0.5x time and 4x power, but they [changed it to 70% effectivity long ago](https://github.com/GregTechCE/GregTech/commit/27666f27a30f087fc144eaa3cbb21bce97b69fd8) so it's actually 0.357x time and 4x power, for a total of 1.429x the EU cost. Well, maybe that's too much detail, I don't know.

Hope that helps!

**Comment by Saereth** [comment]
we;ve addressed this all best we can for now, with the new questbook I'm closing out issues so I dont confuse them with the revamped questbook
