### ISSUE TITLE
Spectre coils cause crash when walking out of render distance

### ISSUE THREAD

**Issue by DrTasslehoff** [FTBTeam/FTB-Interactions#730]
## Modpack Version: 
1.9.1

## Bug Report:
Walking out of range causes the crash, teleporting between dimensions is fine.

## Link to Log or Crash File Paste**: 
https://pastebin.com/zU6DGyBA

**Comment by DictatorBob** [comment]
I have the same issue. I found that disabling everything from p455w0rdlib prevents the crashes. In-game, just go into Mod Options, search for p55w0rdlib, go into config and disable everything that is enabled.

**Comment by A-UNDERSCORE-D** [comment]
Confirming this on behalf of one of my users, 1.9.1

**Comment by Xela10001** [comment]
When teleporting to my thaumcraft place, which is far away, my game crashes.
Its related to the spectre coil i placed recently

https://pastebin.com/QGxpMnYw

https://pastebin.com/z2FjmHz9

**Comment by Xela10001** [comment]
The fix is disabling p455w0rd's shaders.

Go into mod options, search p455w0rd's library, select config and disable shaders. Boom, no more crashes

**Comment by A-UNDERSCORE-D** [comment]
@DrTasslehoff this has been fixed on p455w0rd's side, if you want to close this or wait on the pack being updated

**Comment by Saereth** [comment]
finally got a fix for this!
