### ISSUE TITLE
Large Bloodstone Brick (referenced by inspectoris scandalum ghost blocks) should be replace with Titanium blocks

### ISSUE THREAD

**Issue by skingnet** [FTBTeam/FTB-Interactions#731]
## Modpack Version: 
1.7 (Release) - 1.9.1 (current beta)

## Bug Report:
removed block "Large bloodstone brick" is referenced by the inspectoris scandalum while building the blood altar.   (technically it also tells you to use glowstone instead of skystone block, which doesn't work in the release version 1.7)

## Expected Behavior/Suggestions:
Now that I know it's supposed to be Titanium (thanks Arktiswind), I'm expecting Titanium ghost blocks as caps on the pillars for the tier 4 blood altar while shift-right clicking the inspectoris scandalum on the blood altar. And expecting it tell me I'm missing titanium blocks, not a block that has been removed (large bloodstone brick)

## Is It Repeatable? Steps to Reproduce: 
1. try to build a tier 4 blood altar and don't supply the capstones on the pillars
2. shift-right click on the blood altar with the inspectoris scandalum set to tier 4, it will tell you you're missing a Large Bloodstone Brick and the ghost block will render that block, which has been removed.
(the same problem in 1.7 release version for tier 3/glowstone but at least glowstone is in the game... for the record even more confusing because it doesn't recognize it! (fixed in 1.9 I see, thanks!))

## Link to Log or Crash File Paste**: 
n/a

## Mod/s Affected: 
Blood magic

## Known Fix: 
Use titanium instead of what is directed

**Comment by Arktiswind** [comment]
You don't need large bloodstone bricks in this pack. Just put 4 titan blocks on top.

**Comment by skingnet** [comment]
then the hint blocks need to be updated, still is an issue in my opinion

**Comment by jag0k** [comment]
I agree, the Inspectoris Scandalum & Altar Diviner need to be updated to reflect the changes, I spent a couple hours last night trying to build a tier 3 altar wondering why the diviner/inspectoris kept telling me I was missing glowstone caps when clearly they were in place.

**Comment by Saereth** [comment]
there is no api functionality to update those ghost blocks with the overriden ones, that is why we have a questline for them and tooltips.
