### ISSUE TITLE
Can´t craft a silverwood sapling with the AS lens

### ISSUE THREAD

**Issue by Egelsetzer** [FTBTeam/FTB-Interactions#732]
## Modpack Version: 
1.9.1

## Bug Report:
I linked a floating crystal from a generated astral sorcery altar to a lens, which reflects the light to a greatwood sapling, Nothing happens.

## Expected Behavior/Suggestions:
JEI shows a recipe for the silverwood sapling, that uses the AS lens, but it doesn´t work.

## Is It Repeatable? Steps to Reproduce: 
1. link floating crystal to lens.
2. link lens to greatwood sapling

tried different setup, nothing works

**Comment by TomiBelan** [comment]
Same here. (1.9.1)

I found the reason: The transmutation only works for greatwood saplings with metadata = 0. If I broke and replanted the linked sapling, it worked for a while (white particles appeared), but it broke before the recipe completed. Workaround: Place a block directly above the sapling to stop it from growing.

With op powers ([see hack](https://gaming.stackexchange.com/questions/277542/how-to-turn-cheats-on-or-off)) you can check the sapling data with `/ct blockinfo` and check the crystal data with `/nbtedit`.

BTW a lens is not necessary. You can use the linking tool to directly connect the floating crystal to the block that should be transmuted. E.g. linking the crystal to a sand block worked for me and turned it to clay.

**Comment by Egelsetzer** [comment]
I found my problem....

I didn´t knew, that the collector crystal needs vision to the sky. It was below a shrine and i didn´t mine the blocks above and waited for several hours for the sapling to transform....

Still thx for your fix, might help others.
