### ISSUE TITLE
Floating chests in overworld

### ISSUE THREAD

**Issue by ChickenMacNugget** [FTBTeam/FTB-Interactions#733]
## Modpack Version: 
Interactions 1.9.1

## Bug Report:
There appears to be empty floating chests rarely spawning in groups in the overworld.
World save ported from 1.9 to 1.9.1 may be relevant?

## Expected Behavior/Suggestions:
Not sure if this is intended behaviour... I assume not?

## Is It Repeatable? Steps to Reproduce: 
May only be this save. I have seen it in 3 locations over a pretty wide distance (different biomes).

## Link to Log or Crash File Paste**: 
Images of chests: https://imgur.com/a/JliuAkQ

**Comment by RolaRoul** [comment]
I've had the same problem. Guessing it's an issue with Doomlike Dungeons.
