### ISSUE TITLE
Pickaxe of the Core & Refining Enchantment Don't Work

### ISSUE THREAD

**Issue by Spydrouge** [FTBTeam/FTB-Interactions#735]
This bug most likely has to do with a conflict between Gregtech and Thaumcraft.

## Modpack Version: 
1.7.0

## Bug Report:
Despite wielding the Pickaxe of the Core, native clusters DO NOT drop from any ores. 
None of them.

## Expected Behavior/Suggestions:
When mined by the Refining Enchantment/Pickaxe of the Core, seven ores are expected to drop as native clusters a percentage of the time. These affected ores are: Iron, copper, tin, silver, gold, lead, and cinnabar ore.

When mining these key ores—the ores that can be transmuted via alchemy into a native cluster anyway—the Refining Enchantment should cause those ores to occasionally (exact % depends on the rank of enchantment) drop as native clusters.

## Is It Repeatable? Steps to Reproduce: 
1. Equip self with either Pickaxe of the Core, or go use infusion enchantments to enchant any old pickaxe with the Refining Enchantment. The Pickaxe of the Core simply gets the Refining Enchantment naturally.
2. Go mine iron and gold for awhile, since they're pretty easy to find. You will get the same results on any of the abovementioned ores. 
3. No Native Clusters dropped for you. 
4. I am assuming this has to do with some sort of incompatibility between Gregtech Ores and the Thaumcraft mining enchantment.

## Mod/s Affected: 
Thaumcraft
Gregtech (speculating)

**Comment by Saereth** [comment]
this is wai,thaumcraft is not your ore processing method in this pack

**Comment by Spydrouge** [comment]
Hold on a second, if you're going to put the pack together such that an enchantment doesn't work, DISABLE THE ENCHANTMENT. Don't just LET people rush an item that then doesn't work.
