### ISSUE TITLE
Oxygen and hydrogen do not display in jei

### ISSUE THREAD

**Issue by cabbby** [FTBTeam/FTB-Interactions#737]
## Modpack Version: 
1.9.1

## Bug Report:
Some GT gases like oxygen and hydrogen do not display in jei, which makes it hard to configure GT fluid filter covers.

## Expected Behavior/Suggestions:
GT gases should display properly in jei.

## Is It Repeatable? Steps to Reproduce: 
Open JEI and type the keywords.

**Comment by Xela10001** [comment]
It does display, but its the Advanced Rocketry versions of Oxygen, Hydrogen and even Nitrogen. They all have a missing purple texture

**Comment by cabbby** [comment]
@Xela10001 I realized that just now. But what really matters is that you can't use AdvRocketry's gases to configure the GT fluid filter covers. Normally you can just drag the icons in JEI to add them to white/black list.
