### ISSUE TITLE
Nether portals lead back to void dimension

### ISSUE THREAD

**Issue by Goz3rr** [FTBTeam/FTB-Interactions#738]
## Modpack Version: 
1.9.1

## Bug Report:
When a nether portal (in the nether) is destroyed (by a ghast for example) and rebuilt, it puts the player back into the void dimension instead of at the matching portal in the overworld

## Expected Behavior/Suggestions:
Should put the player back at the existing overworld portal

## Is It Repeatable? Steps to Reproduce: 
1. Create nether portal in the overworld
2. Go through nether portal in the overworld
3. Destroy block of nether portal in the nether
4. Put destroyed block back and relight the portal
5. Go through the nether portal in the nether
6. End up at newly generated portal in the void world

## Link to Log or Crash File Paste**: 
Not applicable

## Mod/s Affected: 
Probably the mod that modifies nether portals?

## Known Fix: 
Unknown

**Comment by Thiana** [comment]
That's because the void dimension is the real overworld. The 'overworld' portal takes you to dim100.

**Comment by Goz3rr** [comment]
Probably, but that doesn't sound like the expected behaviour. Further more if the portal is never destroyed it will lead back to the correct portal in the overworld

**Comment by Saereth** [comment]
because the portal has no way to know you dont want to go to the void world when you build it from the nether, its just a limitation if JED unfortunately. If your portal gets destroyed or something just grab the blocks and /home and rebuild from there.
