### ISSUE TITLE
Please allow extra guiScale options similar to Stoneblock 2

### ISSUE THREAD

**Issue by tetious** [FTBTeam/FTB-Interactions#74]
## Modpack Version: 
1.0.0

## Bug Report:
Currently, the guiScale is only configurable in-game like vanilla, maxing at 2. 

## Expected Behavior/Suggestions:
Many other mod-packs give numerous larger options instead of maxing at 2. 6 is the max before auto on most, and that works really well. 

For my old eyes and a 4k monitor is 2 is too small and auto is too large. :)

Please consider making this more flexible in a future release. Thanks for all your hard work on the pack!

**Comment by Saereth** [comment]
install the clientside mod "tip the scales" and it should do what you're after, not everyone will need this so we dont included by default
