### ISSUE TITLE
Quartz Glass recipe

### ISSUE THREAD

**Issue by Meyakat** [FTBTeam/FTB-Interactions#741]
## Modpack Version: 
1.9.1

## Bug Report:
Quartz glass recipe uses 144mb of glass

## Expected Behavior/Suggestions:
It should use 1000mb of glass like sand to glass recipe

## Is It Repeatable? Steps to Reproduce: 

1.Craft quartz glass in aseembler. Thats it

## Known Fix: 

You should tweak the recipe

**Comment by Saereth** [comment]
nah we want people dedicaating a machine to them, otherwise they're welcome to to deal with the odd glass mb values left over
