### ISSUE TITLE
Ftb interactions wont start since update 1.9.1

### ISSUE THREAD

**Issue by DanielDB1911** [FTBTeam/FTB-Interactions#742]
## Is It Repeatable? Steps to Reproduce: 

1. Start the game and press the play button
2. The game window wont oopen and the game crashes

**Comment by DanielDB1911** [comment]
I can still play the older version without the crash

**Comment by liljames326** [comment]
i had to reinstall the pack. just backup your saves. i had to go into ftb folder and delete the modpacks manually

**Comment by DanielDB1911** [comment]
Thanks it is working now!!
