### ISSUE TITLE
Frequent "Unexpected Error" crash upon entering game

### ISSUE THREAD

**Issue by AbdielKavash** [FTBTeam/FTB-Interactions#743]
## Modpack Version: 

1.9.1

## Bug Report:

When launching the game, after connecting to a server, but before the world loads, the game client crashes with a NPE somewhere in core Minecraft code (not in any of the mods) - see crash reports.

The crash does not occur -every- time, but very consistently in about 50% of attempts to join the server. It does not matter where my character is or what was I doing before the last logout, the crashes have been happening seemingly at random. Restarting the client and/or the Twitch launcher usually lets me log in and play normally. (Obviously this is not an ideal solution, given that the pack takes 15+ minutes to load every time.)

The behavior is similar to #224 , although the stack trace is somewhat different. Also, I am running the latest Java version (1.8.0.211 64 bit), and I have tried allocating anywhere between 6 and 12 GB of memory to the game; the crash occurs regardless. Minecraft is run from its own folder in the root of my D:\ drive, far away from any Windows folders.

I am using the Twitch launcher, running the pack exactly as downloaded, only added the "Ding" mod.

## Link to Log or Crash File Paste: 

Latest three reports, I can provide more if needed.

https://paste.feed-the-beast.com/view/d97e2ce1
https://paste.feed-the-beast.com/view/526d3b38
https://paste.feed-the-beast.com/view/74627215

**Comment by Saereth** [comment]
these pastes are no longer valid so I cant follow up with atm, please repopen a new issue with new pastes if the issue is still occuring after next update
