### ISSUE TITLE
zombies dealing ranged damage

### ISSUE THREAD

**Issue by liljames326** [FTBTeam/FTB-Interactions#744]
My real question is how to turn off zombies doing damage when i shoot them with a bow from about 30 foot away. With no healing its pretty near impossible to start with killing zombies in a dungeon without dying and having to run back to get your grave every time. i just find it annoying with being new and not knowing all the tiers and mods and slows progression a heck of a lot.  It only happens on certain ones and cant specify what kind of armour, just know they are wearing armour when I take damage and i would like to disable the enchantment as is if possible because them psychically dealing damage to me when im not even in range for them to start following me is just crazy. 

## Modpack Version: 
1.9.1

## Expected Behavior/Suggestions:
should not do damage when dealing damage outside melee radius for a zombie

## Is It Repeatable? Steps to Reproduce: 

1.grab a bow
2. shoot a bunch of zombies

**Comment by mckulich** [comment]
Man thats not a bug. Some zombies has enchanted piece of armor, this enchant is Thorns and it deal damage back to attacker no matter how close he is. This just how this enchant work. From my own experience just get some armor, enchant it! Then try to obtain some bandage enchant it with unbreaking and life mending and tadaa you have infinite healing thx to this.

**Comment by liljames326** [comment]
> Man thats not a bug. Some zombies has enchanted piece of armor, this enchant is Thorns and it deal damage back to attacker no matter how close he is. This just how this enchant work. From my own experience just get some armor, enchant it! Then try to obtain some bandage enchant it with unbreaking and life mending and tadaa you have infinite healing thx to this.

i figure thats thorns. but thanks for the idea on the bandaids. that will at least make outside of combat healing plausible. its just that thorns dont reach out and slap you if you pick a rose off a bush with a paid of tongs that are over a foot long. its not logical at all and i think it has something to do with the harder armored mobs mod in this pack. but the mod did not have a config, if necessary ill figure out what it was again

**Comment by liljames326** [comment]
thanks for the help, lol thats why ftb is dead i guess
