### ISSUE TITLE
Not able to generate standard maps

### ISSUE THREAD

**Issue by devlman127** [FTBTeam/FTB-Interactions#745]
##  Modpack Version: 

1.9.1
## Bug Report:
When trying to generate a world with the "Regular" or "Amplified" world type, nothing will generate and you'll fall down to your doom.
## Expected Behavior/Suggestions:
Being able to generate a regular world.
I got this modpack being attracted to the cross-compatibility of the mods, but I'm not a fan of skyblock-like challenges, so I hope this isn't intended behavior.
## Is It Repeatable? Steps to Reproduce: 
1. Set world generation to "Regular" or "Amplified"
2. Generate world

**Comment by Saereth** [comment]
the pack isnt designed for that, the instructions clearly say set to void world type.
