### ISSUE TITLE
Air collector consume energy even with full tank

### ISSUE THREAD

**Issue by mckulich** [FTBTeam/FTB-Interactions#746]
## Modpack Version: 
version 1.9.1 

## Bug Report:
So i just found out that air collector from gregtech consume energy even with full internal tank

## Expected Behavior/Suggestions:
I expect that when internal tank is full, machine should stop work and dont consume energy anymore

## Is It Repeatable? Steps to Reproduce: 
nothing hard to reproduce
1. Craft and place air collector from gregtech
2. give it power and time to fill internal tank
3. watch like that machine consume energy with full internal tank

## Link to Log or Crash File Paste**: 
there is no crash, just tons of steam i lost :D :D 

## Mod/s Affected: 
GregTech community edition

## Known Fix: 
unknown

**Comment by Saereth** [comment]
gtce dev says not a bug, working as intended
