### ISSUE TITLE
Strange Pizza Slice recipe

### ISSUE THREAD

**Issue by ionin-code** [FTBTeam/FTB-Interactions#748]
## Modpack Version: 

1.9.1

## Bug Report:

https://imgur.com/a/RhfZ4NI
There is a strange recipe for 3 Pizza Slice with ID harvestcraft:berryvinaigrettesaladitem using Cutting Board and listAllgreenveggie

## Is It Repeatable? Steps to Reproduce: 

Put in a crafting area Cutting Board and any item from listAllgreenveggie (f. e., Lettuce) and get Pizza Slices

## Mods Affected: 

Pam's HarvestCraft

## Known Fix: 

One should remove harvestcraft:berryvinaigrettesaladitem from foodPizzaslice oredict (assumption)

**Comment by Saereth** [comment]
wtf lol
