### ISSUE TITLE
FTB-Interactions 1.9.1 consistently times out when downloading using Twitch.

### ISSUE THREAD

**Issue by mastrude** [FTBTeam/FTB-Interactions#749]
## Bug Report:
Consistently get the message: "Timeout attempting to download: https://edge.forgecdn.net/files/2730/813/FTBInteractions-1.9.1-1.12.2.zip"
This has happened multiple times over several days. I can download the zip file from Feed-the-Beast.com, but can't install it without the Twitch apparatus. My available bandwidth is OK. My available drive space is OK. 

Other modpacks are working.  After experiencing this problem, I installed the OmniFactory modpack. It's working. 
I have deleted the old installation of Interactions. No change. 
I have uninstalled and reinstalled Twitch. No change. 

I think the installation on the Twitch server must be corrupted.

**Comment by Solid-Metal** [comment]
same issue

Timeout attempting to download: https://edge.forgecdn.net/files/2730/813/FTBInteractions-1.9.1-1.12.2.zip

**Comment by AffectAge** [comment]
Same

**Comment by wadabla48** [comment]
Same here, tried like 20 times didn't change anything :/

**Comment by smb64** [comment]
can confirm that this is still an issue, which is very unfortunate...

**Comment by Saereth** [comment]
yeah twitch was having issues off and on for a bit, working now

**Comment by JMBarber** [comment]
Currently experiencing the same issue.  I'll keep trying it over time.

Any insight into what causes this, and/or possible workarounds?
