### ISSUE TITLE
iron vein quest asks for nickel ore, however nickel doesn't seem to spawn in the vein

### ISSUE THREAD

**Issue by TeamDman** [FTBTeam/FTB-Interactions#75]
Submitter: `FTB Interactions#2470`
Body: `**[Rdjrjqouqcu]** OwO issue "iron vein quest asks for nickel ore, however nickel doesn't seem to spawn in the vein"`
Attachments:

**Comment by Vyraal1** [comment]
iron veins in jungles are nickel

**Comment by tyler489** [comment]
Then can you clarify in the questbook then as the questbook says it's RARE outside jungles not impossible.
