### ISSUE TITLE
GT Robot Arm Loosing Exact settings after server restart

### ISSUE THREAD

**Issue by ValdinH** [FTBTeam/FTB-Interactions#750]
## Modpack Version: 
1.9.1

## Bug Report:
After a server restart a MV Robot Arm on the side of a GT machine will loose its Supply Exact setting and reset to 1. (Tried so far on a Packager and Electrolyzer.)

**Comment by mfkG** [comment]
https://github.com/GregTechCE/GregTech/issues/867

**Comment by ValdinH** [comment]
Look like this is fixed in the new GT 1.8.4 sorry
