### ISSUE TITLE
Astral Sorcery Tree Beacon makes 2x2 Dark Oak saplings turn invisible after 1st pair grows successfully

### ISSUE THREAD

**Issue by robzombie91** [FTBTeam/FTB-Interactions#751]
## Modpack Version: 
1.9.1

## Bug Report:
1. Grow a pair of 2x2 dark oak saplings with a tree beacon
2. Try to grow a second pair of 2x2 saplings
3. Saplings turn invisible until the tree beacon is broken

## Expected Behavior/Suggestions:
1. After growing the first pair of 2x2 dark oak saplings, the second pair should also grow into the ghost that the first pair did

## Is It Repeatable? Steps to Reproduce: 
Yes it is repeatable

1. Grow a pair of 2x2 dark oak saplings with a tree beacon
2. Try to grow a second pair of 2x2 saplings

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/1d6839f6

## Mod/s Affected: 
Astral Sorcery

## Known Fix: 
N/A

**Comment by robzombie91** [comment]
Seems like spacing might be the issue

**Comment by Saereth** [comment]
this is an issue for astral sorcery not the pack, please report over there https://github.com/HellFirePvP/AstralSorcery
