### ISSUE TITLE
Iron Door recipe conflicts with Iron Hammer Head Recipe

### ISSUE THREAD

**Issue by ionin-code** [FTBTeam/FTB-Interactions#753]
## Modpack Version: 

1.9.1

## Bug Report:

Iron Door recipe added by CraftTweaker looks the same as GTCE Iron Hammer Head Recipe. Due to that its impossible to craft Iron Hammer Head without MV Extruder which seems strange (also, recipe for Iron Hammer Head in JEI looks now misleading).
https://imgur.com/a/cWbNsGK
## Expected Behavior/Steps to Reproduce:

One should get the Iron Hammer Head with this craft: https://imgur.com/a/fyF5Xid.

## Mod/s Affected: 
1. CraftTweaker2
2. GregTech Community Edition
## Known Fix: 

Change Iron Door recipe in CraftTweaker script.

**Comment by Saereth** [comment]
there is an artisan table recipe for this to work around the recipe and a quest explaining to make your iron hammer in the artisan work table
