### ISSUE TITLE
world generation wrecks server tps and causes lag

### ISSUE THREAD

**Issue by xBeathovenx** [FTBTeam/FTB-Interactions#758]
## Modpack Version: 
1.9.1
Forge: 2838
## Bug Report:
When moving around and the server generates chunks its causing massive lag

## Is It Repeatable? Steps to Reproduce: 
All the time

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/538e9145

## Mod/s Affected: 
NED, Gregtech, Doomlike dungeon, wizardry

**Comment by Saereth** [comment]
set your server view distance down to 8 or get better hardware
