### ISSUE TITLE
Bug - Can do /island visit but not /island home

### ISSUE THREAD

**Issue by tjsd** [FTBTeam/FTB-Interactions#76]
## Modpack Version: 
v1.0

## Bug Report:
You can do /island visit but /island home is disabled so you cant get back.

## Expected Behavior/Suggestions:
to get home

## Is It Repeatable? Steps to Reproduce: 
1. do /island visit someone
2. do /island home
3. get block
4. be stuck in spectator mode
5. watch the world pass by

## Known Fix: 
edit config/voidislandcontrol.cfg
B:allowHomeCommand=true

**Comment by TheonlyTazz** [comment]
/island spawn brings you to spawn... Remember to set /sethome to get home tho

**Comment by Saereth** [comment]
yeah this is not a bug, if you want to specifically enable it for your playthrough or for your server just edit voidislandcontrol.cfg and enable it. The pack has ftbutilities which provides a /home feature, the island home was just a second free teleport.

**Comment by tjsd** [comment]
That did not take me out of spectator mode, I was stuck there. Even when doing /gamemode 0 I was stuck as spectator. Had to enable the command on the server, reboot and then do /island home to get back to playable state.

**Comment by Saereth** [comment]
not /spawn, /island spawn

**Comment by tjsd** [comment]
we have several people getting stuck in spectator mode with this approach @Saereth

**Comment by Saereth** [comment]
tell them to use /island spawn and not /spawn

**Comment by Saereth** [comment]
will turn /spawn off by default I guess to help avoid this issue.
