### ISSUE TITLE
GTCE Inbuilt timber does not work

### ISSUE THREAD

**Issue by MonolithBR** [FTBTeam/FTB-Interactions#760]
## Modpack Version: 
1.9.1

## Bug Report:
I attempt to break
A log with an axe and it
Simply does not break

## Expected Behavior/Suggestions:
Expected: When broken with a GTCE axe, a log block should drop and cause all other log blocks above it, in an ininterrupted line, to drop as well (inbuilt timber)

## Is It Repeatable? Steps to Reproduce: 
It is repeatable.
1. Craft any axe the modpack recognizes as a GTCE axe Ex. flint axe
2. Attemp to break a log without pressing shift

## Link to Log or Crash File Paste**: 
Does not cause crash.

## Mod/s Affected: 
Gregtech Community Edition

## Known Fix: 
None that I know of.

![Meu Vídeo](https://user-images.githubusercontent.com/52931413/61239774-0cf4ce00-a716-11e9-87fd-1e61cb39d52d.gif)

**Comment by CycnusJones** [comment]
Same exact issue for me. The One Probe shows breaking progress up to 80% then goes back to 0%.

**Comment by heydabop** [comment]
#728

**Comment by Saereth** [comment]
requires GTCE update fix, so will be fixed at a later time
