### ISSUE TITLE
LV Thermal Centrifuge is useless

### ISSUE THREAD

**Issue by RolaRoul** [FTBTeam/FTB-Interactions#761]
## Modpack Version: 
1.9.1

## Bug Report:
The LV thermal centrifuge appears to be useless, because all the thermal centrifuge recipes require at least 60 EU/t and the LV thermal centrifuge can only accept up to 32 EU/t.
Previous versions of the modpack had an Amperage of 2 listed in the thermal centrifuge recipes in JEI, which would allow the LV thermal centrifuge to be used, but in the current version that note is no longer there. It is unclear whether the thermal centrifuge was changed to no longer accept multiple amps, or if JEI was changed to no longer display Amperage for recipes.

## Expected Behavior/Suggestions:
-If the thermal centrifuge was changed, remove the recipe for the LV thermal centrifuge and remove the quest to craft an LV thermal centrifuge in the Metallurgy tab of FTB quests.
-If JEI was changed, add a note somewhere mentioning the thermal centrifuge's ability to accept multiple amps.

## Mod/s Affected: 
GregTech Community Edition
Just Enough Items

**Comment by Saereth** [comment]
GTCE updated to no longer draw multiple amps on basically any of their machines. the lv centrifuge should just be removed
