### ISSUE TITLE
Extra regeneration

### ISSUE THREAD

**Issue by ian-barlow** [FTBTeam/FTB-Interactions#764]
## Modpack Version: 
1.9.1

## Bug Report:
Extra levels of regeneration (from healing fragments)

## Expected Behavior/Suggestions:
When 18 healing fragments are added to inventory player gets regen 2. If 9 of the fragments are removed (to satchel or wherever) the player keeps regen 2.

## Is It Repeatable? Steps to Reproduce: 
1. Add 18 healing fragments to inventory
2. Remove 9 fragments

## Mod/s Affected: 
Animus

## Known Fix: 
Unknown

**Comment by Saereth** [comment]
Shhhh (intended) ;P
