### ISSUE TITLE
Pack Crashing While Loading

### ISSUE THREAD

**Issue by lokon100** [FTBTeam/FTB-Interactions#766]
## Modpack Version: 
1.9.1
## Bug Report:
I am trying to load FTB Interactions and it keeps crashing durning loading.  I have completely uninstalled and reinstalled and still have the same issues.  It is loading the most recent version also.  Attaching the pastebin of the error that comes up.
https://pastebin.com/XFfUyeLP

## Expected Behavior/Suggestions:
Being able to launch the game

## Is It Repeatable? Steps to Reproduce: 
Just booting the game from twitch. I press play in twich, then play in the minecraft launcher when it comes up, and it loads a bit of the game and then crashes.

## Link to Log or Crash File Paste**: 
https://pastebin.com/XFfUyeLP

**Comment by jug007** [comment]
The game did not launch from the twitch launcher for a friend of mine as well. Using the FTB Launcher worked for them.
