### ISSUE TITLE
Steam Machines not working

### ISSUE THREAD

**Issue by Alienz14** [FTBTeam/FTB-Interactions#767]
## Modpack Version: 
1.9.1

## Is It Repeatable? Steps to Reproduce: 

1.
2.

**Comment by jag0k** [comment]
You have blocked up the steam vent, they need to be able to vent steam to perform more operations.
You can change the side on which they vent by whacking them with a wrench.

**Comment by Alienz14** [comment]
wow.... i cant believe that was the problem, a right click fixed it. thank you
