### ISSUE TITLE
Apotheosis level caps are ignored when "Lapis Stays in the Enchanting Table" mod is installed

### ISSUE THREAD

**Issue by DrTasslehoff** [FTBTeam/FTB-Interactions#769]
## Modpack Version: 
1.9.1

## Bug Report:
Apotheosis enchanting maximums are not respected when "Lapis Stays in the Enchanting Table" mod is installed. 

## Expected Behavior/Suggestions:
https://i.imgur.com/AcgzuJG.png

Adding any enchantment boosting items ignore the level caps, Gaia pylons shown for ridiculousness. 

## Mod/s Affected: 
Lapis Stays in the Enchanting Table, Apotheosis

**Comment by Saereth** [comment]
ugh, removing that mod
