### ISSUE TITLE
Spawn under the map and instantly fall to death

### ISSUE THREAD

**Issue by clear0000** [FTBTeam/FTB-Interactions#770]
newest version from twitch app.

no matter what seed or world type i literally just spawn and fall to death. it's all darkness.

**Comment by goldfantast** [comment]
/ru Я создал мир в одиночной игре и перенес его в папку world на сервере
/en I created the world in a single game and moved it to the world folder on the server

**Comment by Saereth** [comment]
the sever worldtype needs to be set to voidworld
