### ISSUE TITLE
 Will there be a Russian translation?

### ISSUE THREAD

**Issue by Drimyr** [FTBTeam/FTB-Interactions#772]
Will there be a Russian translation?

**Comment by Saereth** [comment]
If someone wants to do russian localizations we can gladly include them, Im not able to though personally though no.

**Comment by Saereth** [comment]
The repo is now entirely open to public contribution, as I do not speak russian, Im gonna close this out with the understanding that any community contributed localizations will be gladly accepted/merged in.
