### ISSUE TITLE
Uncraftable Attractor Obelisk

### ISSUE THREAD

**Issue by Moirenill** [FTBTeam/FTB-Interactions#774]
## Modpack Version: 
1.9.1

## Bug Report:
The Attractor Obelisk from Ender IO is uncraftable.

The Attractor Obelisk requires an Enticing Crystal to craft.  The Enticing Crystal is made in a Soul Binder using an Emerald and Soul Vial holding a Villager.   We cannot use that recipe because we cannot capture villagers in Soul Vials.  

## Expected Behavior/Suggestions:
Ordinarily villagers are easily captured, but they seem to be on the Soul Vial blacklist in this pack.  

## Is It Repeatable? Steps to Reproduce: 
Yes, it's repeatable.  

## Mod/s Affected: 
Ender IO

## Known Fix: 
There's no in-game work-around, short of OP privileges.  I would suggest that maybe an Enchanted Book of Temptation might be a thematically acceptable replacement for the Villager Soul Vial in the recipe for Enticing Crystal.

**Comment by ZeekDaGeek** [comment]
Related: https://github.com/modmuss50/VillageTradingBan/issues/2

I just disabled the mod personally.

**Comment by Moirenill** [comment]
Interesting.  I had assumed no villager capturing was a deliberate choice, not a side effect of no trading.

**Comment by Saereth** [comment]
It is a deliberate choice, you should not be able to capture villagers. Disabling that mod also breaks progression substantially via trades. 

There will be an alternate recipe for this in the next update
