### ISSUE TITLE
Thaumcraft Sustainer charm doesn't maintain nutrition

### ISSUE THREAD

**Issue by hacatu** [FTBTeam/FTB-Interactions#775]
##Modpack Version: 1.9.1

## Bug Report:
When the player has a Verdant Heart Charm from Thaumcraft with the Sustainer upgrade equipped, it will feed the player but nutrition will very slowly decrease.  Given the nature of this item (that the player is not actually eating food and that it is sustaining the player), I think it should not decrease nutrition.  However, the charm itself is fairly cheap, requiring only mv technology if the rare earths are made using an lv autoclave with unstable mana and pulverized diamond ore, so if this nutrition behavior is fixed it might make sense to make the recipe for the charm harder.

## Steps to Reproduce: 
1.  Get nutrition up to 100% by eating a few thankful dinners (/other foods if the slowdown from spice of life is too annoying)
2.  Get and equip a vis amulet of some kind and a verdant heart charm with the sustainer upgrade
3.  Lose hunger somehow.  The hunger potion effect should help with this because it will decrease saturation rapidly.  The sustainer charm works by adding half a shank of hunger and half a shank of saturation while hunger is not full (this means when natural regeneration is enabled, the sustainer charm will not make the player heal ridiculously fast, unlike the aevitas mantle of the stars) (I have not tested if the aevitas mantle of the stars also doesn't maintain nutrition).
4.  Check nutrition.  It should go down very slowly.  I have only lost 2% in probably around 7 hours and I have only noticed it decrease after closing the game and re-opening it, but I think it happens in game as well.   Applying hunger 20 will make the charm kick in about every second which should speed it up.

## Mod/s Affected: 
Thaumcraft, Nutrition

**Comment by DrTasslehoff** [comment]
Nutrition decreases when you lose hunger haunches, and since the charm activates based on that condition you lose nutrition stats.

**Comment by Saereth** [comment]
yeah this is not really a bug its just the way the item works unfortunately, you'd have to approach the devs of those mods to add in compatibility.
