### ISSUE TITLE
Crash when clicking "introduction" on the ??? book

### ISSUE THREAD

**Issue by FlyingThunder** [FTBTeam/FTB-Interactions#778]
## Modpack Version: 
1.9.1

## Is It Repeatable? Steps to Reproduce: 
1. open the book
2. click on introduction
happens every time

## Link to Log or Crash File Paste**: 
https://pastebin.com/7zGcnDqp

**Comment by jikuja** [comment]
afaik recipe for the book has been removed because of the crash.

**Comment by Saereth** [comment]
yeah you cant craft the book anymore for this reason, patchouli is updated in the next patch though, should resolve this
