### ISSUE TITLE
Exquisite gems produce useless rods (Gregtech)

### ISSUE THREAD

**Issue by Sirbab** [FTBTeam/FTB-Interactions#782]
## Modpack Version: 
1.91
## Bug Report:
If you look at the uses for exquisite gems, every single one has a presumably auto generated recipe for tool rods.  When examining these tool rods, at least JEI claims they have 0 use aside from producing equally useless other parts.  Given how much of this pack relies on using the recipe/uses feature of JEI, this leads to confusion, and assumedly increased load time for generating these meta tools.

## Expected Behavior/Suggestions:
Either these meta items should recieve a use, or somehow be blacklisted from having a recipe to create them.

## Is It Repeatable? Steps to Reproduce: 
Look at uses for exquisite red garnet, or really any exquisite gem.

## Link to Log or Crash File Paste**: 
N/A

## Mod/s Affected: 
Gregtech CE

## Known Fix: 
Detailed in suggestions area

**Comment by Saereth** [comment]
This is more an issue for GTCE since there is no way to disable them pack side. FWIW their creation is close to negligible performance/ram wise. I will look into hiding them from jei later

**Comment by Yakameen** [comment]
Removed gem rods, long rods, and bolts that do not have any recipes from JEI. I left in rods like emerald and lapis that are used in other recipes.
