### ISSUE TITLE
Primal_Tech Kiln not firing.

### ISSUE THREAD

**Issue by TheMoakMan** [FTBTeam/FTB-Interactions#783]
## Bug Report:
Kiln not turning in to fired kiln when placed correctly over a block with 
fire. This issue occurred on a small multiplayer server where both players
were using the same version and mod-pack.

## Expected Behavior/Suggestions:
Kiln should be turned in to fired kiln when placed properly.

## Is It Repeatable? Steps to Reproduce: 
1. Place block (Preferably wood or charcoal) 
2. Place another block on top of block
3. Place Kiln on top of second block
4. Destroy middle block
5. Light bottom block directly under kiln on fire. 
6. Wait until kiln turns into a fired kiln
7. Use fired kiln as a furnace.

## Link to Log or Crash File Paste**: 
N/A

## Mod/s Affected: 
primal_tech 

## Known Fix: 
Unknown Fix

**Comment by heydabop** [comment]
Put something firable (like clay or sand) in the kiln and wait, it'll become a fired kiln.
