### ISSUE TITLE
All FTB packs fail to launch

### ISSUE THREAD

**Issue by Excalibur204** [FTBTeam/FTB-Interactions#786]
## Modpack Version: 
All versions of FTB modpacks

## Bug Report:
16:34:56.674
Preparing to launch minecraft client for forge-14.23.5.2838
16:34:56.983
Couldn't fetch SHA1 checksum for https://s3.amazonaws.com/Minecraft.Download/versions/1.12.2/1.12.2.jar
16:34:57.000
Have local file C:\Users\****\Twitch\Minecraft\Install\versions\1.12.2\1.12.2.jar but don't know what size or hash it should be. Have to assume it's good.
16:34:57.186
Couldn't fetch SHA1 checksum for https://modloaders.forgecdn.net/647622546/maven/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar
16:34:57.186
Have local file C:\Users\****\Twitch\Minecraft\Install\libraries\org\ow2\asm\asm-all\5.2\asm-all-5.2.jar but don't know what size or hash it should be. Have to assume it's good.
16:34:57.202
Couldn't fetch SHA1 checksum for https://modloaders.forgecdn.net/647622546/maven/net/minecraftforge/forge/1.12.2-14.23.5.2838/forge-1.12.2-14.23.5.2838.jar
16:34:57.202
Have local file C:\Users\*** ***\Twitch\Minecraft\Install\libraries\net\minecraftforge\forge\1.12.2-14.23.5.2838\forge-1.12.2-14.23.5.2838.jar but don't know what size or hash it should be. Have to assume it's good.
16:34:57.227
Couldn't fetch SHA1 checksum for https://modloaders.forgecdn.net/647622546/maven/org/jline/jline/3.5.1/jline-3.5.1.jar
16:34:57.228
Have local file C:\Users\******\Twitch\Minecraft\Install\libraries\org\jline\jline\3.5.1\jline-3.5.1.jar but don't know what size or hash it should be. Have to assume it's good.
16:34:57.375
Couldn't fetch SHA1 checksum for https://modloaders.forgecdn.net/647622546/maven/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
16:34:57.376
Have local file C:\Users\*****\Twitch\Minecraft\Install\libraries\com\typesafe\akka\akka-actor_2.11\2.3.3\akka-actor_2.11-2.3.3.jar but don't know what size or hash it should be. Have to assume it's good.
16:34:57.520
Couldn't fetch SHA1 checksum for https://modloaders.forgecdn.net/647622546/maven/com/typesafe/config/1.2.1/config-1.2.1.jar

## Is It Repeatable? Steps to Reproduce: 

1.
2.

**Comment by Saereth** [comment]
this isnt a pack specific issue and I cant offer you much help you on your problem, sorry
