### ISSUE TITLE
Gregtech needs to be updated

### ISSUE THREAD

**Issue by cabbby** [FTBTeam/FTB-Interactions#788]
Some bugs in old version Gregtech really bothered me during gameplay, and a lot of them were fixed in the latest version, so I think it may be good to keep Gregtech version up to date.

Just to be mentioned, Gregtech provides Coke Oven JEI recipe category by itself now, which conflicts with the one Shadows of Greg has. So a lot of Gregtech stuff is missing recipes when you put them working together. There should be some changes on it. Actually, to solve the problem, it seems okay to simply remove the JEI recipe category registration from Shadows of Greg.

**Comment by jlindsey** [comment]
Shadows of Greg just released a new version a few days ago (1.9.0) that seems to fix this integration. Upgrading both GTCE and SoG to the latest versions as of this post fixed all the issues.

**Comment by lespaul5895** [comment]
> Shadows of Greg just released a new version a few days ago (1.9.0) that seems to fix this integration. Upgrading both GTCE and SoG to the latest versions as of this post fixed all the issues.

I've tried this updating both Shadows and GTCE and now every time I launch it crashes the game.

**Comment by Saereth** [comment]
this is not a simple issue, bringing gregtech up to speed from so far back is requiring alot of work, expect it around the Interactions 2.0 release near christmas (or a bit sooner, my time depending)

**Comment by Glorken** [comment]
To those who update GTCE manually, don't forget to also update its dependents CEU and Shadows of Greg. SoG was mentioned above, but not updating CEU will cause the game to crash, at least with the current versions.
