### ISSUE TITLE
Resizing Potion breaks enderio (and possibly other mods) step assist

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [FTBTeam/FTB-Interactions#789]
## Modpack Version: 
1.9.1

## Bug Report:
Enderio dark boots step assist does not work

## Expected Behavior/Suggestions:
It should work and allow you to step up blocks

## Is It Repeatable? Steps to Reproduce: 
Wear dark boots with at least one piston upgrade and power upgrades, attempt to walk up a block

## Mod/s Affected: 
Enderio

## Known Fix: 
Remove resizing portion.

This issue is caused by resizing potion setting the player step height every tick. https://github.com/CammiePone/Resize-Potion/blob/master/src/main/java/com/camellias/resizer/handlers/PotionHandler.java#L71

Related issue: 
https://github.com/CammiePone/Resize-Potion/issues/11

**Comment by trlababalan** [comment]
Check also Astral Sorcery's Hiking Boots perk. It didn't work for me, either so I had to re-spec the tree.
I always have the Growth Trinket equipped, though... Didn't realize it matters.
