### ISSUE TITLE
D key doesn't work

### ISSUE THREAD

**Issue by nominate17** [FTBTeam/FTB-Interactions#790]
## Modpack Version: 
1.9.1

## Bug Report:
D key doesnt work ingame so i cant move to the right

## Expected Behavior/Suggestions:
it is only in movement, others as typo are acting normally
I want to know how to fix it

## Is It Repeatable? Steps to Reproduce: 
I am sorry to bring no evidence; but it continues happening whenever I launch it

## Mod/s Affected: 
That's I want to know

**Comment by Saereth** [comment]
this is probably some kinda keybind conflict, send me your options.txt file via hastebin and I'll take a look

**Comment by Saereth** [comment]
Never heard back, cant reproduce, closing this
