### ISSUE TITLE
Ender chicken does not produce neutron piles when affected by the fysallidic prime

### ISSUE THREAD

**Issue by Fiaegel** [FTBTeam/FTB-Interactions#791]
## Modpack Version: 
1.9.1

## Bug Report:
When the ender chicken is captured by the Fysallidic prime, it has no AI and it can not be damaged, so the ZenTrigger script fails to run and generate Piles. Since this is one of the intended ways of making them, it could be frustrating and progression breaking.

To reproduce this issue, spawn an ender chicken close to an active fysallidic prime and try to damage it or placing liquid antimatter near it.

This was marked as fixed in the changelogs but this is still not working.

## Known Fix:

In order to fix this you have to update Zen Triggers to version 1.0.10 and modify the script ZenEvents.zs as follows:
```
Handler.setRawInterval(10); 
Handler.onEntityUpdateRaw(
		PredicateBuilder.create()
			.isRemote()
			.negateLatest()
			.isRandom(0.1)
			.isInstanceOf("mightyenderchicken:ent_EnderChicken")
			.isInBlockArea(<blockstate:animus:blockfluidantimatter>.block,3,3,3,3)
		,function(event as EntityLivingUpdateEvent){
		//print ("event triggered correctly for enderchicken");
		val neutron = <avaritia:resource:2>;
		if(isNull(neutron)) {
		print("neutron is null in event");
		return;
		}
		if(isNull(event.entity)){
		print("Entity is null in event");
		return;
		}
		event.entity.world.spawnEntity(neutron.createEntityItem(event.entity.world, event.entity.position));
		event.entityLivingBase.health -= 5;
	}
);
```

**Comment by Saereth** [comment]
this is fixed in the next update, but the next update wont be for a while
