### ISSUE TITLE
FTB Interactions Crash on world load

### ISSUE THREAD

**Issue by PopMcPop** [FTBTeam/FTB-Interactions#792]
## Modpack Version: 
FTB Interactions Version 1.9.1

## Bug Report:
The game crashed whilst exception in server tick loop
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MineTogetherServer (minetogetherserver)
Game Crashes on load of specific world, displays above message in launcher. Does not crash when loading other worlds. Always crashes after displaying the "Building Terrain" message

## Is It Repeatable? Steps to Reproduce: 
Repeats on load of single world

## Link to Log or Crash File Paste**: 
[crash-2019-09-11_12.36.37-server.txt](https://github.com/FTBTeam/FTB-Interactions/files/3602103/crash-2019-09-11_12.36.37-server.txt)

**Comment by Saereth** [comment]
disable minetogether, rare crash for some people but the mod isnt required
