### ISSUE TITLE
Java crash when using portals

### ISSUE THREAD

**Issue by zedekblue** [FTBTeam/FTB-Interactions#795]
Modpack Version: 
1.9.1

## Bug Report:
Client Java crash when going through portals.

## Expected Behavior/Suggestions:
(´･ω･`)

## Is It Repeatable? Steps to Reproduce: 
Not reliably repeatable, but I've had it happen 4 times now, both when playing singleplayer & when connected to a server. Occasionally happens when walking through one of my overworld/nether portals. Haven't seen it when returning, only when leaving the void dimension. It's always a java crash and only spits out a hs_err_pid log.
Note, I do have optifine installed. This more or less makes my report null and void, but I thought I'd report it anyway in case the issue comes up for anyone else.

## Link to Log or Crash File Paste**: 
https://pastebin.com/3xsHzYAP
https://pastebin.com/HsJ19TPF

## Mod/s Affected: 
(´･ω･`)

## Known Fix: 
Happens so occasionally I can't even really test a fix. I would try uninstalling optifine, but it would take a solid week for me to be "kind of sure" it's fixed.

**Comment by Saereth** [comment]
tried a bunch to reproduce this, no dice
