### ISSUE TITLE
Golemancy Iron Plates not working

### ISSUE THREAD

**Issue by heykiditsaaron** [FTBTeam/FTB-Interactions#796]
## Modpack Version: 
1.9.1

## Bug Report:
Cannot use GTCE iron plates with the golem press to make iron golems.

## Expected Behavior/Suggestions:
Should oredict gtce iron plates or give access to making thaumcraft iron plates

## Is It Repeatable? Steps to Reproduce: 
1.Try to make an Iron Golem
2.
## Mod/s Affected: 
Thaumcraft

**Comment by Saereth** [comment]
There is a recipe to convert them to TC plates, just shapecraft with themselves, unfortunately TC has no way to allow GT plates to be used currently.
