### ISSUE TITLE
Blazes retaliate from bleeding effect from Tinkers' Construct

### ISSUE THREAD

**Issue by Bedrockbreaker** [FTBTeam/FTB-Interactions#797]
## Modpack Version: 
1.9.1

## Bug Report:
Blazes will perform the "anti-melee" attack on the player any time they are damaged by the bleeding potion effect from Tinkers' Construct (steel parts). This can happen at long distances with projectiles, seeming that the player is being damaged from an unknown source.

## Expected Behavior/Suggestions:
Blazes should not attack the player back when harmed by the bleeding effect.

## Is It Repeatable? Steps to Reproduce: 
1. Obtain tinker weapon with steel parts (thus bleeding effect)
2. Attack blaze with said weapon
(Note: Only tested in survival single player world with shurikens)

## Mod/s Affected: 
1. Tinkers' Construct
2. Rough Mobs 2? (or whatever mod adds the anti-melee thing)

## Fix?
Not sure how this could be fixed, as it seems mostly a fault on tinkers' end for the potion effect identifying as melee damage instead of magic or something.

**Comment by Saereth** [comment]
this has been reported but not much I can do about it from a pack standpoint
