### ISSUE TITLE
/rtp Command crashes servers

### ISSUE THREAD

**Issue by fGravity** [FTBTeam/FTB-Interactions#80]
## Bug Report:
Whenever a player does /rtp command it times out the server and crashes it (looking for a proper place to teleport the player to for too long?)
## Expected Behavior/Suggestions:
Suggest disabling the /rtp command in configs by default

## Is It Repeatable? Steps to Reproduce: 
1. Join a server
2. Run a /rtp command

## Link to Log or Crash File Paste**: 
https://pastebin.com/XSWK1tEy

## Mod/s Affected: 
FTBUtil

## Known Fix: 
Suggest disabling the /rtp command in configs by default

**Comment by Vyraal1** [comment]
Just an update on this, it already is set to false by default. Can your server owner check the ftbutilities.cfg and pastebin it here? `rtp=false` should be on line 82

**Comment by Saereth** [comment]
as rtp ships off and should not be enabled in a void world anyway im flagging this invalid
