### ISSUE TITLE
Soulus Bone Chunk recipes interaction with Gregtech Mixer

### ISSUE THREAD

**Issue by silvanasmax** [FTBTeam/FTB-Interactions#801]
Soulus bone chunks (6 recipes) do not all work using the Gregtech Mixer recipe provided.
Normal - (life essence, bone) succeeds
Dry - (LE, bone, sand) fails
Mossy - (LE, bone, ball of moss) fails
Frozen - (LE, bone, packed ice) fails
Scale - (LE, bone, pris shard) fails
Ender - (LE, witherbone) - succeeds, and is key to getting around it

NOTE: This only addresses the BONE recipe version, not the RIB BONE version.

## Modpack Version: 
1.9.1 (public server)

## Bug Report:
The four failures above all have one thing in common: they have the Normal Bone Chunk recipe as a subset.  This means that, (problem 1) if the player puts LE and bone into the mixer first, the Mixer will immediately fire off "Normal" recipe. 

(Problem 2) reversing the order of the Mixer inputs to get around the issue still results in Normal recipe firing off and ignoring the unique recipe item completely.

(Problem 3)  Mossy Bone Chunk recipe has a duplicate entry for the BONE variant.

(Problem 4) Scale Bone Chunk recipe is missing the RIB BONE variant.

NOTE: Problems 1 & 2 above do not address RIB BONE recipe variants, but they could very well have a similar problem as well (due to cost of rib bones, was not tested), since they also hve Normal bone chunk recipe as a subset.

## Expected Behavior/Suggestions:
Expected Behaviour: recipes should work as advertised, like normal MIxer recipes.

Suggestion: remove BONE from the recipes would be easiest as it makes each recipe not have overlap.  However, this makes them not make logicl sense.  Possible solution would be to add new items that are combinations of the unique items and bone (i.e. mossy bone = ball of moss + bone, scaly bone = prismarine shard + bone, etc).

## Is It Repeatable? Steps to Reproduce: 
Repeatable.
Go into Gregtech Mixer, add Life Essence, Moss Chunk/Sand/Pris Shard/Ball of Moss, add bone.  The unique recipe item will be ignored.

## Link to Log or Crash File Paste**: 
No log or crash file generated.

## Mod/s Affected: 
Soulus, Gregtech

## Known Fix: 
Not a known fix, but a workaround.  Currently, to get around the issue, the player must go into the mixer and make an Ender recipe first.  WITHOUT LEAVING the Mixer's GUI, then start making other bone chunk recipes in "reverse order" (i.e. putting the bone in last).  This will create the necessary recipes.

**Comment by Saereth** [comment]
Soulus is getting removed in a future update so just not worrying about this for now
