### ISSUE TITLE
Dense Steel Plate/Dense Tungsteel Plate recipes (Bending Machine)

### ISSUE THREAD

**Issue by silvanasmax** [FTBTeam/FTB-Interactions#804]
The Dense Steel Plate recipe in the Bending Machine has two competing recipes that are nearly identical composition, but have different energy needs:
recipe 1: Steel Plate & Programmed Circuit = 5, 10752 EU
recipe 2: Steel Plate & Programmed Circuit = 2, 48384 EU

NOTE: Steel Ingot + Programmed Circuit = 5 is fine.

Edit NOTE: Dense Tungsteel Plate also has this issue.

## Modpack Version: 
1.9.1 (public version)

## Bug Report:
It is unknown what energy requirement is being used.

## Expected Behavior/Suggestions:
There should only be one recipe.

Suggestion: refer to the alternate recipe using ingots +  programmed circuit = 5.  It shares partial  composition with the above duplicated recipes.

## Is It Repeatable? Steps to Reproduce: 
Peristent.

## Link to Log or Crash File Paste**: 
No crash file generated.

## Mod/s Affected: 
Gregtech

## Known Fix: 
None.

**Comment by silvanasmax** [comment]
Additional info: ALL dense plates have the same problem as described above.

**Comment by Saereth** [comment]
This is fixed in the latest gtce update
