### ISSUE TITLE
Primative Blast Furnace quest item not completable

### ISSUE THREAD

**Issue by silvanasmax** [FTBTeam/FTB-Interactions#806]
Under Ayo Technology tab in the Quest Book, "Primative Blast Furnace" has no goal stated, thus no way to accomplish the quest. This is similar to the issue with the Bronze Drum quest bug report (#752).

## Modpack Version: 
1.9.1 (public server)

## Bug Report:
As described

## Expected Behavior/Suggestions:
There should be an item (like the controller, or a number of parts for the overall furnace) available to complete,.

## Is It Repeatable? Steps to Reproduce: 
Persistent

## Link to Log or Crash File Paste**: 
None

## Mod/s Affected: 
Quest Book

**Comment by jug007** [comment]
I am pretty sure the Quest just says something like "Go to the Metallurgy tab to complete the quest".
