### ISSUE TITLE
Telepad Block needs a SAG MIll to work.

### ISSUE THREAD

**Issue by trlababalan** [FTBTeam/FTB-Interactions#809]
## Modpack Version: 
1.9.1

## Bug Report:
Telepad Block needs Dew of the Void to teleport.
Dew of the Void is made in a SAG Mill.
SAG Mill is disabed for other reasons.
Telepad Block can wind up a bit but not teleport. It now functions only as a fancy-looking Travel Anchor.

## Expected Behavior/Suggestions:
Since SAG Mill is disabled and we can't make Dew of the Void, either make it work without the fluid or give us the recipe for the fluid.

**Comment by Saereth** [comment]
dew of the void spawns near bedrock at the moon in pools, you get it there
