### ISSUE TITLE
Can't make Unstable Ingot blocks.

### ISSUE THREAD

**Issue by Uthael** [FTBTeam/FTB-Interactions#810]
## Modpack Version: 
1.9.1

## Bug Report:
I want to make one-way windows from within a in-mountain base, to look outside.
Unstable Ingots don't have their block recipe. 
Block of Unstable Ingot (I'm not sure if that's the correct name) can't be found in JEI. I assume it's disabled.

## Expected Behavior/Suggestions:
There are a couple of glitches that allow for a temporary x-ray. Each of them much easier than making this block. My favorite is to just nudge a GregTech machine. It loses textures on all sides.

But none of that matters since you can do a "noclip" with legit play. And quite early, too.

So, can we get the Block of Unstable Ingot back?
If no, is it possible to make one-way windows some other way?

## Mod/s Affected: 
Extra Utilities 2

**Comment by Saereth** [comment]
this block actually just doesnt seem to exist in this version of exu2 period
