### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Lagicrus** [FTBTeam/FTB-Interactions#812]
## Modpack Version: 
1.9.1

## Bug Report:
Crash on load

## Expected Behavior/Suggestions:
Should load

## Link to Log or Crash File Paste**: 
https://starb.in/AKZCrT.rb

**Comment by Saereth** [comment]
reinstall, log shows some things corrupted when trying to load in, this is not a normal or reproducible issue

**Comment by Lagicrus** [comment]
thanks
