### ISSUE TITLE
[Questbook] Furnaces

### ISSUE THREAD

**Issue by Lagicrus** [FTBTeam/FTB-Interactions#813]
## Modpack Version: 
1.9.1

## Expected Behavior/Suggestions:
Suggestion:
Add a quest tree for furnaces in the machine page
~Funny quest descriptions required~

**Comment by trlababalan** [comment]
A vanilla furnace is hard to come by on servers where villages are raided already. A quest that gives you one would be appreciated. Possibly as a reward for building the TiC one.

**Comment by Saereth** [comment]
there is zero reason to ever have a vanilla furnace, absolutely wont be giving any out as a quest reward. The only reason they even still exist in villages as it was more work to remove them from worldgen than was worth.

A questline for furnaces going from kiln up to multismelter etc would be cool though

**Comment by Uthael** [comment]
Some recipes are still exclusive to it. One example: Astral Sorcery Starmetal Ingot (if I remember its name) is obtainable in the vanilla furnace. GregTech Starmetal Ingots don't work in some recipes.
There may be more examples, but it was a long while ago when I had the problem.

**Comment by Lagicrus** [comment]
> A questline for furnaces going from kiln up to multismelter etc would be cool though

Yeh that is what I was thinking, from the starting kiln which needs the fire under it which could easily link into the starting page, through to the basic steam furnace, high pressure, then electric and beyond :)

**Comment by Saereth** [comment]
lol well aesthetics I can see I suppose, I mean zero technical reason. Every recipe should be doable in gt furnaces, if you find any that arent report them. As for aesthetics purposes maybe I'll add a recipe you can do to make them once you're into LV or something. Just trying to avoid the great wall of furnaces people tend to do if they arent prodded on towards better smelters

**Comment by Saereth** [comment]
you can now convert firebricks into vanilla furnace with salis mundis, it's a bit annoying/pricey but hey there's an option now at least
