### ISSUE TITLE
[Questbook] Add more rewards

### ISSUE THREAD

**Issue by Lagicrus** [FTBTeam/FTB-Interactions#814]
## Modpack Version: 
1.9.1

## Expected Behavior/Suggestions:
Add more random quest rewards for quests which don't have any.
This can both add to the funny nature of doing them as well as a point to doing them
As well as a feeling of "Hey, that was worth it for X item"

**Comment by Saereth** [comment]
this is already planned! :D

**Comment by Lagicrus** [comment]
awesome :D
