### ISSUE TITLE
[Questbook] Add a quest tree for Cyberware

### ISSUE THREAD

**Issue by Lagicrus** [FTBTeam/FTB-Interactions#815]
## Modpack Version: 
1.9.1

## Expected Behavior/Suggestions:
Suggestion
Add quest tree for cyberware as it is a very useful mod to have/use
Also it means you can continue the bender meme from the Plate Bender Machine
"Now you can actually become Bender" and so on

**Comment by Saereth** [comment]
this would go well under the tab "If you can wear it you can progress it" if some wants to tackle it
