### ISSUE TITLE
Electric Piston (LV)

### ISSUE THREAD

**Issue by Lagicrus** [FTBTeam/FTB-Interactions#816]
## Modpack Version: 
1.9.1

## Bug Report:
Recipe only shows 
![image](https://user-images.githubusercontent.com/24227350/67409529-9b4cdb80-f5b2-11e9-9e14-225dbe0b3c4f.png)
but when you put it into modular storage the recipe changes to 
![image](https://user-images.githubusercontent.com/24227350/67409586-ae5fab80-f5b2-11e9-9d3a-a244149947aa.png)
which is an item that doesn't exist

## Expected Behavior/Suggestions:
Bug:
Expected Steel Rod from GregTech
Got Steel Rod from Vulpes

**Comment by trlababalan** [comment]
This is also making issues when you're creating patterns in AE2.

**Comment by Yakameen** [comment]
Proposed fix by removing the Vulpes rods from ore directories. This prevents them from being pulling into the workbench and defaults it to the gregtech rods

https://github.com/FTBTeam/FTB-Interactions/commit/a0362259ddf202313115572cad51db47e486196b

**Comment by Saereth** [comment]
fixed via https://github.com/FTBTeam/FTB-Interactions/pull/860
