### ISSUE TITLE
Lost Block information box 

### ISSUE THREAD

**Issue by IroidoSoner** [FTBTeam/FTB-Interactions#817]
Hello,
We've lost the ability to see block information when looking at a block. We cannot seem to find any information on what mod does this and how to get it back.

Modpack Version: 
1.9.1

**Comment by FireJadian** [comment]
Too lazy to double check and get things exactly right, but...

From projecte's Transmutation Tablet, you can get the thing from "The One Probe" for 1 EMC.  If you use it, you can configure on how much the item The One Probe is needed.  

iirc, leftmost option is "item is not needed at all", middle is "item is needed for full info", rightmost is "item is needed to see anything".  Clicking one of the left two options should bring that info back.

**Comment by Saereth** [comment]
this yeah ^
