### ISSUE TITLE
Stellar Alloy ingot-to-block recipes (edited, see comments)

### ISSUE THREAD

**Issue by silvanasmax** [FTBTeam/FTB-Interactions#819]
Stellar Alloy ingot has 2 flavors (Gregtech and Ender IO)  Fluid solidifier and Alloy Smelter take this into account fine.  However, the Compressor is missing an obvious recipe that would simlify some players experience and methods: stellar alloy ingot x9 (gregtech) --> stellar alloy block (gregtech). 

## Modpack Version: 
1.9.1 (public server)

## Bug Report:
Recipe missing for Compressor (Gregtech) for Stellar Alloy Ingot type.

## Expected Behavior/Suggestions:
Suggest: Modify the current Stellar Alloy Ingot to block recipe in the Compressor to accept any "IngotStellarAlloy" (see Alloy Smelter similar recipe for example).

## Is It Repeatable? Steps to Reproduce: 
Persistent

## Link to Log or Crash File Paste**: 
None

## Mod/s Affected: 
Gregtech, Ender IO

## Known Fix: 
None

**Comment by silvanasmax** [comment]
Further testing showed that stellar alloy ingot (ender io) to stellar alloy block (ender io) has a compressor recipe as well, but the recipe directly conflicts with the one that creates the gregtech stellar alloy block.

**Comment by silvanasmax** [comment]
FURTHER comments: Stellar Alloy dust is shows to "smelt" into the Ender IO verison.  However, this only happens in the smelter obtained from villages (pack restriction).  Putting the same dust in a gregtech smelter makes the gregtech ingot.  Given this, and given play on servers where village smelters are limited, this could possibly halt pack progress if ALL instances of dust and ingots for this are not accounted for in all recipes.

**Comment by Saereth** [comment]
any furnace except the multismelter will cook it properly for you. It's a known issue with the multismelter specifically and it wont be fixed on gregtech's side. You can use any of the electric furnaces to make it.
