### ISSUE TITLE
Advanced Rocketry duping whole rockets

### ISSUE THREAD

**Issue by silvanasmax** [FTBTeam/FTB-Interactions#820]
Doing the rocket progression of the pack, in making a standard rocket (2 engines, 6 tanks, 1 seat, 1 computer), when I scanned, then specifically BUILT the rocket, you could see it happen: the second building finished, a duplicate rocket entity would appear either on top of the parts, or next to it (depending on how big the pad was).  The ENTITY Rocket was inaccessible until the PARTS of the rocket were removed.  This, of course, duplicated all the rocket parts, and still produced a usable rocket.

## Modpack Version: 
1.9.1

## Bug Report:
Creation of rocket entity without removing the original rocket parts.

## Expected Behavior/Suggestions:
When the entity is created, the rocket parts should be removed.  Likewise, upon building, the parts should vanish so that the entity can appear in the proper spot.

## Is It Repeatable? Steps to Reproduce: 
Build a basic rocket.  Scan rocket.  Build rocket.  Result will be present.

## Link to Log or Crash File Paste**: 
None

## Mod/s Affected: 
Advanced Rocketry

## Known Fix: 
None

**Comment by Saereth** [comment]
this is an AR specific bug and sent on to them to deal with
