### ISSUE TITLE
Hitting minecraft zombies crashes the game

### ISSUE THREAD

**Issue by Mudartastisch** [FTBTeam/FTB-Interactions#821]
## Modpack Version: 
1.9.1
I removed Laser Creepers because I find them horribly unbalanced with the number of them spawning.

## Bug Report:
Hitting a normal Minecraft zombie with anything causes the game to crash

## Expected Behavior/Suggestions:
I don't even know why this happening all of the sudden

## Is It Repeatable? Steps to Reproduce: 
https://streamable.com/cujbo

Download link for the entire folder
https://www.dropbox.com/s/y5e6h0n3di242ys/FTBInteractions.zip?dl=0

I tried installing the pack again and copying the world, but this didn't change anything

## Link to Log or Crash File Paste**: 
https://pastebin.com/utgU9GG6

## Mod/s Affected: 
Reliquary
A user on Discord figured out that the zombie charm I had in the bauble belt storage caused this crash.

**Comment by Saereth** [comment]
this is a reliquary bug fixed in next update, there are several issues about it already if you use the search
