### ISSUE TITLE
Miniaturization FIeld Generator vs. ME Controller

### ISSUE THREAD

**Issue by silvanasmax** [FTBTeam/FTB-Interactions#822]
When making the ME Controller (which requires the Miniturization Field Generator setup from Compact Machines 3), initiating the process by throwing the catalyst in (Engineering Processor) results in black smoke particles, and all 12 AE2 cabels disconnecting and dropping to the ground, and the controller fails to create.  I was using ME GlassCable - Fluix (cheapest ones, as the recipe says "AE2 Cable and/or Bus").  When I replaced them with ME Covered Cable - Fluix, the recipe worked (black smoke particles, then the buzzing sound of the field generators starting up, and the multiblock shrinking).

NOTE: This was played on a public server, and as such, there was an issue with at least two other recipes that occured only there, and not in single player local.  This may or may not be an issue, but the behviour described was unique to this situation.

## Modpack Version: 
1.9.1 (public server)

## Bug Report:
See above.

## Expected Behavior/Suggestions:
Expected: Recipe should succeed the first time, no issues.
Suggestion: Get rid of the vague "AE2 Cable and/or Bus" and make it a concrete item, like "ME Covered Cable - Fluix", one that works.

## Is It Repeatable? Steps to Reproduce: 
1. Set up 4 field generators in 3x3 configuration.
2. Build the ME controller multi-block within the 3x3 area
3. Confirm on the field generator that the recipe is valid.
4. Drop the engineering processor in the field.

## Link to Log or Crash File Paste**: 
None.

## Mod/s Affected: 
Compact Machines 3, Applied Energistics 2

## Known Fix: 
Workaround: Instead of using ME Glass Cable - Fluix, make them into ME Covered Cable - Fluix and use those in the multiblock recipe.

**Comment by Saereth** [comment]
weird we were able to use standard glass cables fine, just tested again no issue. I could change them to covered cables though I suppose its not much of an issue

**Comment by Saereth** [comment]
fixed via cf4539382ab7ddbd8a9fc280efcc136eb3d26a1e
