### ISSUE TITLE
Fried Feast and Timpano do not have nutrition values 

### ISSUE THREAD

**Issue by BakaCode** [FTBTeam/FTB-Interactions#824]
## Modpack Version: 
1.9.1
## Bug Report:
Fried Feast and Timpano do not have nutrition values 

## Expected Behavior/Suggestions:
 Fried Feast should have all 5 nutrition values and Timpano should have Protein, Grain and Vegetable as it nutrition values

## Is It Repeatable? Steps to Reproduce: 

1.
2.

**Comment by Saereth** [comment]
These are new foods and the nutritional values just need to be added to the jsons
