### ISSUE TITLE
Thorium Ore into DENSE Uranium Ore

### ISSUE THREAD

**Issue by judders** [FTBTeam/FTB-Interactions#825]
## Modpack Version: 
Interactions 1.9.1 Server.

## Bug Report:
Starlight Transmutation turns Thorium Ore into DENSE Uranium Ore.
This is not as reflected in JEI. It should produce Uranium 238 Ore.
Placing Dense Uranium ore and breaking produces a 2 Uranium Ore.
Would be good if Dense Uranium ore was usefull.

## Expected Behavior/Suggestions:
Fix

## Is It Repeatable? Steps to Reproduce: 
see above

## Known Fix: 
None.

**Comment by Saereth** [comment]
This is not a bug, and no it does not transmute it into dense uranium ore, it transmutes it into uranium 238 ores, then if you leave it in the starlight it will convert uranium 238 into dense uranium which is used as part of the higher tier ore multiplication. Simple solution is mine it up before it transforms a second time or stop giving it starlight once it transforms (Both valid options for automation)
![image](https://user-images.githubusercontent.com/9200909/82736576-db1aa380-9cf8-11ea-91d1-f55e23918ad0.png)

![image](https://user-images.githubusercontent.com/9200909/82736585-e53ca200-9cf8-11ea-9057-9ba631fe3b8d.png)


![image](https://user-images.githubusercontent.com/9200909/82736570-ce964b00-9cf8-11ea-9f99-5a77b8177819.png)
