### ISSUE TITLE
Configure Microblocks

### ISSUE THREAD

**Issue by iComputerfreak** [FTBTeam/FTB-Interactions#826]
## Modpack Version: 
1.9.1

## Bug Report:
The microblocks.cfg config is empty, therefore only some vanilla blocks can be cut into pieces with the Forge Microblocks saw.

## Expected Behavior/Suggestions:
Additional decoration blocks should also be compatible with Forge Microblocks.

## Mod/s Affected: 
Forge Microblocks

## Known Fix: 
I went through all the blocks in the pack and created a working microblocks.cfg config.
If you add this config in the pack, many new block will be compatible with Forge Microblocks.
The config: https://gist.github.com/iComputerfreak/6683a52e1246ace3873c5b894cf12009
I tested the config with version 1.9.1 and it worked as expected.

**Comment by Saereth** [comment]
Added via bf76aebf0d5c421e3f368e2848ef8ae902504407
