### ISSUE TITLE
Visual Bug. Nvidia Update vs Spectre Illuminators.

### ISSUE THREAD

**Issue by WellGramarye** [FTBTeam/FTB-Interactions#827]
## Bug Report:
Since the latest Nvidia Update, Spectre Illuminators are causing entities like chests and liquids visible inside of containers like pipes and thaumcraft bottles, to sway and move outside their model's bounding box. These shots are taken on a single player world, where I have moved out of the starting void, put down some chests and illuminators only. Eventually they sway and jitter blocks away from their actual placement, though still remain interactable.

## Expected Behavior/Suggestions:
Chests and other entities shouldnt visually fly around

## Is It Repeatable? Steps to Reproduce: 
1. Put down chests
2. Put down bunch of Spectre Illuminators.
3. Have newest Nvidia Drivers

![chest1](https://user-images.githubusercontent.com/58095709/69471440-7b046e00-0d64-11ea-848f-5efc0531bb0f.png)
![chest2](https://user-images.githubusercontent.com/58095709/69471441-7dff5e80-0d64-11ea-9c01-7ad770750714.png)

Video of the glitch can be found here:
https://youtu.be/ytAOAMZFE88

**Comment by Saereth** [comment]
I have the latest nvidia drivers and no luck reproducing this, are you using optifine? Anyone else able to reproduce this?

**Comment by iComputerfreak** [comment]
I have the same bug from time to time. No Optifine installed. It's not super annoying for me, because it doesn't happen that often.
Here is another video of it happening to a chest: https://youtu.be/aitqgfi4lL4
And one time it happened to a sign: https://youtu.be/qm1jTx26z9k

I am not sure if I had Spectre Illuminators in the chunks at that time, but I probably had some in the world _somewhere_.

**Comment by Saereth** [comment]
oh wow that is super spooky, kinda cool lol. Definitely beyond the scope of a pack issue I think... maybe a mod interaction or random things, can anyone reproduce this with a stripped down mod list just random things + utilities?

**Comment by Saereth** [comment]
latest rt update seems to have resolved this
