### ISSUE TITLE
Robot arm loses settings if chunk becomes unloaded, supply exact settings resets to 1. 

### ISSUE THREAD

**Issue by Kylew90** [FTBTeam/FTB-Interactions#828]
## Modpack Version: 
1.9.1

## Bug Report:
When placing a robot arm on a packager, setting it to supply exact amounts with import, it will work as long as the chunk stays loaded.  If that chunk is ever unloaded for a certain amount of time, or you log off, upon logging back on, the settings for supply exact are reset to 1 requiring you to constantly have to fix it.

## Expected Behavior/Suggestions:

1.Place robot arm on side of packager 
2. Change settings for robot arm to Supply Exact
3. Set the setting for supply exact to 9 
4. Log out and return to main menu, proceed to log back in to that world after.
5. Check settings for the robot arm to see, they have reset back to 1.

**Comment by Folanlron** [comment]
This has been fixed awhile ago, VIA GregTech, no one knows when/if FTB is releasing a Interactions update though..

=/

**Comment by Saereth** [comment]
GTCE Update should resolve this
