### ISSUE TITLE
LittleTiles and OptiFine Interaction

### ISSUE THREAD

**Issue by Cata-bre** [FTBTeam/FTB-Interactions#831]
## Modpack Version: 
1.9.1

## Bug Report:
If OptiFine is installed any tiles made with LittleTiles will be invisible.

## Expected Behavior/Suggestions:
All tiles made with LittleTiles are invisible.
All tile made with LittleTiles should be visible.

## Is It Repeatable? Steps to Reproduce: 
Install the most recent version of OptiFine, use Little Tiles to create something, notice it is invisible.

## Link to Log or Crash File Paste**: 
No crash file to upload.

## Mod/s Affected: 
LittleTiles.

## Known Fix: 
This issue can be resolved in two ways:
I went to the Little Tiles Discord and asked how to fix the issue with invisible tiles, they said you can:
1. Stop using OptiFine.
2. Update LittleTiles and CreativeCore to the most recent version. The current version of LittleTiles and CreativeCore used in FTB Interactions 1.9.1 are outdated.

Versions used in FTB Interactions 1.9.1
CreativeCore: 1.9.80
LittleTiles: 1.5.0-pre135

Most recent versions
CreativeCore: 1.9.45
LittleTiles: 1.5.0-pre186

**Comment by Saereth** [comment]
fixed via 4954474194beac9b3492e0ad6d1ab7dae68f5ba0
