### ISSUE TITLE
Crashing (NullPointerException) in void world

### ISSUE THREAD

**Issue by KniveX** [FTBTeam/FTB-Interactions#832]
## Modpack Version: 
1.9.1

## Bug Report:
Playing single player mode, with no other player on LAN.
In void world (the starting world), pressed the `E` button to show the inventory, and then make Minecraft window out-of-focus (in my case: by browsing on Firefox).
Then it just suddenly crashed a few minutes later.

This is my first crash on FTB Interactions (debug mode said i'm at 102nd in-game day).

## Expected Behavior/Suggestions:
--

## Is It Repeatable? Steps to Reproduce: 
--

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/0bbf999b

## Mod/s Affected: 
Forge maybe? (just my two-cents by skimming the stack trace)

## Known Fix: 
--

Cheers.

**Comment by Saereth** [comment]
Not sure on this one, crash seems to indicate inControl which is a mcjty mod, maybe toss the log file over to him and see if he has any ideas https://github.com/McJtyMods/InControl/issues
