### ISSUE TITLE
DimensionalControl Portal have hardness of 0

### ISSUE THREAD

**Issue by iComputerfreak** [FTBTeam/FTB-Interactions#833]
# Modpack Version: 
1.9.1

## Bug Report:
DimensionalControl portal blocks have a hardness of 0 and can therefore be destroyed instantly by hand.

## Expected Behavior/Suggestions:
They should be unbreakable, like the vanilla nether portal blocks.

## Is It Repeatable? Steps to Reproduce: 
Create a custom Nether or Overworld portal, go into survival mode, left-click one of the portal blocks.

## Mod/s Affected: 
DimensionalControl

## Known Fix: 
Setting the hardness with CraftTweaker, does not work, since the portal blocks are TileEntities and don't seem to register a normal block.
I also opened an Issue on the DimensionalControl Issue Tracker: https://bitbucket.org/bloodnbonesgaming/dimensionalcontrol/issues/40/dimensional-portal-blocks-are-breakable

**Comment by Saereth** [comment]
This is a mod specific issue so hopefully we'll see it fixed on the mod side, surely an annoyance. As a work around maybe a crafttweaker event to override the attack action entirely if the target is a portal block? Could work....

**Comment by iComputerfreak** [comment]
I gave it another try and found a workaround. Seems the blocks are in fact real blocks, but setting their hardness using `<dimensionalcontrol:dimensional_portal>.asBlock().definition.hardness = -1;` gives me a NullPointerException.
Anyway I found another workaround using the BlockBreakEvent:
```
import crafttweaker.events.IEventManager;
import crafttweaker.event.IBlockEvent;

events.onBlockBreak(function(event as crafttweaker.event.BlockBreakEvent) {
    if (event.block.definition.id == "dimensionalcontrol:dimensional_portal") {
        event.cancel();
    }
});
```

Adding this to one of the scripts makes the portal blocks unbreakable. (they still disappear when breaking the frame)
