### ISSUE TITLE
Alchemical Bag not craftable

### ISSUE THREAD

**Issue by iComputerfreak** [FTBTeam/FTB-Interactions#836]
## Modpack Version: 
1.9.1

## Bug Report:
Alchemical Bag has a crafting recipe using an Alchemical Chest. The Alchemical Chest is not craftable and hidden from JEI.

## Expected Behavior/Suggestions:
Alchemical Bag should either be craftable or hidden from JEI.
If the Alchemical Chest is a loot item, it should be un-hidden from JEI and a Tooltip should be added.

## Mod/s Affected: 
ProjectE

**Comment by Saereth** [comment]
Alchemical bag recipe should be removed/hidden from JEI. Add to loot instead
