### ISSUE TITLE
[Quest] [Recipe] Tinkers' Flint Tools Quest not possible (The World is Your Table)

### ISSUE THREAD

**Issue by DoraTheExploder** [FTBTeam/FTB-Interactions#838]
## Modpack Version:
 1.9.1

## Bug Report:
 After starting the pack on the standard void world and chopping down a few trees, I am trying to complete the quest that requires Tinker's Flint Tools and cannot craft the necessary parts (Flint Axe Head, Pickaxe Head, and Shovel Head) nor can I craft the pre-made "Rudimentary" Tools added by CraftTweaker even if I spawn in the tool parts.

## Expected Behavior/Suggestions:
Crafting recipes indicated in JEI should produce the products indicated, but are producing nothing.

## Evidence: 
1. Recipe Listed in JEI for Flint Axe Head: https://prnt.sc/qi2b50
2. Recipe Followed (w/o Output): http://prntscr.com/qi2b9j
3. (Other Recipes Omitted, but have the same behavior)
4. Recipe Listed in JEI for "Rudimentary Hatchet": http://prntscr.com/qi2bin
5. Recipe Followed (w/o Output): http://prntscr.com/qi2blb
6. (Other Recipes Omitted, but also have the same behavior)

## Is It Repeatable? Steps to Reproduce: 
1. Create a new world in version 1.9.1
2. Chop down trees and feed sticks to Transmutation Table until you have the EMC required
3. Attempt to craft listed tool heads as per quest.
4. (Spawn in broken tool head recipes).
5. Attempt to craft listed tools as per quest.

## Mod/s Affected:
 CraftTweaker2, Tinkers' Construct

**Comment by DoraTheExploder** [comment]
Frankly I'm somewhat surprised that I can't find any mention of this on Google either, as I doubt that I'm the only one who has had an issue like this in the past.

**Comment by Greygor** [comment]
I just started 1.9.1 today. All Rudimentary Recipes work for me, rudimentary part and Stone Rod (2 Cobblestones).

![image](https://user-images.githubusercontent.com/25403225/71643203-c50f3680-2cb6-11ea-8722-72bd155e108b.png)

Of course the GTCE Axe is still broken

**Comment by DoraTheExploder** [comment]
I suppose I could try to reinstall the pack or something, but there's so much configuration...

**Comment by DoraTheExploder** [comment]
Reinstalling the pack did NOT resolve the issue...

**Comment by DoraTheExploder** [comment]
I don't even understand what's going on anymore because now I can't even craft wooden planks...

http://prntscr.com/qibnlq

**Comment by DoraTheExploder** [comment]
@Greygor I have not added any mods, the only pack change I've made is to remove/disable Laser Creeper Robot Dino Riders From Space because I hate that mod for a number of reasons (including lack of respect for spawning rules, they spawn even at 15 light level).

**Comment by Greygor** [comment]
The Wood to plank issue is straight forward, you can't craft them, you place it in world and right click twice with an axe.

But that leads to the other issues which I'm at a loss here, Even random sampling of your start up log and mine looks almost the same. 

It may be time to check out their Discord, someone else may know the answer.

**Comment by Dakme** [comment]
@DoraTheExploder First of all, sorry if my english isn't great. After looking at your screenshots, I saw that you are using a crafting station. Did you try to craft these items from your inventory crafting grid or using a regular crafting table?

**Comment by Dakme** [comment]
After testing with and without "Laser Creeper Robot Dino Riders From Space", I found the problem. It seems that if you disable this mod, these recipes don't work. If you really don't like this mod, you could change the confing of the mod to disable the mob spawning.

**Comment by DoraTheExploder** [comment]
@Dakme Thank you for testing this, it seems that it has worked for me as well. The only thing to see now is if my config edits have worked as expected. I truly hope so.
