### ISSUE TITLE
dolly and greg chests

### ISSUE THREAD

**Issue by dahgul333** [FTBTeam/FTB-Interactions#839]
https://github.com/GregTechCE/GregTech/issues/853
please remove the possibility of crafting gt chests 
before solving the problem with them

**Comment by Saereth** [comment]
Yeah I dont know if removing GT chests entirely is the answer here, it's definitely annoying though. 
Community Opinions? Use at your own risk or remove?

**Comment by Cata-bre** [comment]
I'm in favor of removing since GT chests are glitchier than the iron/gold/diamond chests from iron chests. If you removed GT chests, you'd have to modify the RFTools Modular Storage recipe. I think removing GT chests would fit the pack's description of removing redundant blocks.

**Comment by Saereth** [comment]
yeah I think their place in the pack was always meant to be a jankier/cheaper version of iron chests but honestly, yeah not much point, I'll just need to adjust a few recipes but I'll remove them from next update. I wont disable the blocks though obviously as that would cause issues with existing worlds, will remove/hide from jei though.

**Comment by Saereth** [comment]
fixed via b668df757bfee95dc0fdc6f2fd3dd2741c085491
