### ISSUE TITLE
No terrain worlds generating

### ISSUE THREAD

**Issue by SabbanIndustrial** [FTBTeam/FTB-Interactions#840]
## Modpack Version: 
1.9.1 (btw, why it is not displayed in main screen?)

## Bug Report:
World types such as: "Void? World", "Realistic", "Large bioms", "Default" etc.. generate with no terrain or single bedrock block.

## Expected Behavior/Suggestions:
Generate worls with normal terrain

## Is It Repeatable? Steps to Reproduce: 
1. Download FTB Launcher
2. Download this modpack and launch it
3. Realize youre on 32 bit Java and force stop loading
4. Restart it with installed 64 bit java

## Link to Log or Crash File Paste**: 
No crashes today

## Mod/s Affected: 
??

## Known Fix: 
?

**Comment by Neeve01** [comment]
The “Void? world” preset generates everything just fine for me. 
It’s the intended preset and having no terrain generated when using other presets is the expected behavior.

**Comment by Saereth** [comment]
Yeah this is not a bug, the way the pack is designed you must use the void world preset
