### ISSUE TITLE
vanilla arrows work fine when fired from the same tinkerbow

### ISSUE THREAD

**Issue by fujishiro-m** [FTBTeam/FTB-Interactions#842]
## Modpack Version: 
1.9.1

## Bug Report:
vanilla arrows work fine when fired from the same tinker bow

## Expected Behavior/Suggestions:
tinker arrow better than vanilla

## Is It Repeatable? Steps to Reproduce: 
use tinker bow with tinker arrow and vanilla arrow

## Known Fix: 
see following ticket and update TConstruct.
https://github.com/TheRandomLabs/RandomConfigs/issues/11

**Comment by Saereth** [comment]
https://github.com/FTBTeam/FTB-Interactions/commit/18f94b327cc711f5b25ab640cf67b72d0bda6dd0
