### ISSUE TITLE
Magic Research isn't linked up for Team-Play.

### ISSUE THREAD

**Issue by kevinnnx10** [FTBTeam/FTB-Interactions#843]
I'm trying to do a playthrough with my friends on a server I have set up and I've encountered a problem. While the quest book is linked up, and we can all work towards progression in technology.... Magic research isn't also linked... Essentially, all my friends have to go back and do all the magic research that I've already done, in order to do any magic progression on their own. There needs to either be a way to link up all the progression or not show the quest compleat for my friends if they cant actually use the things made.

## Modpack Version: 
1.9.1

## Bug Report:
Not a bug, more of a flaw in the progression system

## Expected Behavior/Suggestions:
I would expect the magic progression /(all the progression) when playing on a team to also share with my friends... That way they can pick up where I left off and vis versa.

## Is It Repeatable? Steps to Reproduce: 
Yes. load up a server with friends and try to do magic where your friend leaves off at. essentially they cant use any of the magic tables that I've already crafted and completed the quests for.

## Link to Log or Crash File Paste**: 
none.

## Mod/s Affected: 
I would assume the questing mod? or the mod that links up players on a team.

## Known Fix: 
im assuming you would just have to link magic progress for all the people on a team. aka thaum, astral sorcery ect.

**Comment by Saereth** [comment]
Astral and Thaum both have knowledge sharing tomes in this pack, just make them for your friends. Thaum even has more of a share because there are quests in the magic section to directly bypass some researches that your friends can just click to activate.
