### ISSUE TITLE
corporea network not working on GTCE items

### ISSUE THREAD

**Issue by fujishiro-m** [FTBTeam/FTB-Interactions#844]
#  Modpack Version: 
1.9.1

## Bug Report
Botania Corporea Network is not working on almost GTCE items

## Expected Behavior/Suggestions:
Construct corporea network 
Ray some GTCE Ingot like copper ingot
request from corporea index
the ingot can’t be found 

## Is It Repeatable? Steps to Reproduce: 

1.
2.

**Comment by Saereth** [comment]
This is something that will need to be taken up botania and GTCE devs, not a pack specific issue

**Comment by Saereth** [comment]
Updated botania and GTCE seems to have resolved this
![image](https://user-images.githubusercontent.com/9200909/82735925-7dd02380-9cf3-11ea-8b62-46403e4926e1.png)
