### ISSUE TITLE
Random crashes only in over world

### ISSUE THREAD

**Issue by joelbrisco** [FTBTeam/FTB-Interactions#845]
## Modpack Version: 
1.9.1

## Bug Report:
Random crashes that only seem to occur in the over world. So far, with 8+ hours in the void realm, and numerous trips to the nether, this crash has never happen. But taking trips to the over world will randomly CTD, and it seems most of the time no crash log will be generated. Standing still in the over world, or moving around seems to make no difference, nor does the time periods. Sometimes I will only be in the over world for a few seconds and it will crash, other times, I can spend 30+ minutes running around with nothing happening. That being said, the crashes have ONLY ever happen when I have been near the surface, and seem mostly to only ever occur during the day time. The last error log that managed to generate is this
https://pastebin.com/PSeQgxQS

Which seems to be caused by the vanillia chicken? trying to spawn. Which considering the nature of the crashes, it seems to make sense something invalid is trying to spawn, and causing the crashes. It is worth noting however, hosting the map on a server and having this crash, does not crash the server also, and attempting a clean reinstall of the mod pack has also not caused this.

## Expected Behavior/Suggestions:
It does not crash randomly.

## Is It Repeatable? Steps to Reproduce: 
Head to over world, and run around for a while to force spawns? Maybe?

## Link to Log or Crash File Paste**: 
https://pastebin.com/PSeQgxQS

**Comment by Saereth** [comment]
This should be fixed with the next mod updates
