### ISSUE TITLE
AE2

### ISSUE THREAD

**Issue by Indyjunk** [FTBTeam/FTB-Interactions#846]
Sorry if I'm being a bother, but I couldn't find any other place to suggest this. Currently, FTB interactions doesn't have the Mod AE2 Stuff (Found Here https://www.curseforge.com/minecraft/mc-mods/ae2-stuff ) AE2 Stuff adds quality of life improvements to AE2 by adding the Crystal growth chamber and advanced inscriber. The Crystal growth chamber reduces lag and eases the automation of pure Certus quartz and pure Flux crystals. If at all possible this would be a wonderful addition to the pack, and as an AE2 enthusiast, is definitely a necessity to create a large AE2 system late game.

**Comment by benzenebanana** [comment]
It isn't necessary in this modpack. The pure certus and fluix are made in an energetic infuser from thermal and insribers aren't in the pack at all as all of the printed circuits are made via other means
