### ISSUE TITLE
GTCE honey cells in Rustic brewing barrels crash the game and mess up the save

### ISSUE THREAD

**Issue by CreationPro** [FTBTeam/FTB-Interactions#848]
## Modpack Version: 
1.9.1

## Bug Report:
Inserting GTCE cells filled with honey into a Rustic brewing barrel input slot crashes the game. The save remains corrupted unless you use a save editor to remove the cell from the barrel's inventory.

## Expected Behavior/Suggestions:

I expected the cell contents to empty into the barrel and an empty cell to be returned.

It shouldn't crash the game :)

## Is It Repeatable? Steps to Reproduce: 

1. Crush up some honey in a Rustic crushing tub.
2. Scoop it up with a cell.
3. Put into the Rustic barrel.
4. Crash.

## Link to Log or Crash File Paste**: 

Unavailable, sorry.

## Mod/s Affected: 

Rustic, GTCE

## Known Fix: 

Don't know one, sorry.

**Comment by Saereth** [comment]
oof that's gnarly, lets see if the issue still exists once we get some mods updated

**Comment by Saereth** [comment]
this should be fixed in the latest rustic update
