### ISSUE TITLE
Server crash on starting, caused by Thaumatorium or Wopper?

### ISSUE THREAD

**Issue by fujishiro-m** [FTBTeam/FTB-Interactions#849]
## Modpack Version: 
1.9.1

## Bug Report:
Server crash on starting, caused by Thaumatorium or Wopper?

## Is It Repeatable? Steps to Reproduce: 
put wopper on Thaumatorium, send some items, shutdown server, and start.
Maybe, I create and used Thaumonomicon cheat seat, is it relevant to this problem?
Reproduced with Vanilla Hopper

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/f8d56249

**Comment by Saereth** [comment]
This is not something we can fix packside, please report to primaltech/TC maintianers and just avoid using that item to pipe into the thaumatorium for now
