### ISSUE TITLE
Alchemical condenser possible unintended issue

### ISSUE THREAD

**Issue by Surfernick1** [FTBTeam/FTB-Interactions#85]
## Modpack Version: 
1.0.0
## Bug Report:
The alchemical condenser cannot be made with regular terracotta, and must be made with colored terracotta.

## Expected Behavior/Suggestions:
When trying to craft an alchemical condenser using terracotta from smelting clay, it is not craftable, and was only craftable using colored terracotta.

Should be craftable with all terracotta

## Is It Repeatable? Steps to Reproduce: 

No but i have photos
![1](https://user-images.githubusercontent.com/49054827/55213177-bfc50e80-51af-11e9-9a93-4c1ffc772ed3.PNG)
![2](https://user-images.githubusercontent.com/49054827/55213181-c2bfff00-51af-11e9-8009-cf60a7bacc6e.PNG)
 
Photo 1 is crafted with uncolored terracotta
Photo 2 is the JEI recipe which specifies colored

## Link to Log or Crash File Paste**: 

Not a crash

**Comment by Vyraal1** [comment]
players are intended to make it from the terracotta on their island, it is purposefully intended or colorTerracotta
![image](https://user-images.githubusercontent.com/26587049/55233980-75b84900-5200-11e9-80c5-6d95e0a6b068.png)
