### ISSUE TITLE
Can not find oil for Evershifting Fountain

### ISSUE THREAD

**Issue by fujishiro-m** [FTBTeam/FTB-Interactions#850]
## Modpack Version: 
1.9.1

## Bug Report:
I created Ichosic Resonator, and carry it to find oil .
The Astral Sorcery config says: oil and crystalized oil will be there,
but i can only find crystalized oil.

Maybe, it is like #304 .
gregtech oil has too many same id liquids, so AS cant decide which liquid should be there.

## Expected Behavior/Suggestions:
Oil can be mined with Evershifting Fountain.

**Comment by Saereth** [comment]
I have created a new instance and I've been able to reliable find oil in several locations. I will leave this issue open for now in case some others want to help take a look/reproduce
