### ISSUE TITLE
World gen bug

### ISSUE THREAD

**Issue by Stellarwind01** [FTBTeam/FTB-Interactions#852]
## Modpack Version: 
1.9.1

## Bug Report:
Oil fountains are generated in void? world
vein flowers are not generated in overworld, instead nuggets are generated? (I've only find gold nugget but maybe)
Enderman spawned by infinity dust in void? world dropped unfamiliar item(Ender bone)

## Expected Behavior/Suggestions:
Oils shouldn't be generated in void? world
 vein flowers should be generated in overworld

## Is It Repeatable? Steps to Reproduce: 
1.Download FTBApp and install FTB Interactions
2.Create 1.12.2 vanilla profile
3.Start Interactions and create new world

## Link to Log or Crash File Paste**: 
This situation don't cause crashes

## Mod/s Affected: 
mods are untouched

**Comment by Stellarwind01** [comment]
p.s. copper,iron nuggets are also found. Crassula Subulata is found but other vein plants are still unknown. Oil seems to be generated very frequently.(Confirmed generated in forest)

**Comment by Valorzsan** [comment]
Same issues:
-  oil in the Void
- metal nugget/tiny pile of metal generating instead of vein flowers.

**Comment by Stellarwind01** [comment]
I looked into config file and found this.(config>gregtech>worldgen>overworld
[overworld.zip](https://github.com/FTBTeam/FTB-Interactions/files/4450855/overworld.zip)
)
It maybe says that most of the vein flowers we know won't be generated anymore?

**Comment by Valorzsan** [comment]
Old launcher same interaction and gregtech version - flowers correctly generating.

In the new launcher the vein in the main overworld gregtech config file are missing the "vein populator attribute". Veins in Strata exclusive folder seem correct.

I will try to delete the overworld congif file to see if it generates correctly next time I play the pack.

________________________________

**Comment by Stellarwind01** [comment]
Does the old launcher profile config also has unfamiliar vein data such as pitchblende in overworld? I don't have old launcher in my current PC and don't know how to download it.

**Comment by Saereth** [comment]
The new Launcher imported from Twitch but perhaps some things imported incorrectly, The new update im working on isnt going to be an import it'll be a direct upload to both twitch and ftb's launcher so this should correct this disparity.
