### ISSUE TITLE
Thaumcraft copper nugget

### ISSUE THREAD

**Issue by minyman60** [FTBTeam/FTB-Interactions#854]
## Modpack Version: 
v1.9.1

## Bug Report:
You can access Thaumcraft copper nuggets, which are unusable in all recipes and can't be turned into regular nuggets.

Additionally this recipe is not in the recipe finder.

## Expected Behavior/Suggestions:
Give me a way to change the bad thaumcraft nugget into a gregtech nugget, or have the infernal furnace drop the gregtech nugget.

## Is It Repeatable? Steps to Reproduce: 
1.Put native copper cluster from thaumcraft in an infernal furnace
2.The furnace processes the cluster into 2 ingots and has a chance for nuggets.

**Comment by minyman60** [comment]
This may also happen for other native clusters from thaumcraft

**Comment by Saereth** [comment]
Best approach here is probably just removing the cluster processing from the infernal furnace and into standard Gt processing with a bonus yield over standard ore
