### ISSUE TITLE
Item Duplication

### ISSUE THREAD

**Issue by Bedrockbreaker** [FTBTeam/FTB-Interactions#856]
## Modpack Version: 
1.9.1

## Bug Report:
It's possible to duplicate items using dust washing in the cauldron or item burning. Testing for item burning is limited, and was done accidently with wrought iron, though the steps to reproduce should be the same.

## Expected Behavior/Suggestions:
It *probably* shouldn't duplicate items.

## Is It Repeatable? Steps to Reproduce: 
Unsure of the exact details, but throw *less* than a stack of unwashed or washed dust into the cauldron. Immediately throw in a full stack afterwards (untested for smaller stack sizes or different items than the first stack), and when both piles are picked up, you'll suddenly have 2 full stacks. This process can be repeated by splitting one of the stacks, and repeating.

As for item burning, I don't know if you have to wait for items to burn, or whether it works for "already burnt" items.

## Mod/s Affected: 
Gregtech and Wizardry. It might be more of underlying issue than these mods, because the mods themselves should be unrelated between each other.
Note, gregtech has been updated to the robot arm patch version, from the one pinned in the discord.

## Known Fix:
None

**Comment by Saereth** [comment]
not sure if this will still be an issue once the mod updates are in, we'll revisit this then

**Comment by Saereth** [comment]
This appears to be fixed in the new gregtech update
