### ISSUE TITLE
Multiblock Visual Bug

### ISSUE THREAD

**Issue by Yakameen** [FTBTeam/FTB-Interactions#868]
## Modpack Version: 
2.0 Pre-release

## Bug Report:
Multiblock preview in JEI are stuck perpendicular to the ground, preventing the center blocks from being seen. 

## Expected Behavior/Suggestions:
Multiblock preview should be orthogonal to allow all blocks to be seen. 

## Is It Repeatable? Steps to Reproduce: 
Look at the boiler multiblock or blast furnace.

## Mod/s Affected: 
Multiblock, Gregtech Community Edition

**Comment by Saereth** [comment]
this would be an issue for GTCE not pack specific, there is no pack method of changing the display, please submit a ticket here: https://github.com/GregTechCE/GregTech/issues
