### ISSUE TITLE
Items with recipes not fitting 9 stacks.

### ISSUE THREAD

**Issue by Vycka** [FTBTeam/FTB-Interactions#871]
## Modpack Version: 
1.9.2

## Bug Report:
As discussed on discord https://discordapp.com/channels/372448486723158016/560185294842888222/713926265610174545 I'm listing the items having recipes from 10+ stacks:
* Wetware Mainframe
* Field Generator (LuV)**
* Field Generator (UV)**
* Field Generator (ZPM)**

**Though field generator recipes can be workarounded by making pattern which takes 64 osmium wires for earch 4x64 fine osmium wires. and then catch it and pass through wire-mill before sending it to assembly line.

**Comment by Saereth** [comment]
The field generators have exactly 9 inputs
![image](https://user-images.githubusercontent.com/9200909/82832402-f4525a00-9e88-11ea-8789-f079bfec25b9.png)

Typically on the assembly lines you're just gonna keep the fluids auto supplied

I will adjust the mainframe recipe though, thanks for posting

**Comment by Saereth** [comment]
fixed 
![image](https://user-images.githubusercontent.com/9200909/82834053-ef43d980-9e8d-11ea-86a6-aedbb6be66e3.png)
