### ISSUE TITLE
Broken Recipe: Winged Everlasting

### ISSUE THREAD

**Issue by codewarrior0** [FTBTeam/FTB-Interactions#88]
## Modpack Version: 
1.0.0

## Bug Report:
Possible broken recipe, both input and output are `<plants2:cosmetic_2>`

![image](https://user-images.githubusercontent.com/307683/55228038-31578980-51bd-11e9-90dd-142c443c9005.png)

**Comment by Vyraal1** [comment]
Supposed to be marimophosis, fixed
