### ISSUE TITLE
[Mod Suggest] Alternative to SoG

### ISSUE THREAD

**Issue by YoungGT** [FTBTeam/FTB-Interactions#880]
## Modpack Version: 
Development version

## Expected Behavior/Suggestions:
There's an alternative to SoG called Gregicality which better than SoG.
Gregicality adds GT++, GTNH and GT6 things. GTCE now is weak. It needs addons(SoG)to complete its tech tree, that is to say, it's not completed comparing to GT5. It also doesn't have that much addons to provide productive multi-machines, powerful generators and useful ores.

**Comment by Saereth** [comment]
nope, far too much work for literally no gain
