### ISSUE TITLE
Item Duplication

### ISSUE THREAD

**Issue by Flame500** [FTBTeam/FTB-Interactions#881]
## Modpack Version: 
1.9.2

## Bug Report:
By using industrial foregoing conveyors you can duplicate any item that can be smelted/processed.

## Expected Behavior/Suggestions:
It shouldn't duplicate items

## Is It Repeatable? Steps to Reproduce: 
1. set up a industrial foregoing conveyor belt so that it has 2 insertion belts set to "inserting items in all the conveyor"
2. have it insert into a GregTech steam furnace.
3. toss items onto the conveyor one at a time (not sure if it works with partial or full stacks)
4. wait for the items to process/smelt
5. you can then grind the items back into dusts to repeat the process.

## Link to Log or Crash File Paste**: 
none
## Mod/s Affected: 
Probably due to the industrial foregoing conveyors

## Known Fix: 
Don't set up 2 insertion upgrades on the same conveyor and have them both set to insert from anywhere on the conveyor.
![Screenshot (84)](https://user-images.githubusercontent.com/66292601/83480459-0e7bd180-a461-11ea-9254-3868176368a5.png)

**Comment by Flame500** [comment]
note that it has to be multiple items, only using one item will not work for this

**Comment by Saereth** [comment]
mod issue, its been reported, out of my hands for now
