### ISSUE TITLE
Iron Chest

### ISSUE THREAD

**Issue by ResminZ** [FTBTeam/FTB-Interactions#886]
## Modpack Version: 
2.0.0 dev1

## Bug Report:
All the of the "Iron Chests" are uncraftable. You still can craft upgrades just fine and upgrade them, but there are quest which requires the chest, so you have to upgrade -> break -> upgrade -> break, etc

## Known Fix: 
Either make chests craftable or change the quest to require upgrades rather than the chests itself.

**Comment by Saereth** [comment]
yeah they wont be directly craftable, this was something vyraal wanted all along so I'll keep that but someone can change the quest requirements for sure
