### ISSUE TITLE
Just downloaded 1.9.2 and twerking trees doesn't work.

### ISSUE THREAD

**Issue by KelvallRogers** [FTBTeam/FTB-Interactions#889]
## Bug Report:
Twerking trees not working (tree growth). Tried sprinting in both directions, jumping, changing distance, using a few different dirt blocks. I was concerned it was a visual only bug (no green glow like bonemeal) but after ten minutes I've given up.

This is a fresh download, not an update from a previous download in a new world. No outside modifications.

**Comment by Saereth** [comment]
you can replace the contents of config/FTButilmine.cfg with this file to correct it, otherwise it's fixed in the 2.0 update

https://hastebin.com/olubaqudiq.bash.

**Comment by KelvallRogers** [comment]
Thanks for the tip @Saereth ! Worked great, and thanks for letting me know about 2.0 (I was just using the FTB Launcher application). I appreciate your team's hard work, keep it up!

**Comment by Saereth** [comment]
np, thanks!
