### ISSUE TITLE
Lose all EMC when I go to the overworld

### ISSUE THREAD

**Issue by Zendeth** [FTBTeam/FTB-Interactions#89]
## Is It Repeatable? Steps to Reproduce: Yes it is, 
1. Put some EMC and block inside a transmutation table
2. Use the portal to go to the overworld
3.Come back and you will have nothing in it

**Comment by TheonlyTazz** [comment]
Are you playing on a server? Is it a Sponge Server?

**Comment by Saereth** [comment]
can you verify the emc is gone and not just a visual glitch. For example, can you leave the server and rejoin and its still gone?

**Comment by Zendeth** [comment]
Yes I am playing on a server, I don't think it's a sponge server. It's a visual bug, I just disconnected and my EMC is back.

**Comment by TeamDman** [comment]
Mamadreads was also having this issue

**Comment by TheonlyTazz** [comment]
Mamadreads is also playing on a sponge server

**Comment by c0mical** [comment]
was going to comment but a few already have, I've noticed this on a few different modpacks on sponge server, not doesn't seem specific to Interactions

**Comment by TheonlyTazz** [comment]
Because it's not an interactions bug, it's an ProjectE + Sponge bug

Please report on their GitHub

**Comment by Saereth** [comment]
this is supposed to be fixed now
