### ISSUE TITLE
Typo in Steel Ingot JEI description (2.0-dev2)

### ISSUE THREAD

**Issue by Ludi87** [FTBTeam/FTB-Interactions#895]
## Modpack Version: 
FTB-Interactions-community-2.0-dev2

## Bug Report:
Typo in Steel Ingot JEI description
"Can be made in the infernal furnace from Steel ingots" (Make Steel from Steel?)

## Mod/s Affected: 
GT

![stee](https://user-images.githubusercontent.com/13112051/83981351-509f8a00-a91d-11ea-86cc-4f212ffc3148.png)

**Comment by Saereth** [comment]
already fixed in dev3
