### ISSUE TITLE
Can't recycle GregTech fluid drums

### ISSUE THREAD

**Issue by Cata-bre** [FTBTeam/FTB-Interactions#896]
## Modpack Version: 
1.9.1

## Bug Report:
GT frames (used to build machine casings) can be recycled into dust via maceration. When macerated GT frames yield a small fraction of the original material used.

Coil blocks used for the EBF/Multismelter/Pyrolyse oven can be recycled into dust via maceration. When macerated they yield 100% of the original material used.

GT fluid drums cannot be recycled into dust via maceration.

## Expected Behavior/Suggestions:
Add recipes that allow GT fluid drums to be turned into their respective dusts by macerating them.

## Is It Repeatable? Steps to Reproduce: 
Put a GT frame into a macerator => it is turned into dust.
Put a coil block into a macerator => it is turned into dust.
Put a GT drum into a macerator => nothing happens.

## Link to Log or Crash File Paste**: 
N/A

## Mod/s Affected: 
GregTech

## Known Fix: 
Add a recipe allowing GT drums to be macerated into their respective dusts. A GT drum takes 6 ingots to craft if machines are used.

If the added recipe behaves like the coil blocks, then macerating a GT drum would yield 6 dust (it would be lossless).

If the added recipe behaves like the GT frames, then macerating a GT drum would yield 2-3 dust (it would be lossy).

Another question; why do coil blocks macerate without any loss while frames macerate with loss? I can't think of any balance reasons.

**Comment by Saereth** [comment]
I'll add the lossless macerator recipe for the drums, as for why frames are lossy, idk, it's core gregtech and too many recipes to go tweak to be worth it, might be worth mentioning on the GTCE discord as changing it there would only be a couple lines of code to change
