### ISSUE TITLE
Minecraft crashes

### ISSUE THREAD

**Issue by RolaRoul** [FTBTeam/FTB-Interactions#897]
## Modpack Version: 
Commit 59f2724

## Bug Report:
I was walking around in a new area I hadn't explored before and minecraft crashed randomly. I tried opening the world again and minecraft crashed again as soon as I opened the world.

## Link to Log or Crash File Paste**: 
Three crash logs from earliest to latest:
https://paste.feed-the-beast.com/view/ce7cbd4f
https://paste.feed-the-beast.com/view/dacdc57f
https://paste.feed-the-beast.com/view/3a77f146

**Comment by Saereth** [comment]
this is fixed in dev-3
