### ISSUE TITLE
Trees dont grow faster when crouchng and running

### ISSUE THREAD

**Issue by Oceanman006** [FTBTeam/FTB-Interactions#898]
## Modpack Version: 

1.9.2
## Bug Report:

When I crouch/run around saplings they don't grow faster, slowing the early game to a crawl
## Expected Behavior/Suggestions:
I'm told by the quest "twerk to the left, sprint to the right criss cross!" that saplings are supposed the grow considerably faster when crouching or running around it like in Skyfactory4
## Is It Repeatable? Steps to Reproduce: 
1.have a sapling in dirt
2.run around it or crounch on it
3.watch as it doesn't grow faster

## Link to Log or Crash File Paste**: 
[latest - Copy.log](https://github.com/FTBTeam/FTB-Interactions/files/4748540/latest.-.Copy.log)

**Comment by Saereth** [comment]
duplicate https://github.com/FTBTeam/FTB-Interactions/issues/889
