### ISSUE TITLE
Enhancements/Sugestions

### ISSUE THREAD

**Issue by Xela10001** [FTBTeam/FTB-Interactions#899]
## Modpack Version: 
2.0.0 dev3

## Suggestions:
-reduce processing time of crystal matrix ingots, this is an expert pack, the expert part of this recipe should be getting the ingredients, not having to wait 8 mins and 20 secs for a single ingot at HV 

-the whole "canola + oil haha fun processing" is dumb because regular oil isnt renewable, unlike bio diesel and steam. I love this idea tho, so I would like bio diesel + canola to be a thing that works in making nitro diesel. Or you could go the lazy route and make regular black oil renewable. This is all so that diesel can be a viable alternative and you arent stuck with steam from the beggining to the end

-I am seeing very few Deadly Monsters compared to 1.9.1, is that intentional?

-Add a information thingy in JEI telling you to click a book on a chicken to turn it smart

**Comment by Saereth** [comment]
Oil is "effectively infinite" with the use of neuromatic primes, 4+ million buckets which you then triple via the specialized processing chain, its a bit more work to get and it isnt perfectly infinite, but that is part of the pack premise. Infinitely renewable source so of energy like bio-diesel and charcoal you can expect to see future reductions if anything, definitely wont be improving them/making them a more attractive option. 

* Gonna reduce the processing time on the crystal matrix ingot a bit
* will look into the deadly mobs not showing up
* Smart chicken can be summoned via zen summoning easier and this recipe shows in JEI already, so if they as an expert player know about book+chicken they can use it, or they can use the pretty easy summon which is already shown

**Comment by Saereth** [comment]
ok addressed all of these issues now
