### ISSUE TITLE
Rocketfuel Uncraftable

### ISSUE THREAD

**Issue by Eysla** [FTBTeam/FTB-Interactions#908]
## Modpack Version: 
InDev4

## Bug Report:
Cryogenic Oxygen and Hydrogen are uncraftable

## Expected Behavior/Suggestions:
Should combine together to make rocket fuel, cannot craft rocket fuel because of this

**Comment by Saereth** [comment]
cannot reproduce
![image](https://user-images.githubusercontent.com/9200909/86158464-d0f97b00-bad6-11ea-8b68-00974db264b4.png)

**Comment by Saereth** [comment]
![image](https://user-images.githubusercontent.com/9200909/86158666-1e75e800-bad7-11ea-8649-bf84000c1791.png)
