### ISSUE TITLE
Magician Blood Orb

### ISSUE THREAD

**Issue by ResminZ** [FTBTeam/FTB-Interactions#910]
## Modpack Version: 
2.0.0 dev4

## Bug Report:
Blood Magic's Apprentice Blood Orb (tier 2) recipe needs 5k of life essence, but Magician Blood Orb (tier 3) requires only 2.5k, although it feels like it should be way more.

## Suggestions:
Increase Magician Blood Orb life essence requirement.

**Comment by Saereth** [comment]
yep, was literally missing a zero on the cost lol
