### ISSUE TITLE
OC recipes broken

### ISSUE THREAD

**Issue by ResminZ** [FTBTeam/FTB-Interactions#915]
## Modpack Version: 
2.0.0 dev4

## Bug Report:
Practically all of the OpenComputers recipes, that are needed for LazyAE, are broken, i.e transistors, microchips, CPUs, ALUs and many more. Recipes are uncraftable both in crafting table and assembler.

**Comment by Saereth** [comment]
I forgot to upload the config changes to the server, should work in sp, configs are updated on the server for next restart
