### ISSUE TITLE
New Bluesteel ingots/wire bugs

### ISSUE THREAD

**Issue by Flame500** [FTBTeam/FTB-Interactions#916]
## Modpack Version: 
Dev4

## Bug Report:
A couple things,
1. Blue steel is named "material.bluesteel" (this also effects things such as cables)
2. Blue steel cables cannot be combined like normal wires to make 2x wires/cables out of 2 1x wires/cables. This effects all levels of the cables (2x can't go to 4x, etc.)

## Expected Behavior/Suggestions:
Blue steel should be named "Blue Steel" instead of "material.bluesteel"
Cables should be able to be crafted into denser versions.

## Is It Repeatable? Steps to Reproduce: 
look up the JEI recipe for 2x Blue Steel cable and you will see that its named "material.bluesteel cable" and it doesn't have a recipe to convert from 2 1x cables or convert into 4x cables

## Link to Log or Crash File Paste**: 
No crash

**Comment by Saereth** [comment]
this is just the clients not having the localizations yet, not a prob
