### ISSUE TITLE
LuV Diesel Generator

### ISSUE THREAD

**Issue by ResminZ** [FTBTeam/FTB-Interactions#918]
## Modpack Version: 
2.0.0 dev4

## Bug Report:
Looking at LuV Diesel Generator multiblock gives you an "CCL caught an exception rendering a block" error. It could be due to the unknown blocks in the multiblock.
![2020-06-27_00 19 00](https://user-images.githubusercontent.com/42918091/85897739-fb63e380-b80b-11ea-9f50-033cab91fc6d.png)

## Link to Log or Crash File Paste**: 
https://pastebin.com/ZX7kzrSz

**Comment by Saereth** [comment]
fixed in new update, the pipes are replaced with frames and the diselgen replaced with a dimensional transciever which can also be functional and allow the machine to still run... :p
