### ISSUE TITLE
FPS and world change lag

### ISSUE THREAD

**Issue by GodlyIdea** [FTBTeam/FTB-Interactions#919]
##  Modpack Version: 
- 1.9.1
- Multiplayer

## Bug Report:
- FPS lag when moving.
- Switching worlds causes lag.

## Expected Behavior/Suggestions:
- No lag.

## Is It Repeatable? Steps to Reproduce: 
- Play in multiplayer server.
- The more stuff is built or area explored the laggier it gets.

## Link to Log or Crash File Paste**: 
- None
## Mod/s Affected:
- The mod that is causing the lag:
 p455w0rdslib-1.12.2-2.3.151.jar

## Known Fix: 
- Update the mod to latest version:
 p455w0rdslib-1.12.2-2.3.161.jar
- And due dependencies following needs to be updated aswell:
 appliedenergistics2-rv6-stable-7.jar
 AE2WTLib-1.12.2-1.0.34.jar
 WirelessCraftingTerminal-1.12.2-3.12.97.jar

**Comment by GodlyIdea** [comment]
I looked through all the issues which contained "lag" and didn't find any that refers to that issue so I'm interested in what the issue number is that the current one duplicates?

**Comment by Saereth** [comment]
You did nothing wrong here, the issue was originally reported and diagnosed via discord and I'd already implemented the fix, the duplicate note was a reminder to myself. Thanks for the issue report!
