### ISSUE TITLE
Some ores still can be veinmined

### ISSUE THREAD

**Issue by ResminZ** [FTBTeam/FTB-Interactions#920]
## Modpack Version: 
2.0.0 dev4

## Bug Report:
Some ores still can be veinmined (Uranium 235, 238, Uranite, Molybdenite, Wulfenite, Scheelite, Powellite, Palladium) 

## Mod/s Affected: 
FTB Ultimine.

## Known Fix: 
Blacklist those ores.

**Comment by Saereth** [comment]
added all those to the blacklist
