### ISSUE TITLE
quest bugs

### ISSUE THREAD

**Issue by Flame500** [FTBTeam/FTB-Interactions#922]
This is a list of all the quests that I've found with errors.

1. The "Glad you ironed that out" quest require the magical brewing cauldron instead of just the regular cauldron.

2. The "Bronze Hull" quest has a typo "ot" rather than "to"

3. The "Good Electronic Circuit" in the "Fake Electrical Engineering" tab says it can be crafted in the steam age, when it is actually gated behind the LV age with the diode.

4. "What is this Sorcery?" tab has a bunch of quests to the bottom right of the main area that seem to be missing required items and just display a diamond.

Will update if I find more.

**Comment by Saereth** [comment]
fixed the quest artifacts on #4 already, will address the other things soon

**Comment by Saereth** [comment]
ok all of these are fixed now
