### ISSUE TITLE
Roost crafting via JEI does not see a chicken

### ISSUE THREAD

**Issue by proslackergamer** [FTBTeam/FTB-Interactions#925]
## Modpack Version: 
2.0

## Bug Report:  
When hitting the "plus" symbol to craft a roost, JEI does not detect a chicken of any sort in the inventory.

## Is It Repeatable? Steps to Reproduce: 

1. Have required items to craft roost in inventory.
2. Attempt to put items to craft roost in crafting grid via JEI autofill.

## Known Fix: 
Insert items manually.

**Comment by Saereth** [comment]
this is actually intended behavior from the mod so people dont accidentally craft with some high tier chicken. it's a bit of a nuisance though so maybe I'll just change the recipe to use an egg instead
