### ISSUE TITLE
gtce version outdated, covers crash the server

### ISSUE THREAD

**Issue by docteurmystere** [FTBTeam/FTB-Interactions#927]
## Modpack Version: 
1.9.1 (but the same gtce version is in 1.9.2)

## Bug Report:
attaching covers to cables and pipes crashes the server corrupting the world; this bug was fixed in later versions of gtce

## Expected Behavior/Suggestions:
server not crashing?

## Is It Repeatable? Steps to Reproduce: 
1) attach cover (shutter module is fine) to gtce cable or pipe
2) crash server

## Link to Log or Crash File Paste**: 
https://pastebin.com/Tx4v6AZq

## Mod/s Affected: 
gtce

## Known Fix: 
not doing the above step, which is dependent on players not doing them because it is not preventable by config, except by disabling all covers altogether which breaks the game more or less (gtce pumps are both a cover and a crafting ingredient).
note that the bug was known and fixed in gtce, as from this post: https://github.com/GregTechCE/GregTech/issues/966

**Comment by Saereth** [comment]
update to 2.0
