### ISSUE TITLE
AdvR. Precision Assembler does not craft items with GT materials.

### ISSUE THREAD

**Issue by Hachuurui** [FTBTeam/FTB-Interactions#931]
## Modpack Version: 
2.0

## Bug Report:
The link is to an unlisted video of this issue. It appears to affect more than the circuit recipe in the video though. All circuits and the wafer so far have shown to have this issue. This prevents new players from going to space since you cannot make the parts for the fueling station or tracking chips for guidance computer.

## Expected Behavior/Suggestions:
It crafts the item.

## Is It Repeatable? Steps to Reproduce: 
Add materials for craft in input, it shows it crafting and materials vanish, output is empty. input has materials again.
Video of the issue:

https://www.youtube.com/watch?v=Af2fYh4cvT4

## Mod/s Affected: 
Advanced Rocketry, Vulpes, most likely GTCE

## Known Fix: 
Tried resetting server, moving the multiblock, neither worked.

**Comment by Saereth** [comment]
is this on a server or single player? Does it occur in singleplayer as well if it's a server? T did you download from the ftbapp or somewhere else? This seems like a script desync between client and server since you see it clientside and expected result but the server is kicking it back.

**Comment by Hachuurui** [comment]
It's on a server. I have not attempted in SP. Both server files and client are from FTBApp.

server file is...5_82.exe

**Comment by Saereth** [comment]
I definitely cannot recreate this in singleplayer, I'm updating the dev server now to see if I can reproduce it there

**Comment by Saereth** [comment]
I cannot reproduce this on the server either. I suspect your scripts are messed up on your server, I would recopy them
![2020-07-05_10 18 10](https://user-images.githubusercontent.com/9200909/86535520-ec85cc80-beae-11ea-8d62-e1ee5d6d4974.png)
![2020-07-05_11 00 52](https://user-images.githubusercontent.com/9200909/86535521-ec85cc80-beae-11ea-892c-d13504679e47.png)
![2020-07-05_11 00 59](https://user-images.githubusercontent.com/9200909/86535522-ed1e6300-beae-11ea-828c-98025b3bd1a2.png)

**Comment by Hachuurui** [comment]
I never tried the item io circuit only the green one and the blue fluid one and the basic wafer. I'll test the item io to see if that works. but I'll also see about redoing the scripts. 
maybe I'll pull them from the client

**Comment by Hachuurui** [comment]
Repulling the client, then replacing the server xml files with the client xml fixed the issue

Reviewing the two, there are definite differences in comparisons between the server installed files and the newly pulled client files. 

I'd recommend looking at the installer FTBApp uses for the server to see if maybe it has old files still.

**Comment by Hachuurui** [comment]
![2020-07-05 15_30_42-](https://user-images.githubusercontent.com/2464584/86540605-afcccc00-bed4-11ea-947f-fed3cf30958d.png)

**Comment by Saereth** [comment]
yeah I'll report this to the ftbapp dev team, quite annoying for sure
