### ISSUE TITLE
Large titanium and tungensteel boilers not shown in JEI

### ISSUE THREAD

**Issue by proslackergamer** [FTBTeam/FTB-Interactions#933]
Modpack Version: 
2.0.0

## Bug Report:
When searching for "boiler" in JEI, the titanium and tungensteel boiler controller crafting recipies are not shown in JEI, although they can be seen when hitting the "uses" key on the steel and titanium boiler controllers.

**Comment by Saereth** [comment]
This is not a bug, they were removed
