### ISSUE TITLE
World generation issues in 2.0

### ISSUE THREAD

**Issue by JackMeds** [FTBTeam/FTB-Interactions#935]
# Modpack Version: 
2.0
## Bug Report:
![image](https://user-images.githubusercontent.com/38741783/86528884-e576b280-bede-11ea-90e3-4a6e545e3119.png)

FluidName: "oil_light"

**Comment by Saereth** [comment]
There was a bug with the initial release on ftbapp, the FTBApp wasnt sending zero length files so the worldgen_generated file that gregtech creates to indicate it's already extracted its default oregen wasnt being sent to clients. This resulted in GT unpacking its stock oregen along side of interactions' highly custom oregen. I identified the issue and got a fix out which rushmead pushed to the 2.0 branch but anyone that installed before the patch should reinstall to fix it OR you can delete your /config/gregtech folder and replace with this folder:
https://cdn.discordapp.com/attachments/560185294842888222/728823290193248276/gregtech.zip

I'll leave this issue open and pinned until 2.0.1 drops later today in case anyone else runs into this issue
