### ISSUE TITLE
[Enhancement] Can you improve the tps of the server through some optimizations?

### ISSUE THREAD

**Issue by JackMeds** [FTBTeam/FTB-Interactions#936]
Modpack Version:
2.0
Suggestion:
Can you improve the tps of the server through some optimizations?
For example, some mod, or some server core is recommended.
Forge server sometimes experience lag

**Comment by Saereth** [comment]
The pack is highly optimized and I continue to go for every possible method of improving performance. That being said if you have some profiler logs indicating problematic blocks or processes for me to review please post them. There are far too many things that can contribute to poor performance in mine craft. What this report is essentially saying is "make the pack run faster". That's always the goal already.

If your server specifically is lagging I suggest you run a profiler like warmroast, spark tickprofiler etc something like that and help trackdown what's causing the lag on your server and then feel free to share the results with us here.

**Comment by JackMeds** [comment]
I see the improvement you have made in improving performance. After watching spark, I found that I should replace the higher performance VPS. It seems that the problem has been solved, xD.
