### ISSUE TITLE
Slightly Bugged Ore Generation

### ISSUE THREAD

**Issue by AvilionAMillion** [FTBTeam/FTB-Interactions#937]
Version: 2.0

The Ore Generation in and of itself works fine, as in, the plants do generate over the ore veins. The problem is that occasionally small piles generate in the overworld with no ore vein underneath, in the provided picture it is palladium.
![2020-07-05_00 19 56](https://user-images.githubusercontent.com/47298428/86535155-d1618f80-bea3-11ea-80fc-a734b1802fe9.png)

**Comment by Saereth** [comment]
Duplicate issue, see
https://github.com/FTBTeam/FTB-Interactions/issues/935
