### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by AbdusselamBezirganHazretleri** [FTBTeam/FTB-Interactions#939]
## Is It Repeatable? Steps to Reproduce: 

1.
2.

**Comment by AbdusselamBezirganHazretleri** [comment]
https://paste.feed-the-beast.com/view/1f61efd4 I really have issues with these issues

**Comment by Saereth** [comment]
this is just a random cme with vanilla audio code, happens sometimes in many packs, not much I can do about it
