### ISSUE TITLE
Freeze while trying to connect to Multiplayer Server

### ISSUE THREAD

**Issue by Ian-Hernandez** [FTBTeam/FTB-Interactions#941]
## Modpack Version: 
2.0.1
Additional Mods added: Animania, Carry On, CraftStudioAPI

## Bug Report:
When trying to join a multiplayer server, the screen freezes at the loading screen, and cannot cancel connecting. Singleplayer worlds start without issue.

## Expected Behavior/Suggestions:
Successful connection to multiplayer server.

## Is It Repeatable? Steps to Reproduce: 
1. Start up FTB Interactions
2. Try to join a Multiplayer Server

## Link to Log or Crash File Paste**: 
[latest.log](https://github.com/FTBTeam/FTB-Interactions/files/4882023/latest.log)

## Mod/s Affected: 
Crash may to be related to Gemstone Rods (or what would be immediately after it in the logs).

## Known Fix: 
None

**Comment by Saereth** [comment]
[21:40:22] [Client thread/INFO] [FML]: Registry IRecipe: Found a missing id from the world thermalexpansion:tank

This is a strong indication that your client and/or server files are messed up

`[21:27:02] [Client thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, advancedrocketrycore, creativecoredummy, littletilescore, xaerominimap_core, xaeroworldmap_core, openmodscore, bnbgamingcore, foamfixcore, opencomputers|core, botania_tweaks_core, randompatches, appliedenergistics2, enderio, enderiobase, enderioconduits, enderiopowertools, enderioconduitsappliedenergistics, enderstorage, netherbackport, actuallyadditions, actuallybaubles, advancedrocketry, ae2wtlib, animania, animus, apotheosis, applecore, appleskin, architecturecraft, armoreablemobs, artemislib, artisanworktables, astralsorcery, athenaeum, autoreglib, avaritia, backportedflora, base, batterybufferdriver, baubles, bhc, betteradvancements, biggerpacketsplz, bloodmagic, bnbgaminglib, bookshelf, botania, botania_tweaks, brandonscore, buildinggadgets, carryon, ceramics, ceu, chickens, chisel, cleanview, clumps, codechickenlib, cofhcore, cofhworld, commoncapabilities, compactmachines3, contenttweaker, controlling, cookingforblockheads, roost, cosmeticarmorreworked, craftstudioapi, ctgui, crafttweaker, crafttweakerjei, creativecore, cryingobsidian, ctm, cucumber, custommainmenu, cyberware, cyclicmagic, cyclopscore, dmonsters, deepmoblearning, deepmoblearningbm, diethopper, dimensionalcontrol, dimstages, discord, dldungeonsjbg, draconicevolution, dropt, dupefixproject, dynamiclights, dynamiclights_onfire, dynamiclights_creepers, dynamiclights_dropitems, dynamiclights_entityclasses, dynamiclights_mobequipment, dynamiclights_flamearrows, dynamiclights_floodlights, dynamiclights_otherplayers, dynamiclights_theplayer, emberroot, endercore, enderioendergy, enderiointegrationtic, enderiointegrationticlate, enderiomachines, enderutilities, extrautils2, fastbench, floralchemy, fluxnetworks, foamfix, forgelin, microblockcbe, forgemultipartcbe, minecraftmultipartcbe, ftbbackups, ftblib, ftbquests, ftbultimine, ftbutilities, funkylocomotion, fvw, gamestages, gregtech, gtce2oc, guideapi, gunpowderlib, hardcoredarkness, hitwithaxe, hotornot, hungeroverhaul, iceandfire, ichunutil, incontrol, industrialforegoing, initialinventory, insomniac, integrateddynamics, integrateddynamicscompat, integratedtunnels, integratedtunnelscompat, integrationforegoing, inventorytweaks, ironchest, itemfilters, itlt, jei, jeiintegration, jehc, justenoughdimensions, jee, knowledgeshare, lcrdrfs, threng, letsencryptcraft, libnine, librarianliblate, librarianlib, libvulpes, littletiles, logisticsbridge, logisticspipes, loottweaker, mainmenuscale, mantle, mcjtylib_ng, mcmultipart, mekanism, mightyenderchicken, minetogether, minetogetherserver, mobstages, modnametooltip, modtweaker, modulardiversity, modularmachinery, morechickens, moreoverlays, mousetweaks, mtlib, multiblocktweaker, naturescompass, nutrition, openblocks, opencomputers, openmods, p455w0rdslib, harvestcraft, patchouli, pickletweaks, placebo, plants2, plustic, portalgun, primal_tech, projecte, quark, randomthings, randomtweaks, reborncore, redstonearsenal, redstoneflux, xreliquary, resize, resourceloader, rftools, roughmobsrevamped, roughtweaks, rusticthaumaturgy, rustic, scannable, scavenge, gtadditions, lteleporters, simple_trophies, simplylight, sledgehammer, sonarcore, spiceoflife, sqpatch, stats_keeper, stg, sasit, superfactorymanager, tconstruct, terracore, teslacorelib, teslacorelib_registries, thaumcraft, thaumicenergistics, tcinventoryscan, thaumicjei, thaumicperiphery, theoneprobe, thermaldynamics, thermalexpansion, thermalfoundation, thermalinnovation, tcomplement, tinkersextras, tinkerstages, tips, toastcontrol, togetherforever, tombmanygraves, tombmanygraves2api, tombmanypluginscosmeticarmorreworked, topaddons, translocators, traverse, vtb, voidislandcontrol, volumetricflask, watercontrolextreme, 113_water_mechanics, waterstrainer, weirdinggadget, whoops, wct, wizardry, xaerominimap, xaeroworldmap, xtones, zensummoning, zentriggers, zenstages, rf-capability-adapter, gbook, llibrary, phosphor-lighting, reauth] at CLIENT`

You should reinstall your client
