### ISSUE TITLE
Porcelain chicken quest uncompletable

### ISSUE THREAD

**Issue by DrunkenSquirrel** [FTBTeam/FTB-Interactions#943]
## Modpack Version: 
2.0

## Bug Report:
The Porcelain chicken quest calls for a porcelain enriched egg, which can't be obtained since the porcelain chickens lay only unfired porcelain

## Expected Behavior/Suggestions:
Remove the egg as requirement for completing the quest

## Is It Repeatable? Steps to Reproduce: 
1. Open Porcelain chicken quest
2. Check recipes for porcelain enriched egg (There are none)

## Link to Log or Crash File Paste**: 
n/a

## Mod/s Affected: 
n/a

## Known Fix: 
Remove the egg as requirement for completing the quest
Workaround: Spawn an egg in creative

**Comment by Saereth** [comment]
this is fixed in 2.0.1 which is already out
