### ISSUE TITLE
Missing cable recipes

### ISSUE THREAD

**Issue by RawelSan** [FTBTeam/FTB-Interactions#944]
## Modpack Version: 
2.0.1

## Bug Report:
The new lossless cables seem to be missing cable upgrading recipes. Such as 2 1x cables to 1 2x cable.

## Expected Behavior/Suggestions:
It should be possible to use the assembler and crafting table to upscale cables 1x->2x->4x->8x->16x

## Is It Repeatable? Steps to Reproduce: 
Just look in Jei

## Known Fix: 
Assuming new recipes just need to be added.

**Comment by Saereth** [comment]
this will be for 2.0.3
