### ISSUE TITLE
Quests require specific machine tiers

### ISSUE THREAD

**Issue by hacatu** [FTBTeam/FTB-Interactions#947]
Some quests require specific machine tiers but shouldn't:

- Blood magic
    - Digital mob agonizer (lv ceu) (also maybe add a quest to make all blood via apples from dungeons as a joke)
- Lv chemistry
    - Buckets? Those are rookie numbers (pump) (this could be pyrolese oven and distillery or centrifuge instead)
    - Cocktail machine (lv mixer)
    - A pool of who-knows-what (lv bath)
    - Basic air collector (lv collector) (no air collector is required due to chickens I think)
- Mv chemistry
    - Awesome mix tape (mv mixer)
    - Advanced chemical bath (mv bath)
- HV+ chemistry
    - Spinny go fast (HV centrifuge)
- Metallurgy HV
    - Moon rocks (ender air from centrifuging extraterrestrial matter can be substituted, although I think this is good as an Easter egg/late space challenge)
- Ayo technology
    - They see me storin (lv battery buffer) (why)
    - Lv battery charger (lv battery charger)
    - Basic compressor (lv compressor) (these don't have much of an advantage over the steam versions although I understand why the quests exist)
    - Basic alloy smelter (lv alloy smelter)
    - Basic forge hammer (lv forge hammer)
    - Basic macerator (lv macerator)
- How do we power this party
    - Collecting the drops (add advanced item collector and maybe other options like collect seal to the list)
    - Remote power (lv ceu)
    - Basic diesel generator (lv diesel generator)
- Steam power
    - Steam compressor
    - Steam extractor

The metallurgy tab already has some quests that do this (like the arc furnace quest).  I didn't include quests for machines it would be totally unreasonable to skip like the steam forge hammer.  I think in general these quests should accept machines two tiers up from what they do or just any such machine.

**Comment by Saereth** [comment]
I'm changing most of these but some of them, for example the pump. That is the intended default route for the pack the other methods are far less energy efficient (oil from pyrolyse has been removed, and the centrifuging soul sand recipe is very bad efficiency as well). So for those types of quests we'll probably keep them as is. lots of good fixes in this list here though, expect to see most of them in 2.0.2
