### ISSUE TITLE
JEI cleanup of unobtainable Ender Utilities items 

### ISSUE THREAD

**Issue by DrTasslehoff** [FTBTeam/FTB-Interactions#949]
## Modpack Version: 
2.0.1

## Expected Behavior/Suggestions:
Lots of items requiring an ender core or low-tier ender alloys which have been disabled since forever. Could use to clean up and hide the majority of the mod items if they are not craftable or lootable.

**Comment by Saereth** [comment]
oh damn I thought I already did this, alright will do

**Comment by Saereth** [comment]
oh right I removed some but the rest I want to keep via recipe changes or dungeon loot, this will be a job for 2.0.3
