### ISSUE TITLE
Smelting wooden planks in the kiln

### ISSUE THREAD

**Issue by pikachu143234** [FTBTeam/FTB-Interactions#950]
2.0.1

If you right click a wooden plank into a kiln, wait a minute, and take it out, it gives you xp orbs and the wooden block.

I would suggest not leetting someone put wooden planks in the kiln.

1.right click wooden planks into a kiln
2.wait 30 seconds
3.take out the planks

**Comment by Saereth** [comment]
This is a bug with primal tech but its actually one we decided to embrace so it's fine and wont break the pack 👍
