### ISSUE TITLE
Native Cluster inconsistencies

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [FTBTeam/FTB-Interactions#952]
## Modpack Version: 
2.0.1

## Bug Report:
Native Tin / Cassiterite Clusters seem to produce only half the amount of crushed cassiterite ore as crushing actual cassiterite does (see images, oreCassiterite produces `12` crushed cassiterite, the cluster produces `6`)

![fig1](https://user-images.githubusercontent.com/12750501/87212562-7c000500-c31f-11ea-9d10-c03dc0c89513.png)

![fig2](https://user-images.githubusercontent.com/12750501/87212574-8fab6b80-c31f-11ea-98f1-1b3ec3cf1ca3.png)

## Expected Behavior/Suggestions:
Crushed Cassiterite Ore production should be consistent across all types of tin "ores" (as currently, the quadrupling using starlight infusion effectively only comes out to doubling the ore due to this behaviour)

## Is It Repeatable? Steps to Reproduce: 
1. Use Starlight Infusion to convert any Tin Ore to Dense Tin Ore
2. Smelt the Dense Tin Ore into Native Clusters (ignoring #942 as I have manually fixed this already for my current instance)
3. Pulverising the Native Clusters will yield 6 Crushed Cassiterite in total.

## Known (Suggested) Fix: 
The issue seems to be present for more than just Dense Tin (for instance, Cobalt has the opposite problem where it creates `3` Crushed Cobalt instead of `2`, so perhaps, a fitting fix would just be adding the respective clusters to the respective `ore*` tag, as then they would just be able to make use of the "default" GTCE pulverisation recipe. This may add additional secondary outputs, of course, but honestly, this seems like a negligible bonus as people aren't able to leverage it in the early stages (due to having only one Output slot) and I double it would make a large difference in the late game (other than copious amounts of extraneous stone dusts being produced for most ores, and maybe some extra metal dusts that don't amount to much in the late game for clusters like Cassiterite)

**Comment by MaxNeedsSnacks** [comment]
Another inconsistency I've found -- Dense Tin Ore **smelts** into Native Cassiterite Clusters, HOWEVER, *any* other method of further processing the dense tin ore yields Tin Native Clusters instead

![image](https://user-images.githubusercontent.com/12750501/87223565-5ce49000-c37e-11ea-82ac-d5bae9fc3a62.png)

![image](https://user-images.githubusercontent.com/12750501/87223577-6a9a1580-c37e-11ea-967d-431f8bc3e03f.png)

**Comment by Saereth** [comment]
These are fixed, dense tin should smelt to tin clusters, which at face value is obviously less than just macerating the cassiterite, this is done for uniformity and higher tier processing however so its actually intended. Earlier game you can go ahead and just macerate for more, once you get the ability to further process the shards you can still end up getting the 64x out of them. At anyrate, fixed the items you reported here for 2.0.2, if you find more feel free to throw a list my way with any more inconsistencies and I'll fix them up. The new multiplication method is still very new and was only tested by a handful of people so far so these things are bound to crop up. Thanks!

**Comment by MaxNeedsSnacks** [comment]
I've actually gone ahead and went through the material maps myself, adjusting all the clusters (even the unused ones) to their correct values. Most of these were from compounds, where the total output was the number of atoms in one molecule (so with Cassiterite, `SnO₂` = `3` atoms, so 3 dusts), where it was supposed to be twice of that.

Here's a link to the [Ghostbin](https://ghostbin.co/paste/r7ytv) for that if you're interested ^^

**Comment by MaxNeedsSnacks** [comment]
Native Redstone Clusters and I'm assuming a couple others still seem to give incorrect cluster-to-dust ratios (for Redstone, it's 5 instead of 12), so this issue *may* need to be reopened for other inconsistencies that might still be a thing in 2.0.2. I'll be updating this comment with any further things I can find
