### ISSUE TITLE
Hellfire Kiln does not contain Dense Ore -> Cluster recipes

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [FTBTeam/FTB-Interactions#955]
(This ***may*** be intentional. If it is, feel free to close without additional comment!)

## Modpack Version: 
2.0.1

## Bug Report:
The Hellfire Kiln multiblock does not have support for Dense Ore -> Cluster recipes introduced in `Metallurgy.zs`. I figured this might be an oversight because it *is* supported by vanilla furnaces (including adapters of such like Infernal Furnaces, the Seared Furnace, etc.), though this ***might*** also be intentional on your end in order to incentivise using the GT furnaces (as well as the Multi Smelter) for these recipes, as **those** support them, I'm not 100% sure, though

## Expected Behavior/Suggestions:
For each Dense Ore that smelts into clusters, a corresponding Hellfire Kiln recipe should exist.

## Known Fix:
(Disregard my previous comments, I messed up something in the script)
Adding a line to `Metallurgy.zs` to add the recipes to the hellfire should do the trick as far as I am aware

**Comment by MaxNeedsSnacks** [comment]
I think I should add it to *this* thread because it sort of applies as well, Bread can also not be made in an Hellfire Kiln, and in fact, it turns out any custom / added furnace recipes aren't properly being added to the Hellfire Kiln.

I know MM has a "furnace adapter", so could that be a viable option?

**Comment by Saereth** [comment]
hellfire kiln has a bunch of jacked recipes, this is all resolved in 2.0.2 which will be out soon though, all good

**Comment by orville94Bailey** [comment]
I am on pack version 2.0.3 and am not seeing that the Dense Ore -> Cluster recipe has been updated.
