### ISSUE TITLE
Trolls spawn with no AI sometimes

### ISSUE THREAD

**Issue by truenachtara** [FTBTeam/FTB-Interactions#957]
Version two oh one
Trolls will spawn without AI
{NoAI:1b}

Natural troll spawn
I have a world download here
Linked at the bottom

Entitydata
Command shows some problems
Here is the output

![image](https://user-images.githubusercontent.com/16340367/87235556-b959a680-c3a2-11ea-8cfb-fbe53ea69c7f.png)
https://drive.google.com/file/d/1VTfB0OfCMxZfYiaPHZkfxT-1sFYGzfVQ/view?usp=sharing

**Comment by Saereth** [comment]
Ah I see this can sometimes happen when they spawn from DLD as a boss I suspect this is the case, gonna go ahead and just swap them for another mob
