### ISSUE TITLE
GregTech Timber

### ISSUE THREAD

**Issue by Dromsi** [FTBTeam/FTB-Interactions#959]
## Modpack Version: 
FTBInteractions-1.9.1-1.12.2

## Bug Report:
Can't chop trees down with flint axe (even tested other axes, and all from GregTech don't seem to work

## Is It Repeatable? Steps to Reproduce: 

1.
2.

**Comment by Hoody91** [comment]
Same issue here, as the block is about to be broken it reverts back to a full block, no durability is used and Ore Excavation has no effect on the outcome.

**Comment by landrus** [comment]
I am affected, as well. Version 1.9.1-1.12.2

**Comment by Saereth** [comment]
you need to be on version 2.0.1 or better, you guys are reporting outdated issues that have been fixed. You can get the latest on the ftbapp

**Comment by Dromsi** [comment]
sorry that i left out that this was from the Twitch launcher, I never knew the FTB App was a thing.
