### ISSUE TITLE
Zombie spawning ignoring light level

### ISSUE THREAD

**Issue by account417** [FTBTeam/FTB-Interactions#963]
## Modpack Version: 
2.0.1

## Bug Report:
Zombies have been spawning regardless of light level pre-bronze

## Expected Behavior/Suggestions:
This should only happen post-space

## Is It Repeatable? Steps to Reproduce: 
Yes, but occurrences are slightly uncommon.
Light up an area and wait for zombies to spawn.
Could require difficulty being set to hard, 9 light level and/or it to be night.

**Comment by Saereth** [comment]
this should actually never happen pre space or post, specific mobs ignore light level post space, namely the laser creepers and such. I tried to reproduce this but cannot. can you maybe get a video or some more info on how I can reliably reproduce this

**Comment by account417** [comment]
I've never gotten to space yet, I only briefly read the description that tells you about light level ignoring spawns sorry.
Ill try and get a video. It definitely was happening and I am now certain that it only occurs on light level 9 at night.

**Comment by account417** [comment]
I got it on video, how do i post it?

**Comment by Saereth** [comment]
link it on youtube

**Comment by account417** [comment]
https://youtu.be/2Ns1Z94k2k4
At the start of the video the eggs get auto claimed by the hippogryph quest for some reason.
At 1:15 watch the mini map as it clearly shows a second zombie popping into existence in the bottom right corner
after the first one walks onto the minimap.
also note that second zombie is not aggro-ed straight away meaning it spawned in that position.

after entering the bronze age this has stopped happening entirely.

**Comment by Saereth** [comment]
I still cant personally reproduce this but I did add some stricter rules to incontrol which should hopefully just entirely stop it from being an issue
