### ISSUE TITLE
New wires from 2.0.0 still missing crafting recipes

### ISSUE THREAD

**Issue by Hekera** [FTBTeam/FTB-Interactions#964]
## Modpack Version:
2.0.2

## Bug Report:
2.0.2 allowed the new lossless cables to be crafted together to form thicker wires, but does not allow them to be uncrafted into thinner ones.

## Expected Behavior/Suggestions:
For example, 2 1x signalum wires can be crafted to make 1 2x wire, but 1 2x wire cannot be crafted to make 2 1x wires.

## Is It Repeatable? Steps to Reproduce: 
Uses for 2x cable in JEI only show crafting 4x cable.
![image](https://user-images.githubusercontent.com/40907168/87265968-0c5e5700-c492-11ea-9c71-45a12a0cad3d.png)

## Known Fix: 
CraftTweaker 2

**Comment by llearch** [comment]
I think this will fix this, but I haven't tested:

`--- gregtech.zs.orig    2020-08-06 19:33:44.799053329 -0700
+++ gregtech.zs 2020-08-06 19:39:01.642333800 -0700
@@ -2163,36 +2163,60 @@
        recipes.addShapeless(<ore:cableGtOctalSuperconductor>.firstItem, [<ore:cableGtQuadrupleSuperconductor>,<ore:cableGtQuadrupleSuperconductor>]);
        recipes.addShapeless(<ore:cableGtQuadrupleSuperconductor>.firstItem, [<ore:cableGtDoubleSuperconductor>,<ore:cableGtDoubleSuperconductor>]);
        recipes.addShapeless(<ore:cableGtDoubleSuperconductor>.firstItem, [<ore:cableGtSingleSuperconductor>,<ore:cableGtSingleSuperconductor>]);
+       recipes.addShapeless(<ore:cableGtOctalSuperconductor>.firstItem *2, [<ore:cableGtHexSuperconductor>]);
+       recipes.addShapeless(<ore:cableGtQuadrupleSuperconductor>.firstItem *2, [<ore:cableGtOctalSuperconductor>]);
+       recipes.addShapeless(<ore:cableGtDoubleSuperconductor>.firstItem *2, [<ore:cableGtQuadrupleSuperconductor>]);
+       recipes.addShapeless(<ore:cableGtSingleSuperconductor>.firstItem *2, [<ore:cableGtDoubleSuperconductor>]);

        #bluesteel
        recipes.addShapeless(<ore:cableGtHexBluesteel>.firstItem, [<ore:cableGtOctalBluesteel>,<ore:cableGtOctalBluesteel>]);
        recipes.addShapeless(<ore:cableGtOctalBluesteel>.firstItem, [<ore:cableGtQuadrupleBluesteel>,<ore:cableGtQuadrupleBluesteel>]);
        recipes.addShapeless(<ore:cableGtQuadrupleBluesteel>.firstItem, [<ore:cableGtDoubleBluesteel>,<ore:cableGtDoubleBluesteel>]);
        recipes.addShapeless(<ore:cableGtDoubleBluesteel>.firstItem, [<ore:cableGtSingleBluesteel>,<ore:cableGtSingleBluesteel>]);
+       recipes.addShapeless(<ore:cableGtOctalBluesteel>.firstItem *2, [<ore:cableGtHexBluesteel>]);
+       recipes.addShapeless(<ore:cableGtQuadrupleBluesteel>.firstItem *2, [<ore:cableGtOctalBluesteel>]);
+       recipes.addShapeless(<ore:cableGtDoubleBluesteel>.firstItem *2, [<ore:cableGtQuadrupleBluesteel>]);
+       recipes.addShapeless(<ore:cableGtSingleBluesteel>.firstItem *2, [<ore:cableGtDoubleBluesteel>]);

        #manasteel
        recipes.addShapeless(<ore:cableGtHexManasteel>.firstItem, [<ore:cableGtOctalManasteel>,<ore:cableGtOctalManasteel>]);
        recipes.addShapeless(<ore:cableGtOctalManasteel>.firstItem, [<ore:cableGtQuadrupleManasteel>,<ore:cableGtQuadrupleManasteel>]);
        recipes.addShapeless(<ore:cableGtQuadrupleManasteel>.firstItem, [<ore:cableGtDoubleManasteel>,<ore:cableGtDoubleManasteel>]);
        recipes.addShapeless(<ore:cableGtDoubleManasteel>.firstItem, [<ore:cableGtSingleManasteel>,<ore:cableGtSingleManasteel>]);
+       recipes.addShapeless(<ore:cableGtOctalManasteel>.firstItem *2, [<ore:cableGtHexManasteel>]);
+       recipes.addShapeless(<ore:cableGtQuadrupleManasteel>.firstItem *2, [<ore:cableGtOctalManasteel>]);
+       recipes.addShapeless(<ore:cableGtDoubleManasteel>.firstItem *2, [<ore:cableGtQuadrupleManasteel>]);
+       recipes.addShapeless(<ore:cableGtSingleManasteel>.firstItem *2, [<ore:cableGtDoubleManasteel>]);

        #signalum
        recipes.addShapeless(<ore:cableGtHexSignalum>.firstItem, [<ore:cableGtOctalSignalum>,<ore:cableGtOctalSignalum>]);
        recipes.addShapeless(<ore:cableGtOctalSignalum>.firstItem, [<ore:cableGtQuadrupleSignalum>,<ore:cableGtQuadrupleSignalum>]);
        recipes.addShapeless(<ore:cableGtQuadrupleSignalum>.firstItem, [<ore:cableGtDoubleSignalum>,<ore:cableGtDoubleSignalum>]);
        recipes.addShapeless(<ore:cableGtDoubleSignalum>.firstItem, [<ore:cableGtSingleSignalum>,<ore:cableGtSingleSignalum>]);
+       recipes.addShapeless(<ore:cableGtOctalSignalum>.firstItem *2, [<ore:cableGtHexSignalum>]);
+       recipes.addShapeless(<ore:cableGtQuadrupleSignalum>.firstItem *2, [<ore:cableGtOctalSignalum>]);
+       recipes.addShapeless(<ore:cableGtDoubleSignalum>.firstItem *2, [<ore:cableGtQuadrupleSignalum>]);
+       recipes.addShapeless(<ore:cableGtSingleSignalum>.firstItem *2, [<ore:cableGtDoubleSignalum>]);

        #enderium
        recipes.addShapeless(<ore:cableGtHexEnderium>.firstItem, [<ore:cableGtOctalEnderium>,<ore:cableGtOctalEnderium>]);
        recipes.addShapeless(<ore:cableGtOctalEnderium>.firstItem, [<ore:cableGtQuadrupleEnderium>,<ore:cableGtQuadrupleEnderium>]);
        recipes.addShapeless(<ore:cableGtQuadrupleEnderium>.firstItem, [<ore:cableGtDoubleEnderium>,<ore:cableGtDoubleEnderium>]);
        recipes.addShapeless(<ore:cableGtDoubleEnderium>.firstItem, [<ore:cableGtSingleEnderium>,<ore:cableGtSingleEnderium>]);
+       recipes.addShapeless(<ore:cableGtOctalEnderium>.firstItem *2, [<ore:cableGtHexEnderium>]);
+       recipes.addShapeless(<ore:cableGtQuadrupleEnderium>.firstItem *2, [<ore:cableGtOctalEnderium>]);
+       recipes.addShapeless(<ore:cableGtDoubleEnderium>.firstItem *2, [<ore:cableGtQuadrupleEnderium>]);
+       recipes.addShapeless(<ore:cableGtSingleEnderium>.firstItem *2, [<ore:cableGtDoubleEnderium>]);

        #Stellar Alloy
        recipes.addShapeless(<ore:cableGtHexStellarAlloy>.firstItem, [<ore:cableGtOctalStellarAlloy>,<ore:cableGtOctalStellarAlloy>]);
        recipes.addShapeless(<ore:cableGtOctalStellarAlloy>.firstItem, [<ore:cableGtQuadrupleStellarAlloy>,<ore:cableGtQuadrupleStellarAlloy>]);
        recipes.addShapeless(<ore:cableGtQuadrupleStellarAlloy>.firstItem, [<ore:cableGtDoubleStellarAlloy>,<ore:cableGtDoubleStellarAlloy>]);
        recipes.addShapeless(<ore:cableGtDoubleStellarAlloy>.firstItem, [<ore:cableGtSingleStellarAlloy>,<ore:cableGtSingleStellarAlloy>]);
+       recipes.addShapeless(<ore:cableGtOctalStellarAlloy>.firstItem *2, [<ore:cableGtHexStellarAlloy>]);
+       recipes.addShapeless(<ore:cableGtQuadrupleStellarAlloy>.firstItem *2, [<ore:cableGtOctalStellarAlloy>]);
+       recipes.addShapeless(<ore:cableGtDoubleStellarAlloy>.firstItem *2, [<ore:cableGtQuadrupleStellarAlloy>]);
+       recipes.addShapeless(<ore:cableGtSingleStellarAlloy>.firstItem *2, [<ore:cableGtDoubleStellarAlloy>]);


        #Terrasteel
@@ -2200,6 +2224,10 @@
        recipes.addShapeless(<ore:cableGtOctalTerrasteel>.firstItem, [<ore:cableGtQuadrupleTerrasteel>,<ore:cableGtQuadrupleTerrasteel>]);
        recipes.addShapeless(<ore:cableGtQuadrupleTerrasteel>.firstItem, [<ore:cableGtDoubleTerrasteel>,<ore:cableGtDoubleTerrasteel>]);
        recipes.addShapeless(<ore:cableGtDoubleTerrasteel>.firstItem, [<ore:cableGtSingleTerrasteel>,<ore:cableGtSingleTerrasteel>]);
+       recipes.addShapeless(<ore:cableGtOctalTerrasteel>.firstItem *2, [<ore:cableGtHexTerrasteel>]);
+       recipes.addShapeless(<ore:cableGtQuadrupleTerrasteel>.firstItem *2, [<ore:cableGtOctalTerrasteel>]);
+       recipes.addShapeless(<ore:cableGtDoubleTerrasteel>.firstItem *2, [<ore:cableGtQuadrupleTerrasteel>]);
+       recipes.addShapeless(<ore:cableGtSingleTerrasteel>.firstItem *2, [<ore:cableGtDoubleTerrasteel>]);

        #gtfo solar panels
        recipes.remove(<metaitem:cover.solar.panel>);
`
