### ISSUE TITLE
Hellfire Kiln Cluster woes

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [FTBTeam/FTB-Interactions#965]
## Modpack Version: 
2.0.2

## Bug Report:
Smelting clusters in a Hellfire Kiln still only produces a single cluster. I'm pretty sure this might be because the manual list of furnace recipes was generated before this specific bug was fixed?
![image](https://user-images.githubusercontent.com/12750501/87299789-f8a40680-c50c-11ea-8829-efc23c68a1f7.png)

**Comment by Saereth** [comment]
yeah you are right, I'll get this fixed for 2.0.3
