### ISSUE TITLE
Replicator crash

### ISSUE THREAD

**Issue by Achros1** [FTBTeam/FTB-Interactions#966]
## Modpack Version: 
2.0.2 (present in previous versions)

## Bug Report:
Putting a bucket with liquids into a replicator makes the server sad and it crashes. Cannot load save after this.
Stumbled upon this in a creative test world since there are no fluid cells in JEI.

## Expected Behavior/Suggestions:
One would expect to either see the liquid replicated or not be able to put the bucket in.
The recipe calls for cells but people are dumb, maybe idiot-proof this by not allowing buckets to go in?

## Is It Repeatable? Steps to Reproduce: 
1. Put down replicator and put in matter.
2. Bucket of liquid.

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/61cc8216

**Comment by Saereth** [comment]
bug with shadow of greg, I reported an issue there, I help maintain that so I'll try to have a look at it. Yeah use cells as a work around and we'll have to prevent insertion of buckets instead of cells.

**Comment by Saereth** [comment]
I added a tooltip to replicators for now, rest is mod issue so closing out packwise
