### ISSUE TITLE
AdvancedRocketry can not use spacestation chip in server

### ISSUE THREAD

**Issue by JackMeds** [FTBTeam/FTB-Interactions#971]
## Modpack Version: 
2.0.2
## Bug Report:
AdvancedRocketry can not use spacestation chip in server
![image](https://user-images.githubusercontent.com/38741783/87389966-69fdbb00-c5da-11ea-8321-48516ac0e325.png)

## Link to Log or Crash File Paste**: 
When I press shift and right-click with spacestation chip , it will report an error in server  console
https://paste.ubuntu.com/p/B8zNBYMBqv/

**Comment by Saereth** [comment]
https://github.com/zmaster587/AdvancedRocketry/issues/1876
we'll see what he says
