### ISSUE TITLE
Hellfire Kiln only adds one recipe per output item

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [FTBTeam/FTB-Interactions#974]
## Modpack Version: 
2.0.2

## Bug Report:

Certain vanilla furnace recipes don't seem to want to carry over to the Hellfire Kiln which is... odd to say the least. For instance, I can't smelt Impure Piles of Copper Dust (or regular copper dust for that matter) using a Hellfire Kiln despite the recipe being present in the script (I went ahead and checked), which is kinda odd.

## Examples / Images

Vanilla Smelting working fine:
![image](https://user-images.githubusercontent.com/12750501/87442739-f0bf9180-c5f4-11ea-8dd7-e75ba8f5831b.png)

Hellfire Kiln not working for some reason:
![image](https://user-images.githubusercontent.com/12750501/87442767-f87f3600-c5f4-11ea-9520-7964312f72ee.png)

The recipe inside the script file:
![image](https://user-images.githubusercontent.com/12750501/87442948-2bc1c500-c5f5-11ea-9fd1-a5d026289981.png)

**Comment by MaxNeedsSnacks** [comment]
Oh hold on, actually, I know what the problem is!!

You're using an ItemStack -> ItemStack ***map***, which per definition only stores one __unique__ value per key, so you'd have to flip the list (which I'm assuming you got from `/ct furnace` such that the *inputs* are the keys, as furnace *inputs* are unique.

**Comment by MaxNeedsSnacks** [comment]
Yup, confirmed working on my instance, here's the regex I used to flip everything (except for the last line and for loop, which I both flipped manually) into place so that it works correctly

![image](https://user-images.githubusercontent.com/12750501/87443736-2d3fbd00-c5f6-11ea-9371-99984d656787.png)

**Comment by Saereth** [comment]
https://github.com/FTBTeam/FTB-Interactions/issues/965
trying to combine issue reports here
