### ISSUE TITLE
Typos in questline headers

### ISSUE THREAD

**Issue by llearch** [FTBTeam/FTB-Interactions#977]
## Modpack Version: 
2.0.1 server (yes, I know it's out of date, but I don't run the server, so I'm stuck with what they provide)

## Bug Report:
In some of the float text in the quest book are a few minor typos. Ones I have noticed so far include:
 - Second chapter (A Very Broad Overview): "you can reffer back to" => refer
 - Chickens chapter: "Evironmental and Server friendly" => Environmental
 - Infinity Dust quest: "low chance of summonin enemies" => summoning
 - Dimensionality >> Space: Spacey (Not Kevin): "satelite" and "unprogramed" => satellite and unprogrammed
 - Dimensionality >> Space: Unmanned Rockets To Spaaaceee!: "your going" => you're going
 - Dimensionality >> Space: Space Raced: "orbial miner" => orbital miner
 - Dimensionality >> Space: Bloody Hell: "black qaurtz" => quartz
 - Dimensionality >> La Fin: Chaos Mining: "isntead" => instead
 - Steam Power And The First Multiblocks: Not That Kind Of Coke: "recourses" => resources
 - How Do We Power This Party: More Coke Ovens looks like the float text got left in the main name
 - Metallurgy IV: Concetrate Indi -> Concentrate Indi
 - What Is This Sorcery >> Mana: Mana Creation: "avaialble" => available
 - What Is This Sorcery >> Blood for the Blood Gods: Netherite Block: "recourses" => resources
 - Party Equipment: Spectre Sapling: "source of ecotplasm" => ectoplasm
 - Party Equipment: Spectre Coil: "will extrcact energy" => extract
 - Supply Chain Management: Intergated Tunnelling With Items => Integrated
 - Supply Chain Management: SFM Tutorial: "sitll checks out" => still, and I think the second half should move to the float text rather than the title, but that's more of an optional thought.
 - God's Plan: Floating Crystal: "Astral Sourcery" => Sorcery

Hopefully some of these have already been addressed in 2.0.2, but, if not, it's not a big deal.

**Comment by NappingPanda** [comment]
- Steam Power and the First Multiblocks >> The Infernal Furnace: "3 steel nuggets" => 2 steel nuggets
- Steam Power and the First Multiblocks >> The Infernal Furnace: "15 nuggets per crude ingot" => 10 nuggets per crude ingot

**Comment by Saereth** [comment]
I'm both glad you took the time to note all these and also hate you for it because now I have to go fix them all. Thanks. :P

**Comment by Saereth** [comment]
all of these have now been addressed for 2.0.3

**Comment by llearch** [comment]
Your hate is understood, and appreciated, and I apologise for providing you this impetus.

Having said that, if I notice more, I will provide them as well. ;-]

TY for your efforts, it's much appreciated.
