### ISSUE TITLE
Portable Transmutation Tablets

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [FTBTeam/FTB-Interactions#978]
## Modpack Version: 
2.0.2

## Description:
With how easy it is to just take a Transmutation Table with you on the go and place and break it whenever you need it, I feel that reintroducing the Transmutation Tablet from Project E might not actually be that bad of an idea. Currently, it seems to be ***very*** heavily gated as it needs Dark Matter Blocks, and I 100% got that at first as well, as obviously, it seems a bit OP at first, but when you remember that people can just pull a Transmutation Table out for 32 EMC and then take it with them on the go... it's really not that bad to just have it available as an item form to remove that extra "placing and breaking" bit that's more of a nuisance than a gate.

## Suggestion:
Perhaps, the Transmutation Tablet could be an Arcane Worktable recipe that requires mana to make, using something like steel plates for instance instead of dark matter blocks? I don't think it should be EMCable, though, it's a small, but valuable QoL upgrade over the less portable Table and I think that the way you should be able to get it should reflect that (as both steel and mana are early game, but require you to have done at least SOME form of work, so that the Tablet isn't just handed to you haphazardly)

**Comment by Hekera** [comment]
You can collect dark matter blocks from Aurellia dungeons. I have a portable tablet in my world.

**Comment by MaxNeedsSnacks** [comment]
Oh that's good to know. I'm still early-game rn (right around the MV age, reporting bugs as I go) so I never found out that was a thing, thanks! That said, that is still pretty heavily gated for such a small QoL update, ngl ^^'

**Comment by Saereth** [comment]
This is actually an oversight, the transmutation tablet will have a much easier recipe in 2.0.3
