### ISSUE TITLE
basic artisan worktable and toolbox not accepting tools

### ISSUE THREAD

**Issue by Sparhawk52** [FTBTeam/FTB-Interactions#980]
## Modpack Version: 
2.0.2

## Bug Report:
Cannot add tools to the basic artisan worktable or toolbox (stone mallet from quests), items and tools can be entered into the 3x3 pattern without issue. but cannot add tools to the tool slot.
JEI recipes do not show any usable tools except the artisan cutters and the ice and fire axes, all other recipes show a blank tool slot with just a durability loss. 
![iceandfire](https://user-images.githubusercontent.com/68357425/87612464-9ac41a00-c6d8-11ea-985f-d36ece3f08d2.jpg)
![cutters](https://user-images.githubusercontent.com/68357425/87612467-9bf54700-c6d8-11ea-9393-36876b748c66.jpg)

## Expected Behavior/Suggestions:
Should be able to add tools to the basic worktable. 
From video evidence of others playing game, they are able to insert stone mallet into table, suspect older version of modpack.

## Is It Repeatable? Steps to Reproduce: 
1. Followed quest line to create basic artisan worktable
2. Created stone mallet with sticks and cobble, open up the tables GUI, can place the mallet in the 3x3 but cannot place into the tool slot.

**Comment by aydan1313** [comment]
I am having a similar problem.
In addition my game is spamming the following whenever I break most blocks:
 ERROR: crafttweeker/api/item/IItemStackAny
I am using the FTBApp to download and run the modpack. I have deleted it and redownloaded the modpack and still have both problems. 
While the spam is annoying the inability to use the tools makes the modpack unplayable.

**Comment by Saereth** [comment]
your installations are corrupt just reinstall, yay for the ongoing nightmare that is this ftbapp

**Comment by aydan1313** [comment]
Saereth,
I understand that an installation can be corrupted. I also understand how those corruptions occur. If there was a "hickup" in traffic as the data packets where passed from the source to the destination then deleting the download and initiating the transfer again would definitely work.
However, if the problem continues to happen in EXACTLY the same way through several iterations of the download process, especially when the software preforming the download is re-initialized, then you have exactly 3 possibilities:
   1: the source is corrupt.
   2: the software is causing the problem
   3: the system receiving the information has a compatibility issue.
I am fairly certain option 2 is not the case as I can download other modpacks without problems using the app. I am providing my system information to help with the resolution of option 3, although I doubt it as I have no problems with the other modpacks I play through the FTBApp.
[DxDiag.txt](https://github.com/FTBTeam/FTB-Interactions/files/4935393/DxDiag.txt)

I apologies if this sounded harsh or confrontational, that is not my intent. I mean this next statement as a joke.
While I will question my sanity for a number of reasons but I will not repeat the same action more than 3 (ok 6 ish) times expecting a different result. I have reinstalled the modpack 5 times now with the same results.

I am also including the crafttweeker text file from the base folder of the instance for interactions
[crafttweaker.log](https://github.com/FTBTeam/FTB-Interactions/files/4935433/crafttweaker.log)
