### ISSUE TITLE
GregtechHammers Create Terrasteel

### ISSUE THREAD

**Issue by litten8** [FTBTeam/FTB-Interactions#982]
## Modpack Version: 
2.0.2

## Bug Report:
When melting any Gregtech hammer in the porcelain melter, I get 6 ingots of molten terrasteel

## Expected Behavior/Suggestions:
I should get 6 ingots of whatever was used to make a hammer. Iron, in my case. Or you should not be able to melt hammers

## Is It Repeatable? Steps to Reproduce: 

1. Place Porcelain Melter with fuel
2. Insert Gregtech Hammer

## Mod/s Affected: 
Gregtech and Tinkers' Complement

**Comment by eleanoryeung** [comment]
Mine always result iron, interesting
