### ISSUE TITLE
Plants mod pineapple cannot be used in recipes that accept any listAllFruits, even though it is.

### ISSUE THREAD

**Issue by Joris914** [FTBTeam/FTB-Interactions#987]
## Modpack Version: 
2.02

## Bug Report:
Plants mod pineapple cannot be used in recipes that accept any listAllFruits, even though it is.

## Expected Behavior/Suggestions:
It has the ore dictionary tag so it should be usable, for example, to craft fruit baits.

## Is It Repeatable? Steps to Reproduce: 
1. Try to craft a recipe with "accepts any: listAllFruits" as an ingredient using Plants pineapple.

## Link to Log or Crash File Paste**: 
n/a

## Mod/s Affected: 
1. Plants
2. Pam's Harvestcraft
3. (some OreDic controller? IDK)

## Known Fix: 
n/a

**Comment by Saereth** [comment]
I cannot reproduce this
![image](https://user-images.githubusercontent.com/9200909/87783721-0acebf00-c803-11ea-8680-6011397db4d2.png)

**Comment by Joris914** [comment]
That's because Pineapple Yogurt only accepts cropPineapple, not listAllFruits... if you use a different fruit you get a different item. What I'm talking about is recipes that use any listAllFruits and give you the same item. For example, pemmican, fruit salad, fruit punch, fruit bait. Try crafting any of those and you should see you cannot use the pineapple from plants.

**Comment by Joris914** [comment]
I think I found the reason. All other fruits have the tag listAllfruits with a small letter f, but for this pineapple it's a capital F.
