### ISSUE TITLE
Ink Black Chicken Egg texture missing

### ISSUE THREAD

**Issue by dcoolArne** [FTBTeam/FTB-Interactions#99]
## Modpack Version: 
1.0.1

## Bug Report:
"Ink Black Chicken Egg" has no texture in JEI.

## Is It Repeatable? Steps to Reproduce: 
1. open new game
2. look at Fried Egg recipe
3. wait untill Ink Black Chicken Egg shows up 

## Mod/s Affected: 
Chickens

**Comment by Vyraal1** [comment]
Not sure if there's any fix we can do on our end, we disabled those chickens and them or their eggs shouldn't be appearing anywhere.
