### ISSUE TITLE
Crashing while launching world

### ISSUE THREAD

**Issue by Najiro11** [FTBTeam/FTB-Interactions#990]
When i try to launch my world, the game crashes but i dont get any crash log or something that is telling me what happened or why my game crashed. So i search in modpack folder ´´Crash-reports´´ but it´s only showing my old crash-report which was in back in 14.7. 2020 and not the new one. I wasn´t doing anything crazy that could crash my world, so i really dont know what happened. I tried to start a new world but everything was fine, only the one that i was playing is not working. And my last backup of the world was 2 days ago (15.7) and that is around 15-20 hours and i really dont wanna lose that time.

Message that is showing when my game crash: There was an unexpected problem and the game crashed.

**Comment by Saereth** [comment]
send your latest.let

**Comment by Najiro11** [comment]
I cant find it, and tbh ive played on my last backup since then so it´s not a big deal anymore. And i think that crash happened because our electricity turn off when i was in the game and doing sth that was laggy, so i think my world just got corrupted, but like im saying it´s not a big deal, and im just gonna be more careful next time. You can closed this issue, cause it was 1 week and it seems that nobody had this issue too, so im pretty sure it was because of that. Thanks for your time.
