### ISSUE TITLE
No way to get wool during the "Void" section of the pack and therefore can not complete the quest "Rain-B-Gone".

### ISSUE THREAD

**Issue by rockdemon696** [FTBTeam/FTB-Interactions#993]
## Modpack Version: 
<2.0.3>

## Bug Report:
<Wool can only be gotten from sheep, which can't be summoned without wool, and which do not spawn naturally and therefore a quest requiring wool as a crafting component is not completible during the void world section within which it is found.>

## Is It Repeatable? Steps to Reproduce: 
1. Look up the "Rain-B-Gone" quest.
2. See that a rainshield requires wool.
3. Look up the recipe for wool.
4. See that wool can't be crafted.
5. Look up how to summon a sheep.
6. See that summoning a sheep requires wool.
7. Shake fist at the sky cursing the rain that can't be stopped.

**Comment by Saereth** [comment]
You can summon sheep with zen summoning

**Comment by Kawzeg** [comment]
Summoning sheep requires wool according to the recipe, so how do you get wool to summon the sheep without having sheep in the first place?

**Comment by E3FxGaming** [comment]
I'd like to know how you're supposed to get wool in the void world, too.

Zen summoning is not an option for the first piece of wool.
