### ISSUE TITLE
2.0.3 Template Manager Quest Reward Soft Crash

### ISSUE THREAD

**Issue by Duckgrass** [FTBTeam/FTB-Interactions#995]
## Modpack Version: 
2.0.3

## Bug Report:
When mousing over the photonuclear multiblock schematic in the rewards section for the Template Manager Quest, the client gets kicked out, at least on a server, and shown a Minecraft crashed screen displaying Building Gadgets and FTB Library as being the cause.

## Expected Behavior/Suggestions:
You should be able to mouse over the schematic.
Either change it to fix or maybe put a warning for the bug.

## Is It Repeatable? Steps to Reproduce: 

1. Open the quest menu. 
2. Open the quest page of 'Multiblock Mastery'
3. Mouse over the schematics rewards on the second row
4. It kicks you out

## Link to Log or Crash File Paste**: 
https://paste.feed-the-beast.com/view/d9fb0f02

## Mod/s Affected: 
Building Gadgets and FTB Library/ FTB Questing

**Comment by Saereth** [comment]
This code here shows the crash happening in building gadgets, please create an issue over on their github 
https://github.com/Direwolf20-MC/BuildingGadgets/issues

**Comment by Saereth** [comment]
https://github.com/FTBTeam/FTB-Interactions/issues/994
