### ISSUE TITLE
An Eggcelent Endeavour quest "choice"

### ISSUE THREAD

**Issue by Martin-Astos** [FTBTeam/FTB-Interactions#996]
## Modpack Version: 
2.02

## Bug Report:
An Eggcelent Endeavour quest:

The text says you get a choice of which egg/Hippogryph you can have but the textures and text are all identical, therefore no choice.

## Expected Behavior/Suggestions:
Either:

- adjust how the choices appear (metadata? changed names? tooltip?), 
- add to the main quest description a list of what each slot is
- change the quest description to not say we can choose
- say the choice is a lucky dip (even if not actually randomised).

This may seem trivial but has stopped me progressing due to FOMO/anxiety/stress. I hate to use this as a reason but in this modern world the more we can all do to avoid adding small and inconsequential (to the majority) things that trigger conditions suffered by many people, during fun/relaxing activities, the better. Therefore as 2 of the potential fixes should be within the range of "Easy Fixes", and this isn't exactly an 'easy' pack anyway, I hope a small change to help some people not just give up in your hard work (as i was close to doing tbh) is something that can be done.

## Is It Repeatable? Steps to Reproduce: 
Um just text visible in the quest book.

Thanks

**Comment by MaxNeedsSnacks** [comment]
To my knowledge, all the Hippogryph eggs are exactly the same save for colour differences, so I guess a good way to go about it would be to just add their colours as tooltips or their display name

**Comment by Saereth** [comment]
I can name them in an anvil actually I'll go that route

**Comment by Martin-Astos** [comment]
Thanks, that sounds great.
