### ISSUE TITLE
singleplayer veinmining issue with flint axe (gregtech type)

### ISSUE THREAD

**Issue by MidnightAmratha** [FTBTeam/FTB-Interactions#997]
## Modpack Version: 
1,9,1

## Bug Report:
: harvesting with flint axe cycles to 80% then resets

**Comment by proslackergamer** [comment]
It's a known bug with 1.9.x.  You'll either have to grab the robot arm fix from the pins in discord to replace your current Gregtech.jar, or even better update to 2.0!  2.0 has to be installed via the FTB App, or by importing the pack into Twitch or MultiMC.  To get the files to import the pack, there's a pinned message in discord with the zip file with everything you will need.

**Comment by Saereth** [comment]
This has been fixed in the newer versions
