### ISSUE TITLE
Version 2.0.3 Serverscript not downloading correctly

### ISSUE THREAD

**Issue by 88mmAufSfl8** [FTBTeam/FTB-Interactions#999]
## Modpack Version: 
<2.0.3 on a Server>

## Bug Report:
The Formed Hellfire Kiln, will not smelt or do any work constantly saying "missing input item".

Edit: Turned out The server was missing a mods, we found this out after restarting it and i got word about it throwing errors.

## Is It Repeatable? Steps to Reproduce: 
IDK as only Thaumcraft was missing, perhaps it was the bad internet of the owner?

## Link to Log or Crash File Paste:
Sadly i have neither Logs or Crash Reports

## Mod/s Affected: 
Thaumcraft

**Comment by 88mmAufSfl8** [comment]
It appears the server was missing 5 Mods, so this isn't really about the Kiln more about the Server Script?

**Comment by Saereth** [comment]
the server script is autogenerated from FTB app, this is an issue with their launcher not the pack, please create an issue and over on the app tracker if you would
https://github.com/FTBTeam/FTB-App/issues
